// <auto-generated />
using System;
using ArturRios.Cerberus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArturRios.Cerberus.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008193129_ProfileTrash")]
    partial class ProfileTrash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cerberus")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("server_sequence", "cerberus")
                .HasMax(9007199254740991L);

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Access.VaultAccessSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HandleVerifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("handle_verifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("policy_revision");

                    b.Property<long?>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<long>("RevocationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("revocation_generation");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.HasKey("Id")
                        .HasName("pk_vault_access_session");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_vault_access_session_account_id");

                    b.HasIndex("HandleVerifier")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_access_session_handle_verifier");

                    b.ToTable("vault_access_session", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Accounts.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosurePurgeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closure_purge_at");

                    b.Property<DateTimeOffset?>("ClosureRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closure_requested_at");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<byte[]>("DetailsEnvelope")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("details_envelope");

                    b.Property<Guid>("HeimdallPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("heimdall_public_id");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("policy_revision");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<bool>("RenewalEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("renewal_enabled");

                    b.Property<TimeSpan?>("RenewalInterval")
                        .HasColumnType("interval")
                        .HasColumnName("renewal_interval");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<long>("RevocationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("revocation_generation");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("HeimdallPublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_heimdall_public_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_public_id");

                    b.ToTable("account", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Accounts.RegistrationOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_public_id");

                    b.Property<Guid?>("CompletedIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_identity_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.HasKey("Id")
                        .HasName("pk_registration_operation");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_operation_operation_id");

                    b.ToTable("registration_operation", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Operations.RetentionWorkItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_token");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation_key");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_retention_work_item");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_retention_work_item_operation_key");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_retention_work_item_public_id");

                    b.ToTable("retention_work_item", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Operations.TerminalErasure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("resource_kind");

                    b.HasKey("Id")
                        .HasName("pk_terminal_erasure");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_terminal_erasure_resource_id");

                    b.ToTable("terminal_erasure", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Profiles.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<byte[]>("Envelope")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("envelope");

                    b.Property<byte[]>("KeyWrappers")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_wrappers");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("PurgeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<long>("ServerSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("server_sequence")
                        .HasDefaultValueSql("nextval('cerberus.server_sequence')");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_public_id");

                    b.HasIndex("AccountId", "ServerSequence")
                        .HasDatabaseName("ix_profile_account_id_server_sequence");

                    b.ToTable("profile", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Protection.VaultProtection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("KeyEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("key_epoch");

                    b.Property<byte[]>("Material")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("material");

                    b.Property<long>("RecoveryGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("recovery_generation");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_vault_protection");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_protection_account_id");

                    b.ToTable("vault_protection", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Protection.VaultRecoveryOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("ProtectionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("protection_revision");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("request_hash");

                    b.Property<long>("RevocationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("revocation_generation");

                    b.HasKey("Id")
                        .HasName("pk_vault_recovery_operation");

                    b.HasIndex("AccountId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_recovery_operation_account_id_idempotency_key");

                    b.ToTable("vault_recovery_operation", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Protection.VaultUnlockChallenge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<byte[]>("Challenge")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("challenge");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("policy_revision");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long>("RevocationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("revocation_generation");

                    b.HasKey("Id")
                        .HasName("pk_vault_unlock_challenge");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_unlock_challenge_public_id");

                    b.HasIndex("AccountId", "ExpiresAt")
                        .HasDatabaseName("ix_vault_unlock_challenge_account_id_expires_at");

                    b.ToTable("vault_unlock_challenge", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Trash.TrashEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("AssociationSnapshot")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("association_snapshot");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("resource_kind");

                    b.HasKey("Id")
                        .HasName("pk_trash_entry");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("ix_trash_entry_operation_id");

                    b.HasIndex("ResourceKind", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_trash_entry_resource_kind_resource_id");

                    b.ToTable("trash_entry", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Trash.TrashOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("PurgeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_at");

                    b.Property<Guid>("RootResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_resource_id");

                    b.Property<string>("RootResourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("root_resource_kind");

                    b.HasKey("Id")
                        .HasName("pk_trash_operation");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_trash_operation_public_id");

                    b.HasIndex("AccountId", "PurgeAt")
                        .HasDatabaseName("ix_trash_operation_account_id_purge_at");

                    b.ToTable("trash_operation", "cerberus");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Access.VaultAccessSession", b =>
                {
                    b.HasOne("ArturRios.Cerberus.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_access_session_account_account_id");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Profiles.Profile", b =>
                {
                    b.HasOne("ArturRios.Cerberus.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_accounts_account_id");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Protection.VaultProtection", b =>
                {
                    b.HasOne("ArturRios.Cerberus.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_protection_account_account_id");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Protection.VaultRecoveryOperation", b =>
                {
                    b.HasOne("ArturRios.Cerberus.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_recovery_operation_account_account_id");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Protection.VaultUnlockChallenge", b =>
                {
                    b.HasOne("ArturRios.Cerberus.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_unlock_challenge_account_account_id");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Trash.TrashEntry", b =>
                {
                    b.HasOne("ArturRios.Cerberus.Domain.Trash.TrashOperation", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trash_entry_trash_operation_operation_id");
                });

            modelBuilder.Entity("ArturRios.Cerberus.Domain.Trash.TrashOperation", b =>
                {
                    b.HasOne("ArturRios.Cerberus.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trash_operation_accounts_account_id");
                });
#pragma warning restore 612, 618
        }
    }
}
