    [FunctionalTheory][InlineData("wide")][InlineData("direct")][InlineData("ancestor")][InlineData("collection")][InlineData("collectionAncestor")]
    public async Task GivenCurrentOwnedFolderScope_WhenTrashing_ThenOneRetainedCascadeAndUnchangedHandle(string route)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);
        if(route.StartsWith("collection"))await Members(s,a.Collection,[],[route=="collection"?root.Id:a.Folder.Id]);
        if(route!="wide"){var p=await Profile(s,owner,key,folders:route=="direct"?[root.PublicId]:route=="ancestor"?[a.Folder.PublicId]:[],collections:route.StartsWith("collection")?[a.Collection.PublicId]:[]);s=s with{Verifier=await Selected(s,p.Id)};}
        var result=await Trash(s,root);await Success(s,root,[root,child],[record],result);await using var db=fixture.CreateContext();Assert.False((await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==s.Verifier)).Revoked);Assert.NotNull((await db.Folders.SingleAsync(x=>x.Id==a.Folder.Id)).ParentFolderId is null?new object():null);
        Assert.Equal("not_found",(await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,child.PublicId),default)).Error);Assert.Equal("not_found",(await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);
    }
    [FunctionalFact]
    public async Task GivenDeepCascadeWithOverlappingInactiveLinksAndRecipient_WhenTrashing_ThenSnapshotEveryMemberAndBumpEachActiveExternalParentOnce()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();using var key2=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);var child=await Folder(s,root.Id);var leaf=await Folder(s,child.Id);var r1=await Record(s,root.Id);var r2=await Record(s,leaf.Id);var p=await Profile(s,owner,key,records:[r1.PublicId,r2.PublicId],folders:[root.PublicId,child.PublicId]);var inactive=await Profile(s,owner,key2,records:[r2.PublicId],folders:[leaf.PublicId]);var b=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[r1.Id,r2.Id],[root.Id,leaf.Id]);await Members(s,b.Collection,[r2.Id],[child.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection,CollectionGrantAccess.ReadWrite);
        await using(var db=fixture.CreateContext()){await db.Profiles.Where(x=>x.Id==inactive.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));await db.Collections.Where(x=>x.Id==b.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}
        p=await ProfileRow(p.Id);inactive=await ProfileRow(inactive.Id);var parent=await Row(a.Folder.Id);var other=Bytes(a.Record);var recipientBefore=await Snapshot(recipient);var result=await Trash(s,root);await Success(s,root,[root,child,leaf],[r1,r2],result);
        await using(var db=fixture.CreateContext()){
            var nowP=await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id);Assert.Equal(p.Revision+1,nowP.Revision);Assert.True(nowP.ServerSequence>p.ServerSequence);Assert.Equal(p.Envelope,nowP.Envelope);Assert.Equal(p.KeyWrappers,nowP.KeyWrappers);Assert.Equal(p.EditedAt,nowP.EditedAt);Assert.Equal(Bytes(inactive),Bytes(await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==inactive.Id)));
            var nowC=await db.Collections.AsNoTracking().SingleAsync(x=>x.Id==a.Collection.Id);Assert.Equal(a.Collection.Revision+1,nowC.Revision);Assert.True(nowC.ServerSequence>a.Collection.ServerSequence);Assert.Equal(a.Collection.Envelope,nowC.Envelope);Assert.Equal(a.Collection.KeyEpoch,nowC.KeyEpoch);Assert.Equal(b.Collection.Revision,(await db.Collections.SingleAsync(x=>x.Id==b.Collection.Id)).Revision);
            var nowParent=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==parent.Id);Assert.Equal(parent.Revision+1,nowParent.Revision);Assert.Equal(parent.Envelope,nowParent.Envelope);Assert.Equal(parent.EditedAt,nowParent.EditedAt);Assert.Equal(other,Bytes(await db.Records.AsNoTracking().SingleAsync(x=>x.Id==a.Record.Id)));
            var fs=JsonSerializer.Deserialize<FolderAssociationSnapshot>((await db.TrashEntries.SingleAsync(x=>x.ResourceKind=="folder"&&x.ResourceId==leaf.PublicId)).AssociationSnapshot,ProtectionFixture.Json)!;Assert.Equal(child.PublicId,fs.ParentFolderId);Assert.Equal(new[]{inactive.PublicId},fs.ProfileIds);Assert.Equal(new[]{a.Collection.PublicId},fs.CollectionIds);
            var rs=JsonSerializer.Deserialize<RecordAssociationSnapshot>((await db.TrashEntries.SingleAsync(x=>x.ResourceKind=="record"&&x.ResourceId==r2.PublicId)).AssociationSnapshot,ProtectionFixture.Json)!;Assert.Equal(leaf.PublicId,rs.FolderId);Assert.Equal(new[]{p.PublicId,inactive.PublicId}.Order(),rs.ProfileIds);Assert.Equal(new[]{a.Collection.PublicId,b.Collection.PublicId}.Order(),rs.CollectionIds);
            Assert.True(await db.CollectionGrants.AnyAsync(x=>x.CollectionId==a.Collection.Id&&x.State==CollectionGrantState.Active));
        }
        Assert.Equal(recipientBefore,await Snapshot(recipient));Assert.Equal("not_found",(await new FolderReadStore(fixture).ReadAsync(new(recipient.Actor,recipient.Verifier,leaf.PublicId),default)).Error);Assert.Equal("not_found",(await new RecordReadStore(fixture).ReadAsync(new(recipient.Actor,recipient.Verifier,r2.PublicId),default)).Error);
    }
    [FunctionalFact]
    public async Task GivenActualIndependentRecordAndFolderTrash_WhenLaterTrashingRoot_ThenPreserveEarlierOperationsAndDeadlines()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var independent=await Folder(s,root.Id);var previousRecord=await Record(s,root.Id);var previousChildRecord=await Record(s,independent.Id);var child=await Folder(s,root.Id);var activeRecord=await Record(s,child.Id);
        var first=await new RecordTrashStore(fixture).TrashAsync(new(s.Actor,s.Verifier,previousRecord.PublicId,1),default);Assert.Null(first.Error);var second=await Trash(s,independent);await Success(s,independent,[independent],[previousChildRecord],second);root=await Row(root.Id);var oldFolder=Bytes(await Row(independent.Id));var oldRecord=Bytes(await RecordRow(previousRecord.Id));var oldChildRecord=Bytes(await RecordRow(previousChildRecord.Id));
        await using var db=fixture.CreateContext();var oldOps=Bytes(await db.TrashOperations.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync());var oldEntries=Bytes(await db.TrashEntries.AsNoTracking().Where(x=>x.ResourceId==previousRecord.PublicId||x.ResourceId==independent.PublicId||x.ResourceId==previousChildRecord.PublicId).OrderBy(x=>x.Id).ToArrayAsync());await Success(s,root,[root,child],[activeRecord],await Trash(s,root,root.Revision));
        Assert.Equal(oldFolder,Bytes(await Row(independent.Id)));Assert.Equal(oldRecord,Bytes(await RecordRow(previousRecord.Id)));Assert.Equal(oldChildRecord,Bytes(await RecordRow(previousChildRecord.Id)));Assert.Equal(oldEntries,Bytes(await db.TrashEntries.AsNoTracking().Where(x=>x.ResourceId==previousRecord.PublicId||x.ResourceId==independent.PublicId||x.ResourceId==previousChildRecord.PublicId).OrderBy(x=>x.Id).ToArrayAsync()));Assert.Equal(oldOps,Bytes(await db.TrashOperations.AsNoTracking().Where(x=>x.PublicId==first.Data!.TrashOperationId||x.PublicId==second.Data!.TrashOperationId).OrderBy(x=>x.Id).ToArrayAsync()));
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenActualNativeVisibleForeignFolder_WhenDeletingStaleDamagedTarget_Then403AndNoGraphMutation(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var target=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,access);if(selected){var p=await Profile(s,client,key,collections:[a.Collection.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};}
        Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,target.PublicId),default)).Error);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged"u8.ToArray()));var before=await Snapshot(o);var recipient=await Snapshot(s);Assert.Equal("vault_access_denied",(await Trash(s,target,99)).Error);Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenActualNativeRecordOnlyMembership_WhenDeletingItsContainingFolder_Then404AfterSuccessfulRecordRead(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var record=await Record(o,a.Folder.Id);await Members(o,a.Collection,[record.Id],[]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,access);if(selected){var p=await Profile(s,client,key,collections:[a.Collection.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};}
        Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);var before=await Snapshot(o);Assert.Equal("not_found",(await Trash(s,a.Folder,99)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalFact]
    public async Task GivenSelectedDirectRecordWithoutFolderMembership_WhenDeletingContainer_Then404AfterSuccessfulRecordRead()
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var record=await Record(s,folder.Id);var p=await Profile(s,owner,key,records:[record.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);var before=await Snapshot(s);Assert.Equal("not_found",(await Trash(s,folder,99)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("missing","not_found")][InlineData("closing","not_found")][InlineData("terminal","not_found")][InlineData("access","vault_access_denied")][InlineData("revoked","vault_access_denied")][InlineData("expired","vault_access_denied")][InlineData("future","vault_access_denied")][InlineData("policy","vault_access_denied")][InlineData("generation","vault_access_denied")][InlineData("zeroPolicy","vault_access_denied")][InlineData("zeroGeneration","vault_access_denied")][InlineData("nullExpiry","vault_access_denied")][InlineData("disabledExpiry","vault_access_denied")][InlineData("noExpiry",null)][InlineData("selection","vault_access_denied")]
    public async Task GivenInvalidCurrentAuthority_WhenTrashing_ThenFailClosed(string kind,string? error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);await using(var db=fixture.CreateContext()){var a=await db.Accounts.SingleAsync(x=>x.Id==s.InternalId);var v=await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==s.Verifier);if(kind=="closing")a.State=AccountState.ClosurePending;if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="zeroPolicy")v.PolicyRevision=0;if(kind=="zeroGeneration")v.RevocationGeneration=0;if(kind is "noExpiry" or "disabledExpiry")a.RenewalEnabled=false;if(kind is "nullExpiry" or "noExpiry")v.ExpiresAt=null;if(kind=="selection")v.ProfileId=long.MaxValue;await db.SaveChangesAsync();}
        var before=await Snapshot(s);var r=await Store().TrashAsync(new(kind=="missing"?Guid.NewGuid():s.Actor,kind=="access"?new string('a',64):s.Verifier,target.PublicId,1),default);Assert.Equal(error,r.Error);if(error is null)await Success(s,target,[target],[],r);else Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("actor","authentication_required")][InlineData("id","validation_failed")][InlineData("zero","validation_failed")][InlineData("unsafe","validation_failed")]
    public async Task GivenInvalidInternalRequest_WhenTrashing_ThenRejectWithoutWrite(string kind,string error)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var before=await Snapshot(s);var r=await Store().TrashAsync(new(kind=="actor"?Guid.Empty:s.Actor,s.Verifier,kind=="id"?Guid.Empty:target.PublicId,kind=="zero"?0:kind=="unsafe"?ProtocolBinary.MaxInteger+1:1),default);Assert.Equal(error,r.Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("self",false)][InlineData("long",false)][InlineData("self",true)]
    public async Task GivenRelevantCyclicOrHiddenAncestry_WhenTrashing_ThenBounded503OrHidden404(string kind,bool hidden)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var target=await Folder(s,root.Id);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,(long?)(kind=="self"?root.Id:target.Id)).SetProperty(v=>v.DeletedAt,hidden?(DateTimeOffset?)DateTimeOffset.UtcNow:null));var before=await Snapshot(s);Assert.Equal(hidden?"not_found":"persistence_unavailable",(await Trash(s,target)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("account")][InlineData("profile")][InlineData("record")][InlineData("folder")][InlineData("collection")][InlineData("grant")]
    public async Task GivenTerminalAliasWithDifferentKind_WhenDeletingFolder_ThenOnlyMatchingFolderKindHidesIt(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceKind=kind,ResourceId=target.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);var r=await Trash(s,target);if(kind=="folder"){Assert.Equal("not_found",r.Error);Assert.Equal(before,await Snapshot(s));}else await Success(s,target,[target],[],r);}
    [FunctionalTheory][InlineData("folder","zeroRevision","persistence_unavailable")][InlineData("folder","zeroSequence","persistence_unavailable")][InlineData("folder","maxRevision","revision_conflict")][InlineData("folder","purge","persistence_unavailable")][InlineData("folder","oldEntry","revision_conflict")][InlineData("child","zeroRevision","persistence_unavailable")][InlineData("child","unsafeSequence","persistence_unavailable")][InlineData("child","maxRevision","revision_conflict")][InlineData("child","purge","persistence_unavailable")][InlineData("child","oldEntry","revision_conflict")][InlineData("record","zeroRevision","persistence_unavailable")][InlineData("record","zeroSequence","persistence_unavailable")][InlineData("record","maxRevision","revision_conflict")][InlineData("record","purge","persistence_unavailable")][InlineData("record","oldEntry","revision_conflict")]
    public async Task GivenCorruptOrConflictingCascadeMember_WhenTrashing_ThenNoPartialOperation(string member,string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var id=member=="folder"?root.PublicId:member=="child"?child.PublicId:record.PublicId;await using(var db=fixture.CreateContext()){
            if(member=="record"){var r=await db.Records.SingleAsync(x=>x.Id==record.Id);if(kind=="zeroRevision")r.Revision=0;if(kind=="zeroSequence")r.ServerSequence=0;if(kind=="maxRevision")r.Revision=ProtocolBinary.MaxInteger;if(kind=="purge")r.PurgeAt=DateTimeOffset.UtcNow.AddDays(30);}
            else{var f=await db.Folders.SingleAsync(x=>x.PublicId==id);if(kind=="zeroRevision")f.Revision=0;if(kind=="zeroSequence")f.ServerSequence=0;if(kind=="unsafeSequence")f.ServerSequence=ProtocolBinary.MaxInteger+1;if(kind=="maxRevision")f.Revision=ProtocolBinary.MaxInteger;if(kind=="purge")f.PurgeAt=DateTimeOffset.UtcNow.AddDays(30);}
            if(kind=="oldEntry"){var op=new TrashOperation{AccountId=s.InternalId,RootResourceKind=member=="record"?"record":"folder",RootResourceId=id,DeletedAt=DateTimeOffset.UtcNow,PurgeAt=DateTimeOffset.UtcNow.AddDays(30)};db.TrashOperations.Add(op);await db.SaveChangesAsync();db.TrashEntries.Add(new(){OperationId=op.Id,ResourceKind=op.RootResourceKind,ResourceId=id,AssociationSnapshot="{}"u8.ToArray()});}await db.SaveChangesAsync();}
        var before=await Snapshot(s);Assert.Equal(error,(await Trash(s,root,member=="folder"&&kind=="maxRevision"?ProtocolBinary.MaxInteger:1)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenDamagedOwnedCascadeCipher_WhenTrashing_ThenRetainOpaqueBytesWithoutParsing()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);await using(var db=fixture.CreateContext()){await db.Folders.Where(x=>x.Id==root.Id||x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged-folder"u8.ToArray()));await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged-record"u8.ToArray()));}root=await Row(root.Id);child=await Row(child.Id);record=await RecordRow(record.Id);await Success(s,root,[root,child],[record],await Trash(s,root));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenConcurrentTrashOrLostSuccessRetry_WhenDeleting_ThenExactlyOneOperationAndUnchangedDeadline(bool concurrent)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var results=concurrent?await Task.WhenAll(Trash(s,root),Trash(s,root)):new[]{await Trash(s,root),await Trash(s,root)};await Success(s,root,[root,child],[record],Assert.Single(results,x=>x.Error is null));Assert.Equal("not_found",Assert.Single(results,x=>x.Error is not null).Error);var before=await Snapshot(s);Assert.Equal("not_found",(await Trash(s,root)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenStaleRootRevision_WhenDeleting_ThenConflictPreservesCompleteGraph()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);await Folder(s,root.Id);var before=await Snapshot(s);Assert.Equal("revision_conflict",(await Trash(s,root,2)).Error);Assert.Equal(before,await Snapshot(s));}
    private FolderTrashStore Store()=>new(fixture);
    private Task<VaultResult<FolderTrashDetails>> Trash(ProfileSetup.State s,VaultFolder folder,long revision=1)=>Store().TrashAsync(new(s.Actor,s.Verifier,folder.PublicId,revision),default);
    private async Task<Profile> ProfileRow(long id){await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task<VaultRecord> RecordRow(long id){await using var db=fixture.CreateContext();return await db.Records.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task Success(ProfileSetup.State s,VaultFolder original,VaultFolder[] folders,VaultRecord[] records,VaultResult<FolderTrashDetails> result)
    {
        Assert.Null(result.Error);var d=result.Data!;Assert.Equal(original.PublicId,d.FolderId);Assert.NotEqual(Guid.Empty,d.TrashOperationId);Assert.Equal(original.Revision+1,d.Revision);Assert.True(d.ServerSequence>original.ServerSequence);Assert.InRange(d.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.Equal(TimeSpan.Zero,d.DeletedAt.Offset);Assert.Equal(0,d.DeletedAt.Ticks%10);Assert.Equal(TimeSpan.FromDays(30),d.PurgeAt-d.DeletedAt);Assert.Equal(TimeSpan.Zero,d.PurgeAt.Offset);
        await using var db=fixture.CreateContext();var op=await db.TrashOperations.AsNoTracking().SingleAsync(x=>x.PublicId==d.TrashOperationId);Assert.Equal("folder",op.RootResourceKind);Assert.Equal(s.InternalId,op.AccountId);Assert.Equal(original.PublicId,op.RootResourceId);Assert.Equal(d.DeletedAt,op.DeletedAt);Assert.Equal(d.PurgeAt,op.PurgeAt);var entries=await db.TrashEntries.AsNoTracking().Where(x=>x.OperationId==op.Id).ToListAsync();Assert.Equal(folders.Length+records.Length,entries.Count);Assert.Equal(folders.Select(x=>x.PublicId).Order(),entries.Where(x=>x.ResourceKind=="folder").Select(x=>x.ResourceId).Order());Assert.Equal(records.Select(x=>x.PublicId).Order(),entries.Where(x=>x.ResourceKind=="record").Select(x=>x.ResourceId).Order());var q=Assert.Single(await db.RetentionWorkItems.AsNoTracking().Where(x=>x.OperationKey=="trash/"+op.PublicId).ToListAsync());Assert.Equal(d.PurgeAt,q.DueAt);Assert.Null(q.CompletedAt);
        foreach(var f in folders){var row=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==f.Id);Assert.Equal(f.Envelope,row.Envelope);Assert.Equal(f.EditedAt,row.EditedAt);Assert.Equal(f.AccountId,row.AccountId);Assert.Null(row.ParentFolderId);Assert.Equal(f.Revision+1,row.Revision);Assert.True(row.ServerSequence>f.ServerSequence);Assert.InRange(row.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.Equal(d.DeletedAt,row.DeletedAt);Assert.Equal(d.PurgeAt,row.PurgeAt);Assert.NotEqual(f.ConcurrencyStamp,row.ConcurrencyStamp);Assert.False(await db.ProfileFolders.AnyAsync(x=>x.FolderId==f.Id));Assert.False(await db.CollectionFolders.AnyAsync(x=>x.FolderId==f.Id));}
        foreach(var r in records){var row=await db.Records.AsNoTracking().SingleAsync(x=>x.Id==r.Id);Assert.Equal(r.Envelope,row.Envelope);Assert.Equal(r.EditedAt,row.EditedAt);Assert.Equal(r.AccountId,row.AccountId);Assert.Null(row.FolderId);Assert.Equal(r.Revision+1,row.Revision);Assert.True(row.ServerSequence>r.ServerSequence);Assert.InRange(row.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.Equal(d.DeletedAt,row.DeletedAt);Assert.Equal(d.PurgeAt,row.PurgeAt);Assert.NotEqual(r.ConcurrencyStamp,row.ConcurrencyStamp);Assert.False(await db.ProfileRecords.AnyAsync(x=>x.RecordId==r.Id));Assert.False(await db.CollectionRecords.AnyAsync(x=>x.RecordId==r.Id));}
    }
