    [FunctionalTheory][InlineData("wide")][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenActualCreatedSubtreeAndNativeOwnedAccess_WhenDeleting_ThenOneCascadeWithExactSixMetadataFields(string mode)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);var child=await Create(s,folder:root.FolderId);var record=await CreateRecord(s,child.FolderId);var rootRow=await FolderRow(root.FolderId);var p=await Profile(s,owner,key,rootRow,mode=="wide"?"Master":mode);var actor=mode=="wide"?s:s with{Access=await Open(s,p,key)};var childRow=await FolderRow(child.FolderId);var recordRow=await RecordRow(record.RecordId);var protectedBefore=await Protected(s);using var response=await Trash(actor,root.FolderId,rootRow.Revision);var output=await Success<DeleteFolderOutput>(response,200);Fields(output,"folderId","trashOperationId","revision","serverSequence","deletedAt","purgeAt");Assert.Contains("folder_deleted",await response.Content.ReadAsStringAsync());await Trashed(s,rootRow,[rootRow,childRow],[recordRow],output);Assert.Equal(protectedBefore,await Protected(s));
        using var get=await Read(actor,"/api/folders/"+child.FolderId);await Failure(get,404,"not_found");using var rg=await Read(actor,"/api/records/"+record.RecordId);await Failure(rg,404,"not_found");using var list=await Read(actor,"/api/folders");Assert.Empty((await Success<FolderListOutput>(list,200)).Items);
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,"wide")][InlineData(CollectionGrantAccess.ReadWrite,"wide")][InlineData(CollectionGrantAccess.ReadOnly,"Master")][InlineData(CollectionGrantAccess.ReadWrite,"Master")][InlineData(CollectionGrantAccess.ReadOnly,"PerProfile")][InlineData(CollectionGrantAccess.ReadWrite,"PerProfile")]
    public async Task GivenActualNativeForeignFolderScope_WhenDeletingStaleDamagedCipher_Then403ForEveryRecipientMode(CollectionGrantAccess access,string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Create(o);var target=await Create(o,folder:root.FolderId);var (c,_)=await Share(o,owner,s,client,access,[root.FolderId],[]);var p=await Profile(s,client,key,mode:mode=="wide"?"Master":mode,collections:[c.PublicId]);var actor=mode=="wide"?s:s with{Access=await Open(s,p,key)};using(var get=await Read(actor,"/api/folders/"+target.FolderId))await Success<FolderDetailsOutput>(get,200);await using(var db=fixture.Context())await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged"u8.ToArray()));var before=await Snapshot(o);var recipient=await Snapshot(s);using var r=await Trash(actor,target.FolderId,99);await Failure(r,403,"vault_access_denied");Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenActualIndependentRecordAndChildFolderDeletion_WhenLaterDeletingRoot_ThenEarlierTrashOperationsKeepDeadlines()
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);var child=await Create(s,folder:root.FolderId);var active=await Create(s,folder:root.FolderId);var independent=await CreateRecord(s,root.FolderId);using var recordDelete=Delete(s,"/api/records/"+independent.RecordId,Bytes(new{expectedRevision=1}));using var recordResponse=await Gateway.Client.SendAsync(recordDelete);var rd=await Success<ArturRios.Cerberus.Command.Records.DeleteRecordOutput>(recordResponse,200);var childRow=await FolderRow(child.FolderId);using var childDelete=await Trash(s,child.FolderId,childRow.Revision);var fd=await Success<DeleteFolderOutput>(childDelete,200);var oldChild=Bytes(await FolderRow(child.FolderId));var oldRecord=Bytes(await RecordRow(independent.RecordId));var rootRow=await FolderRow(root.FolderId);var activeRow=await FolderRow(active.FolderId);using var rootDelete=await Trash(s,root.FolderId,rootRow.Revision);var output=await Success<DeleteFolderOutput>(rootDelete,200);await Trashed(s,rootRow,[rootRow,activeRow],[],output);Assert.Equal(oldChild,Bytes(await FolderRow(child.FolderId)));Assert.Equal(oldRecord,Bytes(await RecordRow(independent.RecordId)));await using var db=fixture.Context();Assert.Equal(rd.PurgeAt,(await db.TrashOperations.SingleAsync(x=>x.PublicId==rd.TrashOperationId)).PurgeAt);Assert.Equal(fd.PurgeAt,(await db.TrashOperations.SingleAsync(x=>x.PublicId==fd.TrashOperationId)).PurgeAt);
    }
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenCorruptOverlappingContributor_WhenDeleting_ThenSelectedValidRoute403AndWide503WithoutMutation(string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Create(o);var (good,_)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[root.FolderId],[]);var (_,bad)=await Share(o,owner,s,client,CollectionGrantAccess.ReadOnly,[root.FolderId],[]);var p=await Profile(s,client,key,mode:mode,collections:[good.PublicId]);var selected=s with{Access=await Open(s,p,key)};await using(var db=fixture.Context())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(o);using var scoped=await Trash(selected,root.FolderId,99);await Failure(scoped,403,"vault_access_denied");using var wide=await Trash(s,root.FolderId,99);await Failure(wide,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalFact]
    public async Task GivenStaleRootOrLostDeleteSuccess_WhenRetrying_ThenConflictBeforeSuccessAnd404AfterWithoutExtendingDeadline()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);var row=await FolderRow(root.FolderId);var before=await Snapshot(s);using(var stale=await Trash(s,root.FolderId,2))await Failure(stale,409,"revision_conflict");Assert.Equal(before,await Snapshot(s));using(var response=await Trash(s,root.FolderId,1))await Trashed(s,row,[row],[],await Success<DeleteFolderOutput>(response,200));var after=await Snapshot(s);using var retry=await Trash(s,root.FolderId,1);await Failure(retry,404,"not_found");Assert.Equal(after,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenSharedCascadeAlsoContainsDirectlySharedRecord_WhenOwnerDeletes_ThenRecipientReadsAndListsHideAllContentWithoutRevokingGrant()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Create(o);var child=await Create(o,folder:root.FolderId);var record=await CreateRecord(o,child.FolderId);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[root.FolderId],[]);await using(var db=fixture.Context()){var r=await db.Records.SingleAsync(x=>x.PublicId==record.RecordId);db.CollectionRecords.Add(new(){AccountId=o.InternalId,CollectionId=c.Id,RecordId=r.Id});await db.SaveChangesAsync();}using(var before=await Read(s,"/api/records/"+record.RecordId))await Success<RecordDetailsOutput>(before,200);var row=await FolderRow(root.FolderId);var recipientBefore=await Snapshot(s);using var deleted=await Trash(o,root.FolderId,row.Revision);await Success<DeleteFolderOutput>(deleted,200);using var get=await Read(s,"/api/records/"+record.RecordId);await Failure(get,404,"not_found");using var folder=await Read(s,"/api/folders/"+child.FolderId);await Failure(folder,404,"not_found");using var list=await Read(s,"/api/records");Assert.Empty((await Success<RecordListOutput>(list,200)).Items);Assert.Equal(recipientBefore,await Snapshot(s));await using var check=fixture.Context();Assert.Equal(CollectionGrantState.Active,(await check.CollectionGrants.SingleAsync(x=>x.Id==g.Id)).State);
    }
    [FunctionalFact]
    public async Task GivenDamagedOwnedCipher_WhenDeleting_ThenRetainOpaqueBytesAndRemoveActiveVisibility()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);await using(var db=fixture.Context())await db.Folders.Where(x=>x.PublicId==root.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"opaque-damage"u8.ToArray()));var row=await FolderRow(root.FolderId);using var response=await Trash(s,root.FolderId,1);await Trashed(s,row,[row],[],await Success<DeleteFolderOutput>(response,200));}
    private static HttpRequestMessage Delete(State s,string path,byte[] body){var r=Request(s,body,path);r.Method=HttpMethod.Delete;return r;}
    private async Task<HttpResponseMessage> Trash(State s,Guid id,long revision=1){using var req=Delete(s,"/api/folders/"+id,Bytes(new{expectedRevision=revision}));return await Gateway.Client.SendAsync(req);}
    private async Task<VaultFolder> FolderRow(Guid id){await using var db=fixture.Context();return await db.Folders.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<VaultRecord> RecordRow(Guid id){await using var db=fixture.Context();return await db.Records.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task Trashed(State owner,VaultFolder root,VaultFolder[] folders,VaultRecord[] records,DeleteFolderOutput output)
    {
        Assert.Equal(root.PublicId,output.FolderId);Assert.Equal(root.Revision+1,output.Revision);Assert.True(output.ServerSequence>root.ServerSequence);Assert.InRange(output.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.NotEqual(Guid.Empty,output.TrashOperationId);Assert.Equal(TimeSpan.Zero,output.DeletedAt.Offset);Assert.Equal(0,output.DeletedAt.Ticks%10);Assert.Equal(TimeSpan.FromDays(30),output.PurgeAt-output.DeletedAt);Assert.Equal(TimeSpan.Zero,output.PurgeAt.Offset);await using var db=fixture.Context();var op=await db.TrashOperations.SingleAsync(x=>x.PublicId==output.TrashOperationId);Assert.Equal(owner.InternalId,op.AccountId);Assert.Equal("folder",op.RootResourceKind);Assert.Equal(root.PublicId,op.RootResourceId);Assert.Equal(output.DeletedAt,op.DeletedAt);Assert.Equal(output.PurgeAt,op.PurgeAt);var entries=await db.TrashEntries.Where(x=>x.OperationId==op.Id).ToListAsync();Assert.Equal(folders.Length+records.Length,entries.Count);var queue=await db.RetentionWorkItems.SingleAsync(x=>x.OperationKey=="trash/"+output.TrashOperationId);Assert.Equal(output.PurgeAt,queue.DueAt);Assert.Null(queue.CompletedAt);
        foreach(var old in folders){var row=await FolderRow(old.PublicId);Assert.Equal(old.Envelope,row.Envelope);Assert.Equal(old.EditedAt,row.EditedAt);Assert.Equal(old.AccountId,row.AccountId);Assert.Equal(old.Revision+1,row.Revision);Assert.True(row.ServerSequence>old.ServerSequence);Assert.Equal(output.DeletedAt,row.DeletedAt);Assert.Equal(output.PurgeAt,row.PurgeAt);Assert.Null(row.ParentFolderId);Assert.False(await db.ProfileFolders.AnyAsync(x=>x.FolderId==row.Id));Assert.False(await db.CollectionFolders.AnyAsync(x=>x.FolderId==row.Id));Assert.Contains(entries,x=>x.ResourceKind=="folder"&&x.ResourceId==row.PublicId);}
        foreach(var old in records){var row=await RecordRow(old.PublicId);Assert.Equal(old.Envelope,row.Envelope);Assert.Equal(old.EditedAt,row.EditedAt);Assert.Equal(old.AccountId,row.AccountId);Assert.Equal(old.Revision+1,row.Revision);Assert.True(row.ServerSequence>old.ServerSequence);Assert.Equal(output.DeletedAt,row.DeletedAt);Assert.Equal(output.PurgeAt,row.PurgeAt);Assert.Null(row.FolderId);Assert.False(await db.ProfileRecords.AnyAsync(x=>x.RecordId==row.Id));Assert.False(await db.CollectionRecords.AnyAsync(x=>x.RecordId==row.Id));Assert.Contains(entries,x=>x.ResourceKind=="record"&&x.ResourceId==row.PublicId);}
    }
