    [FunctionalTheory][InlineData("profile",false)][InlineData("profile",true)][InlineData("collection",false)][InlineData("collection",true)][InlineData("folder",false)][InlineData("folder",true)]
    public async Task GivenCorruptOrExhaustedActiveExternalParent_WhenDeleting_ThenRollbackCompleteGraph(string kind,bool exhausted)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);await Members(s,a.Collection,[],[root.Id]);var p=await Profile(s,owner,key,folders:[root.PublicId]);await using(var db=fixture.CreateContext()){if(kind=="profile")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,exhausted?ProtocolBinary.MaxInteger:0));if(kind=="collection")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,exhausted?ProtocolBinary.MaxInteger:0));if(kind=="folder")await db.Folders.Where(x=>x.Id==a.Folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,exhausted?ProtocolBinary.MaxInteger:0));}var before=await Snapshot(s);Assert.Equal(exhausted?"revision_conflict":"persistence_unavailable",(await Trash(s,root)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("folder")][InlineData("record")]
    public async Task GivenUnrepresentableStoredCascadeEditTime_WhenDeleting_Then503BeforeAnyMutation(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var record=await Record(s,root.Id);await using(var db=fixture.CreateContext()){if(kind=="folder")await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.EditedAt,DateTimeOffset.MinValue));else await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.EditedAt,DateTimeOffset.MinValue));}var before=await Snapshot(s);Assert.Equal("persistence_unavailable",(await Trash(s,root)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("folder")][InlineData("record")]
    public async Task GivenTypedTerminalDescendant_WhenTrashingRoot_ThenExcludeTerminalBranchWithoutChangingRetainedRows(string kind)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var active=await Record(s,root.Id);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceKind=kind,ResourceId=kind=="folder"?child.PublicId:record.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var previousChild=Bytes(await Row(child.Id));var previousRecord=Bytes(await RecordRow(record.Id));await Success(s,root,kind=="folder"?[root]:[root,child],[active],await Trash(s,root));Assert.Equal(previousRecord,Bytes(await RecordRow(record.Id)));if(kind=="folder")Assert.Equal(previousChild,Bytes(await Row(child.Id)));
    }
    [FunctionalTheory][InlineData("parent")][InlineData("sibling")]
    public async Task GivenNativeMemberLeafGrant_WhenDeletingPrivateParentOrSibling_Then404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var leaf=await Folder(o,a.Folder.Id);var sibling=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[leaf.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,leaf.PublicId),default)).Error);var before=await Snapshot(o);Assert.Equal("not_found",(await Trash(s,kind=="parent"?a.Folder:sibling,99)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalFact]
    public async Task GivenActualOwnerRotationWaitsForCascadeAccount_WhenTrashCommits_ThenStaleInventoryConflictsAndProofSurvives()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),[new("account",s.AccountId,1,ProfileSetup.Envelope(2)),new("folder",root.PublicId,1,ProfileSetup.Envelope(2)),new("folder",child.PublicId,1,ProfileSetup.Envelope(2)),new("record",record.PublicId,1,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));var trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new BeforeContent(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var rotation=new VaultProtectionChangeStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"account"))).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),ct.Token);try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(rotation.IsCompleted);}finally{release.TrySetResult();}await Success(s,root,[root,child],[record],await trash);Assert.Equal("revision_conflict",(await rotation).Error);await using var db=fixture.CreateContext();Assert.False((await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==challenge.ChallengeId)).Consumed);Assert.Equal(1,(await db.VaultProtections.SingleAsync(x=>x.AccountId==s.InternalId)).Revision);
    }
    [FunctionalFact]
    public async Task GivenDeepUnrelatedInventories_WhenTrashingSmallSubtree_ThenBoundedRootAndOnlyCapturedStructuralLocks()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,client);var upper=await Folder(s);var parent=await Folder(s,upper.Id);var root=await Folder(s,parent.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);foreach(var state in new[]{s,foreign}){long? previous=null;for(var i=0;i<50;i++){var f=await Folder(state,previous);previous=f.Id;}for(var i=0;i<50;i++)await Folder(state);}
        var capture=new Capture(fixture);await Success(s,root,[root,child],[record],await new FolderTrashStore(new ProfileSetup.Factory(fixture,capture)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default));Assert.NotNull(capture.Plan);using var doc=JsonDocument.Parse(capture.Plan!);var nodes=Nodes(doc.RootElement[0].GetProperty("Plan")).ToArray();Assert.Equal(1,Assert.Single(nodes.Where(x=>x.TryGetProperty("Subplan Name",out var n)&&n.GetString()=="CTE candidates")).GetProperty("Actual Rows").GetInt32());Assert.Equal(3,Assert.Single(nodes.Where(x=>x.TryGetProperty("Subplan Name",out var n)&&n.GetString()=="CTE ancestry")).GetProperty("Actual Rows").GetInt32());Assert.Single(capture.Locks.Where(x=>x.Contains("FROM cerberus.account")));Assert.DoesNotContain(capture.Locks,x=>x.Contains("cerberus.collection_grant"));var folders=Assert.Single(capture.Locks.Where(x=>x.Contains("FROM cerberus.folder")&&x.Contains("FOR UPDATE")));Assert.Contains("ORDER BY",folders);Assert.Single(capture.Locks.Where(x=>x.Contains("FROM cerberus.record")&&x.Contains("FOR UPDATE")));Assert.Null((await Row(upper.Id)).DeletedAt);Assert.Equal(upper.Revision,(await Row(upper.Id)).Revision);
    }
    private static IEnumerable<JsonElement> Nodes(JsonElement node){yield return node;if(node.TryGetProperty("Plans",out var children))foreach(var c in children.EnumerateArray())foreach(var n in Nodes(c))yield return n;}
    private sealed class Capture(PostgresFixture fixture):DbCommandInterceptor
    {
        public List<string> Locks{get;}=[];public string? Plan{get;private set;}
        private void Note(DbCommand c){if(c.CommandText.Contains("FOR UPDATE")||c.CommandText.Contains("FOR NO KEY UPDATE")||c.CommandText.Contains("FOR SHARE"))Locks.Add(c.CommandText);}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Note(c);return ValueTask.FromResult(r);}
        public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Note(c);if(Plan is null&&c.CommandText.StartsWith("WITH RECURSIVE")){await using var db=fixture.CreateContext();await db.Database.OpenConnectionAsync(ct);await using var cmd=db.Database.GetDbConnection().CreateCommand();cmd.CommandText="EXPLAIN (ANALYZE, FORMAT JSON) "+c.CommandText;foreach(var p in c.Parameters.Cast<NpgsqlParameter>())cmd.Parameters.Add(p.Clone());Plan=(string)(await cmd.ExecuteScalarAsync(ct))!;}return r;}
    }
