    [FunctionalTheory][InlineData("account")][InlineData("session")][InlineData("profile")][InlineData("collection")][InlineData("folder")][InlineData("record")]
    public async Task GivenNaturalExpiryDuringEachCascadeLockWait_WhenDeleting_Then403BeforeStaleRevisionAndNoMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s);var record=await Record(s,root.Id);await Members(s,a.Collection,[record.Id],[root.Id]);var p=await Profile(s,owner,key,folders:[root.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);
        await using var held=fixture.CreateContext();await using var tx=await held.Database.BeginTransactionAsync();var id=kind switch{"account"=>s.InternalId,"profile"=>p.Id,"collection"=>a.Collection.Id,"folder"=>root.Id,_=>record.Id};var table=kind=="session"?"vault_access_session":kind;await held.Database.ExecuteSqlRawAsync(kind=="session"?"SELECT FROM cerberus.vault_access_session WHERE handle_verifier={0} FOR UPDATE":"SELECT FROM cerberus."+table+" WHERE id={0} FOR UPDATE",kind=="session"?(object)s.Verifier:id);
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var pending=new FolderTrashStore(new ProfileSetup.Factory(fixture,new Signal(reached,table))).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,99),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);await Past(deadline);await tx.CommitAsync();Assert.Equal("vault_access_denied",(await pending).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("expiry","vault_access_denied")][InlineData("folderTerminal","not_found")][InlineData("actorTerminal","not_found")]
    public async Task GivenChangeImmediatelyBeforeRootGuard_WhenDeleting_ThenDenyWithoutPartialCascade(string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var deadline=DateTimeOffset.UtcNow.AddSeconds(2);if(kind=="expiry")await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);var hook=new BeforeRoot(async()=>{if(kind=="expiry"){await Past(deadline);return;}await using var db=fixture.CreateContext();db.TerminalErasures.Add(new(){ResourceKind=kind=="folderTerminal"?"folder":"account",ResourceId=kind=="folderTerminal"?root.PublicId:s.AccountId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();});Assert.Equal(error,(await new FolderTrashStore(new ProfileSetup.Factory(fixture,hook)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("folder")][InlineData("record")][InlineData("profile")][InlineData("collection")]
    public async Task GivenUncapturedExistingItemOrAssociationBeforeContentLock_WhenDeleting_Then409PreservesNewInventory(string kind)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var outside=await Folder(s);var record=await Record(s);var p=await Profile(s,owner,key);var a=await AssociationSetup.Items(fixture,s);string? winning=null;var hook=new BeforeContent(async()=>{await using var db=fixture.CreateContext();if(kind=="folder")await db.Folders.Where(x=>x.Id==outside.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,(long?)root.Id));else if(kind=="record")await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.FolderId,(long?)root.Id));else{if(kind=="profile")db.ProfileFolders.Add(new(){AccountId=s.InternalId,ProfileId=p.Id,FolderId=root.Id});else db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=a.Collection.Id,FolderId=root.Id});await db.SaveChangesAsync();}winning=await Snapshot(s);});Assert.Equal("revision_conflict",(await new FolderTrashStore(new ProfileSetup.Factory(fixture,hook)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.NotNull(winning);Assert.Equal(winning,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("root")][InlineData("child")][InlineData("record")][InlineData("links")][InlineData("parent")][InlineData("operation")][InlineData("entry")][InlineData("queue")]
    public async Task GivenFaultAfterPartialCascadeWork_WhenDeleting_ThenRollbackEveryMemberAndRetrySucceeds(string stage)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);await Members(s,a.Collection,[record.Id],[root.Id]);await Profile(s,owner,key,folders:[root.PublicId],records:[record.PublicId]);var before=await Snapshot(s);var fail=new Fail(stage);Assert.Equal("persistence_unavailable",(await new FolderTrashStore(new ProfileSetup.Factory(fixture,fail)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.True(fail.Triggered);Assert.Equal(before,await Snapshot(s));await Success(s,root,[root,child],[record],await Trash(s,root));
    }
    [FunctionalTheory][InlineData("root",false)][InlineData("root",true)][InlineData("child",false)][InlineData("child",true)][InlineData("parent",false)][InlineData("parent",true)]
    public async Task GivenExhaustedOrRegressedSequenceAtDifferentCascadeStages_WhenDeleting_ThenRollbackAllContent(string stage,bool regression)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);await Folder(s,root.Id);await Profile(s,owner,key,folders:[root.PublicId]);var before=await Snapshot(s);await using var db=fixture.CreateContext();var previous=await db.Database.SqlQuery<long>($"SELECT nextval('cerberus.server_sequence') AS \"Value\"").SingleAsync();var hook=new AtWrite(stage,async()=>{await using var other=fixture.CreateContext();await other.Database.ExecuteSqlRawAsync(regression?"SELECT setval('cerberus.server_sequence',1,false)":"SELECT setval('cerberus.server_sequence',9007199254740991,true)");});try{Assert.Equal(regression?"persistence_unavailable":"revision_conflict",(await new FolderTrashStore(new ProfileSetup.Factory(fixture,hook)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.True(hook.Triggered);Assert.Equal(before,await Snapshot(s));}finally{await db.Database.ExecuteSqlInterpolatedAsync($"SELECT setval('cerberus.server_sequence',{previous},true)");}
    }
    [FunctionalTheory][InlineData("folder",false)][InlineData("folder",true)][InlineData("record",false)][InlineData("record",true)]
    public async Task GivenActualRecipientContentEditAndOwnerCascade_WhenCompeting_ThenOneWinnerWithoutCollectionContentLockCycle(string resource,bool trashFirst)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var root=await Folder(o);var record=await Record(o,root.Id);await Members(o,a.Collection,[],[root.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));Task<VaultResult<FolderTrashDetails>> trash;Task<string?> edit;
        async Task<string?> Edit(IDbContextFactory<AppDbContext> f){return resource=="folder"?(await new FolderUpdateStore(f).UpdateAsync(new(s.Actor,s.Verifier,root.PublicId,new(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch)),ct.Token)).Error:(await new RecordUpdateStore(f).UpdateAsync(new(s.Actor,s.Verifier,record.PublicId,new(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch)),ct.Token)).Error;}
        if(trashFirst){trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new BeforeContent(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(o.Actor,o.Verifier,root.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));edit=Edit(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection")));}
        else{edit=Edit(new ProfileSetup.Factory(fixture,new PauseUpdate(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);})));await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection"))).TrashAsync(new(o.Actor,o.Verifier,root.PublicId,1),ct.Token);}
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(trashFirst?edit.IsCompleted:trash.IsCompleted);}finally{release.TrySetResult();}await Task.WhenAll(trash,edit);
        if(trashFirst){Assert.Null(trash.Result.Error);Assert.Equal("not_found",edit.Result);}else{Assert.Null(edit.Result);Assert.Equal("revision_conflict",trash.Result.Error);await using var db=fixture.CreateContext();Assert.False(await db.TrashOperations.AnyAsync(x=>x.AccountId==o.InternalId));Assert.Null((await Row(root.Id)).DeletedAt);Assert.Equal(2,resource=="folder"?(await Row(root.Id)).Revision:(await RecordRow(record.Id)).Revision);}
    }
    [FunctionalTheory][InlineData("folderCreate")][InlineData("recordCreate")][InlineData("recordMove")][InlineData("association")]
    public async Task GivenCascadeOwnsAccountBeforeContentLocks_WhenActualOwnerWriterStarts_ThenSerializeWithoutDeadlock(string writer)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var outside=await Record(s);var p=await Profile(s,owner,key,folders:[root.PublicId]);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));var trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new BeforeContent(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var f=new ProfileSetup.Factory(fixture,new Signal(blocked,"account"));
        async Task<string?> Write()=>writer switch{"folderCreate"=>(await new FolderCreateStore(f).CreateAsync(new(s.Actor,s.Verifier,new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],root.PublicId)),ct.Token)).Error,"recordCreate"=>(await new RecordCreateStore(f).CreateAsync(new(s.Actor,s.Verifier,new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],root.PublicId)),ct.Token)).Error,"recordMove"=>(await new RecordMoveStore(f).MoveAsync(new(s.Actor,s.Verifier,outside.PublicId,1,root.PublicId),ct.Token)).Error,_=>(await new ProfileAssociationStore(f).SetAsync(new(s.Actor,s.Verifier,p.PublicId,new(p.Revision,[],[],[])),ct.Token)).Error};
        var pending=Write();try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);}finally{release.TrySetResult();}Assert.Null((await trash).Error);Assert.Equal(writer=="association"?"revision_conflict":"not_found",await pending);Assert.Equal(Bytes(outside),Bytes(await RecordRow(outside.Id)));
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenRetainedFolderCascade_WhenNativeRotatingProtection_ThenRequireCompleteRetainedInventoryAndPreserveTrash(bool omit)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var trash=await Trash(s,root);Assert.Null(trash.Error);var all=new[]{new ContentReplacement("account",s.AccountId,1,ProfileSetup.Envelope(2)),new ContentReplacement("folder",root.PublicId,2,ProfileSetup.Envelope(2)),new ContentReplacement("folder",child.PublicId,2,ProfileSetup.Envelope(2)),new ContentReplacement("record",record.PublicId,2,ProfileSetup.Envelope(2))};var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),omit?all[..3]:all);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;var result=await new VaultProtectionChangeStore(fixture).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),default);Assert.Equal(omit?"validation_failed":null,result.Error);
        await using var db=fixture.CreateContext();foreach(var id in new[]{root.Id,child.Id}){var row=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==id);Assert.Equal(trash.Data!.DeletedAt,row.DeletedAt);Assert.Equal(trash.Data.PurgeAt,row.PurgeAt);Assert.Equal(omit?2:3,row.Revision);}var rr=await RecordRow(record.Id);Assert.Equal(trash.Data!.PurgeAt,rr.PurgeAt);Assert.Equal(omit?2:3,rr.Revision);Assert.Equal(3,await db.TrashEntries.CountAsync(x=>x.OperationId==db.TrashOperations.Single(o=>o.PublicId==trash.Data.TrashOperationId).Id));
    }
    [FunctionalTheory][InlineData("cancel")][InlineData("timeout")][InlineData("db")][InlineData("dbUpdate")][InlineData("json")][InlineData("format")][InlineData("wrapped")]
    public async Task GivenNecessaryProviderFailure_WhenDeleting_Then503WithNoLeakedException(string kind)
    {Exception e=kind switch{"cancel"=>new OperationCanceledException(),"timeout"=>new TimeoutException(),"db"=>new NpgsqlException("private-database"),"dbUpdate"=>new DbUpdateException(),"json"=>new JsonException(),"format"=>new FormatException(),_=>new InvalidOperationException("private",new TimeoutException())};Assert.Equal("persistence_unavailable",(await new FolderTrashStore(new ThrowingFactory(e)).TrashAsync(new(Guid.NewGuid(),new string('a',64),Guid.NewGuid(),1),default)).Error);}
    [FunctionalFact]
    public async Task GivenActualProviderOutageOrCancelledCaller_WhenDeleting_Then503OrExactCancellation()
    {var request=new FolderTrashRequest(Guid.NewGuid(),new string('a',64),Guid.NewGuid(),1);var dead=new ProfileSetup.Factory(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql("Host=127.0.0.1;Port=1;Database=absent;Username=fixture;Password=fixture;Timeout=1").Options);Assert.Equal("persistence_unavailable",(await new FolderTrashStore(dead).TrashAsync(request,default)).Error);using var ct=new CancellationTokenSource();ct.Cancel();var e=await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Store().TrashAsync(request,ct.Token));Assert.Equal(ct.Token,e.CancellationToken);}
    private sealed class ThrowingFactory(Exception exception):IDbContextFactory<AppDbContext>{public AppDbContext CreateDbContext()=>throw exception;public Task<AppDbContext> CreateDbContextAsync(CancellationToken ct=default)=>Task.FromException<AppDbContext>(exception);}
    private static async Task Past(DateTimeOffset t){var delay=t-DateTimeOffset.UtcNow;if(delay>TimeSpan.Zero)await Task.Delay(delay+TimeSpan.FromMilliseconds(100));}
    private static bool RootWrite(DbCommand c)=>c.CommandText.Contains("UPDATE cerberus.folder AS root");
    private static bool ChildWrite(DbCommand c)=>c.CommandText.Contains("UPDATE cerberus.folder AS child");
    private static bool RecordWrite(DbCommand c)=>c.CommandText.Contains("UPDATE cerberus.record AS child");
    private static bool ParentWrite(DbCommand c)=>c.CommandText.StartsWith("UPDATE cerberus.profile SET")||c.CommandText.StartsWith("UPDATE cerberus.collection SET")||c.CommandText.StartsWith("UPDATE cerberus.folder SET");
    private sealed class Signal(TaskCompletionSource reached,string table):DbCommandInterceptor
    {private void Check(DbCommand c){if(c.CommandText.Contains("cerberus."+table)&&c.CommandText.Contains("FOR "))reached.TrySetResult();}public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}}
    private sealed class BeforeRoot(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&RootWrite(c)){used=true;await action();}return r;}}
    private sealed class BeforeContent(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&c.CommandText.Contains("cerberus.folder")&&c.CommandText.Contains("FOR UPDATE")){used=true;await action();}return r;}}
    private sealed class PauseUpdate(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&(c.CommandText.Contains("UPDATE cerberus.folder AS r")||c.CommandText.Contains("UPDATE cerberus.record AS r"))){used=true;await action();}return r;}}
    private sealed class AtWrite(string stage,Func<Task> action):DbCommandInterceptor
    {public bool Triggered{get;private set;}public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!Triggered&&(stage=="root"&&RootWrite(c)||stage=="child"&&ChildWrite(c)||stage=="parent"&&ParentWrite(c))){Triggered=true;await action();}return r;}}
    private sealed class Fail(string stage):DbCommandInterceptor
    {
        public bool Triggered{get;private set;}private bool written;
        private void Check(DbCommand c){if(Triggered)return;var sql=c.CommandText;var hit=written||stage=="links"&&(sql.Contains("DELETE FROM cerberus.profile_folder")||sql.Contains("DELETE FROM cerberus.collection_folder"))||stage=="parent"&&ParentWrite(c)||stage=="operation"&&sql.Contains("INSERT INTO cerberus.trash_operation")||stage=="entry"&&sql.Contains("INSERT INTO cerberus.trash_entry")||stage=="queue"&&sql.Contains("INSERT INTO cerberus.retention_work_item");if(hit){Triggered=true;throw new TimeoutException("synthetic cascade outage");}}
        public override ValueTask<int> NonQueryExecutedAsync(DbCommand c,CommandExecutedEventData d,int r,CancellationToken ct=default){if(r>0&&(stage=="root"&&RootWrite(c)||stage=="child"&&ChildWrite(c)||stage=="record"&&RecordWrite(c)))written=true;return ValueTask.FromResult(r);}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}
        public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}
    }
