from pathlib import Path
import json,subprocess
w=Path('/tmp/cerberus-uc27-worktree');base='a03bf90a99bc6310e5a8b11841203363fa0a7c8b';head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip();workspace=w/'.superpowers/sdd/2026-10-09-uc-27-delete-folder';ledger=(workspace/'progress.md').read_text();assert all(f'Task {n}: complete' in ledger for n in (1,2,3));rulings=[x for x in ledger.splitlines() if 'Ruling:' in x];assert len(rulings)==12
v=json.loads(Path('/tmp/cerberus-uc27-validation.json').read_text());assert v['tests']==6110;assert not subprocess.check_output(['git','status','--porcelain'],cwd=w,text=True).strip();plan=w/'docs/superpowers/plans/2026-10-09-uc-27-delete-folder.md';spec=w/'docs/superpowers/specs/2026-10-09-uc-27-delete-folder.md';focus=plan.read_text().split('## Review Focus\n',1)[1].split('### Task 1:',1)[0];packages=list(workspace.glob('review-*.diff'));assert len(packages)==1
old=Path('/tmp/cerberus-uc26-review-prompt.md').read_text();tail=old.split('\n## Git Range to Review\n',1)[1].replace('9aa8e51e7ee39a78294d072f36e17833306a856c',base).replace('612c5b8de98a76f615d49f61e2883b0693d30c30',head)
prompt=f'''You are a Senior Code Reviewer with expertise in software architecture,
design patterns, and best practices. Your job is to review completed work
against its plan or requirements and identify issues before they cascade.

## What Was Implemented

UC27 owner-only recoverable folder deletion. DELETE /api/folders/{{id}} accepts strict required expectedRevision, canonical UUID path, one vault header/noquery/bounded UTF8/no-store; exact six fields folderId/trashOperationId/revision/serverSequence/deletedAt/purgeAt. Visible owned root admits active owned subtree/contained records, even selected descendants lack separate links or records are directly shared elsewhere. Folder-only PF/CF authority and full active same-owner root ancestry/current typed account/session/selection lifecycle; native RO/RW foreign scope403 after every needed native contributor validates, record-only scope404. Damaged owned ciphertext retained without parsing. Own account FOR UPDATE/session UPDATE serializes current owners/implicit new entity FK; ordered own profiles/collections NO KEY UPDATE then captured subtree+externalparent folders UPDATE/records UPDATE/typed links UPDATE, no foreign account/profile/grant/upward-chain locks. Fresh root authority after waiting phases, complete captured active inventory and stored links reload/full root guard. Root write is atomic authorization linearization; all members guarded/verified, common actual database root UTC microsecond720hour deadline, rev+1 and safe strictly increasing sequence. Preserve opaquebytes/edittime/ownership; detach parent/direct PFPRCFCR; snapshot original sorted public parents/links inactiveincluded; active external profiles/collections/rootparent bump once; no ancestor/subtree second bumps. Independently actually trashed detached records/folders and typed terminal branches untouched; active oldtypedentry409. One operation/many typed entries/one trash retention queue/one commit, rollback all graph stages. Existing missing trash handler retries; UC50–53 restore/physical purge and UC48 sync remain later gates. Retained complete native protection rotation includes all members/deadlines/entries. No schema/dependency/crypto changes.

## Requirements / Plan

Read only {w}. Binding spec {spec}; completed plan {plan}; ledger {workspace}/progress.md; complete review package {packages[0]}. All three tasks complete. Fresh unfiltered6110PASS zero fail/skip in /tmp/cerberus-uc27-validation.json and coverage.log: {json.dumps(v['families'])}; actual Summary {v['line']}%line/{v['branch']}%branch, all six assemblies>=90line. Focused Command75/Data147/HTTP108; whole Command987/Data2245. Installed genuine missing-contract/store CS0246 occurred BEFORE products, and actual missing DELETE RED108cases had103fail solely405 +5middlewarepass after successful native prerequisites BEFORE route/3DI. First actual Data147run146PASS/1FAIL only EXPLAIN GetInt32 decimalfixture parser; corrected test GetDouble like existing stores, retained actual EXPLAIN /tmp/cerberus-uc27-explain.json. Post-store compile had omitted test-only Malformed helper/xUnit2031 analyzer failures, corrected only helpers/assert form, retained log, not claimed runtimeRED. No runtime product correction. All three test files installed BEFORE respective genuineRED; no later broadconfidence suite claims. HTTP draft preflight corrected obsolete Update/Replacement testhelpers and Startup builder.Services anchor outside worktree before installation; actual installed tests compiled immediately and all108 firstpostroute passed. Inspect actual source/evidence, do not rerun builds/tests.

Exactly ONE ordinary whole-branch review under executing-plans. Independent formal security/crypto/protocol and real external-client operability approvals explicitly development-only deferred by user; release/main/tag gates remain. Review concrete ownership/native boundary/strict input/output/transactions/lifecycle/concurrency, not formal certification. Ordinary lockedrestore/NuGetdirect+transitive/nativeOSV153/corpus322x4/helpers36+23/specs/OpenAPIwrite+drift+shape/range whitespace logs /tmp/cerberus-uc27-*. Helper89.9/90/94.7 are examples, not production Summary. Shared OpenAPI header/body optional/outputrequired[]/wrappernullable and actual empty413 advertisedProblemDetails remain inherited release findings; re-grade actualeffects. UC25 queryctorrecordId, UC23 narrowed grant/post-parentfailurefixtures, UC22 permissionoutage500 and UC21formatting are prior outside-diff followups. UC27 actual record-only fixtures establish native record GET before folder404 and real CF/nativewide/Master/PerProfile403; selected owner CF covers actual native access and selectedprofile unchanged. Actual recipient folder+record writers bothorders synchronize collection locks; actual owner create/recordmove/profileassociation/rotation race serialize ataccount. Growth tests reparent EXISTING detached folders/records or insert existing-parent links BEFOREcontentlock; newentityINSERT blocks on strongaccount implicitFK, proved actual writers. Actual expiry ataccount/session/profile/collection/folder/record phases and immediatelybefore root guard; fullgraph faults assert triggered afterroot/child/record/link/parent/operation/entry/queue andcleanretry. Actual earlier RecordTrashStore/FolderTrashStore deletions detach and rootrevision reload preserves deadlines. Complete account+root+child+record native rotation AFTERtrash include/omit and trash-first rotation conflict prove retainedinventory. Actual EXPLAIN target1/selfancestry3 among200unrelated folders plus exact held parent/root/child lockIDs/capturedrecord and ownaccount only; bounded evidence not productionload qualification. Defensive corrupt ancestry remains SQL/schema guard, no integrity-bypass fixture claimed. Complete physical purge/restoration/durable sync are explicitly later requirements; retained snapshots must be revalidated and old typed entries consumed before re-trash. Rootguard authorized atomic transaction permits expiry AFTERlinearization; not stale permission beforewrite. Mandatory BEFORE UC35 implicit recipient-account FK audit remains a later gate, not certified future grant safety. Fresh UC26 merged/tested5780/exactCI baseline reuse then current newcheckout fullsuite; executor provenance not remote certification.

Every behavior considered but set aside belongs in Declined to judge with a reason; executor must rule explicitly on each. No checkout/index/HEAD/branch edits, builds/test reruns, subagents, GitHub actions/approvals. Write ONLY /tmp/cerberus-uc27-final-review.md outside worktree; return verdict/findings by actual effect with file:line. No second/duplicate reviewer.

Verbatim Review Focus:
{focus}
ALL12 initial rulings with reasons/costs:
'''+ '\n'.join(rulings)+'\n\n## Git Range to Review\n'+tail
assert '[HEAD_SHA]' not in prompt and '[BASE_SHA]' not in prompt
Path('/tmp/cerberus-uc27-review-prompt.md').write_text(prompt);Path('/tmp/cerberus-uc27-tested-head.txt').write_text(head+'\n');print('ONE review prompt complete:',head,'all12Rulings and actual6110PASS evidence')
