using System.Text.Json;
using System.Text.Json.Serialization;
using ArturRios.Cerberus.Command.Folders;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Folders;
using ArturRios.Cerberus.TestSupport;
using ArturRios.Cerberus.WebApi;
using Moq;
namespace ArturRios.Cerberus.Command.Tests;
public class MoveFolderHandlerTests
{
    private const string Access="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    private readonly Guid actor=Guid.NewGuid(),target=Guid.NewGuid(),parent=Guid.NewGuid();
    private static readonly JsonSerializerOptions Json=new(ProtectionFixture.Json){NumberHandling=JsonNumberHandling.Strict,Converters={new CanonicalGuidConverter()}};
    [UnitTheory][InlineData("actor","authentication_required")][InlineData("missing","vault_access_required")][InlineData("empty","validation_failed")][InlineData("handle","validation_failed")][InlineData("noncanonical","validation_failed")][InlineData("id","validation_failed")][InlineData("parent","validation_failed")][InlineData("self","validation_failed")][InlineData("zero","validation_failed")][InlineData("negative","validation_failed")][InlineData("unsafe","validation_failed")]
    public async Task GivenInvalidContextRevisionOrSelfParent_WhenHandling_ThenRejectBeforePersistence(string kind,string error)
    {var c=Command();c.SetContext(kind=="actor"?Guid.Empty:actor,kind=="missing"?null:kind=="empty"?"":kind=="handle"?"bad":kind=="noncanonical"?new string('A',42)+"B":Access,kind=="id"?Guid.Empty:target);c.ExpectedRevision=kind=="zero"?0:kind=="negative"?-1:kind=="unsafe"?ProtocolBinary.MaxInteger+1:1;if(kind=="parent")c.ParentFolderId=Guid.Empty;if(kind=="self")c.ParentFolderId=target;var r=await Handler(new Mock<IFolderMoveStore>(MockBehavior.Strict).Object).HandleAsync(c);Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains(error,r.Errors);}
    [UnitTheory][InlineData(false,false)][InlineData(true,false)][InlineData(false,true)][InlineData(true,true)]
    public async Task GivenValidMoveMetadata_WhenHandling_ThenForwardTrustedContextAndReturnExactFourFields(bool nullParent,bool largestRevision)
    {
        var c=Command();c.ParentFolderId=nullParent?null:parent;if(largestRevision)c.ExpectedRevision=ProtocolBinary.MaxInteger-1;var d=new FolderMoveDetails(target,c.ParentFolderId,c.ExpectedRevision+1,largestRevision?ProtocolBinary.MaxInteger:1);using var ct=new CancellationTokenSource();FolderMoveRequest? received=null;CancellationToken token=default;var store=new Mock<IFolderMoveStore>(MockBehavior.Strict);store.Setup(x=>x.MoveAsync(It.IsAny<FolderMoveRequest>(),It.IsAny<CancellationToken>())).Returns<FolderMoveRequest,CancellationToken>((r,t)=>{received=r;token=t;return Task.FromResult(new VaultResult<FolderMoveDetails>(d));});var result=await Handler(store.Object).HandleAsync(c,ct.Token);
        Assert.True(result.Success);Assert.Contains("folder_moved",result.Messages);Assert.Equal(target,result.Data!.FolderId);Assert.Equal(c.ParentFolderId,result.Data.ParentFolderId);Assert.Equal(d.Revision,result.Data.Revision);Assert.Equal(d.ServerSequence,result.Data.ServerSequence);Assert.Equal(actor,received!.Actor);Assert.Equal(target,received.FolderId);Assert.Equal(c.ExpectedRevision,received.ExpectedRevision);Assert.Equal(c.ParentFolderId,received.ParentFolderId);Assert.Equal("66687aadf862bd776c8fc18b8e9f8e20089714856ee233b3902a591d0d5f2925",received.AccessVerifier);Assert.Equal(ct.Token,token);
        using var output=JsonDocument.Parse(JsonSerializer.Serialize(result.Data,Json));Assert.Equal(new[]{"folderId","parentFolderId","revision","serverSequence"},output.RootElement.EnumerateObject().Select(x=>x.Name).Order());Assert.Equal(nullParent?JsonValueKind.Null:JsonValueKind.String,output.RootElement.GetProperty("parentFolderId").ValueKind);using var input=JsonDocument.Parse(JsonSerializer.Serialize(c,Json));Assert.Equal(new[]{"expectedRevision","parentFolderId"},input.RootElement.EnumerateObject().Select(x=>x.Name).Order());
    }
    [UnitTheory][InlineData("validation_failed",400)][InlineData("not_found",404)][InlineData("vault_access_denied",403)][InlineData("revision_conflict",409)][InlineData("persistence_unavailable",503)][InlineData("secret_owner_123",503)][InlineData("authentication_required",503)][InlineData("vault_access_required",503)][InlineData("identity_unavailable",503)][InlineData("folder_moved",503)][InlineData("",503)]
    public async Task GivenStoreFailure_WhenHandling_ThenOnlyAllowExpectedSafeCodes(string error,int status)
    {var store=new Mock<IFolderMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<FolderMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(new VaultResult<FolderMoveDetails>(Error:error));var r=await Handler(store.Object).HandleAsync(Command());var expected=error is "validation_failed" or "not_found" or "vault_access_denied" or "revision_conflict"?error:"persistence_unavailable";Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains(expected,r.Errors);Assert.Equal(status,MoveFolderMessages.StatusCodes[expected]);}
    [UnitTheory][InlineData("not_found")][InlineData("validation_failed")][InlineData("vault_access_denied")][InlineData("revision_conflict")][InlineData("persistence_unavailable")][InlineData("secret_owner_123")]
    public async Task GivenStoreErrorAndData_WhenHandling_Then503WithoutPartialPayload(string error)
    {var store=new Mock<IFolderMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<FolderMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(new VaultResult<FolderMoveDetails>(Details(),error));var r=await Handler(store.Object).HandleAsync(Command());Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains("persistence_unavailable",r.Errors);}
    [UnitTheory][InlineData("nullResult")][InlineData("nullData")][InlineData("folderId")][InlineData("emptyId")][InlineData("parentFolderId")][InlineData("emptyFolder")][InlineData("nullFolder")][InlineData("revision0")][InlineData("revisionOld")][InlineData("revisionAhead")][InlineData("unsafeRevision")][InlineData("sequence0")][InlineData("negativeSequence")][InlineData("unsafeSequence")]
    public async Task GivenMalformedStoreSuccess_WhenHandling_Then503WithoutMetadata(string kind)
    {FolderMoveDetails? d=Details();d=kind switch{"nullData"=>null,"folderId"=>d with{FolderId=Guid.NewGuid()},"emptyId"=>d with{FolderId=Guid.Empty},"parentFolderId"=>d with{ParentFolderId=Guid.NewGuid()},"emptyFolder"=>d with{ParentFolderId=Guid.Empty},"nullFolder"=>d with{ParentFolderId=null},"revision0"=>d with{Revision=0},"revisionOld"=>d with{Revision=1},"revisionAhead"=>d with{Revision=3},"unsafeRevision"=>d with{Revision=ProtocolBinary.MaxInteger+1},"sequence0"=>d with{ServerSequence=0},"negativeSequence"=>d with{ServerSequence=-1},"unsafeSequence"=>d with{ServerSequence=ProtocolBinary.MaxInteger+1},_=>d};var store=new Mock<IFolderMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<FolderMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(kind=="nullResult"?null!:new VaultResult<FolderMoveDetails>(d));var r=await Handler(store.Object).HandleAsync(Command());Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains("persistence_unavailable",r.Errors);}
    [UnitFact]
    public async Task GivenUnexpectedParentForNullDestination_WhenHandling_Then503WithoutMetadata()
    {var c=Command();c.ParentFolderId=null;var store=new Mock<IFolderMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<FolderMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(new VaultResult<FolderMoveDetails>(Details()));var r=await Handler(store.Object).HandleAsync(c);Assert.Contains("persistence_unavailable",r.Errors);Assert.Null(r.Data);}
    [UnitTheory][InlineData("{}")][InlineData("{\"expectedRevision\":1}")][InlineData("{\"parentFolderId\":null}")]
    public void GivenOmittedRequiredMember_WhenParsing_ThenReject(string raw)=>Assert.Throws<JsonException>(()=>JsonSerializer.Deserialize<MoveFolderCommand>(raw,Json));
    [UnitTheory][InlineData("actor")][InlineData("vaultAccess")][InlineData("folderId")][InlineData("recordId")][InlineData("cascade")][InlineData("ownerId")][InlineData("profileIds")][InlineData("collectionIds")][InlineData("name")][InlineData("fields")][InlineData("keyWrappers")][InlineData("envelope")][InlineData("editedAt")][InlineData("trashOperationId")][InlineData("deletedAt")][InlineData("purgeAt")]
    public void GivenForgedContextOrAlternateInput_WhenParsing_ThenReject(string field)
    {var body=JsonSerializer.SerializeToNode(Command(),Json)!.AsObject();body[field]=null;Assert.Throws<JsonException>(()=>JsonSerializer.Deserialize<MoveFolderCommand>(body.ToJsonString(),Json));}
    [UnitTheory][InlineData("duplicateRevision")][InlineData("duplicateFolder")][InlineData("caseRevision")][InlineData("caseFolder")][InlineData("numericString")][InlineData("null")][InlineData("fraction")][InlineData("overflow")][InlineData("badFolder")][InlineData("numericFolder")]
    public void GivenAlternateJson_WhenParsing_ThenReject(string kind)
    {var raw=kind switch{"duplicateRevision"=>"{\"expectedRevision\":1,\"expectedRevision\":1,\"parentFolderId\":null}","duplicateFolder"=>"{\"expectedRevision\":1,\"parentFolderId\":null,\"parentFolderId\":null}","caseRevision"=>"{\"ExpectedRevision\":1,\"parentFolderId\":null}","caseFolder"=>"{\"expectedRevision\":1,\"ParentFolderId\":null}","numericString"=>"{\"expectedRevision\":\"1\",\"parentFolderId\":null}","null"=>"{\"expectedRevision\":null,\"parentFolderId\":null}","fraction"=>"{\"expectedRevision\":1.5,\"parentFolderId\":null}","overflow"=>"{\"expectedRevision\":9223372036854775808,\"parentFolderId\":null}","badFolder"=>"{\"expectedRevision\":1,\"parentFolderId\":\"bad\"}",_=>"{\"expectedRevision\":1,\"parentFolderId\":1}"};Assert.Throws<JsonException>(()=>JsonSerializer.Deserialize<MoveFolderCommand>(raw,Json));}
    [UnitTheory][InlineData("bad")][InlineData("zero")][InlineData("uppercase")][InlineData("compact")][InlineData("braced")][InlineData("urn")][InlineData("whitespace")][InlineData("array")][InlineData("object")][InlineData("boolean")]
    public void GivenNoncanonicalParentIdentifier_WhenParsing_ThenReject(string kind)
    {
        var id=Guid.Parse("abcdefab-1234-4321-abcd-123456789abc");var value=kind switch{"bad"=>"bad","zero"=>Guid.Empty.ToString(),"uppercase"=>id.ToString().ToUpperInvariant(),"compact"=>id.ToString("N"),"braced"=>id.ToString("B"),"urn"=>"urn:uuid:"+id,_=>" "+id};var rawValue=kind switch{"array"=>"[]","object"=>"{}","boolean"=>"false",_=>JsonSerializer.Serialize(value)};var raw="{\"expectedRevision\":1,\"parentFolderId\":"+rawValue+"}";Assert.Throws<JsonException>(()=>JsonSerializer.Deserialize<MoveFolderCommand>(raw,Json));
    }
    [UnitFact]public async Task GivenCancelledCaller_WhenHandling_ThenPropagateBeforePersistence(){using var ct=new CancellationTokenSource();ct.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Handler(new Mock<IFolderMoveStore>(MockBehavior.Strict).Object).HandleAsync(Command(),ct.Token));}
    [UnitFact]public async Task GivenPersistenceCancellation_WhenHandling_ThenPropagateExactToken(){using var ct=new CancellationTokenSource();var store=new Mock<IFolderMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<FolderMoveRequest>(),ct.Token)).ThrowsAsync(new OperationCanceledException(ct.Token));var e=await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Handler(store.Object).HandleAsync(Command(),ct.Token));Assert.Equal(ct.Token,e.CancellationToken);}
    [UnitFact]public void GivenMovedMessage_WhenMapping_Then200()=>Assert.Equal(200,MoveFolderMessages.StatusCodes["folder_moved"]);
    private MoveFolderCommand Command(){var c=new MoveFolderCommand{ExpectedRevision=1,ParentFolderId=parent};c.SetContext(actor,Access,target);return c;}
    private FolderMoveDetails Details()=>new(target,parent,2,7);
    private static MoveFolderHandler Handler(IFolderMoveStore store)=>new(new MoveFolderValidator(),store);
}
