using System.Text.Json;
using System.Text.Json.Serialization;
using ArturRios.Cerberus.Command.Records;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Records;
using ArturRios.Cerberus.TestSupport;
using Moq;
namespace ArturRios.Cerberus.Command.Tests;
public class MoveRecordHandlerTests
{
    private const string Access="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    private readonly Guid actor=Guid.NewGuid(),target=Guid.NewGuid(),folder=Guid.NewGuid();
    private static readonly JsonSerializerOptions Json=new(ProtectionFixture.Json){NumberHandling=JsonNumberHandling.Strict};
    [UnitTheory][InlineData("actor","authentication_required")][InlineData("missing","vault_access_required")][InlineData("empty","validation_failed")][InlineData("handle","validation_failed")][InlineData("noncanonical","validation_failed")][InlineData("id","validation_failed")][InlineData("folder","validation_failed")][InlineData("zero","validation_failed")][InlineData("negative","validation_failed")][InlineData("unsafe","validation_failed")]
    public async Task GivenInvalidAuthorityOrInput_WhenHandling_ThenRejectBeforePersistence(string kind,string error)
    {var c=Command();c.SetContext(kind=="actor"?Guid.Empty:actor,kind=="missing"?null:kind=="empty"?"":kind=="handle"?"bad":kind=="noncanonical"?new string('A',42)+"B":Access,kind=="id"?Guid.Empty:target);c.ExpectedRevision=kind=="zero"?0:kind=="negative"?-1:kind=="unsafe"?ProtocolBinary.MaxInteger+1:1;if(kind=="folder")c.FolderId=Guid.Empty;var r=await Handler(new Mock<IRecordMoveStore>(MockBehavior.Strict).Object).HandleAsync(c);Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains(error,r.Errors);}
    [UnitTheory][InlineData(false,false)][InlineData(true,false)][InlineData(false,true)][InlineData(true,true)]
    public async Task GivenValidMoveMetadata_WhenHandling_ThenForwardTrustedContextAndReturnExactlyFourFieldsWithNullableParent(bool nullParent,bool largestRevision)
    {
        var c=Command();c.FolderId=nullParent?null:folder;if(largestRevision)c.ExpectedRevision=ProtocolBinary.MaxInteger-1;var d=new RecordMoveDetails(target,c.FolderId,c.ExpectedRevision+1,largestRevision?ProtocolBinary.MaxInteger:1);using var ct=new CancellationTokenSource();RecordMoveRequest? received=null;CancellationToken token=default;var store=new Mock<IRecordMoveStore>(MockBehavior.Strict);store.Setup(x=>x.MoveAsync(It.IsAny<RecordMoveRequest>(),It.IsAny<CancellationToken>())).Returns<RecordMoveRequest,CancellationToken>((r,t)=>{received=r;token=t;return Task.FromResult(new VaultResult<RecordMoveDetails>(d));});var result=await Handler(store.Object).HandleAsync(c,ct.Token);
        Assert.True(result.Success);Assert.Contains("record_moved",result.Messages);Assert.Equal(target,result.Data!.RecordId);Assert.Equal(c.FolderId,result.Data.FolderId);Assert.Equal(d.Revision,result.Data.Revision);Assert.Equal(d.ServerSequence,result.Data.ServerSequence);Assert.Equal(actor,received!.Actor);Assert.Equal(target,received.RecordId);Assert.Equal(c.ExpectedRevision,received.ExpectedRevision);Assert.Equal(c.FolderId,received.FolderId);Assert.Equal("66687aadf862bd776c8fc18b8e9f8e20089714856ee233b3902a591d0d5f2925",received.AccessVerifier);Assert.Equal(ct.Token,token);
        using var output=JsonDocument.Parse(JsonSerializer.Serialize(result.Data,Json));Assert.Equal(new[]{"folderId","recordId","revision","serverSequence"},output.RootElement.EnumerateObject().Select(x=>x.Name).Order());Assert.Equal(nullParent?JsonValueKind.Null:JsonValueKind.String,output.RootElement.GetProperty("folderId").ValueKind);using var input=JsonDocument.Parse(JsonSerializer.Serialize(c,Json));Assert.Equal(new[]{"expectedRevision","folderId"},input.RootElement.EnumerateObject().Select(x=>x.Name).Order());
    }
    [UnitTheory][InlineData("validation_failed",400)][InlineData("not_found",404)][InlineData("vault_access_denied",403)][InlineData("revision_conflict",409)][InlineData("persistence_unavailable",503)][InlineData("secret_owner_123",503)][InlineData("authentication_required",503)][InlineData("vault_access_required",503)][InlineData("identity_unavailable",503)][InlineData("record_moved",503)][InlineData("",503)]
    public async Task GivenStoreFailure_WhenHandling_ThenOnlyAllowExpectedSafeCodes(string error,int status)
    {var store=new Mock<IRecordMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<RecordMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(new VaultResult<RecordMoveDetails>(Error:error));var r=await Handler(store.Object).HandleAsync(Command());var expected=error is "validation_failed" or "not_found" or "vault_access_denied" or "revision_conflict"?error:"persistence_unavailable";Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains(expected,r.Errors);Assert.Equal(status,MoveRecordMessages.StatusCodes[expected]);}
    [UnitTheory][InlineData("not_found")][InlineData("validation_failed")][InlineData("vault_access_denied")][InlineData("revision_conflict")][InlineData("persistence_unavailable")][InlineData("secret_owner_123")]
    public async Task GivenStoreErrorAndData_WhenHandling_Then503WithoutPartialPayload(string error)
    {var store=new Mock<IRecordMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<RecordMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(new VaultResult<RecordMoveDetails>(Details(),error));var r=await Handler(store.Object).HandleAsync(Command());Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains("persistence_unavailable",r.Errors);}
    [UnitTheory][InlineData("nullResult")][InlineData("nullData")][InlineData("recordId")][InlineData("emptyId")][InlineData("folderId")][InlineData("emptyFolder")][InlineData("nullFolder")][InlineData("revision0")][InlineData("revisionOld")][InlineData("revisionAhead")][InlineData("unsafeRevision")][InlineData("sequence0")][InlineData("negativeSequence")][InlineData("unsafeSequence")]
    public async Task GivenMalformedStoreSuccess_WhenHandling_Then503WithoutMetadata(string kind)
    {RecordMoveDetails? d=Details();d=kind switch{"nullData"=>null,"recordId"=>d with{RecordId=Guid.NewGuid()},"emptyId"=>d with{RecordId=Guid.Empty},"folderId"=>d with{FolderId=Guid.NewGuid()},"emptyFolder"=>d with{FolderId=Guid.Empty},"nullFolder"=>d with{FolderId=null},"revision0"=>d with{Revision=0},"revisionOld"=>d with{Revision=1},"revisionAhead"=>d with{Revision=3},"unsafeRevision"=>d with{Revision=ProtocolBinary.MaxInteger+1},"sequence0"=>d with{ServerSequence=0},"negativeSequence"=>d with{ServerSequence=-1},"unsafeSequence"=>d with{ServerSequence=ProtocolBinary.MaxInteger+1},_=>d};var store=new Mock<IRecordMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<RecordMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(kind=="nullResult"?null!:new VaultResult<RecordMoveDetails>(d));var r=await Handler(store.Object).HandleAsync(Command());Assert.False(r.Success);Assert.Null(r.Data);Assert.Contains("persistence_unavailable",r.Errors);}
    [UnitFact]
    public async Task GivenUnexpectedFolderForNullDestination_WhenHandling_Then503WithoutMetadata()
    {var c=Command();c.FolderId=null;var store=new Mock<IRecordMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<RecordMoveRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(new VaultResult<RecordMoveDetails>(Details()));var r=await Handler(store.Object).HandleAsync(c);Assert.Contains("persistence_unavailable",r.Errors);Assert.Null(r.Data);}
    [UnitTheory][InlineData("{}")][InlineData("{\"expectedRevision\":1}")][InlineData("{\"folderId\":null}")]
    public void GivenOmittedRequiredMember_WhenParsing_ThenReject(string raw)=>Assert.Throws<JsonException>(()=>JsonSerializer.Deserialize<MoveRecordCommand>(raw,Json));
    [UnitTheory][InlineData("actor")][InlineData("vaultAccess")][InlineData("recordId")][InlineData("ownerId")][InlineData("profileIds")][InlineData("collectionIds")][InlineData("name")][InlineData("fields")][InlineData("keyWrappers")][InlineData("envelope")][InlineData("editedAt")][InlineData("trashOperationId")][InlineData("deletedAt")][InlineData("purgeAt")]
    public void GivenForgedContextOrAlternateInput_WhenParsing_ThenReject(string field)
    {var body=JsonSerializer.SerializeToNode(Command(),Json)!.AsObject();body[field]=null;Assert.Throws<JsonException>(()=>JsonSerializer.Deserialize<MoveRecordCommand>(body.ToJsonString(),Json));}
    [UnitTheory][InlineData("duplicateRevision")][InlineData("duplicateFolder")][InlineData("caseRevision")][InlineData("caseFolder")][InlineData("numericString")][InlineData("null")][InlineData("fraction")][InlineData("overflow")][InlineData("badFolder")][InlineData("numericFolder")]
    public void GivenAlternateJson_WhenParsing_ThenReject(string kind)
    {var raw=kind switch{"duplicateRevision"=>"{\"expectedRevision\":1,\"expectedRevision\":1,\"folderId\":null}","duplicateFolder"=>"{\"expectedRevision\":1,\"folderId\":null,\"folderId\":null}","caseRevision"=>"{\"ExpectedRevision\":1,\"folderId\":null}","caseFolder"=>"{\"expectedRevision\":1,\"FolderId\":null}","numericString"=>"{\"expectedRevision\":\"1\",\"folderId\":null}","null"=>"{\"expectedRevision\":null,\"folderId\":null}","fraction"=>"{\"expectedRevision\":1.5,\"folderId\":null}","overflow"=>"{\"expectedRevision\":9223372036854775808,\"folderId\":null}","badFolder"=>"{\"expectedRevision\":1,\"folderId\":\"bad\"}",_=>"{\"expectedRevision\":1,\"folderId\":1}"};Assert.Throws<JsonException>(()=>JsonSerializer.Deserialize<MoveRecordCommand>(raw,Json));}
    [UnitFact]public async Task GivenCancelledCaller_WhenHandling_ThenPropagateBeforePersistence(){using var ct=new CancellationTokenSource();ct.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Handler(new Mock<IRecordMoveStore>(MockBehavior.Strict).Object).HandleAsync(Command(),ct.Token));}
    [UnitFact]public async Task GivenPersistenceCancellation_WhenHandling_ThenPropagateExactToken(){using var ct=new CancellationTokenSource();var store=new Mock<IRecordMoveStore>();store.Setup(x=>x.MoveAsync(It.IsAny<RecordMoveRequest>(),ct.Token)).ThrowsAsync(new OperationCanceledException(ct.Token));var e=await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Handler(store.Object).HandleAsync(Command(),ct.Token));Assert.Equal(ct.Token,e.CancellationToken);}
    [UnitFact]public void GivenMovedMessage_WhenMapping_Then200()=>Assert.Equal(200,MoveRecordMessages.StatusCodes["record_moved"]);
    private MoveRecordCommand Command(){var c=new MoveRecordCommand{ExpectedRevision=1,FolderId=folder};c.SetContext(actor,Access,target);return c;}
    private RecordMoveDetails Details()=>new(target,folder,2,7);
    private static MoveRecordHandler Handler(IRecordMoveStore store)=>new(new MoveRecordValidator(),store);
}
