from pathlib import Path
w=Path('/tmp/cerberus-uc20-worktree');old=(w/'tests/Presentation/ArturRios.Cerberus.WebApi.Tests/RecordUpdateHttpTests.cs').read_text()
header=old[:old.index('    [FunctionalTheory]')].replace('RecordUpdateHttpTests','RecordTrashHttpTests').replace('using ArturRios.Cerberus.Domain.Resources;','using ArturRios.Cerberus.Domain.Resources;\nusing ArturRios.Cerberus.Domain.Trash;')
def part(start,end):return old[old.index(start):old.index(end)]
def convert(s):return s.replace('Bytes(Replacement())','Bytes(new{expectedRevision=1})').replace('Replacement(88)','88').replace('Replacement()','1').replace('await Update(','await Trash(').replace('Put(s,','Delete(s,').replace('WhenReplacing','WhenTrashing').replace('c.Request.Method="PUT"','c.Request.Method="DELETE"')
canonical=convert(part('    [FunctionalTheory][InlineData("bad")][InlineData("zero")]','    [FunctionalTheory][InlineData("unknown")]'))
transport=convert(part('    [FunctionalTheory][InlineData("query",400)]','    [FunctionalTheory][InlineData("closing",404)]'))
actor=convert(part('    [FunctionalTheory][InlineData("closing",404)]','    [FunctionalTheory][InlineData("grant",404)]'))
relations=convert(part('    [FunctionalTheory][InlineData("grant",404)]','    [FunctionalTheory][InlineData("signature")]'))
native=convert(part('    [FunctionalTheory][InlineData("signature")]','    [FunctionalTheory][InlineData("envelope")]'))
hidden=convert(part('    [FunctionalTheory][InlineData("missing")][InlineData("foreign")]','    [FunctionalTheory][InlineData("bad")][InlineData("zero")]'))
hidden=hidden.replace('[InlineData("revoked")]','[InlineData("revoked")][InlineData("ancestorTerminal")][InlineData("ownerTerminal")][InlineData("collectionTrash")]')
hidden=hidden.replace('        var before=await Snapshot(o);using var response=',r'''        await using(var db=fixture.Context()){if(grant is not null)await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind is "ancestorTerminal" or "ownerTerminal"){db.TerminalErasures.Add(new(){ResourceId=kind=="ancestorTerminal"?folder.PublicId:o.AccountId,ResourceKind=kind=="ancestorTerminal"?"folder":"account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}if(kind=="collectionTrash")await db.Collections.Where(x=>db.CollectionGrants.Any(g=>g.Id==grant!.Id&&g.CollectionId==x.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}
        var before=await Snapshot(o);using var response=''')
helpers=old[old.index('    private async Task<RecordCreateInput> Create('):]
helpers=helpers.replace('Records=await db.Records', 'Operations=await db.TrashOperations.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Entries=await db.TrashEntries.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.Id==x.OperationId&&o.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Queue=await db.RetentionWorkItems.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.AccountId==s.InternalId&&x.OperationKey=="trash/"+o.PublicId)).OrderBy(x=>x.Id).ToArrayAsync(),Records=await db.Records')
main=r'''
    [FunctionalTheory][InlineData("wide",false)][InlineData("Master",false)][InlineData("PerProfile",false)][InlineData("Master",true)][InlineData("PerProfile",true)]
    public async Task GivenActualNativeOwnedScope_WhenTrashing_ThenRetainCipherAndAssociationsWithExactSixMetadataFields(string mode,bool folderRoute)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var child=await Folder(s,root.Id);var p=await Profile(s,owner,scoped,folderRoute?root:null,mode=="wide"?"Master":mode);var target=await Create(s,folderRoute?[]:[p.PublicId],child.PublicId);var actor=mode=="wide"?s:s with{Access=await Open(s,p,scoped)};var before=await Row(target.RecordId);var protectedBefore=await Protected(s);
        await using var db=fixture.Context();var profileBefore=await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id);var folderBefore=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==child.Id);
        using var response=await Trash(actor,target.RecordId);var d=await Success<DeleteRecordOutput>(response,200);Fields(d,"recordId","trashOperationId","revision","serverSequence","deletedAt","purgeAt");Assert.Contains("record_deleted",await response.Content.ReadAsStringAsync());await Trashed(s,before,d);Assert.Equal(protectedBefore,await Protected(s));
        var entry=await db.TrashEntries.AsNoTracking().SingleAsync(x=>x.ResourceKind=="record"&&x.ResourceId==target.RecordId);var snapshot=JsonSerializer.Deserialize<RecordAssociationSnapshot>(entry.AssociationSnapshot,ProtectionFixture.Json)!;Assert.Equal(child.PublicId,snapshot.FolderId);Assert.Equal(target.ProfileIds.Order(),snapshot.ProfileIds);Assert.Empty(snapshot.CollectionIds);
        var nowP=await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id);Assert.Equal(profileBefore.Revision+(folderRoute?0:1),nowP.Revision);Assert.Equal(profileBefore.Envelope,nowP.Envelope);Assert.Equal(profileBefore.EditedAt,nowP.EditedAt);Assert.Equal(profileBefore.KeyWrappers,nowP.KeyWrappers);var nowF=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==child.Id);Assert.Equal(folderBefore.Revision+1,nowF.Revision);Assert.Equal(folderBefore.Envelope,nowF.Envelope);Assert.Equal(folderBefore.EditedAt,nowF.EditedAt);Assert.Equal(root.Revision,(await db.Folders.SingleAsync(x=>x.Id==root.Id)).Revision);
        using var get=await Read(actor,"/api/records/"+target.RecordId);await Failure(get,404,"not_found");using var list=await Read(actor,"/api/records");Assert.DoesNotContain((await Success<RecordListOutput>(list,200)).Items,x=>x.RecordId==target.RecordId);
    }
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenSelectedOwnedCollection_WhenTrashing_ThenDetachOnlyRecordMembershipAndPreserveHandle(string mode)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var c=await OwnedCollection(s,target.RecordId);var p=await Profile(s,owner,scoped,mode:mode,collections:[c.PublicId]);var actor=s with{Access=await Open(s,p,scoped)};var before=await Row(target.RecordId);using var response=await Trash(actor,target.RecordId);await Trashed(s,before,await Success<DeleteRecordOutput>(response,200));await using var db=fixture.Context();var row=await db.Collections.AsNoTracking().SingleAsync(x=>x.Id==c.Id);Assert.Equal(c.Revision+1,row.Revision);Assert.Equal(c.Envelope,row.Envelope);Assert.Equal(c.EditedAt,row.EditedAt);Assert.Equal(Bytes(p),Bytes(await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id)));var entry=await db.TrashEntries.SingleAsync(x=>x.ResourceKind=="record"&&x.ResourceId==target.RecordId);var snapshot=JsonSerializer.Deserialize<RecordAssociationSnapshot>(entry.AssociationSnapshot,ProtectionFixture.Json)!;Assert.Equal(new[]{c.PublicId},snapshot.CollectionIds);Assert.Empty(snapshot.ProfileIds);Assert.Null(snapshot.FolderId);using var list=await Read(actor,"/api/records");Assert.Empty((await Success<RecordListOutput>(list,200)).Items);
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false,false)][InlineData(CollectionGrantAccess.ReadOnly,false,true)][InlineData(CollectionGrantAccess.ReadOnly,true,false)][InlineData(CollectionGrantAccess.ReadOnly,true,true)][InlineData(CollectionGrantAccess.ReadWrite,false,false)][InlineData(CollectionGrantAccess.ReadWrite,false,true)][InlineData(CollectionGrantAccess.ReadWrite,true,false)][InlineData(CollectionGrantAccess.ReadWrite,true,true)]
    public async Task GivenActualNativeVisibleForeignScope_WhenDeletingStaleCorruptTarget_ThenReadOnlyAndReadWriteBoth403(CollectionGrantAccess access,bool selected,bool inherited)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (c,_)=await Share(o,owner,s,client,access,inherited?[]:[target.RecordId],inherited?[root.Id]:[]);var p=await Profile(s,client,scoped,collections:[c.PublicId]);var actor=selected?s with{Access=await Open(s,p,scoped)}:s;await using(var db=fixture.Context())await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"bad"u8.ToArray()));var before=await Snapshot(o);var recipient=await Snapshot(s);using var response=await Trash(actor,target.RecordId,99);await Failure(response,403,"vault_access_denied");Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("unknown")][InlineData("actor")][InlineData("vaultAccess")][InlineData("recordId")][InlineData("ownerId")][InlineData("profileIds")][InlineData("folderId")][InlineData("collectionIds")][InlineData("name")][InlineData("fields")][InlineData("keyWrappers")][InlineData("envelope")][InlineData("editedAt")][InlineData("trashOperationId")][InlineData("deletedAt")][InlineData("purgeAt")][InlineData("zero")][InlineData("negative")][InlineData("unsafe")][InlineData("missing")][InlineData("duplicate")][InlineData("case")][InlineData("numericString")][InlineData("nullRevision")][InlineData("fraction")][InlineData("overflow")][InlineData("null")][InlineData("array")][InlineData("empty")]
    public async Task GivenStrictOrForgedDeleteBody_WhenTrashing_Then400WithoutAnyOperation(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var body=JsonSerializer.SerializeToNode(new{expectedRevision=1},ProtectionFixture.Json)!.AsObject();var fields=new[]{"actor","vaultAccess","recordId","ownerId","profileIds","folderId","collectionIds","name","fields","keyWrappers","envelope","editedAt","trashOperationId","deletedAt","purgeAt"};if(fields.Contains(kind))body[kind]=null;if(kind=="unknown")body["secret"]=null;var raw=kind switch{"zero"=>"{\"expectedRevision\":0}","negative"=>"{\"expectedRevision\":-1}","unsafe"=>"{\"expectedRevision\":9007199254740992}","missing"=>"{}","duplicate"=>"{\"expectedRevision\":1,\"expectedRevision\":1}","case"=>"{\"ExpectedRevision\":1}","numericString"=>"{\"expectedRevision\":\"1\"}","nullRevision"=>"{\"expectedRevision\":null}","fraction"=>"{\"expectedRevision\":1.5}","overflow"=>"{\"expectedRevision\":9223372036854775808}","null"=>"null","array"=>"[]","empty"=>"",_=>body.ToJsonString()};var before=await Snapshot(s);using var req=Delete(s,"/api/records/"+target.RecordId,Encoding.UTF8.GetBytes(raw));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenSelectedCollectionLinkRemovedAfterUnlock_WhenTrashingForeignTarget_Then404WithoutExpandingScope()
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var (c,_)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.RecordId],[]);var p=await Profile(s,client,scoped,collections:[c.PublicId]);var actor=s with{Access=await Open(s,p,scoped)};await using(var db=fixture.Context())await db.ProfileCollections.Where(x=>x.ProfileId==p.Id).ExecuteDeleteAsync();var before=await Snapshot(o);using var response=await Trash(actor,target.RecordId);await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));}
    [FunctionalTheory][InlineData("sequence")][InlineData("revision")][InlineData("purgeWithoutTrash")][InlineData("outage")]
    public async Task GivenCorruptMetadataOrPersistenceOutage_WhenTrashing_Then503WithoutPartialOperation(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using var db=fixture.Context();if(kind=="sequence")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ServerSequence,0));if(kind=="revision")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,0));if(kind=="purgeWithoutTrash")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.PurgeAt,DateTimeOffset.UtcNow.AddDays(30)));var before=await Snapshot(s);if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.record RENAME TO fixture_unavailable_record");try{using var response=await Trash(s,target.RecordId);await Failure(response,503,"persistence_unavailable");}finally{if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_record RENAME TO record");}Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenDamagedOwnedOpaqueCipher_WhenTrashing_ThenSuccessPreservesThoseBytes()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using(var db=fixture.Context())await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged-opaque"u8.ToArray()));var before=await Row(target.RecordId);using var response=await Trash(s,target.RecordId);await Trashed(s,before,await Success<DeleteRecordOutput>(response,200));}
    [FunctionalFact]
    public async Task GivenLostTrashSuccessRetry_WhenDeletingAgain_Then404WithoutSecondOperationOrExtendedDeadline()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var original=await Row(target.RecordId);using(var response=await Trash(s,target.RecordId))await Trashed(s,original,await Success<DeleteRecordOutput>(response,200));var before=await Snapshot(s);using var retry=await Trash(s,target.RecordId);await Failure(retry,404,"not_found");Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenActualPutWins_WhenDeletingWithOldRevision_Then409PreservesCipherAndReloadedDeleteSucceeds()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);using(var req=Delete(s,"/api/records/"+target.RecordId,Bytes(new RecordUpdateInput(1,Envelope(),DateTimeOffset.UnixEpoch)))){req.Method=HttpMethod.Put;using var edit=await Gateway.Client.SendAsync(req);await Success<UpdateRecordOutput>(edit,200);}var before=await Snapshot(s);using(var response=await Trash(s,target.RecordId))await Failure(response,409,"revision_conflict");Assert.Equal(before,await Snapshot(s));var winner=await Row(target.RecordId);using var current=await Trash(s,target.RecordId,2);await Trashed(s,winner,await Success<DeleteRecordOutput>(current,200));}
    [FunctionalFact]
    public async Task GivenCancelledHttpCaller_WhenTrashing_ThenPropagateAndPreserveRecord()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);using var ct=new CancellationTokenSource();ct.Cancel();using var req=Delete(s,"/api/records/"+target.RecordId,Bytes(new{expectedRevision=1}));await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Gateway.Client.SendAsync(req,ct.Token));Assert.Equal(before,await Snapshot(s));}

    private static HttpRequestMessage Delete(State s,string path,byte[] body){var r=Request(s,body,path);r.Method=HttpMethod.Delete;return r;}
    private async Task<HttpResponseMessage> Trash(State s,Guid id,long revision=1){using var req=Delete(s,"/api/records/"+id,Bytes(new{expectedRevision=revision}));return await Gateway.Client.SendAsync(req);}
    private async Task<VaultRecord> Row(Guid id){await using var db=fixture.Context();return await db.Records.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<VaultCollection> OwnedCollection(State s,Guid target){await using var db=fixture.Context();var c=new VaultCollection{AccountId=s.InternalId,PublicId=Guid.NewGuid(),Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(c);await db.SaveChangesAsync();var r=await db.Records.SingleAsync(x=>x.PublicId==target);db.CollectionRecords.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,RecordId=r.Id});await db.SaveChangesAsync();return c;}
    private async Task Trashed(State owner,VaultRecord original,DeleteRecordOutput output)
    {
        Fields(output,"recordId","trashOperationId","revision","serverSequence","deletedAt","purgeAt");Assert.Equal(original.PublicId,output.RecordId);Assert.NotEqual(Guid.Empty,output.TrashOperationId);Assert.Equal(original.Revision+1,output.Revision);Assert.True(output.ServerSequence>original.ServerSequence);Assert.Equal(TimeSpan.Zero,output.DeletedAt.Offset);Assert.Equal(0,output.DeletedAt.Ticks%10);Assert.Equal(TimeSpan.FromDays(30),output.PurgeAt-output.DeletedAt);var row=await Row(original.PublicId);Assert.Equal(original.AccountId,row.AccountId);Assert.Equal(original.Envelope,row.Envelope);Assert.Equal(original.EditedAt,row.EditedAt);Assert.Null(row.FolderId);Assert.Equal(output.Revision,row.Revision);Assert.Equal(output.ServerSequence,row.ServerSequence);Assert.Equal(output.DeletedAt,row.DeletedAt);Assert.Equal(output.PurgeAt,row.PurgeAt);Assert.NotEqual(original.ConcurrencyStamp,row.ConcurrencyStamp);
        await using var db=fixture.Context();var operation=await db.TrashOperations.SingleAsync(x=>x.PublicId==output.TrashOperationId);Assert.Equal(owner.InternalId,operation.AccountId);Assert.Equal("record",operation.RootResourceKind);Assert.Equal(original.PublicId,operation.RootResourceId);Assert.Equal(output.DeletedAt,operation.DeletedAt);Assert.Equal(output.PurgeAt,operation.PurgeAt);Assert.Single(await db.TrashEntries.Where(x=>x.ResourceKind=="record"&&x.ResourceId==original.PublicId&&x.OperationId==operation.Id).ToListAsync());var queue=await db.RetentionWorkItems.SingleAsync(x=>x.OperationKey=="trash/"+output.TrashOperationId);Assert.Equal(output.PurgeAt,queue.DueAt);Assert.Null(queue.CompletedAt);Assert.False(await db.ProfileRecords.AnyAsync(x=>x.RecordId==original.Id));Assert.False(await db.CollectionRecords.AnyAsync(x=>x.RecordId==original.Id));
    }
'''
source=header+main+hidden+canonical+transport+actor+relations+native+helpers
(w/'tests/Presentation/ArturRios.Cerberus.WebApi.Tests/RecordTrashHttpTests.cs').write_text(source)
print('Actual HTTP tests before route:',source.count('[InlineData(')+source.count('[FunctionalFact]'))
