from pathlib import Path
import json
r=Path('/tmp/cerberus-uc20-worktree');p=r/'.superpowers/sdd/2026-10-09-uc-20-delete-record/progress.md'
lines=[
'Final: Ruling: Actual restoration and association re-admission remains UC51 beforeRelease — current development endpoint retains historical typed associations, but a restore endpoint must revalidate links/authority and consume or reconcile the old entry — cost if wrong: users cannot recover through the API yet, and unsafe future readmission could revive unauthorized links; Important release limitation.',
'Final: Ruling: Actual erasure at720hours remains UC53 beforeRelease — existing executor fails closed/retries unavailable typedhandler and never marks fakepurgecomplete; scheduling is not completed erasure — cost if wrong: ciphertext can remain beyond deadline until handler ships; Important release limitation.',
'Final: Ruling: Resource-kind-aware terminal identity repair remains mandatory BEFORE ANY physicalpurge — inherited globalGUIDexclusions/uniqueness conservatively deny and this branch adds no purge; nevernullselectedProfileId — cost if wrong: cross-kind sameGUID can falselyhide live content; Important availability limitation until typedrepair.',
'Final: Ruling: Durable offline removal/descendant notifications remain future synchronization integration — online currentget/list exclude trash now, while later sync must publish dynamicvisibilityremovals — cost if wrong: released offlineclients could retain stalevisiblecontent; Important release limitation for offline product.',
'Final: Ruling: Independent cryptographic/protocol and actual external-client approvals remain explicitly development-onlydeferred — ordinaryreview/nativecorpus/actualHTTP do not replace those qualifications and releasegates staymandatory — cost if wrong: latent security or interoperability defects await required release approval.',
'Final: Ruling: Future sharing/foldermove/lifecycle/restore writers require their own integration tests with this orderedlock/currentauthority protocol — currentactualwriters reviewed and racescovered, unwrittenwriters cannot be certified now; BEFORE UC35 implicitrecipient-accountFK audit staysmandatory — cost if wrong: future deadlock/scope failures could be Important or securityCritical.',
'Final: Ruling: Repair/authenticated recovery of alreadydamagedciphertext remains a separate operation — deletion preservesexistingopaquebytes and doesnotclaimtocure corruption; intactmetadata and unchangedcontentguard required — cost if wrong: damagedretainedcontent can still prevent authenticated client recovery and complete rotation until repair/purge.',
'Final: Ruling: Do not broaden this atomic endpoint into generalized permission/authority framework refactor — purposebuiltSQL currentlymatches reviewedauthority and observablecorrectness; broadrefactor needs separate behavioralreview — cost if wrong: SQLduplication/maintenance complexity can cause futuredrift.'
]
minors=[
'Final: minor (deferred): Shared OpenAPI lacks required header/requestBody and guaranteed six-outputfield annotations (openapi.json2352/2359/5059); inputexpectedRevisionISrequired; runtime strictness tested. Correctsharedgeneratorbeforerelease; generatedclients may treatinputs/metadataasoptional.',
'Final: minor (deferred): Shared OpenAPI advertises ProblemDetails content for actualempty413 (openapi.json2499, HTTPtest96); commonlimittestrejectswithoutbody/mutation. Correctsharedgeneratorbeforerelease; generatedparsermayfailonemptyresponse.'
]
p.write_text(p.read_text()+'\nFinal ordinaryreview67042c4 complete /tmp/cerberus-uc20-final-review.md:0Critical/0Importantblocking;2existingOpenAPIminors; all12initialrulings+5Focuschecked. Regradedactualeffects: inherited/future Importantreleaselimitations explicitlypreserved below; none newlyintroducedUC20runtimeblocker. No blockingfixpass/re-review needed.\n\n'+'\n'.join(lines+minors)+'\n')
a=Path('/root/repositories/cerberus-api/.superpowers/checkpoints/batch-review-decisions-2026-10-08.md');a.write_text(a.read_text()+'\n\nUC20 final review decisions (all8declinedbehaviors,2existingminors; actualImportantreleaseeffectsretained):\n'+'\n'.join(lines+minors)+'\n')
s=Path('/tmp/cerberus-uc20-pr-body-draft.md').read_text();s=s.replace('Fresh unfiltered six-family suite:3878 expected; substitute actual verified totals/coverage before publication.','Fresh unfiltered six-family suite: **3878 passed, zero failed/skipped** (Domain313,Query259,Shared125,Command641,Data1304,Web1236). Allsixproductionassemblies exceed90%line; merged **98.3%line /91.7%branch**.');s=s.replace('Ordinary fresh whole-branch review: pending. Exact-head required CI and verified normal merge remain mandatory.','Ordinary fresh whole-branch review of67042c4: **0Critical /0Important blocking**. No blocking corrections needed. Two existing shared OpenAPI Minors retained; inherited/future Importantreleaseeffects explicitly ruled below. Exact-head required CI and verified normal merge remain mandatory.');rulings=[x for x in p.read_text().splitlines() if 'Ruling:' in x];assert len(rulings)==20
s+='\n## Rulings I made\n\n'+'\n'.join('- '+x for x in rulings)+'\n\n## Deferred minors\n\n'+'\n'.join('- '+x for x in minors)+'\n\n## Approval scope\n\nExisting explicit unattended authorization covers this development PR and normal squash merge only after latest exact-head branch-policy/test/dockerSUCCESS, MERGEABLE/CLEAN and freshunchangedtestedbase. Main/tag/releaseapprovalgates remainintact.\n';Path('/tmp/cerberus-uc20-pr-body.md').write_text(s)
p=Path('/root/repositories/cerberus-api/.superpowers/checkpoints/open-issues-2026-10-08.json');d=json.loads(p.read_text());v='UC20 HEAD67042c4632936dcb73ee170e00ea10e061a1a2a5/full3878PASS98.3line91.7branch. ONE finalreviewcomplete0Critical/0Importantblocking; all20rulings(12initial+8declined)reason/cost+2OpenAPIminors inledger/aggregate/exhaustivePRbody. PushPRnext, projectTesting thenlatestexacthead3CI/CLEAN/MERGEABLE/freshbase/normalmerge/9DoD/archive beforeUC21.20UCsmerged.'
for k in ('currentTask','resumeInstruction','requiredToResume'):d[k]=v
for x in d['useCases']:
 if x.get('id')=='UC-20':x.update({'review':'ONEfreshordinary review0Critical0Importantblocking;8declinedbehaviors reason/cost ruled;2OpenAPIminors retained','rulings':20,'focusedHttpTests':99,'currentTask':'PR creation and required CI'})
p.write_text(json.dumps(d,indent=2)+'\n');print('20exhaustiveRulings+2Minors recorded; PRbody ready.')
