from pathlib import Path
w=Path('/tmp/cerberus-uc20-worktree');p=w/'tests/Infrastructure/ArturRios.Cerberus.Data.Tests/RecordTrashStoreTests.cs';s=p.read_text().replace('using Microsoft.EntityFrameworkCore.Diagnostics;','using Microsoft.EntityFrameworkCore.Diagnostics;\nusing Npgsql;')
extra=r'''
    [FunctionalTheory][InlineData("self","persistence_unavailable")][InlineData("long","persistence_unavailable")][InlineData("hidden","not_found")]
    public async Task GivenRelevantCyclicAncestry_WhenTrashing_ThenFailClosedWithoutRecursingForever(string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var target=await Record(s,child.Id);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,(long?)(kind=="self"?root.Id:child.Id)).SetProperty(v=>v.DeletedAt,kind=="hidden"?(DateTimeOffset?)DateTimeOffset.UtcNow:null));var before=await Snapshot(s);Assert.Equal(error,(await Trash(s,target)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenRemovedLinkBeforeAssociationLock_WhenTrashing_ThenUseCurrentScopeAndSnapshot(bool selected)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Record(s);var p=await Profile(s,owner,scoped,records:[target.PublicId]);if(selected)s=s with{Verifier=await Selected(s,p.Id)};
        var hook=new BeforeAssociations(async()=>{await using var db=fixture.CreateContext();await db.ProfileRecords.Where(x=>x.RecordId==target.Id).ExecuteDeleteAsync();});var r=await new RecordTrashStore(new ProfileSetup.Factory(fixture,hook)).TrashAsync(new(s.Actor,s.Verifier,target.PublicId,1),default);
        if(selected){Assert.Equal("not_found",r.Error);Assert.Equal(Bytes(target),Bytes(await Row(target.Id)));await NoOperation(target.PublicId);}else{await Success(s,target,r);await using var db=fixture.CreateContext();var entry=await db.TrashEntries.SingleAsync(x=>x.ResourceKind=="record"&&x.ResourceId==target.PublicId);Assert.Empty(JsonSerializer.Deserialize<RecordAssociationSnapshot>(entry.AssociationSnapshot,ProtectionFixture.Json)!.ProfileIds);Assert.Equal(p.Revision,(await db.Profiles.SingleAsync(x=>x.Id==p.Id)).Revision);}
    }
    [FunctionalTheory][InlineData("create")][InlineData("association")]
    public async Task GivenOwnerTrashHoldsParents_WhenAnotherOwnedWriterStarts_ThenSerializeWithoutDeadlock(string writer)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var target=await Record(s,folder.Id);var p=await Profile(s,owner,scoped,records:[target.PublicId]);
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var trash=new RecordTrashStore(new ProfileSetup.Factory(fixture,new BeforeTarget(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(s.Actor,s.Verifier,target.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var factory=new ProfileSetup.Factory(fixture,new Signal(blocked,"account"));
        var create=writer=="create"?new RecordCreateStore(factory).CreateAsync(new(s.Actor,s.Verifier,new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],folder.PublicId)),ct.Token):null;
        var association=writer=="association"?new ProfileAssociationStore(factory).SetAsync(new(s.Actor,s.Verifier,p.PublicId,new(1,[],[],[])),ct.Token):null;
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(create?.IsCompleted??association!.IsCompleted);}finally{release.TrySetResult();}
        await Success(s,target,await trash);if(create is not null)Assert.Null((await create).Error);if(association is not null)Assert.Equal("revision_conflict",(await association).Error);
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenControlledRecipientEditAndOwnerTrash_WhenWaitingOnCollections_ThenNoLockCycleAndOneWinner(bool trashFirst)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[a.Record.Id],[]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));
        Task<VaultResult<RecordTrashDetails>> trash;Task<VaultResult<RecordCreateDetails>> edit;
        if(trashFirst){trash=new RecordTrashStore(new ProfileSetup.Factory(fixture,new BeforeTarget(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(o.Actor,o.Verifier,a.Record.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));edit=new RecordUpdateStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection"))).UpdateAsync(new(s.Actor,s.Verifier,a.Record.PublicId,new(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch)),ct.Token);}
        else{edit=new RecordUpdateStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).UpdateAsync(new(s.Actor,s.Verifier,a.Record.PublicId,new(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch)),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));trash=new RecordTrashStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection"))).TrashAsync(new(o.Actor,o.Verifier,a.Record.PublicId,1),ct.Token);}
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(trashFirst?edit.IsCompleted:trash.IsCompleted);}finally{release.TrySetResult();}
        await Task.WhenAll(trash,edit);if(trashFirst){await Success(o,a.Record,trash.Result);Assert.Equal("not_found",edit.Result.Error);}else{Assert.Null(edit.Result.Error);Assert.Equal("revision_conflict",trash.Result.Error);await NoOperation(a.Record.PublicId);Assert.Equal(edit.Result.Data!.Revision,(await Row(a.Record.Id)).Revision);}
    }
    [FunctionalFact]
    public async Task GivenActualOwnerRotationWaitsOnTrashAccount_WhenTrashCommits_ThenStaleInventoryConflictsWithoutConsumingProof()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Record(s);var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),[new("account",s.AccountId,1,ProfileSetup.Envelope(2)),new("record",target.PublicId,1,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var trash=new RecordTrashStore(new ProfileSetup.Factory(fixture,new BeforeTarget(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(s.Actor,s.Verifier,target.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var rotation=new VaultProtectionChangeStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"account"))).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),ct.Token);
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(rotation.IsCompleted);}finally{release.TrySetResult();}await Success(s,target,await trash);Assert.Equal("revision_conflict",(await rotation).Error);await using var db=fixture.CreateContext();Assert.False((await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==challenge.ChallengeId)).Consumed);Assert.Equal(1,(await db.VaultProtections.SingleAsync(x=>x.AccountId==s.InternalId)).Revision);
    }
    [FunctionalTheory][InlineData("foreign")][InlineData("trash")][InlineData("terminal")]
    public async Task GivenInvalidSelectedProfile_WhenTrashingOwnedRecord_ThenDenyWithoutBroadening(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Record(s);var other=kind=="foreign"?await ProfileSetup.Create(fixture,owner):s;var p=await Profile(other,owner,scoped);s=s with{Verifier=await Selected(s,p.Id)};await using(var db=fixture.CreateContext()){if(kind=="trash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="terminal"){db.TerminalErasures.Add(new(){ResourceId=p.PublicId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}var before=await Snapshot(s);Assert.Equal("vault_access_denied",(await Trash(s,target)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenOverlappingNativeAuthorityWithMalformedContributor_WhenNonownerDeletes_ThenWholeDenialFailsClosed(bool invalidReadWrite)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var b=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[a.Record.Id],[]);await Members(o,b.Collection,[a.Record.Id],[]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,invalidReadWrite?CollectionGrantAccess.ReadOnly:CollectionGrantAccess.ReadWrite);var bad=await AssociationSetup.Grant(fixture,o,owner,s,client,b.Collection,invalidReadWrite?CollectionGrantAccess.ReadWrite:CollectionGrantAccess.ReadOnly);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(o);Assert.Equal("persistence_unavailable",(await Trash(s,a.Record)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalFact]
    public async Task GivenVisibleForeignNativeTarget_WhenDenyingTrash_ThenNoForeignResourceLocks()
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[a.Record.Id],[]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);var capture=new Capture(fixture);Assert.Equal("vault_access_denied",(await new RecordTrashStore(new ProfileSetup.Factory(fixture,capture)).TrashAsync(new(s.Actor,s.Verifier,a.Record.PublicId,1),default)).Error);Assert.Equal(2,capture.Locks.Count);Assert.Contains("cerberus.account",capture.Locks[0]);Assert.Contains("cerberus.vault_access_session",capture.Locks[1]);}
    [FunctionalFact]
    public async Task GivenUnrelatedDeepInventory_WhenTrashingOneOwnedTarget_ThenAnalyzeOneCandidateAndOrderedOwnedParentLocks()
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var scoped2=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var child=await Folder(s,a.Folder.Id);var target=await Record(s,child.Id);await Members(s,a.Collection,[target.Id],[]);await Profile(s,owner,scoped,records:[target.PublicId]);await Profile(s,owner,scoped2,records:[target.PublicId]);foreach(var account in new[]{s,foreign}){long? parent=null;for(var n=0;n<40;n++){var f=await Folder(account,parent);await Record(account,f.Id);parent=f.Id;}}
        var capture=new Capture(fixture,true);await Success(s,target,await new RecordTrashStore(new ProfileSetup.Factory(fixture,capture)).TrashAsync(new(s.Actor,s.Verifier,target.PublicId,1),default));Assert.Single(capture.Locks,x=>x.Contains("FROM cerberus.account "));Assert.Single(capture.Locks,x=>x.Contains("FROM cerberus.folder "));var profile=capture.Locks.FindIndex(x=>x.Contains("FROM cerberus.profile "));var collection=capture.Locks.FindIndex(x=>x.Contains("FROM cerberus.collection "));var folder=capture.Locks.FindIndex(x=>x.Contains("FROM cerberus.folder "));var record=capture.Locks.FindIndex(x=>x.Contains("FROM cerberus.record "));Assert.True(profile<collection&&collection<folder&&folder<record);Assert.Contains("ORDER BY p.public_id",capture.Locks[profile]);Assert.Contains("ORDER BY c.public_id",capture.Locks[collection]);using var plan=JsonDocument.Parse(capture.Plan!);
        static IEnumerable<JsonElement> Nodes(JsonElement n){yield return n;if(n.TryGetProperty("Plans",out var children))foreach(var c in children.EnumerateArray())foreach(var x in Nodes(c))yield return x;}
        var nodes=Nodes(plan.RootElement[0].GetProperty("Plan")).ToArray();Assert.Equal(1d,Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var name)&&name.GetString()=="CTE candidates").GetProperty("Actual Rows").GetDouble());Assert.Equal(2d,Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var name)&&name.GetString()=="CTE ancestry").GetProperty("Actual Rows").GetDouble());
    }
    private sealed class BeforeAssociations(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&c.CommandText.Contains("FROM cerberus.profile_record")&&c.CommandText.Contains("FOR UPDATE")){used=true;await action();}return r;}}
    private sealed class Capture(PostgresFixture fixture,bool analyze=false):DbCommandInterceptor
    {
        public List<string> Locks{get;}=[];public string? Plan{get;private set;}
        private void Note(DbCommand c){if(c.CommandText.Contains("FOR UPDATE")||c.CommandText.Contains("FOR NO KEY UPDATE")||c.CommandText.Contains("FOR SHARE"))Locks.Add(c.CommandText);}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Note(c);return ValueTask.FromResult(r);}
        public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Note(c);if(analyze&&Plan is null&&c.CommandText.StartsWith("WITH RECURSIVE")){await using var db=fixture.CreateContext();await db.Database.OpenConnectionAsync(ct);await using var cmd=db.Database.GetDbConnection().CreateCommand();cmd.CommandText="EXPLAIN (ANALYZE, FORMAT JSON) "+c.CommandText;foreach(var param in c.Parameters.Cast<NpgsqlParameter>())cmd.Parameters.Add(param.Clone());Plan=(string)(await cmd.ExecuteScalarAsync(ct))!;}return r;}
    }
'''
s=s.replace('    private RecordTrashStore Store()',extra+'\n    private RecordTrashStore Store()');p.write_text(s)
with (w/'.superpowers/sdd/2026-10-09-uc-20-delete-record/progress.md').open('a') as f:f.write('\nTask1 firstimplementation90/90 focusedPASS zero failure/skip (data-green-1.log), no corrections needed. Added remaining planned controlled actualcreate/association/recipient/rotation races, currentlink-removal/cycles/selection/overlappingnative/foreignlock/EXPLAINANALYZE cases beforewholeData completion; do not claim the additional cases failed missingtypes ininitialRED. NativeOSV153/corpus322fourdirections/36helpers/23Python/spec107FR55UC29BR freshPASS.\n')
print('Expanded planned concurrency/current-snapshot/actual-plan matrix.')
