using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using ArturRios.Cerberus.Command.Profiles;
using ArturRios.Cerberus.Command.Folders;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Folders;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Query.Folders;
using ArturRios.Cerberus.TestSupport;
using ArturRios.Configuration.Enums;
using ArturRios.Output;
using ArturRios.Util.Test.Functional;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;

namespace ArturRios.Cerberus.WebApi.Tests;

[Collection("Registration host")]
public class FolderUpdateHttpTests(RegistrationApiFixture fixture):WebApiTest<Program>(EnvironmentType.Local)
{
    [FunctionalTheory][InlineData("wide",false)][InlineData("Master",false)][InlineData("PerProfile",false)][InlineData("Master",true)][InlineData("PerProfile",true)]
    public async Task GivenNativeCurrentOwnedAccess_WhenReplacing_ThenOnlyFolderContentAndFourMetadataFieldsChange(string mode,bool folderRoute)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var child=await Folder(s,root.Id);var p=await Profile(s,owner,key,folderRoute?root:null,mode=="wide"?"Master":mode);var target=await Create(s,folderRoute?[]:[p.PublicId],child.PublicId);var actor=mode=="wide"?s:s with{Access=await Open(s,p,key)};var before=await Unrelated(s,target.FolderId);var input=Replacement();
        using var response=await Update(actor,target.FolderId,input);var data=await Success<UpdateFolderOutput>(response,200);Fields(data,"folderId","revision","serverSequence","editedAt");Assert.Contains("folder_updated",await response.Content.ReadAsStringAsync());await Changed(s,target,input,data);Assert.Equal(before,await Unrelated(s,target.FolderId));
        using var get=await Read(actor,"/api/folders/"+target.FolderId);Assert.Equal(input.Envelope,(await Success<FolderDetailsOutput>(get,200)).Envelope);
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false,false)][InlineData(CollectionGrantAccess.ReadOnly,true,true)][InlineData(CollectionGrantAccess.ReadWrite,false,false)][InlineData(CollectionGrantAccess.ReadWrite,true,false)][InlineData(CollectionGrantAccess.ReadWrite,false,true)][InlineData(CollectionGrantAccess.ReadWrite,true,true)]
    public async Task GivenNativeSharedGrant_WhenReplacing_ThenReadOnly403AndReadWriteUpdatesOriginalOwner(CollectionGrantAccess access,bool selected,bool folderRoute)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (collection,_)=await Share(o,owner,s,client,access,folderRoute?[]:[target.FolderId],folderRoute?[root.Id]:[]);var p=await Profile(s,client,key,collections:[collection.PublicId]);var actor=selected?s with{Access=await Open(s,p,key)}:s;var before=await Snapshot(o);var unrelated=await Unrelated(o,target.FolderId);var recipient=await Snapshot(s);var input=Replacement(access==CollectionGrantAccess.ReadOnly?99:1);
        using var response=await Update(actor,target.FolderId,input);if(access==CollectionGrantAccess.ReadOnly){await Failure(response,403,"vault_access_denied");Assert.Equal(before,await Snapshot(o));}else{var data=await Success<UpdateFolderOutput>(response,200);Fields(data,"folderId","revision","serverSequence","editedAt");await Changed(o,target,input,data);Assert.Equal(unrelated,await Unrelated(o,target.FolderId));}Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("missing")][InlineData("foreign")][InlineData("unselected")][InlineData("folderTrash")][InlineData("ancestorTrash")][InlineData("folderTerminal")][InlineData("ownerClosing")][InlineData("revoked")]
    public async Task GivenHiddenTargetWithBadCipherAndStaleRevision_WhenReplacing_ThenNonrevealing404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=kind=="unselected"?o:await Setup(client);var folder=await Folder(o);var target=await Create(o,folder:folder.PublicId);CollectionGrant? grant=null;if(kind!="foreign"&&s.InternalId!=o.InternalId){var share=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.FolderId],[]);grant=share.Item2;}if(kind=="unselected"){var p=await Profile(s,owner,key);s=s with{Access=await Open(s,p,key)};}
        await using(var db=fixture.Context()){await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Envelope,"bad"u8.ToArray()).SetProperty(r=>r.DeletedAt,kind=="folderTrash"?(DateTimeOffset?)DateTimeOffset.UtcNow:null));if(kind=="ancestorTrash")await db.Folders.Where(x=>x.Id==folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.DeletedAt,DateTimeOffset.UtcNow));if(kind=="folderTerminal"){db.TerminalErasures.Add(new(){ResourceId=target.FolderId,ResourceKind="folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==o.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="revoked")await db.CollectionGrants.Where(x=>x.Id==grant!.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));}
        var before=await Snapshot(o);using var response=await Update(s,kind=="missing"?Guid.NewGuid():target.FolderId,Replacement(88));await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("bad")][InlineData("zero")][InlineData("uppercase")][InlineData("compact")][InlineData("braced")][InlineData("urn")]
    public async Task GivenNoncanonicalRoute_WhenReplacing_Then400WithoutMutation(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var g=Guid.Parse("abcdefab-1234-4321-abcd-123456789abc");var id=kind switch{"bad"=>"bad","zero"=>Guid.Empty.ToString(),"uppercase"=>g.ToString().ToUpperInvariant(),"compact"=>g.ToString("N"),"braced"=>g.ToString("B"),_=>"urn:uuid:"+g};var before=await Snapshot(s);using var req=Put(s,"/api/folders/"+id,Bytes(Replacement()));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400,"validation_failed");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("unknown")][InlineData("owner")][InlineData("parent")][InlineData("record")][InlineData("profile")][InlineData("folder")][InlineData("collection")][InlineData("name")][InlineData("duplicate")][InlineData("case")][InlineData("numericRevision")][InlineData("numericEpoch")][InlineData("missingRevision")][InlineData("missingEnvelope")][InlineData("missingTime")][InlineData("null")][InlineData("empty")][InlineData("format")][InlineData("epoch")][InlineData("revision")][InlineData("unsafeRevision")][InlineData("time")][InlineData("offset")][InlineData("saltReuse")][InlineData("nonceReuse")]
    public async Task GivenInvalidOrForgedBody_WhenReplacing_Then400AndNoChanges(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var i=Replacement();if(kind=="format")i=i with{Envelope=i.Envelope with{Format="unknown"}};if(kind=="epoch")i=i with{Envelope=i.Envelope with{KeyEpoch=2}};if(kind=="revision")i=i with{ExpectedRevision=0};if(kind=="unsafeRevision")i=i with{ExpectedRevision=ProtocolBinary.MaxInteger+1};if(kind=="time")i=i with{EditedAt=new(9,TimeSpan.Zero)};if(kind=="offset")i=i with{EditedAt=i.EditedAt.ToOffset(TimeSpan.FromHours(1))};if(kind=="saltReuse")i=i with{Envelope=i.Envelope with{KeySalt=target.Envelope.KeySalt}};if(kind=="nonceReuse")i=i with{Envelope=i.Envelope with{Nonce=target.Envelope.Nonce}};
        var body=JsonSerializer.SerializeToNode(i,ProtectionFixture.Json)!.AsObject();if(kind=="missingRevision")body.Remove("expectedRevision");if(kind=="missingEnvelope")body.Remove("envelope");if(kind=="missingTime")body.Remove("editedAt");var field=kind switch{"unknown"=>"secret","owner"=>"ownerId","parent"=>"parentFolderId","record"=>"recordId","profile"=>"profileIds","folder"=>"folderId","collection"=>"collectionIds","name"=>"name",_=>null};if(field is not null)body[field]=null;var raw=body.ToJsonString();raw=kind switch{"null"=>"null","empty"=>"{}","duplicate"=>raw.Insert(1,"\"expectedRevision\":1,"),"case"=>raw.Replace("expectedRevision","ExpectedRevision"),"numericRevision"=>raw.Replace("\"expectedRevision\":1","\"expectedRevision\":\"1\""),"numericEpoch"=>raw.Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""),_=>raw};
        var before=await Snapshot(s);using var request=Put(s,"/api/folders/"+target.FolderId,Encoding.UTF8.GetBytes(raw));using var r=await Gateway.Client.SendAsync(request);await Failure(r,400);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("query",400)][InlineData("duplicate",400)][InlineData("bad",400)][InlineData("missing",401)][InlineData("utf8",400)][InlineData("bom",400)][InlineData("compression",400)][InlineData("charset",400)][InlineData("oversized",413)]
    public async Task GivenInvalidTransportOrAccess_WhenReplacing_ThenRejectWithoutMutation(string kind,int status)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);var raw=kind=="oversized"?Encoding.UTF8.GetBytes(new string(' ',65537)):kind=="utf8"?new byte[]{0xc3,0x28}:Bytes(Replacement());if(kind=="bom")raw=new byte[]{239,187,191}.Concat(raw).ToArray();using var req=Put(s,"/api/folders/"+target.FolderId+(kind=="query"?"?ownerId=secret":""),raw);if(kind=="missing")req.Headers.Remove("X-Cerberus-Vault-Access");if(kind=="bad"){req.Headers.Remove("X-Cerberus-Vault-Access");req.Headers.Add("X-Cerberus-Vault-Access","bad");}if(kind=="duplicate")req.Headers.TryAddWithoutValidation("X-Cerberus-Vault-Access",s.Access);if(kind=="compression")req.Content!.Headers.ContentEncoding.Add("gzip");if(kind=="charset")req.Content!.Headers.ContentType!.CharSet="utf-16";using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenRawEmptyAccessHeader_WhenReplacing_Then400()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);using var host=new WebApplicationFactory<Program>();var raw=Bytes(Replacement());var context=await host.Server.SendAsync(c=>{c.Request.Method="PUT";c.Request.Path="/api/folders/"+Guid.NewGuid();c.Request.Headers.Authorization="Bearer "+RegistrationApiFixture.Token(s.Actor);c.Request.Headers["X-Cerberus-Vault-Access"]="";c.Request.ContentType="application/json";c.Request.ContentLength=raw.Length;c.Request.Body=new MemoryStream(raw);});Assert.Equal(400,context.Response.StatusCode);Assert.Contains("no-store",context.Response.Headers.CacheControl.ToString());}
    [FunctionalTheory][InlineData("missing",401)][InlineData("scope",401)][InlineData("deleted",401)][InlineData("unavailable",503)]
    public async Task GivenInvalidCurrentIdentity_WhenReplacing_ThenRejectWithoutPersistence(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);if(kind is "deleted" or "unavailable")fixture.Users[s.Actor+"@example.test"]=new(s.Actor,"fixture-password",Deleted:kind=="deleted",IdentityUnavailable:kind=="unavailable");var before=await Snapshot(s);using var req=Put(s,"/api/folders/"+target.FolderId,Bytes(Replacement()));if(kind=="missing")req.Headers.Authorization=null;if(kind=="scope")req.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor,Guid.NewGuid()));using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("closing",404)][InlineData("terminal",404)][InlineData("revoked",403)][InlineData("expired",403)][InlineData("future",403)][InlineData("policy",403)][InlineData("generation",403)][InlineData("dangling",403)]
    public async Task GivenInvalidCurrentActorState_WhenReplacing_ThenNoMutation(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using(var db=fixture.Context()){var v=await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId);if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="dangling")v.ProfileId=long.MaxValue;if(kind=="closing")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);using var r=await Update(s,target.FolderId,Replacement());await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("grant",404)][InlineData("downgrade",403)][InlineData("member",404)][InlineData("move",404)]
    public async Task GivenCommittedSharedRelationshipChange_WhenReplacing_ThenCurrentPermissionWins(string kind,int status)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[],[root.Id]);using(var get=await Read(s,"/api/folders/"+target.FolderId))await Success<FolderDetailsOutput>(get,200);await using(var db=fixture.Context()){if(kind=="grant")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));if(kind=="downgrade")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.Access,CollectionGrantAccess.ReadOnly));if(kind=="member")await db.CollectionFolders.Where(x=>x.CollectionId==c.Id).ExecuteDeleteAsync();if(kind=="move")await db.Folders.Where(x=>x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.ParentFolderId,(long?)null));}var before=await Snapshot(o);using var r=await Update(s,target.FolderId,Replacement());await Failure(r,status);Assert.Equal(before,await Snapshot(o));}
    [FunctionalTheory][InlineData("signature")][InlineData("numericString")][InlineData("pins")]
    public async Task GivenRelevantMalformedNativeAuthority_WhenReplacing_Then503WithoutAnyContentChange(string kind)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.FolderId],[]);await using(var db=fixture.Context()){if(kind=="signature")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind=="numericString")await db.Collections.Where(x=>x.Id==c.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Envelope,Encoding.UTF8.GetBytes(Encoding.UTF8.GetString(c.Envelope).Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""))));if(kind=="pins")await db.VaultProtections.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Material,"bad"u8.ToArray()));}var before=await Snapshot(o);using var r=await Update(s,target.FolderId,Replacement());await Failure(r,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));}
    [FunctionalTheory][InlineData("envelope")][InlineData("sequence")][InlineData("revision")][InlineData("outage")]
    public async Task GivenCorruptVisibleTargetOrUnavailableDatabase_WhenReplacing_Then503WithoutPartialPayload(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using var db=fixture.Context();if(kind=="envelope")await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Envelope,"bad"u8.ToArray()));if(kind=="sequence")await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.ServerSequence,0));if(kind=="revision")await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Revision,0));var before=await Snapshot(s);if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.folder RENAME TO fixture_unavailable_folder");try{using var r=await Update(s,target.FolderId,Replacement());await Failure(r,503,"persistence_unavailable");}finally{if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_folder RENAME TO folder");}Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenLostSuccessRetryAndStaleRevision_WhenReplacing_Then409PreservesWinner()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var input=Replacement();using(var r=await Update(s,target.FolderId,input))await Changed(s,target,input,await Success<UpdateFolderOutput>(r,200));var before=await Snapshot(s);using var retry=await Update(s,target.FolderId,input);await Failure(retry,409,"revision_conflict");using var other=await Update(s,target.FolderId,Replacement());await Failure(other,409,"revision_conflict");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(1,400)][InlineData(9,400)][InlineData(10,200)]
    public async Task GivenTimestampAtStorageMinimum_WhenReplacing_ThenRejectUnrepresentableAndPreserveGetContract(long ticks,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);var input=Replacement() with{EditedAt=new(ticks,TimeSpan.Zero)};using var r=await Update(s,target.FolderId,input);if(status==400){await Failure(r,status);Assert.Equal(before,await Snapshot(s));}else await Changed(s,target,input,await Success<UpdateFolderOutput>(r,200));using var get=await Read(s,"/api/folders/"+target.FolderId);await Success<FolderDetailsOutput>(get,200);}

    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,"wide")][InlineData(CollectionGrantAccess.ReadWrite,"wide")][InlineData(CollectionGrantAccess.ReadOnly,"Master")][InlineData(CollectionGrantAccess.ReadWrite,"Master")][InlineData(CollectionGrantAccess.ReadOnly,"PerProfile")][InlineData(CollectionGrantAccess.ReadWrite,"PerProfile")]
    public async Task GivenActualNativeRecordOnlyGrant_WhenReplacingContainingFolder_Then404AfterSuccessfulRecordGet(CollectionGrantAccess access,string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var record=await CreateRecord(o,target.FolderId);var (collection,grant)=await Share(o,owner,s,client,access,[],[]);
        await using(var db=fixture.Context()){var row=await db.Records.SingleAsync(x=>x.PublicId==record.RecordId);db.CollectionRecords.Add(new(){AccountId=o.InternalId,CollectionId=collection.Id,RecordId=row.Id});await db.SaveChangesAsync();}
        var actor=s;if(mode!="wide"){var p=await Profile(s,client,key,mode:mode,collections:[collection.PublicId]);actor=s with{Access=await Open(s,p,key)};}
        using(var get=await Read(actor,"/api/records/"+record.RecordId)){var proof=await Success<ArturRios.Cerberus.Query.Records.RecordDetailsOutput>(get,200);Assert.Equal(record.RecordId,proof.RecordId);Assert.Null(proof.FolderId);}
        await using(var db=fixture.Context()){await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.Envelope,"bad"u8.ToArray()));await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));}
        var before=await Snapshot(o);var recipient=await Snapshot(s);using var response=await Update(actor,target.FolderId,Replacement(77));await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenSelectedDirectRecordOnly_WhenReplacingContainingFolder_Then404AfterSuccessfulRecordGet(string mode)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var record=await CreateRecord(s,target.FolderId);var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,key.Material.UnlockVerifier,owner.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?key.Material.PasswordWrapper:null),DateTimeOffset.UnixEpoch,[record.RecordId],[],[]);
        using(var req=Request(s,Bytes(input),"/api/profiles"))using(var response=await Gateway.Client.SendAsync(req))await Success<CreateProfileOutput>(response,201);
        await using var db=fixture.Context();var p=await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);var selected=s with{Access=await Open(s,p,key)};
        using(var get=await Read(selected,"/api/records/"+record.RecordId)){var proof=await Success<ArturRios.Cerberus.Query.Records.RecordDetailsOutput>(get,200);Assert.Equal(record.RecordId,proof.RecordId);Assert.Null(proof.FolderId);}
        var before=await Snapshot(s);using var response2=await Update(selected,target.FolderId,Replacement(77));await Failure(response2,404,"not_found");Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("parent",false)][InlineData("sibling",false)][InlineData("parent",true)][InlineData("sibling",true)]
    public async Task GivenNativeMemberLeafWriteGrant_WhenReplacingUnsharedParentOrSibling_Then404AndNoChanges(string kind,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var leaf=await Create(o,folder:root.PublicId);var sibling=await Create(o,folder:root.PublicId);var (collection,_)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[leaf.FolderId],[]);var actor=s;
        if(selected){var p=await Profile(s,client,key,collections:[collection.PublicId]);actor=s with{Access=await Open(s,p,key)};}
        using(var get=await Read(actor,"/api/folders/"+leaf.FolderId)){var proof=await Success<FolderDetailsOutput>(get,200);Assert.Null(proof.ParentFolderId);Assert.Empty(proof.ProfileIds);}
        var before=await Snapshot(o);using var response=await Update(actor,kind=="parent"?root.PublicId:sibling.FolderId,Replacement(77));await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenCorruptOverlappingContributor_WhenReplacing_ThenSelectedValidRouteSucceedsAndWideFailsWholeResponse(string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var (good,_)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.FolderId],[]);var (_,bad)=await Share(o,owner,s,client,CollectionGrantAccess.ReadOnly,[target.FolderId],[]);var p=await Profile(s,client,key,mode:mode,collections:[good.PublicId]);var selected=s with{Access=await Open(s,p,key)};
        await using(var db=fixture.Context())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));var input=Replacement();using(var response=await Update(selected,target.FolderId,input))await Changed(o,target,input,await Success<UpdateFolderOutput>(response,200));
        var before=await Snapshot(o);using var denied=await Update(s,target.FolderId,Replacement(2));await Failure(denied,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("profileTrash")][InlineData("profileTerminal")]
    public async Task GivenSelectedProfileBecomesHidden_WhenReplacing_Then403WithoutNullingOrWideningSelection(string kind)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var p=await Profile(s,owner,key);var target=await Create(s,[p.PublicId]);var selected=s with{Access=await Open(s,p,key)};
        await using(var db=fixture.Context()){if(kind=="profileTrash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));else{db.TerminalErasures.Add(new(){ResourceId=p.PublicId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}
        var before=await Snapshot(s);using var response=await Update(selected,target.FolderId,Replacement());await Failure(response,403,"vault_access_denied");Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenFolderWithActualChildAndRecord_WhenReplacingContent_ThenOnlyTargetMetadataChanges()
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await Create(s,folder:target.FolderId);await CreateRecord(s,target.FolderId);await using var db=fixture.Context();var row=await db.Folders.AsNoTracking().SingleAsync(x=>x.PublicId==target.FolderId);Assert.Equal(3,row.Revision);var before=await Unrelated(s,target.FolderId);var input=Replacement(3);
        using var response=await Update(s,target.FolderId,input);await Changed(s,target,input,await Success<UpdateFolderOutput>(response,200));Assert.Equal(before,await Unrelated(s,target.FolderId));
    }
    private async Task<ArturRios.Cerberus.Domain.Records.RecordCreateInput> CreateRecord(State s,Guid folder)
    {
        var input=new ArturRios.Cerberus.Domain.Records.RecordCreateInput(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch,[],folder);using var req=Request(s,Bytes(input),"/api/records");using var response=await Gateway.Client.SendAsync(req);await Success<ArturRios.Cerberus.Command.Records.CreateRecordOutput>(response,201);return input;
    }
    [FunctionalTheory][InlineData("older")][InlineData("equal")][InlineData("pre2000")][InlineData("sameEnvelope")]
    public async Task GivenMatchingRevisionAndRepresentableClientTime_WhenReplacing_ThenRevisionWinsAndGetPreservesAcceptedCipher(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var input=Replacement() with{EditedAt=kind=="older"?target.EditedAt.AddTicks(-11):kind=="pre2000"?new DateTimeOffset(1999,12,31,23,59,59,TimeSpan.Zero).AddTicks(19):target.EditedAt};if(kind=="sameEnvelope")input=input with{Envelope=target.Envelope};
        using(var response=await Update(s,target.FolderId,input))await Changed(s,target,input,await Success<UpdateFolderOutput>(response,200));using var get=await Read(s,"/api/folders/"+target.FolderId);var result=await Success<FolderDetailsOutput>(get,200);Assert.Equal(2,result.Revision);Assert.Equal(Normalize(input.EditedAt),result.EditedAt);Assert.Equal(input.Envelope,result.Envelope);
    }
    private static FolderUpdateInput Replacement(long revision=1)=>new(revision,Envelope(),DateTimeOffset.Parse("2026-10-09T00:00:00Z").AddTicks(19));
    private static HttpRequestMessage Put(State s,string path,byte[] body){var r=Request(s,body,path);r.Method=HttpMethod.Put;return r;}
    private async Task<HttpResponseMessage> Update(State s,Guid id,FolderUpdateInput input){using var req=Put(s,"/api/folders/"+id,Bytes(input));return await Gateway.Client.SendAsync(req);}
    private async Task Changed(State owner,FolderCreateInput target,FolderUpdateInput input,UpdateFolderOutput output)
    {
        Assert.Equal(target.FolderId,output.FolderId);Assert.Equal(input.ExpectedRevision+1,output.Revision);Assert.Equal(Normalize(input.EditedAt),output.EditedAt);
        await using var db=fixture.Context();var row=await db.Folders.SingleAsync(x=>x.PublicId==target.FolderId);Assert.Equal(owner.InternalId,row.AccountId);Assert.Equal(output.Revision,row.Revision);Assert.Equal(output.ServerSequence,row.ServerSequence);Assert.True(output.ServerSequence>0);Assert.Equal(output.EditedAt,row.EditedAt);Assert.Equal(input.Envelope,JsonSerializer.Deserialize<EncryptedEnvelope>(row.Envelope,ProtectionFixture.Json));
        if(target.ParentFolderId is null)Assert.Null(row.ParentFolderId);else Assert.Equal(target.ParentFolderId,(await db.Folders.SingleAsync(x=>x.Id==row.ParentFolderId)).PublicId);
    }
    private async Task<string> Unrelated(State s,Guid target){var node=JsonNode.Parse(await Snapshot(s))!.AsObject();var rows=node["Folders"]!.AsArray();node["Folders"]=new JsonArray(rows.Where(r=>r!["PublicId"]!.GetValue<Guid>()!=target).Select(r=>r!.DeepClone()).ToArray());return node.ToJsonString();}
    private async Task<FolderCreateInput> Create(State s,Guid[]? profiles=null,Guid? folder=null){var input=Input(profiles,folder);using var response=await Send(s,input);await Success<CreateFolderOutput>(response,201);return input;}
    private async Task<(VaultCollection,CollectionGrant)> Share(State owner,ProtectionFixture author,State recipient,ProtectionFixture recipientKeys,CollectionGrantAccess access,Guid[] folderIds,long[] folders){await using var db=fixture.Context();var collection=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=owner.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(collection);await db.SaveChangesAsync();var grant=new CollectionGrant{PublicId=Guid.NewGuid(),CollectionId=collection.Id,RecipientAccountId=recipient.InternalId,Access=access};grant.RecipientKeyEnvelope=Bytes(author.WrapGrant(owner.AccountId,collection.PublicId,grant.PublicId,recipient.Actor,recipientKeys.Material.RecipientKey));db.CollectionGrants.Add(grant);foreach(var id in folderIds){var folder=await db.Folders.SingleAsync(x=>x.PublicId==id);db.CollectionFolders.Add(new(){AccountId=owner.InternalId,CollectionId=collection.Id,FolderId=folder.Id});}db.CollectionFolders.AddRange(folders.Select(id=>new CollectionFolder{AccountId=owner.InternalId,CollectionId=collection.Id,FolderId=id}));await db.SaveChangesAsync();return(collection,grant);}
    private sealed class BodyFeature:IHttpRequestBodyDetectionFeature{public bool CanHaveBody=>true;}
    private sealed record State(Guid Actor,Guid AccountId,long InternalId,string Access);
    private async Task<State> Setup(ProtectionFixture client)
    {var actor=Guid.NewGuid();fixture.Users[actor+"@example.test"]=new(actor,"fixture-password");await using var db=fixture.Context();var account=new Account{PublicId=Guid.NewGuid(),HeimdallPublicId=actor,DetailsEnvelope=Bytes(Envelope())};db.Accounts.Add(account);await db.SaveChangesAsync();var access=ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32));OpaqueAccessHandle.TryHash(access,out var verifier);db.VaultProtections.Add(new(){AccountId=account.Id,Material=Bytes(client.Material)});db.VaultAccessSessions.Add(new(){AccountId=account.Id,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return new(actor,account.PublicId,account.Id,access);}
    private async Task<VaultFolder> Folder(State s,long? parent=null){var f=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.Context();db.Folders.Add(f);await db.SaveChangesAsync();return f;}
    private async Task<Profile> Profile(State s,ProtectionFixture owner,ProtectionFixture scoped,VaultFolder? folder=null,string mode="Master",Guid[]? collections=null)
    {var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,scoped.Material.UnlockVerifier,owner.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?scoped.Material.PasswordWrapper:null),DateTimeOffset.UnixEpoch,[],folder is null?[]:[folder.PublicId],collections??[]);using var request=Request(s,Bytes(input),"/api/profiles");using var r=await Gateway.Client.SendAsync(request);Assert.Equal(HttpStatusCode.Created,r.StatusCode);await using var db=fixture.Context();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<string> Open(State s,Profile p,ProtectionFixture scoped)
    {await using var db=fixture.Context();var revision=(await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id)).Revision;var raw=Bytes(new{expectedRevision=revision});using var challengeRequest=Request(s,Bytes(new{expectedRevision=revision,requestHash=ProtocolBinary.Encode(SHA256.HashData(raw))}),"/api/profiles/"+p.PublicId+"/access/challenges");challengeRequest.Headers.Remove("X-Cerberus-Vault-Access");using var issued=await Gateway.Client.SendAsync(challengeRequest);var challenge=(await Success<IssueProfileAccessChallengeOutput>(issued,201)).Challenge;using var open=Request(s,raw,"/api/profiles/"+p.PublicId+"/access");open.Headers.Remove("X-Cerberus-Vault-Access");open.Headers.Add("X-Cerberus-Challenge-Id",challenge.ChallengeId.ToString());open.Headers.Add("X-Cerberus-Proof",scoped.Sign(challenge));using var response=await Gateway.Client.SendAsync(open);return (await Success<OpenProfileAccessOutput>(response,200)).VaultAccess;}
    private static FolderCreateInput Input(Guid[]? profiles=null,Guid? folder=null)=>new(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch.AddTicks(19),profiles??[],folder);
    private static EncryptedEnvelope Envelope(long epoch=1)=>new("cerberus-content-v1",epoch,ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(12)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(73)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(16)));
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
    private static DateTimeOffset Normalize(DateTimeOffset value)=>value.AddTicks(-(value.Ticks%10));
    private static HttpRequestMessage Request(State s,byte[] body,string path="/api/folders"){var r=new HttpRequestMessage(HttpMethod.Post,path){Content=new ByteArrayContent(body)};r.Content.Headers.ContentType=new("application/json");r.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));r.Headers.Add("X-Cerberus-Vault-Access",s.Access);return r;}
    private async Task<HttpResponseMessage> Send(State s,FolderCreateInput input){using var request=Request(s,Bytes(input));return await Gateway.Client.SendAsync(request);}
    private async Task<HttpResponseMessage> Read(State s,string path){using var request=new HttpRequestMessage(HttpMethod.Get,path);request.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));request.Headers.Add("X-Cerberus-Vault-Access",s.Access);return await Gateway.Client.SendAsync(request);}
    private async Task<string> Protected(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Protection=await db.VaultProtections.AsNoTracking().SingleAsync(x=>x.AccountId==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<string> Snapshot(State s,bool skipMembers=false){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Protected=await Protected(s),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>x.RecipientAccountId==s.InternalId || db.Collections.Any(c=>c.Id==x.CollectionId && c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Members=await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),CollectionFolders=skipMembers?[]:await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId && p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync()});}
    private static async Task<T> Success<T>(HttpResponseMessage r,int status) where T:class{Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);var result=await r.Content.ReadFromJsonAsync<DataOutput<T>>();Assert.True(result!.Success);return Assert.IsType<T>(result.Data);}
    private static void Fields(object value,params string[] names){using var d=JsonDocument.Parse(JsonSerializer.Serialize(value,ProtectionFixture.Json));Assert.Equal(names.Order(),d.RootElement.EnumerateObject().Select(x=>x.Name).Order());}
    private static async Task Failure(HttpResponseMessage r,int status,string? error=null){Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);if(status==413){Assert.Equal("",await r.Content.ReadAsStringAsync());return;}using var d=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.False(d.RootElement.GetProperty("success").GetBoolean());if(d.RootElement.TryGetProperty("data",out var data))Assert.Equal(JsonValueKind.Null,data.ValueKind);if(error is not null)Assert.Contains(error,d.RootElement.GetProperty("errors").EnumerateArray().Select(x=>x.GetString()));}
}
