using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using ArturRios.Cerberus.Command.Profiles;
using ArturRios.Cerberus.Command.Folders;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Folders;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Query.Folders;
using ArturRios.Cerberus.Query.Records;
using ArturRios.Cerberus.Domain.Trash;
using ArturRios.Cerberus.TestSupport;
using ArturRios.Configuration.Enums;
using ArturRios.Output;
using ArturRios.Util.Test.Functional;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;

namespace ArturRios.Cerberus.WebApi.Tests;

[Collection("Registration host")]
public class FolderMoveHttpTests(RegistrationApiFixture fixture):WebApiTest<Program>(EnvironmentType.Local)
{
    [FunctionalTheory][InlineData("bad")][InlineData("zero")][InlineData("uppercase")][InlineData("compact")][InlineData("braced")][InlineData("urn")]
    public async Task GivenNoncanonicalRoute_WhenMoving_Then400WithoutMutation(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var g=Guid.Parse("abcdefab-1234-4321-abcd-123456789abc");var id=kind switch{"bad"=>"bad","zero"=>Guid.Empty.ToString(),"uppercase"=>g.ToString().ToUpperInvariant(),"compact"=>g.ToString("N"),"braced"=>g.ToString("B"),_=>"urn:uuid:"+g};var before=await Snapshot(s);using var req=PutParent(s,"/api/folders/"+id,Bytes(new{expectedRevision=1,parentFolderId=(Guid?)null}));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400,"validation_failed");Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData("query",400)][InlineData("duplicate",400)][InlineData("bad",400)][InlineData("missing",401)][InlineData("utf8",400)][InlineData("bom",400)][InlineData("compression",400)][InlineData("charset",400)][InlineData("oversized",413)]
    public async Task GivenInvalidTransportOrAccess_WhenMoving_ThenRejectWithoutMutation(string kind,int status)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);var raw=kind=="oversized"?Encoding.UTF8.GetBytes(new string(' ',65537)):kind=="utf8"?new byte[]{0xc3,0x28}:Bytes(new{expectedRevision=1,parentFolderId=(Guid?)null});if(kind=="bom")raw=new byte[]{239,187,191}.Concat(raw).ToArray();using var req=PutParent(s,"/api/folders/"+target.FolderId+(kind=="query"?"?ownerId=secret":""),raw);if(kind=="missing")req.Headers.Remove("X-Cerberus-Vault-Access");if(kind=="bad"){req.Headers.Remove("X-Cerberus-Vault-Access");req.Headers.Add("X-Cerberus-Vault-Access","bad");}if(kind=="duplicate")req.Headers.TryAddWithoutValidation("X-Cerberus-Vault-Access",s.Access);if(kind=="compression")req.Content!.Headers.ContentEncoding.Add("gzip");if(kind=="charset")req.Content!.Headers.ContentType!.CharSet="utf-16";using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalFact]
    public async Task GivenRawEmptyAccessHeader_WhenMoving_Then400()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);using var host=new WebApplicationFactory<Program>();var raw=Bytes(new{expectedRevision=1,parentFolderId=(Guid?)null});var context=await host.Server.SendAsync(c=>{c.Request.Method="PUT";c.Request.Path="/api/folders/"+Guid.NewGuid()+"/parent";c.Request.Headers.Authorization="Bearer "+RegistrationApiFixture.Token(s.Actor);c.Request.Headers["X-Cerberus-Vault-Access"]="";c.Request.ContentType="application/json";c.Request.ContentLength=raw.Length;c.Request.Body=new MemoryStream(raw);});Assert.Equal(400,context.Response.StatusCode);Assert.Contains("no-store",context.Response.Headers.CacheControl.ToString());}

    [FunctionalTheory][InlineData("missing",401)][InlineData("scope",401)][InlineData("deleted",401)][InlineData("unavailable",503)]
    public async Task GivenInvalidCurrentIdentity_WhenMoving_ThenRejectWithoutPersistence(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);if(kind is "deleted" or "unavailable")fixture.Users[s.Actor+"@example.test"]=new(s.Actor,"fixture-password",Deleted:kind=="deleted",IdentityUnavailable:kind=="unavailable");var before=await Snapshot(s);using var req=PutParent(s,"/api/folders/"+target.FolderId,Bytes(new{expectedRevision=1,parentFolderId=(Guid?)null}));if(kind=="missing")req.Headers.Authorization=null;if(kind=="scope")req.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor,Guid.NewGuid()));using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData("closing",404)][InlineData("terminal",404)][InlineData("revoked",403)][InlineData("expired",403)][InlineData("future",403)][InlineData("policy",403)][InlineData("generation",403)][InlineData("dangling",403)]
    public async Task GivenInvalidCurrentActorState_WhenMoving_ThenNoMutation(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using(var db=fixture.Context()){var v=await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId);if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="dangling")v.ProfileId=long.MaxValue;if(kind=="closing")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);using var r=await Move(s,target.FolderId,1);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData("missing")][InlineData("foreign")][InlineData("unselected")][InlineData("folderTrash")][InlineData("ancestorTrash")][InlineData("folderTerminal")][InlineData("ownerClosing")][InlineData("revoked")]
    public async Task GivenHiddenTargetWithBadCipherAndStaleRevision_WhenMoving_ThenNonrevealing404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=kind=="unselected"?o:await Setup(client);var folder=await Folder(o);var target=await Create(o,folder:folder.PublicId);CollectionGrant? grant=null;if(kind!="foreign"&&s.InternalId!=o.InternalId){var share=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.FolderId],[]);grant=share.Item2;}if(kind=="unselected"){var p=await Profile(s,owner,key);s=s with{Access=await Open(s,p,key)};}
        await using(var db=fixture.Context()){await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Envelope,"bad"u8.ToArray()).SetProperty(r=>r.DeletedAt,kind=="folderTrash"?(DateTimeOffset?)DateTimeOffset.UtcNow:null));if(kind=="ancestorTrash")await db.Folders.Where(x=>x.Id==folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.DeletedAt,DateTimeOffset.UtcNow));if(kind=="folderTerminal"){db.TerminalErasures.Add(new(){ResourceId=target.FolderId,ResourceKind="folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==o.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="revoked")await db.CollectionGrants.Where(x=>x.Id==grant!.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));}
        var before=await Snapshot(o);using var response=await Move(s,kind=="missing"?Guid.NewGuid():target.FolderId,88);await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalTheory][InlineData("grant",404)][InlineData("downgrade",403)][InlineData("member",404)][InlineData("move",404)]
    public async Task GivenCommittedSharedRelationshipChange_WhenMoving_ThenCurrentPermissionWins(string kind,int status)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[],[root.Id]);using(var get=await Read(s,"/api/folders/"+target.FolderId))await Success<FolderDetailsOutput>(get,200);await using(var db=fixture.Context()){if(kind=="grant")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));if(kind=="downgrade")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.Access,CollectionGrantAccess.ReadOnly));if(kind=="member")await db.CollectionFolders.Where(x=>x.CollectionId==c.Id).ExecuteDeleteAsync();if(kind=="move")await db.Folders.Where(x=>x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.ParentFolderId,(long?)null));}var before=await Snapshot(o);using var r=await Move(s,target.FolderId,1);await Failure(r,status);Assert.Equal(before,await Snapshot(o));}

    [FunctionalTheory][InlineData("signature")][InlineData("numericString")][InlineData("pins")]
    public async Task GivenRelevantMalformedNativeAuthority_WhenMoving_Then503WithoutAnyContentChange(string kind)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.FolderId],[]);await using(var db=fixture.Context()){if(kind=="signature")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind=="numericString")await db.Collections.Where(x=>x.Id==c.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Envelope,Encoding.UTF8.GetBytes(Encoding.UTF8.GetString(c.Envelope).Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""))));if(kind=="pins")await db.VaultProtections.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Material,"bad"u8.ToArray()));}var before=await Snapshot(o);using var r=await Move(s,target.FolderId,1);await Failure(r,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));}

    [FunctionalTheory][InlineData("profileTrash")][InlineData("profileTerminal")]
    public async Task GivenSelectedProfileBecomesHidden_WhenMoving_Then403WithoutNullingOrWideningSelection(string kind)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var p=await Profile(s,owner,key);var target=await Create(s,[p.PublicId]);var selected=s with{Access=await Open(s,p,key)};
        await using(var db=fixture.Context()){if(kind=="profileTrash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));else{db.TerminalErasures.Add(new(){ResourceId=p.PublicId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}
        var before=await Snapshot(s);using var response=await Move(selected,target.FolderId,1);await Failure(response,403,"vault_access_denied");Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("parent",false)][InlineData("sibling",false)][InlineData("parent",true)][InlineData("sibling",true)]
    public async Task GivenNativeMemberLeafWriteGrant_WhenMovingUnsharedParentOrSibling_Then404AndNoChanges(string kind,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var leaf=await Create(o,folder:root.PublicId);var sibling=await Create(o,folder:root.PublicId);var (collection,_)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[leaf.FolderId],[]);var actor=s;
        if(selected){var p=await Profile(s,client,key,collections:[collection.PublicId]);actor=s with{Access=await Open(s,p,key)};}
        using(var get=await Read(actor,"/api/folders/"+leaf.FolderId)){var proof=await Success<FolderDetailsOutput>(get,200);Assert.Null(proof.ParentFolderId);Assert.Empty(proof.ProfileIds);}
        var before=await Snapshot(o);using var response=await Move(actor,kind=="parent"?root.PublicId:sibling.FolderId,77);await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,"wide")][InlineData(CollectionGrantAccess.ReadWrite,"wide")][InlineData(CollectionGrantAccess.ReadOnly,"Master")][InlineData(CollectionGrantAccess.ReadWrite,"Master")][InlineData(CollectionGrantAccess.ReadOnly,"PerProfile")][InlineData(CollectionGrantAccess.ReadWrite,"PerProfile")]
    public async Task GivenActualNativeRecordOnlyGrant_WhenMovingContainingFolder_Then404AfterSuccessfulRecordGet(CollectionGrantAccess access,string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var record=await CreateRecord(o,target.FolderId);var (collection,grant)=await Share(o,owner,s,client,access,[],[]);
        await using(var db=fixture.Context()){var row=await db.Records.SingleAsync(x=>x.PublicId==record.RecordId);db.CollectionRecords.Add(new(){AccountId=o.InternalId,CollectionId=collection.Id,RecordId=row.Id});await db.SaveChangesAsync();}
        var actor=s;if(mode!="wide"){var p=await Profile(s,client,key,mode:mode,collections:[collection.PublicId]);actor=s with{Access=await Open(s,p,key)};}
        using(var get=await Read(actor,"/api/records/"+record.RecordId)){var proof=await Success<ArturRios.Cerberus.Query.Records.RecordDetailsOutput>(get,200);Assert.Equal(record.RecordId,proof.RecordId);Assert.Null(proof.FolderId);}
        await using(var db=fixture.Context()){await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.Envelope,"bad"u8.ToArray()));await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));}
        var before=await Snapshot(o);var recipient=await Snapshot(s);using var response=await Move(actor,target.FolderId,77);await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenSelectedDirectRecordOnly_WhenMovingContainingFolder_Then404AfterSuccessfulRecordGet(string mode)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var record=await CreateRecord(s,target.FolderId);var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,key.Material.UnlockVerifier,owner.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?key.Material.PasswordWrapper:null),DateTimeOffset.UnixEpoch,[record.RecordId],[],[]);
        using(var req=Request(s,Bytes(input),"/api/profiles"))using(var response=await Gateway.Client.SendAsync(req))await Success<CreateProfileOutput>(response,201);
        await using var db=fixture.Context();var p=await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);var selected=s with{Access=await Open(s,p,key)};
        using(var get=await Read(selected,"/api/records/"+record.RecordId)){var proof=await Success<ArturRios.Cerberus.Query.Records.RecordDetailsOutput>(get,200);Assert.Equal(record.RecordId,proof.RecordId);Assert.Null(proof.FolderId);}
        var before=await Snapshot(s);using var response2=await Move(selected,target.FolderId,77);await Failure(response2,404,"not_found");Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("sequence")][InlineData("revision")][InlineData("outage")]
    public async Task GivenCorruptVisibleTargetOrUnavailableDatabase_WhenMoving_Then503WithoutPartialPayload(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using var db=fixture.Context();if(kind=="sequence")await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.ServerSequence,0));if(kind=="revision")await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Revision,0));var before=await Snapshot(s);if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.folder RENAME TO fixture_unavailable_folder");try{using var r=await Move(s,target.FolderId,1);await Failure(r,503,"persistence_unavailable");}finally{if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_folder RENAME TO folder");}Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,"wide")][InlineData(CollectionGrantAccess.ReadWrite,"wide")][InlineData(CollectionGrantAccess.ReadOnly,"Master")][InlineData(CollectionGrantAccess.ReadWrite,"Master")][InlineData(CollectionGrantAccess.ReadOnly,"PerProfile")][InlineData(CollectionGrantAccess.ReadWrite,"PerProfile")]
    public async Task GivenActualNativeForeignFolderScope_WhenMovingStaleDamagedCipher_Then403ForEveryRecipientMode(CollectionGrantAccess access,string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Create(o);var target=await Create(o,folder:root.FolderId);var (c,_)=await Share(o,owner,s,client,access,[root.FolderId],[]);var p=await Profile(s,client,key,mode:mode=="wide"?"Master":mode,collections:[c.PublicId]);var actor=mode=="wide"?s:s with{Access=await Open(s,p,key)};using(var get=await Read(actor,"/api/folders/"+target.FolderId))await Success<FolderDetailsOutput>(get,200);await using(var db=fixture.Context())await db.Folders.Where(x=>x.PublicId==target.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged"u8.ToArray()));var before=await Snapshot(o);var recipient=await Snapshot(s);using var r=await Move(actor,target.FolderId,99);await Failure(r,403,"vault_access_denied");Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenCorruptOverlappingContributor_WhenMoving_ThenSelectedValidRoute403AndWide503WithoutMutation(string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Create(o);var (good,_)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[root.FolderId],[]);var (_,bad)=await Share(o,owner,s,client,CollectionGrantAccess.ReadOnly,[root.FolderId],[]);var p=await Profile(s,client,key,mode:mode,collections:[good.PublicId]);var selected=s with{Access=await Open(s,p,key)};await using(var db=fixture.Context())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(o);using var scoped=await Move(selected,root.FolderId,99);await Failure(scoped,403,"vault_access_denied");using var wide=await Move(s,root.FolderId,99);await Failure(wide,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalTheory][InlineData("recordId")][InlineData("cascade")][InlineData("actor")][InlineData("vaultAccess")][InlineData("folderId")][InlineData("ownerId")][InlineData("profileIds")][InlineData("collectionIds")][InlineData("name")][InlineData("fields")][InlineData("keyWrappers")][InlineData("envelope")][InlineData("editedAt")][InlineData("trashOperationId")][InlineData("deletedAt")][InlineData("purgeAt")][InlineData("unknown")][InlineData("zero")][InlineData("negative")][InlineData("unsafe")][InlineData("missingRevision")][InlineData("missingFolder")][InlineData("duplicateRevision")][InlineData("duplicateFolder")][InlineData("caseRevision")][InlineData("caseFolder")][InlineData("numericString")][InlineData("nullRevision")][InlineData("fraction")][InlineData("overflow")][InlineData("null")][InlineData("array")][InlineData("empty")][InlineData("folderZero")][InlineData("folderBad")][InlineData("folderUppercase")][InlineData("folderCompact")][InlineData("folderNumeric")]
    public async Task GivenStrictOrForgedMoveBody_WhenMoving_Then400WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var raw=StrictBody(kind);var before=await Snapshot(s);using var req=PutParent(s,"/api/folders/"+target.FolderId,Encoding.UTF8.GetBytes(raw));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400);Assert.Equal(before,await Snapshot(s));
    }


    [FunctionalFact]
    public async Task GivenUnmodifiedStrictBodyFixture_WhenMoving_ThenAcceptValidBodyAndReturnExactMetadata()
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var original=await FolderRow(target.FolderId);var stable=await Stable(s,original.Id);
        using var request=PutParent(s,"/api/folders/"+target.FolderId,Encoding.UTF8.GetBytes(StrictBody("valid")));
        using var response=await Gateway.Client.SendAsync(request);
        await Moved(original,null,await Success<MoveFolderOutput>(response,200));
        Assert.Equal(stable,await Stable(s,original.Id));
    }

    private static string StrictBody(string kind)
    {
        var body=JsonSerializer.SerializeToNode(new{expectedRevision=1,parentFolderId=(Guid?)null},ProtectionFixture.Json)!.AsObject();var fields=new[]{"recordId","cascade","actor","vaultAccess","folderId","ownerId","profileIds","collectionIds","name","fields","keyWrappers","envelope","editedAt","trashOperationId","deletedAt","purgeAt"};if(fields.Contains(kind))body[kind]=null;if(kind=="unknown")body["secret"]=null;if(kind is "zero" or "negative" or "unsafe")body["expectedRevision"]=kind=="zero"?0:kind=="negative"?-1:9007199254740992;if(kind=="missingRevision")body.Remove("expectedRevision");if(kind=="missingFolder")body.Remove("parentFolderId");if(kind=="caseRevision"){body.Remove("expectedRevision");body["ExpectedRevision"]=1;}if(kind=="caseFolder"){body.Remove("parentFolderId");body["ParentFolderId"]=null;}if(kind=="numericString")body["expectedRevision"]="1";if(kind=="nullRevision")body["expectedRevision"]=null;if(kind=="fraction")body["expectedRevision"]=1.5;if(kind=="overflow")body["expectedRevision"]=9223372036854775808m;if(kind is "folderZero" or "folderBad" or "folderUppercase" or "folderCompact" or "folderNumeric")body["parentFolderId"]=kind switch{"folderZero"=>Guid.Empty.ToString(),"folderBad"=>"bad","folderUppercase"=>"ABCDEFAB-1234-4321-ABCD-123456789ABC",_=>"abcdefab12344321abcd123456789abc"};if(kind=="folderNumeric")body["parentFolderId"]=1;
        return kind switch{"duplicateRevision"=>"{\"expectedRevision\":1,\"expectedRevision\":1,\"parentFolderId\":null}","duplicateFolder"=>"{\"expectedRevision\":1,\"parentFolderId\":null,\"parentFolderId\":null}","null"=>"null","array"=>"[]","empty"=>"",_=>body.ToJsonString()};
    }

    [FunctionalTheory][InlineData("wide","between")][InlineData("Master","between")][InlineData("PerProfile","between")][InlineData("wide","toRoot")][InlineData("Master","toRoot")][InlineData("PerProfile","toRoot")][InlineData("wide","fromRoot")][InlineData("wide","same")][InlineData("Master","same")][InlineData("PerProfile","same")][InlineData("wide","rootNoop")]
    public async Task GivenRealCreatedMixedSubtreeAndNativeCurrentOwnedScope_WhenMoving_ThenExactFourFieldsAndOnlyChangedImmediateParentsAdvance(string mode,string route)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var from=await Create(s);var to=await Create(s);var root=await Create(s,folder:route is "fromRoot" or "rootNoop"?null:from.FolderId);var child=await Create(s,folder:root.FolderId);var record=await CreateRecord(s,child.FolderId);var p=await ProfileFolders(s,owner,key,mode=="wide"?"Master":mode,[root.FolderId,to.FolderId,from.FolderId]);var actor=mode=="wide"?s:s with{Access=await Open(s,p,key)};var original=await FolderRow(root.FolderId);var oldFrom=await FolderRow(from.FolderId);var oldTo=await FolderRow(to.FolderId);var destination=route is "toRoot" or "rootNoop"?null:route=="same"?oldFrom:oldTo;
        var stable=await Stable(s,original.Id,oldFrom.Id,oldTo.Id);using var response=await Move(actor,root.FolderId,original.Revision,destination?.PublicId);await Moved(original,destination,await Success<MoveFolderOutput>(response,200));Assert.Contains("folder_moved",await response.Content.ReadAsStringAsync());Assert.Equal(stable,await Stable(s,original.Id,oldFrom.Id,oldTo.Id));
        var nowFrom=await FolderRow(from.FolderId);var nowTo=await FolderRow(to.FolderId);Assert.Equal(oldFrom.Revision+(original.ParentFolderId==oldFrom.Id&&destination?.Id!=oldFrom.Id?1:0),nowFrom.Revision);Assert.Equal(oldTo.Revision+(destination?.Id==oldTo.Id&&original.ParentFolderId!=oldTo.Id?1:0),nowTo.Revision);Assert.Equal(oldFrom.Envelope,nowFrom.Envelope);Assert.Equal(oldTo.Envelope,nowTo.Envelope);
        using(var get=await Read(actor,"/api/folders/"+child.FolderId))Assert.Equal(child.FolderId,(await Success<FolderDetailsOutput>(get,200)).FolderId);using(var get=await Read(actor,"/api/records/"+record.RecordId))Assert.Equal(record.RecordId,(await Success<RecordDetailsOutput>(get,200)).RecordId);
    }
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenNativeSelectedOwnedCollectionCommonAncestor_WhenMoving_ThenInheritedScopeAndAllOpaqueWrappersRemain(string mode)
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var common=await Create(s);var from=await Create(s,folder:common.FolderId);var to=await Create(s,folder:common.FolderId);var root=await Create(s,folder:from.FolderId);var child=await Create(s,folder:root.FolderId);var record=await CreateRecord(s,child.FolderId);await using var db=fixture.Context();var c=new VaultCollection{AccountId=s.InternalId,PublicId=Guid.NewGuid(),Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(c);await db.SaveChangesAsync();db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,FolderId=(await FolderRow(common.FolderId)).Id});await db.SaveChangesAsync();var p=await Profile(s,owner,key,mode:mode,collections:[c.PublicId]);var actor=s with{Access=await Open(s,p,key)};var original=await FolderRow(root.FolderId);var dest=await FolderRow(to.FolderId);var stable=await Stable(s,original.Id,(await FolderRow(from.FolderId)).Id,dest.Id);using var response=await Move(actor,root.FolderId,original.Revision,to.FolderId);await Moved(original,dest,await Success<MoveFolderOutput>(response,200));Assert.Equal(stable,await Stable(s,original.Id,(await FolderRow(from.FolderId)).Id,dest.Id));using(var get=await Read(actor,"/api/folders/"+child.FolderId))Assert.Contains(c.PublicId,(await Success<FolderDetailsOutput>(get,200)).CollectionIds);using(var get=await Read(actor,"/api/records/"+record.RecordId))Assert.Contains(c.PublicId,(await Success<RecordDetailsOutput>(get,200)).CollectionIds);}
    [FunctionalTheory][InlineData("Master","profile",false)][InlineData("PerProfile","profile",false)][InlineData("Master","collection",false)][InlineData("PerProfile","collection",false)][InlineData("Master","profile",true)][InlineData("PerProfile","collection",true)]
    public async Task GivenSourceAndDestinationVisibleWithNewInheritedScope_WhenSelectedMoving_ThenRejectExpansionWithFullSnapshotOrAllowExistingOverlap(string mode,string kind,bool existing)
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();using var other=new ProtectionFixture();var s=await Setup(owner);var from=await Create(s);var to=await Create(s);var root=await Create(s,folder:from.FolderId);var child=await Create(s,folder:root.FolderId);var record=await CreateRecord(s,child.FolderId);var p=await ProfileFolders(s,owner,key,mode,[root.FolderId,to.FolderId]);if(kind=="profile")await ProfileFolders(s,owner,other,"Master",existing?[root.FolderId,to.FolderId]:[to.FolderId],[record.RecordId]);else{await using var db=fixture.Context();var c=new VaultCollection{AccountId=s.InternalId,PublicId=Guid.NewGuid(),Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(c);await db.SaveChangesAsync();db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,FolderId=(await FolderRow(to.FolderId)).Id});if(existing)db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,FolderId=(await FolderRow(root.FolderId)).Id});db.CollectionRecords.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,RecordId=(await RecordRow(record.RecordId)).Id});await db.SaveChangesAsync();}var actor=s with{Access=await Open(s,p,key)};using(var get=await Read(actor,"/api/folders/"+root.FolderId))await Success<FolderDetailsOutput>(get,200);using(var get=await Read(actor,"/api/folders/"+to.FolderId))await Success<FolderDetailsOutput>(get,200);var original=await FolderRow(root.FolderId);var before=await Snapshot(s);using var response=await Move(actor,root.FolderId,original.Revision,to.FolderId);if(existing)await Moved(original,await FolderRow(to.FolderId),await Success<MoveFolderOutput>(response,200));else{await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(s));}}
    [FunctionalTheory][InlineData("self",400)][InlineData("child",400)][InlineData("deep",400)][InlineData("missing",404)][InlineData("foreign",404)][InlineData("trash",404)][InlineData("cycle",503)]
    public async Task GivenInvalidCurrentDestination_WhenMovingStaleRevision_ThenCurrentTopologyWinsWithoutMutation(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);var child=await Create(s,folder:root.FolderId);var leaf=await Create(s,folder:child.FolderId);var outside=await Create(s);Guid destination=kind=="self"?root.FolderId:kind=="child"?child.FolderId:kind=="deep"?leaf.FolderId:outside.FolderId;if(kind=="missing")destination=Guid.NewGuid();if(kind=="foreign")destination=(await Create(await Setup(owner))).FolderId;if(kind=="trash")await using(var db=fixture.Context())await db.Folders.Where(x=>x.PublicId==outside.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="cycle"){var other=await Create(s,folder:outside.FolderId);var otherId=(await FolderRow(other.FolderId)).Id;await using var db=fixture.Context();await db.Folders.Where(x=>x.PublicId==outside.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,otherId));}var before=await Snapshot(s);using var response=await Move(s,root.FolderId,99,destination);await Failure(response,status,status==400?"validation_failed":status==404?"not_found":"persistence_unavailable");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,"wide")][InlineData(CollectionGrantAccess.ReadWrite,"wide")][InlineData(CollectionGrantAccess.ReadOnly,"Master")][InlineData(CollectionGrantAccess.ReadWrite,"Master")][InlineData(CollectionGrantAccess.ReadOnly,"PerProfile")][InlineData(CollectionGrantAccess.ReadWrite,"PerProfile")]
    public async Task GivenNativeRecipientsWithOldNewAndDirectSubtreeRoutes_WhenOwnerMoves_ThenCurrentGetAndListChangeWhileKeysAndDirectLinksRemain(CollectionGrantAccess access,string mode)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();using var oldKey=new ProtectionFixture();var s=await Setup(owner);var recipient=await Setup(client);var from=await Create(s);var to=await Create(s);var root=await Create(s,folder:from.FolderId);var child=await Create(s,folder:root.FolderId);var record=await CreateRecord(s,child.FolderId);var (old,_)=await Share(s,owner,recipient,client,access,[from.FolderId],[]);var (next,_)=await Share(s,owner,recipient,client,access,[to.FolderId],[]);var (direct,_)=await Share(s,owner,recipient,client,access,[child.FolderId],[]);
        await using(var db=fixture.Context()){db.CollectionRecords.Add(new(){AccountId=s.InternalId,CollectionId=direct.Id,RecordId=(await RecordRow(record.RecordId)).Id});await db.SaveChangesAsync();}
        var p=await Profile(recipient,client,key,mode:mode=="wide"?"Master":mode,collections:[old.PublicId,next.PublicId,direct.PublicId]);var oldProfile=await Profile(recipient,client,oldKey,collections:[old.PublicId]);var oldActor=recipient with{Access=await Open(recipient,oldProfile,oldKey)};var actor=mode=="wide"?recipient:recipient with{Access=await Open(recipient,p,key)};var recipientBefore=await Snapshot(recipient);var original=await FolderRow(root.FolderId);var fromRow=await FolderRow(from.FolderId);var dest=await FolderRow(to.FolderId);var stable=await Stable(s,original.Id,fromRow.Id,dest.Id);
        using(var get=await Read(actor,"/api/folders/"+child.FolderId)){var d=await Success<FolderDetailsOutput>(get,200);Assert.Contains(old.PublicId,d.CollectionIds);Assert.DoesNotContain(next.PublicId,d.CollectionIds);}using(var get=await Read(actor,"/api/records/"+record.RecordId))await Success<RecordDetailsOutput>(get,200);
        using(var response=await Move(s,root.FolderId,original.Revision,to.FolderId))await Moved(original,dest,await Success<MoveFolderOutput>(response,200));Assert.Equal(stable,await Stable(s,original.Id,fromRow.Id,dest.Id));Assert.Equal(recipientBefore,await Snapshot(recipient));
        using(var get=await Read(actor,"/api/folders/"+child.FolderId)){var d=await Success<FolderDetailsOutput>(get,200);Assert.DoesNotContain(old.PublicId,d.CollectionIds);Assert.Contains(next.PublicId,d.CollectionIds);Assert.Contains(direct.PublicId,d.CollectionIds);}using(var get=await Read(actor,"/api/records/"+record.RecordId)){var d=await Success<RecordDetailsOutput>(get,200);Assert.DoesNotContain(old.PublicId,d.CollectionIds);Assert.Contains(next.PublicId,d.CollectionIds);Assert.Contains(direct.PublicId,d.CollectionIds);}
        using(var list=await Read(actor,"/api/folders"))Assert.Contains((await Success<FolderListOutput>(list,200)).Items,x=>x.FolderId==child.FolderId);using(var list=await Read(actor,"/api/records"))Assert.Contains((await Success<RecordListOutput>(list,200)).Items,x=>x.RecordId==record.RecordId);using(var get=await Read(oldActor,"/api/folders/"+child.FolderId))await Failure(get,404,"not_found");using(var get=await Read(oldActor,"/api/records/"+record.RecordId))await Failure(get,404,"not_found");using(var list=await Read(oldActor,"/api/folders"))Assert.DoesNotContain((await Success<FolderListOutput>(list,200)).Items,x=>x.FolderId==root.FolderId||x.FolderId==child.FolderId);using(var list=await Read(oldActor,"/api/records"))Assert.DoesNotContain((await Success<RecordListOutput>(list,200)).Items,x=>x.RecordId==record.RecordId);
    }
    [FunctionalTheory][InlineData("signature","destination")][InlineData("pins","destination")][InlineData("missing","destination")][InlineData("signature","child")][InlineData("signature","record")]
    public async Task GivenMissingOrMalformedRequiredNativeResultBinding_WhenMoving_Then503AndNoPartialGraphOrPayload(string kind,string route)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await Setup(owner);var recipient=await Setup(client);var root=await Create(s);var child=await Create(s,folder:root.FolderId);var record=await CreateRecord(s,child.FolderId);var to=await Create(s);var (c,g)=await Share(s,owner,recipient,client,CollectionGrantAccess.ReadWrite,route=="destination"?[to.FolderId]:route=="child"?[child.FolderId]:[],[]);await using(var db=fixture.Context()){if(route=="record"){db.CollectionRecords.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,RecordId=(await RecordRow(record.RecordId)).Id});await db.SaveChangesAsync();}if(kind=="pins")await db.VaultProtections.Where(x=>x.AccountId==recipient.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,"bad"u8.ToArray()));else await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,kind=="missing"?Array.Empty<byte>():"bad"u8.ToArray()));}var before=await Snapshot(s);var recipientBefore=await Snapshot(recipient);using var response=await Move(s,root.FolderId,(await FolderRow(root.FolderId)).Revision,to.FolderId);await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(s));Assert.Equal(recipientBefore,await Snapshot(recipient));}
    [FunctionalTheory][InlineData("lostSuccess")][InlineData("putWinner")][InlineData("trashWinner")]
    public async Task GivenActualCommittedWinner_WhenMovingOldRevision_ThenConflictOrCurrent404PreservesTheWinner(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);var to=await Create(s);if(kind=="lostSuccess"){using var win=await Move(s,root.FolderId,1,to.FolderId);await Success<MoveFolderOutput>(win,200);}else{using var req=Request(s,kind=="putWinner"?Bytes(new FolderUpdateInput(1,Envelope(),DateTimeOffset.UnixEpoch)):Bytes(new{expectedRevision=1}),"/api/folders/"+root.FolderId);req.Method=kind=="putWinner"?HttpMethod.Put:HttpMethod.Delete;using var win=await Gateway.Client.SendAsync(req);Assert.Equal(HttpStatusCode.OK,win.StatusCode);}var before=await Snapshot(s);using var retry=await Move(s,root.FolderId,1,to.FolderId);await Failure(retry,kind=="trashWinner"?404:409,kind=="trashWinner"?"not_found":"revision_conflict");Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenDamagedOwnedRoot_WhenMoving_Then503RetainsAllOpaqueBytes()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);await using(var db=fixture.Context())await db.Folders.Where(x=>x.PublicId==root.FolderId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"bad"u8.ToArray()));var before=await Snapshot(s);using var response=await Move(s,root.FolderId);await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenActualIndependentRecordAndChildTrash_WhenMovingActiveAncestor_ThenOriginalDeadlinesAndSnapshotsRemain()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Create(s);var oldChild=await Create(s,folder:root.FolderId);var oldRecord=await CreateRecord(s,root.FolderId);var nested=await CreateRecord(s,oldChild.FolderId);var active=await Create(s,folder:root.FolderId);var to=await Create(s);using(var req=Request(s,Bytes(new{expectedRevision=1}),"/api/records/"+oldRecord.RecordId)){req.Method=HttpMethod.Delete;using var response=await Gateway.Client.SendAsync(req);Assert.Equal(HttpStatusCode.OK,response.StatusCode);}using(var req=Request(s,Bytes(new{expectedRevision=(await FolderRow(oldChild.FolderId)).Revision}),"/api/folders/"+oldChild.FolderId)){req.Method=HttpMethod.Delete;using var response=await Gateway.Client.SendAsync(req);Assert.Equal(HttpStatusCode.OK,response.StatusCode);}var original=await FolderRow(root.FolderId);var dest=await FolderRow(to.FolderId);var stable=await Stable(s,original.Id,dest.Id);using var moved=await Move(s,root.FolderId,original.Revision,to.FolderId);await Moved(original,dest,await Success<MoveFolderOutput>(moved,200));Assert.Equal(stable,await Stable(s,original.Id,dest.Id));Assert.NotNull((await RecordRow(nested.RecordId)).PurgeAt);Assert.Null((await FolderRow(active.FolderId)).DeletedAt);}

    private static HttpRequestMessage PutParent(State s,string path,byte[] body){var split=path.IndexOf('?');var uri=split<0?path+"/parent":path[..split]+"/parent"+path[split..];var r=Request(s,body,uri);r.Method=HttpMethod.Put;return r;}
    private async Task<HttpResponseMessage> Move(State s,Guid id,long revision=1,Guid? destination=null){using var req=PutParent(s,"/api/folders/"+id,Bytes(new{expectedRevision=revision,parentFolderId=destination}));return await Gateway.Client.SendAsync(req);}
    private async Task<VaultFolder> FolderRow(Guid id){await using var db=fixture.Context();return await db.Folders.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<VaultRecord> RecordRow(Guid id){await using var db=fixture.Context();return await db.Records.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task Moved(VaultFolder original,VaultFolder? destination,MoveFolderOutput output)
    {Fields(output,"folderId","parentFolderId","revision","serverSequence");Assert.Equal(original.PublicId,output.FolderId);Assert.Equal(destination?.PublicId,output.ParentFolderId);Assert.Equal(original.Revision+1,output.Revision);Assert.True(output.ServerSequence>original.ServerSequence);Assert.InRange(output.ServerSequence,1,ProtocolBinary.MaxInteger);var row=await FolderRow(original.PublicId);Assert.Equal(original.AccountId,row.AccountId);Assert.Equal(original.Envelope,row.Envelope);Assert.Equal(original.EditedAt,row.EditedAt);Assert.Equal(destination?.Id,row.ParentFolderId);Assert.Equal(output.Revision,row.Revision);Assert.Equal(output.ServerSequence,row.ServerSequence);Assert.Null(row.DeletedAt);Assert.Null(row.PurgeAt);Assert.NotEqual(original.ConcurrencyStamp,row.ConcurrencyStamp);}
    private async Task<string> Stable(State s,params long[] ignored){var node=JsonNode.Parse(await Snapshot(s))!.AsObject();var rows=node["Folders"]!.AsArray();foreach(var row in rows.ToArray())if(ignored.Contains(row!["Id"]!.GetValue<long>()))rows.Remove(row);return node.ToJsonString();}
    private async Task<Profile> ProfileFolders(State s,ProtectionFixture owner,ProtectionFixture key,string mode,Guid[] folders,Guid[]? records=null,Guid[]? collections=null)
    {var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,key.Material.UnlockVerifier,owner.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?key.Material.PasswordWrapper:null),DateTimeOffset.UnixEpoch,records??[],folders,collections??[]);using var req=Request(s,Bytes(input),"/api/profiles");using var response=await Gateway.Client.SendAsync(req);await Success<CreateProfileOutput>(response,201);await using var db=fixture.Context();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);}

    private async Task<ArturRios.Cerberus.Domain.Records.RecordCreateInput> CreateRecord(State s,Guid folder)
    {
        var input=new ArturRios.Cerberus.Domain.Records.RecordCreateInput(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch,[],folder);using var req=Request(s,Bytes(input),"/api/records");using var response=await Gateway.Client.SendAsync(req);await Success<ArturRios.Cerberus.Command.Records.CreateRecordOutput>(response,201);return input;
    }
    private async Task<FolderCreateInput> Create(State s,Guid[]? profiles=null,Guid? folder=null){var input=Input(profiles,folder);using var response=await Send(s,input);await Success<CreateFolderOutput>(response,201);return input;}
    private async Task<(VaultCollection,CollectionGrant)> Share(State owner,ProtectionFixture author,State recipient,ProtectionFixture recipientKeys,CollectionGrantAccess access,Guid[] folderIds,long[] folders){await using var db=fixture.Context();var collection=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=owner.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(collection);await db.SaveChangesAsync();var grant=new CollectionGrant{PublicId=Guid.NewGuid(),CollectionId=collection.Id,RecipientAccountId=recipient.InternalId,Access=access};grant.RecipientKeyEnvelope=Bytes(author.WrapGrant(owner.AccountId,collection.PublicId,grant.PublicId,recipient.Actor,recipientKeys.Material.RecipientKey));db.CollectionGrants.Add(grant);foreach(var id in folderIds){var folder=await db.Folders.SingleAsync(x=>x.PublicId==id);db.CollectionFolders.Add(new(){AccountId=owner.InternalId,CollectionId=collection.Id,FolderId=folder.Id});}db.CollectionFolders.AddRange(folders.Select(id=>new CollectionFolder{AccountId=owner.InternalId,CollectionId=collection.Id,FolderId=id}));await db.SaveChangesAsync();return(collection,grant);}
    private sealed class BodyFeature:IHttpRequestBodyDetectionFeature{public bool CanHaveBody=>true;}
    private sealed record State(Guid Actor,Guid AccountId,long InternalId,string Access);
    private async Task<State> Setup(ProtectionFixture client)
    {var actor=Guid.NewGuid();fixture.Users[actor+"@example.test"]=new(actor,"fixture-password");await using var db=fixture.Context();var account=new Account{PublicId=Guid.NewGuid(),HeimdallPublicId=actor,DetailsEnvelope=Bytes(Envelope())};db.Accounts.Add(account);await db.SaveChangesAsync();var access=ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32));OpaqueAccessHandle.TryHash(access,out var verifier);db.VaultProtections.Add(new(){AccountId=account.Id,Material=Bytes(client.Material)});db.VaultAccessSessions.Add(new(){AccountId=account.Id,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return new(actor,account.PublicId,account.Id,access);}
    private async Task<VaultFolder> Folder(State s,long? parent=null){var f=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.Context();db.Folders.Add(f);await db.SaveChangesAsync();return f;}
    private async Task<Profile> Profile(State s,ProtectionFixture owner,ProtectionFixture scoped,VaultFolder? folder=null,string mode="Master",Guid[]? collections=null)
    {var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,scoped.Material.UnlockVerifier,owner.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?scoped.Material.PasswordWrapper:null),DateTimeOffset.UnixEpoch,[],folder is null?[]:[folder.PublicId],collections??[]);using var request=Request(s,Bytes(input),"/api/profiles");using var r=await Gateway.Client.SendAsync(request);Assert.Equal(HttpStatusCode.Created,r.StatusCode);await using var db=fixture.Context();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<string> Open(State s,Profile p,ProtectionFixture scoped)
    {await using var db=fixture.Context();var revision=(await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id)).Revision;var raw=Bytes(new{expectedRevision=revision});using var challengeRequest=Request(s,Bytes(new{expectedRevision=revision,requestHash=ProtocolBinary.Encode(SHA256.HashData(raw))}),"/api/profiles/"+p.PublicId+"/access/challenges");challengeRequest.Headers.Remove("X-Cerberus-Vault-Access");using var issued=await Gateway.Client.SendAsync(challengeRequest);var challenge=(await Success<IssueProfileAccessChallengeOutput>(issued,201)).Challenge;using var open=Request(s,raw,"/api/profiles/"+p.PublicId+"/access");open.Headers.Remove("X-Cerberus-Vault-Access");open.Headers.Add("X-Cerberus-Challenge-Id",challenge.ChallengeId.ToString());open.Headers.Add("X-Cerberus-Proof",scoped.Sign(challenge));using var response=await Gateway.Client.SendAsync(open);return (await Success<OpenProfileAccessOutput>(response,200)).VaultAccess;}
    private static FolderCreateInput Input(Guid[]? profiles=null,Guid? folder=null)=>new(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch.AddTicks(19),profiles??[],folder);
    private static EncryptedEnvelope Envelope(long epoch=1)=>new("cerberus-content-v1",epoch,ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(12)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(73)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(16)));
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
    private static DateTimeOffset Normalize(DateTimeOffset value)=>value.AddTicks(-(value.Ticks%10));
    private static HttpRequestMessage Request(State s,byte[] body,string path="/api/folders"){var r=new HttpRequestMessage(HttpMethod.Post,path){Content=new ByteArrayContent(body)};r.Content.Headers.ContentType=new("application/json");r.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));r.Headers.Add("X-Cerberus-Vault-Access",s.Access);return r;}
    private async Task<HttpResponseMessage> Send(State s,FolderCreateInput input){using var request=Request(s,Bytes(input));return await Gateway.Client.SendAsync(request);}
    private async Task<HttpResponseMessage> Read(State s,string path){using var request=new HttpRequestMessage(HttpMethod.Get,path);request.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));request.Headers.Add("X-Cerberus-Vault-Access",s.Access);return await Gateway.Client.SendAsync(request);}
    private async Task<string> Protected(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Protection=await db.VaultProtections.AsNoTracking().SingleAsync(x=>x.AccountId==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<string> Snapshot(State s,bool skipMembers=false){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Protected=await Protected(s),Operations=await db.TrashOperations.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Entries=await db.TrashEntries.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.Id==x.OperationId&&o.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Queue=await db.RetentionWorkItems.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.AccountId==s.InternalId&&x.OperationKey=="trash/"+o.PublicId)).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>x.RecipientAccountId==s.InternalId || db.Collections.Any(c=>c.Id==x.CollectionId && c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Members=await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),CollectionFolders=skipMembers?[]:await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId && p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync()});}
    private static async Task<T> Success<T>(HttpResponseMessage r,int status) where T:class{Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);if(typeof(T)==typeof(MoveFolderOutput)){using var raw=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.Equal(new[]{"folderId","parentFolderId","revision","serverSequence"},raw.RootElement.GetProperty("data").EnumerateObject().Select(x=>x.Name).Order());}var result=await r.Content.ReadFromJsonAsync<DataOutput<T>>();Assert.True(result!.Success);return Assert.IsType<T>(result.Data);}
    private static void Fields(object value,params string[] names){using var d=JsonDocument.Parse(JsonSerializer.Serialize(value,ProtectionFixture.Json));Assert.Equal(names.Order(),d.RootElement.EnumerateObject().Select(x=>x.Name).Order());}
    private static async Task Failure(HttpResponseMessage r,int status,string? error=null){Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);if(status==413){Assert.Equal("",await r.Content.ReadAsStringAsync());return;}using var d=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.False(d.RootElement.GetProperty("success").GetBoolean());if(d.RootElement.TryGetProperty("data",out var data))Assert.Equal(JsonValueKind.Null,data.ValueKind);if(error is not null)Assert.Contains(error,d.RootElement.GetProperty("errors").EnumerateArray().Select(x=>x.GetString()));}
}
