using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Net.Http.Json;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using ArturRios.Cerberus.Command.Profiles;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Query.Profiles;
using ArturRios.Cerberus.TestSupport;
using ArturRios.Configuration.Enums;
using ArturRios.Output;
using ArturRios.Util.Test.Functional;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
namespace ArturRios.Cerberus.WebApi.Tests;

[Collection("Registration host")]
public class ProfileAccessHttpTests(RegistrationApiFixture fixture):WebApiTest<Program>(EnvironmentType.Local)
{
    private static readonly byte[] Raw="{\"expectedRevision\":1}"u8.ToArray();
    [FunctionalTheory][InlineData("Master",true)][InlineData("Master",false)][InlineData("PerProfile",true)][InlineData("PerProfile",false)]
    public async Task GivenNativeProfileAndCurrentIdentity_WhenOpeningWithoutPriorHandle_ThenIssueOnlySelectedHashedAccess(string mode,bool renewal)
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherScoped=new ProtectionFixture();using var author=new ProtectionFixture();var s=await Setup(client);var foreign=await Setup(author);var own=await Items(s);var shared=await Items(foreign);await Grant(foreign,author,s,client,shared.Collection);var ids=new ProfileAssociationInput(1,[own.Record.PublicId],[own.Folder.PublicId],[own.Collection.PublicId,shared.Collection.PublicId]);var p=await Add(s,client,scoped,ids,mode);var other=await Add(s,client,otherScoped);
        await using(var db=fixture.Context()){await db.VaultAccessSessions.Where(x=>x.AccountId==s.InternalId).ExecuteDeleteAsync();if(!renewal)await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.RenewalEnabled,false));}
        var before=await Snapshot(s);var resources=await Content(s,foreign);var challenge=await Challenge(s,p.PublicId);Assert.Equal(mode,challenge.Profile.KeyWrappers.UnlockMode);Assert.Equal(p.PublicId,challenge.Challenge.ScopeId);Assert.Equal(s.Actor,challenge.Challenge.IdentityId);Assert.Equal(s.AccountId,challenge.Profile.AccountId);Assert.Equal("unlock-profile",challenge.Challenge.Operation);Assert.Equal("profile",challenge.Challenge.ScopeKind);Assert.Equal(60,challenge.Challenge.ExpiresAt-challenge.Challenge.IssuedAt);
        using var response=await Open(s,p.PublicId,challenge.Challenge,scoped.Sign(challenge.Challenge));var output=await Success<OpenProfileAccessOutput>(response,200);Assert.Equal(s.AccountId,output.AccountId);Assert.Equal(p.PublicId,output.Profile.ProfileId);Assert.Equal(1,output.Profile.Revision);Assert.Equal(p.ServerSequence,output.Profile.ServerSequence);Assert.Equal(p.EditedAt,output.Profile.EditedAt);Assert.Equal(ids.RecordIds,output.Profile.RecordIds);Assert.Equal(ids.FolderIds,output.Profile.FolderIds);Assert.Equal(ids.CollectionIds.Order(),output.Profile.CollectionIds);Assert.Equal(renewal,output.ExpiresAt is not null);Assert.Equal(before,await Snapshot(s));Assert.Equal(resources,await Content(s,foreign));
        AssertFields(output,"accountId","expiresAt","issuedAt","profile","vaultAccess");AssertFields(output.Profile,"collectionIds","editedAt","envelope","folderIds","keyWrappers","profileId","recordIds","revision","serverSequence");
        await using(var db=fixture.Context()){var session=await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId);Assert.Equal(p.Id,session.ProfileId);OpaqueAccessHandle.TryHash(output.VaultAccess,out var verifier);Assert.Equal(verifier,session.HandleVerifier);Assert.NotEqual(output.VaultAccess,session.HandleVerifier);Assert.True((await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==challenge.Challenge.ChallengeId)).Consumed);}
        using var get=await WithAccess(s,HttpMethod.Get,"/api/profiles/"+p.PublicId,output.VaultAccess);Assert.Equal(p.PublicId,(await Success<ProfileDetailsOutput>(get,200)).ProfileId);using var list=await WithAccess(s,HttpMethod.Get,"/api/profiles",output.VaultAccess);Assert.Equal(p.PublicId,Assert.Single((await Success<ProfileListOutput>(list,200)).Items).ProfileId);using var outside=await WithAccess(s,HttpMethod.Get,"/api/profiles/"+other.PublicId,output.VaultAccess);await Failure(outside,404);var newProfile=Guid.NewGuid();using var create=await WithAccess(s,HttpMethod.Post,"/api/profiles",output.VaultAccess,new ProfileCreateInput(newProfile,Envelope(),new("Master",otherScoped.Material.UnlockVerifier,client.Wrap(s.AccountId,"profile",newProfile,s.Actor),null),DateTimeOffset.UtcNow,[],[],[]));await Failure(create,403);using var replay=await Open(s,p.PublicId,challenge.Challenge,scoped.Sign(challenge.Challenge));await Failure(replay,401,"vault_proof_rejected");
    }
    [FunctionalFact]
    public async Task GivenNewSelectedHandle_WhenUpdatingAssociationsAndTrashing_ThenRestrictSelectionAndRevokeWithoutReviving()
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherScoped=new ProtectionFixture();var s=await Setup(client);var own=await Items(s);var extra=await Items(s);var ids=new ProfileAssociationInput(1,[own.Record.PublicId],[own.Folder.PublicId],[own.Collection.PublicId]);var p=await Add(s,client,scoped,ids);var other=await Add(s,client,otherScoped);var c=await Challenge(s,p.PublicId);using var opened=await Open(s,p.PublicId,c.Challenge,scoped.Sign(c.Challenge));var access=(await Success<OpenProfileAccessOutput>(opened,200)).VaultAccess;
        using var outsideUpdate=await WithAccess(s,HttpMethod.Put,"/api/profiles/"+other.PublicId,access,new ProfileUpdateInput(1,Envelope(),DateTimeOffset.UtcNow));await Failure(outsideUpdate,404);using var outsideTrash=await WithAccess(s,HttpMethod.Delete,"/api/profiles/"+other.PublicId,access,new{expectedRevision=1});await Failure(outsideTrash,404);
        using var update=await WithAccess(s,HttpMethod.Put,"/api/profiles/"+p.PublicId,access,new ProfileUpdateInput(1,Envelope(),DateTimeOffset.UtcNow));Assert.Equal(2,(await Success<UpdateProfileOutput>(update,200)).Revision);
        using var retain=await WithAccess(s,HttpMethod.Put,"/api/profiles/"+p.PublicId+"/associations",access,ids with {ExpectedRevision=2});Assert.Equal(3,(await Success<SetProfileAssociationsOutput>(retain,200)).Revision);
        var before=await Snapshot(s);using var expand=await WithAccess(s,HttpMethod.Put,"/api/profiles/"+p.PublicId+"/associations",access,ids with {ExpectedRevision=3,RecordIds=[extra.Record.PublicId]});await Failure(expand,404);Assert.Equal(before,await Snapshot(s));using var clear=await WithAccess(s,HttpMethod.Put,"/api/profiles/"+p.PublicId+"/associations",access,new ProfileAssociationInput(3,[],[],[]));Assert.Equal(4,(await Success<SetProfileAssociationsOutput>(clear,200)).Revision);
        using var trash=await WithAccess(s,HttpMethod.Delete,"/api/profiles/"+p.PublicId,access,new{expectedRevision=4});await Success<DeleteProfileOutput>(trash,200);using var denied=await WithAccess(s,HttpMethod.Get,"/api/profiles/"+other.PublicId,access);await Failure(denied,403);await using var db=fixture.Context();Assert.True((await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId && x.ProfileId==p.Id)).Revoked);Assert.Null((await db.Profiles.SingleAsync(x=>x.Id==other.Id)).DeletedAt);Assert.True(await db.Records.AnyAsync(x=>x.Id==own.Record.Id));
    }
    public static TheoryData<bool,string> HiddenCases=>Pairs("foreign","missing","trash","erased","closing","accountErased","missingAccount");
    [FunctionalTheory][MemberData(nameof(HiddenCases))]
    public async Task GivenHiddenTarget_WhenChallengingOrOpening_Then404BeforeRevisionOrNativeDisclosure(bool open,string kind)
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var owner=kind=="foreign"?await Setup(client):s;var p=await Add(owner,client,scoped);var actor=s.Actor;
        await using(var db=fixture.Context()){if(kind=="trash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="closing")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,AccountState.ClosurePending));if(kind is "erased" or "accountErased")db.TerminalErasures.Add(new(){ResourceId=kind=="erased"?p.PublicId:s.AccountId,ResourceKind=kind=="erased"?"profile":"account",DeletedAt=DateTimeOffset.UtcNow});if(kind=="missingAccount"){actor=Guid.NewGuid();fixture.Users[actor+"@example.test"]=new(actor,"fixture-password");}await db.SaveChangesAsync();await db.VaultProtections.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,new byte[]{1}));}
        var before=await SecuritySnapshot(s);using var request=Request(s with {Actor=actor},kind=="missing"?Guid.NewGuid():p.PublicId,open,Encoding.UTF8.GetBytes(open?"{\"expectedRevision\":9}":"{\"expectedRevision\":9,\"requestHash\":\""+Hash(Raw)+"\"}"));using var response=await Gateway.Client.SendAsync(request);await Failure(response,404,"not_found");Assert.Equal(before,await SecuritySnapshot(s));
    }
    public static TheoryData<bool,string> CorruptCases=>Pairs("envelope","wrappers","pins","sequence","legacyDuplicate","legacyTrashDuplicate","corruptOtherKey");
    [FunctionalTheory][MemberData(nameof(CorruptCases))]
    public async Task GivenCorruptRequiredNativeState_WhenChallengingOrOpening_Then503WithoutConsumptionOrHandle(bool open,string kind)
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();using var another=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var other=await Add(s,client,another);var c=open?await Challenge(s,p.PublicId):null;
        await using(var db=fixture.Context()){if(kind=="envelope")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,new byte[]{1}));if(kind=="wrappers")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.KeyWrappers,new byte[]{1}));if(kind=="pins")await db.VaultProtections.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,new byte[]{1}));if(kind=="sequence")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ServerSequence,0));if(kind is "legacyDuplicate" or "legacyTrashDuplicate"){var w=JsonSerializer.Deserialize<ProfileKeyWrappers>(other.KeyWrappers,ProtectionFixture.Json)!;await db.Profiles.Where(x=>x.Id==other.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.KeyWrappers,JsonSerializer.SerializeToUtf8Bytes(w with {UnlockVerifier=scoped.Material.UnlockVerifier},ProtectionFixture.Json)));if(kind=="legacyTrashDuplicate")await db.Profiles.Where(x=>x.Id==other.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}if(kind=="corruptOtherKey")await db.Profiles.Where(x=>x.Id==other.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.KeyWrappers,new byte[]{1}));}
        var before=await SecuritySnapshot(s);using var response=open?await Open(s,p.PublicId,c!.Challenge,scoped.Sign(c.Challenge)):await Gateway.Client.SendAsync(Request(s,p.PublicId,false,ChallengeBody()));await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await SecuritySnapshot(s));
    }
    [FunctionalTheory][InlineData("expected")][InlineData("revision")][InlineData("policy")][InlineData("generation")]
    public async Task GivenStaleProfileOrChallengePolicy_WhenOpening_Then409WithoutConsuming(string kind)
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var c=await Challenge(s,p.PublicId);await using(var db=fixture.Context()){if(kind=="revision")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,2));if(kind=="policy")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.PolicyRevision,2));if(kind=="generation")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RevocationGeneration,2));}var before=await SecuritySnapshot(s);using var response=await Open(s,p.PublicId,c.Challenge,scoped.Sign(c.Challenge),kind=="expected"?"{\"expectedRevision\":2}"u8.ToArray():Raw);await Failure(response,409,"revision_conflict");Assert.Equal(before,await SecuritySnapshot(s));
    }
    [FunctionalTheory][InlineData("accountKey")][InlineData("otherProfileKey")][InlineData("otherProfileChallenge")][InlineData("body")][InlineData("nonce")][InlineData("expired")][InlineData("future")]
    public async Task GivenWrongNativeProofOrExpiredChallenge_WhenOpening_Then401AndNoSelectedSession(string kind)
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherScoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var other=await Add(s,client,otherScoped);var c=await Challenge(s,kind=="otherProfileChallenge"?other.PublicId:p.PublicId);var signed=c.Challenge;if(kind=="nonce")signed=signed with {Nonce=Hash("different"u8.ToArray())};if(kind is "expired" or "future"){signed=signed with {IssuedAt=DateTimeOffset.UtcNow.ToUnixTimeSeconds()+(kind=="expired"?-120:120),ExpiresAt=0};signed=signed with {ExpiresAt=signed.IssuedAt+60};await using var db=fixture.Context();var row=await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==signed.ChallengeId);row.Challenge=JsonSerializer.SerializeToUtf8Bytes(signed,ProtectionFixture.Json);row.ExpiresAt=DateTimeOffset.FromUnixTimeSeconds(signed.ExpiresAt);await db.SaveChangesAsync();}var before=await SecuritySnapshot(s);var proof=(kind=="accountKey"?client:kind is "otherProfileKey" or "otherProfileChallenge"?otherScoped:scoped).Sign(signed);using var response=await Open(s,p.PublicId,c.Challenge,proof,kind=="body"?"{ \"expectedRevision\":1}"u8.ToArray():Raw);await Failure(response,401,"vault_proof_rejected");Assert.Equal(before,await SecuritySnapshot(s));
    }
    public static TheoryData<bool,string> MalformedCases=>Pairs("actor","profileId","vaultAccess","password","unknown","missingRevision","numeric","unsafe","zero","fraction","duplicate","case","null","array","bom","invalidUtf8","gzip","charset","oversized");
    [FunctionalTheory][MemberData(nameof(MalformedCases))]
    public async Task GivenMalformedBody_WhenChallengingOrOpening_ThenRejectWithoutStateChanges(bool open,string kind)
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var raw=open?Encoding.UTF8.GetString(Raw):Encoding.UTF8.GetString(ChallengeBody());if(kind is "actor" or "profileId" or "vaultAccess" or "password" or "unknown")raw=raw.Insert(1,"\""+kind+"\":null,");if(kind=="missingRevision")raw=open?"{}":raw.Replace("\"expectedRevision\":1,","");if(kind=="numeric")raw=raw.Replace(":1",":\"1\"");if(kind=="unsafe")raw=raw.Replace(":1",":9007199254740992");if(kind=="zero")raw=raw.Replace(":1",":0");if(kind=="fraction")raw=raw.Replace(":1",":1.5");if(kind=="duplicate")raw=raw.Insert(1,"\"expectedRevision\":1,");if(kind=="case")raw=raw.Replace("expectedRevision","ExpectedRevision");if(kind=="null")raw="null";if(kind=="array")raw="[]";if(kind=="oversized")raw=new string(' ',65537)+raw;var bytes=kind=="invalidUtf8"?new byte[]{255}:kind=="bom"?new byte[]{239,187,191}.Concat(Encoding.UTF8.GetBytes(raw)).ToArray():Encoding.UTF8.GetBytes(raw);var before=await SecuritySnapshot(s);using var request=Request(s,p.PublicId,open,bytes);if(kind=="gzip")request.Content!.Headers.ContentEncoding.Add("gzip");if(kind=="charset")request.Content!.Headers.ContentType!.CharSet="iso-8859-1";using var response=await Gateway.Client.SendAsync(request);await Failure(response,kind=="oversized"?413:400,kind=="oversized"?null:"validation_failed");Assert.Equal(before,await SecuritySnapshot(s));
    }
    [FunctionalTheory][InlineData("missing")][InlineData("null")][InlineData("bad")][InlineData("padded")]
    public async Task GivenMalformedChallengeDigest_WhenChallenging_Then400(string kind)
    {using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var body=kind=="missing"?"{\"expectedRevision\":1}":"{\"expectedRevision\":1,\"requestHash\":"+(kind=="null"?"null":JsonSerializer.Serialize(kind=="bad"?"bad":Hash(Raw)+"="))+"}";var before=await SecuritySnapshot(s);using var response=await Gateway.Client.SendAsync(Request(s,p.PublicId,false,Encoding.UTF8.GetBytes(body)));await Failure(response,400);Assert.Equal(before,await SecuritySnapshot(s));}
    public static TheoryData<bool,string> RouteCases=>Pairs("bad","uppercase","zero","compact","query");
    [FunctionalTheory][MemberData(nameof(RouteCases))]
    public async Task GivenInvalidRouteOrQuery_WhenChallengingOrOpening_Then400(bool open,string kind)
    {using var client=new ProtectionFixture();var s=await Setup(client);var id=kind=="bad"?"invalid":kind=="uppercase"?"ABCDEFAB-1234-1234-1234-ABCDEFABCDEF":kind=="zero"?Guid.Empty.ToString():kind=="compact"?Guid.NewGuid().ToString("N"):Guid.NewGuid().ToString();using var request=Request(s,Guid.NewGuid(),open,open?Raw:ChallengeBody());request.RequestUri=new("/api/profiles/"+id+"/access"+(open?"":"/challenges")+(kind=="query"?"?unexpected=1":""),UriKind.Relative);using var response=await Gateway.Client.SendAsync(request);await Failure(response,400);}
    [FunctionalTheory][InlineData("missingId",401)][InlineData("missingProof",401)][InlineData("duplicateId",400)][InlineData("duplicateProof",400)][InlineData("emptyId",400)][InlineData("emptyProof",400)][InlineData("uppercaseId",400)][InlineData("badId",400)][InlineData("badProof",400)]
    public async Task GivenInvalidProofHeaders_WhenOpening_ThenRejectWithoutStateChanges(string kind,int status)
    {using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var before=await SecuritySnapshot(s);using var request=Request(s,p.PublicId,true,Raw);if(kind is "missingId" or "emptyId" or "badId" or "uppercaseId")request.Headers.Remove("X-Cerberus-Challenge-Id");if(kind is "missingProof" or "emptyProof" or "badProof")request.Headers.Remove("X-Cerberus-Proof");if(kind=="badId")request.Headers.TryAddWithoutValidation("X-Cerberus-Challenge-Id","bad");if(kind=="uppercaseId")request.Headers.TryAddWithoutValidation("X-Cerberus-Challenge-Id","ABCDEFAB-1234-1234-1234-ABCDEFABCDEF");if(kind=="badProof")request.Headers.TryAddWithoutValidation("X-Cerberus-Proof","bad");if(kind=="duplicateId")request.Headers.TryAddWithoutValidation("X-Cerberus-Challenge-Id",Guid.NewGuid().ToString());if(kind=="duplicateProof")request.Headers.TryAddWithoutValidation("X-Cerberus-Proof",ProtocolBinary.Encode(new byte[64]));if(kind is "emptyId" or "emptyProof"){
        using var host=new WebApplicationFactory<Program>();var context=await host.Server.SendAsync(c=>{c.Request.Method="POST";c.Request.Path="/api/profiles/"+p.PublicId+"/access";c.Request.Headers.Authorization="Bearer "+RegistrationApiFixture.Token(s.Actor);c.Request.Headers["X-Cerberus-Challenge-Id"]=kind=="emptyId"?"":Guid.NewGuid().ToString();c.Request.Headers["X-Cerberus-Proof"]=kind=="emptyProof"?"":ProtocolBinary.Encode(new byte[64]);c.Request.ContentType="application/json";c.Request.Body=new MemoryStream(Raw);c.Request.ContentLength=Raw.Length;});Assert.Equal(status,context.Response.StatusCode);Assert.Contains("no-store",context.Response.Headers.CacheControl.ToString());
    }else{using var response=await Gateway.Client.SendAsync(request);await Failure(response,status);}Assert.Equal(before,await SecuritySnapshot(s));}
    public static TheoryData<bool,string> IdentityCases=>Pairs("missing","wrongScope","deleted","unavailable");
    [FunctionalTheory][MemberData(nameof(IdentityCases))]
    public async Task GivenInvalidCurrentIdentity_WhenChallengingOrOpening_ThenFailClosed(bool open,string kind)
    {using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);if(kind is "deleted" or "unavailable"){var pair=fixture.Users.Single(x=>x.Value.Id==s.Actor);fixture.Users[pair.Key]=pair.Value with {Deleted=kind=="deleted",IdentityUnavailable=kind=="unavailable"};}var before=await SecuritySnapshot(s);using var request=Request(s,p.PublicId,open,open?Raw:ChallengeBody());request.Headers.Authorization=kind=="missing"?null:new("Bearer",RegistrationApiFixture.Token(s.Actor,kind=="wrongScope"?Guid.NewGuid():null));using var response=await Gateway.Client.SendAsync(request);await Failure(response,kind=="unavailable"?503:401);Assert.Equal(before,await SecuritySnapshot(s));}
    [FunctionalTheory][InlineData("old")][InlineData("future")][InlineData("missing")]
    public async Task GivenUnfreshSignedIdentity_WhenChallenging_Then401WithoutIssuingChallenge(string kind)
    {using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var before=await SecuritySnapshot(s);using var request=Request(s,p.PublicId,false,ChallengeBody());request.Headers.Authorization=new("Bearer",TokenWithIssuedAt(s.Actor,kind));using var response=await Gateway.Client.SendAsync(request);await Failure(response,401,"fresh_authentication_required");Assert.Equal(before,await SecuritySnapshot(s));}
    [FunctionalFact]
    public async Task GivenConcurrentNativeProofs_WhenOpening_ThenOneWinnerAndLostResponseRequiresFreshChallenge()
    {using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var c=await Challenge(s,p.PublicId);var proof=scoped.Sign(c.Challenge);var results=await Task.WhenAll(Open(s,p.PublicId,c.Challenge,proof),Open(s,p.PublicId,c.Challenge,proof));try{Assert.Single(results,x=>x.StatusCode==HttpStatusCode.OK);await Failure(Assert.Single(results,x=>x.StatusCode!=HttpStatusCode.OK),401);}finally{foreach(var r in results)r.Dispose();}var next=await Challenge(s,p.PublicId);using var retry=await Open(s,p.PublicId,next.Challenge,scoped.Sign(next.Challenge));await Success<OpenProfileAccessOutput>(retry,200);await using var db=fixture.Context();Assert.Equal(2,await db.VaultAccessSessions.CountAsync(x=>x.AccountId==s.InternalId && x.ProfileId==p.Id));}
    [FunctionalFact]
    public async Task GivenPostConsumptionSessionFailure_WhenOpening_Then503RollsBackAndSameProofRetries()
    {using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var c=await Challenge(s,p.PublicId);var proof=scoped.Sign(c.Challenge);var before=await SecuritySnapshot(s);await using var db=fixture.Context();await db.Database.ExecuteSqlRawAsync("CREATE FUNCTION cerberus.reject_profile_access_fixture() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.profile_id IS NOT NULL THEN RAISE EXCEPTION 'synthetic session outage' USING ERRCODE='08006'; END IF; RETURN NEW; END $$; CREATE TRIGGER reject_profile_access_fixture BEFORE INSERT ON cerberus.vault_access_session FOR EACH ROW EXECUTE FUNCTION cerberus.reject_profile_access_fixture();");try{using var response=await Open(s,p.PublicId,c.Challenge,proof);await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await SecuritySnapshot(s));}finally{await db.Database.ExecuteSqlRawAsync("DROP TRIGGER IF EXISTS reject_profile_access_fixture ON cerberus.vault_access_session; DROP FUNCTION IF EXISTS cerberus.reject_profile_access_fixture();");}using var retry=await Open(s,p.PublicId,c.Challenge,proof);await Success<OpenProfileAccessOutput>(retry,200);}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenUnavailableDatabaseDependency_WhenChallengingOrOpening_Then503(bool open)
    {using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(client);var p=await Add(s,client,scoped);var c=open?await Challenge(s,p.PublicId):null;var before=await SecuritySnapshot(s);await using var db=fixture.Context();await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.profile RENAME TO fixture_unavailable_profile");try{using var response=open?await Open(s,p.PublicId,c!.Challenge,scoped.Sign(c.Challenge)):await Gateway.Client.SendAsync(Request(s,p.PublicId,false,ChallengeBody()));await Failure(response,503);}finally{await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_profile RENAME TO profile");}Assert.Equal(before,await SecuritySnapshot(s));}
    private static TheoryData<bool,string> Pairs(params string[] names){var cases=new TheoryData<bool,string>();foreach(var open in new[]{false,true})foreach(var n in names)cases.Add(open,n);return cases;}
    private static string Hash(byte[] bytes)=>ProtocolBinary.Encode(SHA256.HashData(bytes));
    private static byte[] ChallengeBody()=>JsonSerializer.SerializeToUtf8Bytes(new{expectedRevision=1,requestHash=Hash(Raw)});
    private static HttpRequestMessage Request(State s,Guid id,bool open,byte[] body)
    {var r=new HttpRequestMessage(HttpMethod.Post,"/api/profiles/"+id+"/access"+(open?"":"/challenges")){Content=new ByteArrayContent(body)};r.Content.Headers.ContentType=new("application/json"){CharSet="utf-8"};r.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));if(open){r.Headers.Add("X-Cerberus-Challenge-Id",Guid.NewGuid().ToString());r.Headers.Add("X-Cerberus-Proof",ProtocolBinary.Encode(new byte[64]));}return r;}
    private async Task<IssueProfileAccessChallengeOutput> Challenge(State s,Guid id){using var request=Request(s,id,false,ChallengeBody());using var r=await Gateway.Client.SendAsync(request);var output=await Success<IssueProfileAccessChallengeOutput>(r,201);AssertFields(output,"challenge","profile");AssertFields(output.Profile,"accountId","envelope","keyWrappers","profileId","revision");return output;}
    private async Task<HttpResponseMessage> Open(State s,Guid id,VaultProofChallenge challenge,string proof,byte[]? raw=null){using var r=Request(s,id,true,raw??Raw);r.Headers.Remove("X-Cerberus-Challenge-Id");r.Headers.Remove("X-Cerberus-Proof");r.Headers.Add("X-Cerberus-Challenge-Id",challenge.ChallengeId.ToString());r.Headers.Add("X-Cerberus-Proof",proof);return await Gateway.Client.SendAsync(r);}
    private async Task<HttpResponseMessage> WithAccess(State s,HttpMethod method,string path,string access,object? body=null){using var r=new HttpRequestMessage(method,path);r.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));r.Headers.Add("X-Cerberus-Vault-Access",access);if(body is not null)r.Content=JsonContent.Create(body);return await Gateway.Client.SendAsync(r);}
    private static async Task<T> Success<T>(HttpResponseMessage r,int status) where T:class{Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);var output=await r.Content.ReadFromJsonAsync<DataOutput<T>>();Assert.True(output!.Success);return Assert.IsType<T>(output.Data);}
    private static void AssertFields(object value,params string[] names){using var d=JsonDocument.Parse(JsonSerializer.Serialize(value,ProtectionFixture.Json));Assert.Equal(names.Order(),d.RootElement.EnumerateObject().Select(x=>x.Name).Order());}
    private async Task<string> SecuritySnapshot(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Content=await Snapshot(s),Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Challenges=await db.VaultUnlockChallenges.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync()});}
    private sealed record State(Guid Actor,Guid AccountId,long InternalId,string Access);
    private sealed record ResourceSet(VaultRecord Record,VaultFolder Folder,VaultCollection Collection);
    private async Task<State> Setup(ProtectionFixture client)
    {var actor=Guid.NewGuid();fixture.Users[actor+"@example.test"]=new(actor,"fixture-password");await using var db=fixture.Context();var a=new Account{PublicId=Guid.NewGuid(),HeimdallPublicId=actor,DetailsEnvelope=JsonSerializer.SerializeToUtf8Bytes(Envelope(),ProtectionFixture.Json)};db.Accounts.Add(a);await db.SaveChangesAsync();var access=ProtectionFixture.Encode(RandomNumberGenerator.GetBytes(32));OpaqueAccessHandle.TryHash(access,out var verifier);db.VaultProtections.Add(new(){AccountId=a.Id,Material=JsonSerializer.SerializeToUtf8Bytes(client.Material,ProtectionFixture.Json)});db.VaultAccessSessions.Add(new(){AccountId=a.Id,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return new(actor,a.PublicId,a.Id,access);}
    private async Task<ResourceSet> Items(State s)
    {var bytes=JsonSerializer.SerializeToUtf8Bytes(Envelope(),ProtectionFixture.Json);var now=DateTimeOffset.FromUnixTimeMilliseconds(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());var record=new VaultRecord{PublicId=Guid.NewGuid(),AccountId=s.InternalId,Envelope=bytes,EditedAt=now};var folder=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,Envelope=bytes,EditedAt=now};var collection=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=s.InternalId,Envelope=bytes,EditedAt=now};await using var db=fixture.Context();db.Records.Add(record);db.Folders.Add(folder);db.Collections.Add(collection);await db.SaveChangesAsync();return new(record,folder,collection);}
    private async Task<CollectionGrant> Grant(State owner,ProtectionFixture author,State recipient,ProtectionFixture client,VaultCollection collection,CollectionGrantAccess access=CollectionGrantAccess.ReadOnly)
    {var id=Guid.NewGuid();var grant=new CollectionGrant{PublicId=id,CollectionId=collection.Id,RecipientAccountId=recipient.InternalId,Access=access,RecipientKeyEnvelope=JsonSerializer.SerializeToUtf8Bytes(author.WrapGrant(owner.AccountId,collection.PublicId,id,recipient.Actor,client.Material.RecipientKey),ProtectionFixture.Json)};await using var db=fixture.Context();db.CollectionGrants.Add(grant);await db.SaveChangesAsync();return grant;}
    private async Task<Profile> Add(State s,ProtectionFixture client,ProtectionFixture scoped,ProfileAssociationInput? ids=null,string mode="Master")
    {var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,scoped.Material.UnlockVerifier,client.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?scoped.Material.PasswordWrapper:null),DateTimeOffset.UtcNow,ids?.RecordIds??[],ids?.FolderIds??[],ids?.CollectionIds??[]);using var request=new HttpRequestMessage(HttpMethod.Post,"/api/profiles"){Content=JsonContent.Create(input)};request.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));request.Headers.Add("X-Cerberus-Vault-Access",s.Access);using var response=await Gateway.Client.SendAsync(request);Assert.Equal(HttpStatusCode.Created,response.StatusCode);await using var db=fixture.Context();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private static EncryptedEnvelope Envelope()=>new("cerberus-content-v1",1,ProtectionFixture.Encode(RandomNumberGenerator.GetBytes(32)),ProtectionFixture.Encode(RandomNumberGenerator.GetBytes(12)),"AQID",ProtectionFixture.Encode(new byte[16]));
    private async Task<string> Content(State s,State foreign){await using var db=fixture.Context();var owners=new[]{s.InternalId,foreign.InternalId};return JsonSerializer.Serialize(new{Records=await db.Records.AsNoTracking().Where(x=>owners.Contains(x.AccountId)).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>owners.Contains(x.AccountId)).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>owners.Contains(x.AccountId)).OrderBy(x=>x.Id).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>owners.Contains(x.RecipientAccountId)).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<string> Snapshot(State s){await using var db=fixture.Context();var profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync();var ids=profiles.Select(x=>x.Id).ToArray();return JsonSerializer.Serialize(new{Profiles=profiles,Records=await db.ProfileRecords.AsNoTracking().Where(x=>ids.Contains(x.ProfileId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),Folders=await db.ProfileFolders.AsNoTracking().Where(x=>ids.Contains(x.ProfileId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),Collections=await db.ProfileCollections.AsNoTracking().Where(x=>ids.Contains(x.ProfileId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync()});}
    private static async Task Failure(HttpResponseMessage response,int status,string? error=null){Assert.Equal((HttpStatusCode)status,response.StatusCode);Assert.True(response.Headers.CacheControl?.NoStore);if(status==413){Assert.Equal("",await response.Content.ReadAsStringAsync());return;}using var doc=JsonDocument.Parse(await response.Content.ReadAsStringAsync());Assert.False(doc.RootElement.GetProperty("success").GetBoolean());if(doc.RootElement.TryGetProperty("data",out var data))Assert.Equal(JsonValueKind.Null,data.ValueKind);if(error is not null)Assert.Contains(error,doc.RootElement.GetProperty("errors").EnumerateArray().Select(x=>x.GetString()));}
    private static string TokenWithIssuedAt(Guid actor,string freshness)
    {
        var claims = new List<Claim> { new("id",actor.ToString()),new("roleId","3"),new("scopeId",RegistrationApiFixture.Scope.ToString()) };
        if (freshness != "missing") claims.Add(new("iat",(DateTimeOffset.UtcNow.ToUnixTimeSeconds()+(freshness == "old" ? -120 : 120)).ToString(),ClaimValueTypes.Integer64));
        return new JwtSecurityTokenHandler().WriteToken(new JwtSecurityToken("fixture-issuer","fixture-audience",claims,
            DateTime.UtcNow.AddMinutes(-5),DateTime.UtcNow.AddMinutes(5),new SigningCredentials(new SymmetricSecurityKey(Encoding.ASCII.GetBytes("fixture-only-signing-key-32-characters")),SecurityAlgorithms.HmacSha256)));
    }
}
