using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using ArturRios.Cerberus.Command.Profiles;
using ArturRios.Cerberus.Command.Records;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Records;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Domain.Trash;
using ArturRios.Cerberus.Query.Records;
using ArturRios.Cerberus.TestSupport;
using ArturRios.Configuration.Enums;
using ArturRios.Output;
using ArturRios.Util.Test.Functional;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;

namespace ArturRios.Cerberus.WebApi.Tests;

[Collection("Registration host")]
public class RecordMoveHttpTests(RegistrationApiFixture fixture):WebApiTest<Program>(EnvironmentType.Local)
{

    [FunctionalTheory][InlineData("wide","between")][InlineData("Master","between")][InlineData("PerProfile","between")][InlineData("wide","toRoot")][InlineData("Master","toRoot")][InlineData("PerProfile","toRoot")][InlineData("wide","fromRoot")][InlineData("wide","same")][InlineData("Master","same")][InlineData("PerProfile","same")][InlineData("wide","rootNoop")][InlineData("MasterFolder","between")][InlineData("PerProfileFolder","between")][InlineData("MasterFolder","toRoot")][InlineData("PerProfileFolder","toRoot")]
    public async Task GivenActualNativeOwnedScope_WhenMoving_ThenRetainCipherLinksAndHandleAndReturnFourFields(string mode,string route)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var from=await Folder(s,root.Id);var to=await Folder(s,root.Id);var p=await Profile(s,owner,scoped,root,mode=="wide" || mode=="MasterFolder"?"Master":mode=="PerProfileFolder"?"PerProfile":mode);var target=await Create(s,mode.EndsWith("Folder")?[]:[p.PublicId],route is "fromRoot" or "rootNoop"?null:from.PublicId);var actor=mode=="wide"?s:s with{Access=await Open(s,p,scoped)};var original=await Row(target.RecordId);await using(var beforeDb=fixture.Context()){root=await beforeDb.Folders.AsNoTracking().SingleAsync(x=>x.Id==root.Id);from=await beforeDb.Folders.AsNoTracking().SingleAsync(x=>x.Id==from.Id);to=await beforeDb.Folders.AsNoTracking().SingleAsync(x=>x.Id==to.Id);}var links=await Links(s);var destination=route is "toRoot" or "rootNoop"?null:route=="same"?from:to;
        using var response=await Move(actor,target.RecordId,destination:destination?.PublicId);await Moved(original,destination,await Success<MoveRecordOutput>(response,200));Assert.Contains("record_moved",await response.Content.ReadAsStringAsync());Assert.Equal(links,await Links(s));
        await using var db=fixture.Context();var nowFrom=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==from.Id);var nowTo=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==to.Id);Assert.Equal(from.Revision+(original.FolderId==from.Id && destination?.Id!=from.Id?1:0),nowFrom.Revision);Assert.Equal(to.Revision+(destination?.Id==to.Id && original.FolderId!=to.Id?1:0),nowTo.Revision);Assert.Equal(from.Envelope,nowFrom.Envelope);Assert.Equal(from.EditedAt,nowFrom.EditedAt);Assert.Equal(to.Envelope,nowTo.Envelope);Assert.Equal(to.EditedAt,nowTo.EditedAt);Assert.Equal(root.Revision,(await db.Folders.SingleAsync(x=>x.Id==root.Id)).Revision);using var get=await Read(actor,"/api/records/"+target.RecordId);var losesVisibility=mode.EndsWith("Folder") && route=="toRoot";if(losesVisibility)await Failure(get,404,"not_found");else await Success<RecordDetailsOutput>(get,200);using var list=await Read(actor,"/api/records");var items=(await Success<RecordListOutput>(list,200)).Items;if(losesVisibility)Assert.DoesNotContain(items,x=>x.RecordId==target.RecordId);else Assert.Contains(items,x=>x.RecordId==target.RecordId);
    }
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenSelectedOwnedCollectionFolderRoute_WhenMovingWithinCommonAncestor_ThenDynamicVisibilityAndWrappersSurvive(string mode)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var from=await Folder(s,root.Id);var to=await Folder(s,root.Id);var target=await Create(s,folder:from.PublicId);await using var db=fixture.Context();var c=new VaultCollection{AccountId=s.InternalId,PublicId=Guid.NewGuid(),Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(c);await db.SaveChangesAsync();db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,FolderId=root.Id});await db.SaveChangesAsync();var p=await Profile(s,owner,scoped,mode:mode,collections:[c.PublicId]);var actor=s with{Access=await Open(s,p,scoped)};var original=await Row(target.RecordId);var before=await Links(s);using var response=await Move(actor,target.RecordId,destination:to.PublicId);await Moved(original,to,await Success<MoveRecordOutput>(response,200));Assert.Equal(before,await Links(s));using var get=await Read(actor,"/api/records/"+target.RecordId);Assert.Contains(c.PublicId,(await Success<RecordDetailsOutput>(get,200)).CollectionIds);
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeOldNewAndDirectRecipientRoutes_WhenOwnerMoves_ThenGetAndListRecalculateAndOldOnlySelectionLosesVisibility(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();using var oldKey=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var from=await Folder(o);var to=await Folder(o);var target=await Create(o,folder:from.PublicId);var (old,oldGrant)=await Share(o,owner,s,client,access,[],[from.Id]);var (next,nextGrant)=await Share(o,owner,s,client,access,[],[to.Id]);var (direct,directGrant)=await Share(o,owner,s,client,access,[target.RecordId],[]);var p=await Profile(s,client,scoped,collections:[old.PublicId,next.PublicId,direct.PublicId]);var oldOnly=await Profile(s,client,oldKey,collections:[old.PublicId]);var oldActor=s with{Access=await Open(s,oldOnly,oldKey)};var actor=selected?s with{Access=await Open(s,p,scoped)}:s;var recipientBefore=await Snapshot(s);var links=await Links(o);var original=await Row(target.RecordId);
        using(var before=await Read(actor,"/api/records/"+target.RecordId)){var data=await Success<RecordDetailsOutput>(before,200);Assert.Contains(old.PublicId,data.CollectionIds);Assert.DoesNotContain(next.PublicId,data.CollectionIds);}using(var response=await Move(o,target.RecordId,destination:to.PublicId))await Moved(original,to,await Success<MoveRecordOutput>(response,200));Assert.Equal(links,await Links(o));Assert.Equal(recipientBefore,await Snapshot(s));using(var after=await Read(actor,"/api/records/"+target.RecordId)){var data=await Success<RecordDetailsOutput>(after,200);Assert.DoesNotContain(old.PublicId,data.CollectionIds);Assert.Contains(next.PublicId,data.CollectionIds);Assert.Contains(direct.PublicId,data.CollectionIds);}using(var list=await Read(actor,"/api/records"))Assert.Contains((await Success<RecordListOutput>(list,200)).Items,x=>x.RecordId==target.RecordId);using(var gone=await Read(oldActor,"/api/records/"+target.RecordId))await Failure(gone,404,"not_found");using(var oldList=await Read(oldActor,"/api/records"))Assert.DoesNotContain((await Success<RecordListOutput>(oldList,200)).Items,x=>x.RecordId==target.RecordId);
    }
    [FunctionalTheory][InlineData("newProfile",false)][InlineData("newCollection",false)][InlineData("hiddenFolder",false)][InlineData("existingProfile",true)][InlineData("existingCollection",true)][InlineData("remove",true)][InlineData("wide",true)]
    public async Task GivenSelectedContentScope_WhenMovingToVisibleOrHiddenFolder_ThenNeverIntroduceNewEffectiveProfileOrCollection(string kind,bool allowed)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var from=await Folder(s,root.Id);var to=await Folder(s,kind=="hiddenFolder"?null:root.Id);var p=await Profile(s,owner,key,root);var other=kind is "newProfile" or "existingProfile" or "wide"?await Profile(s,owner,otherKey,to):null;var target=await Create(s,kind=="existingProfile"?[p.PublicId,other!.PublicId]:[p.PublicId],from.PublicId);
        await using(var db=fixture.Context()){if(kind is "newCollection" or "existingCollection"){var c=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=s.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(c);await db.SaveChangesAsync();db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,FolderId=to.Id});if(kind=="existingCollection")db.CollectionRecords.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,RecordId=(await Row(target.RecordId)).Id});await db.SaveChangesAsync();}}
        var actor=kind=="wide"?s:s with{Access=await Open(s,p,key)};var before=await Snapshot(s);var original=await Row(target.RecordId);var destination=kind=="remove"?null:to;using var response=await Move(actor,target.RecordId,destination:destination?.PublicId);if(allowed)await Moved(original,destination,await Success<MoveRecordOutput>(response,200));else{await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(s));}
    }
    [FunctionalTheory][InlineData("actor")][InlineData("vaultAccess")][InlineData("recordId")][InlineData("ownerId")][InlineData("profileIds")][InlineData("collectionIds")][InlineData("name")][InlineData("fields")][InlineData("keyWrappers")][InlineData("envelope")][InlineData("editedAt")][InlineData("trashOperationId")][InlineData("deletedAt")][InlineData("purgeAt")][InlineData("unknown")][InlineData("zero")][InlineData("negative")][InlineData("unsafe")][InlineData("missingRevision")][InlineData("missingFolder")][InlineData("duplicateRevision")][InlineData("duplicateFolder")][InlineData("caseRevision")][InlineData("caseFolder")][InlineData("numericString")][InlineData("nullRevision")][InlineData("fraction")][InlineData("overflow")][InlineData("null")][InlineData("array")][InlineData("empty")][InlineData("folderZero")][InlineData("folderBad")][InlineData("folderUppercase")][InlineData("folderCompact")][InlineData("folderNumeric")]
    public async Task GivenStrictOrForgedMoveBody_WhenMoving_Then400WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var body=JsonSerializer.SerializeToNode(new{expectedRevision=1,folderId=(Guid?)null},ProtectionFixture.Json)!.AsObject();var fields=new[]{"actor","vaultAccess","recordId","ownerId","profileIds","collectionIds","name","fields","keyWrappers","envelope","editedAt","trashOperationId","deletedAt","purgeAt"};if(fields.Contains(kind))body[kind]=null;if(kind=="unknown")body["secret"]=null;if(kind is "zero" or "negative" or "unsafe")body["expectedRevision"]=kind=="zero"?0:kind=="negative"?-1:9007199254740992;if(kind=="missingRevision")body.Remove("expectedRevision");if(kind=="missingFolder")body.Remove("folderId");if(kind=="caseRevision"){body.Remove("expectedRevision");body["ExpectedRevision"]=1;}if(kind=="caseFolder"){body.Remove("folderId");body["FolderId"]=null;}if(kind=="numericString")body["expectedRevision"]="1";if(kind=="nullRevision")body["expectedRevision"]=null;if(kind=="fraction")body["expectedRevision"]=1.5;if(kind=="overflow")body["expectedRevision"]=9223372036854775808m;if(kind.StartsWith("folder"))body["folderId"]=kind switch{"folderZero"=>Guid.Empty.ToString(),"folderBad"=>"bad","folderUppercase"=>"ABCDEFAB-1234-4321-ABCD-123456789ABC",_=>"abcdefab12344321abcd123456789abc"};if(kind=="folderNumeric")body["folderId"]=1;
        var raw=kind switch{"duplicateRevision"=>"{\"expectedRevision\":1,\"expectedRevision\":1,\"folderId\":null}","duplicateFolder"=>"{\"expectedRevision\":1,\"folderId\":null,\"folderId\":null}","null"=>"null","array"=>"[]","empty"=>"",_=>body.ToJsonString()};var before=await Snapshot(s);using var req=PutFolder(s,"/api/records/"+target.RecordId,Encoding.UTF8.GetBytes(raw));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("lostSuccess")][InlineData("putWinner")][InlineData("trashWinner")]
    public async Task GivenActualWinningMutation_WhenMovingOldRevision_ThenPreserveWinnerAndUseCurrentState(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var from=await Folder(s);var to=await Folder(s);var target=await Create(s,folder:from.PublicId);if(kind=="lostSuccess"){using var win=await Move(s,target.RecordId,destination:to.PublicId);await Success<MoveRecordOutput>(win,200);}else{using var req=Request(s,kind=="putWinner"?Bytes(new RecordUpdateInput(1,Envelope(),DateTimeOffset.UnixEpoch)):Bytes(new{expectedRevision=1}),"/api/records/"+target.RecordId);req.Method=kind=="putWinner"?HttpMethod.Put:HttpMethod.Delete;using var win=await Gateway.Client.SendAsync(req);Assert.Equal(HttpStatusCode.OK,win.StatusCode);}var before=await Snapshot(s);using(var retry=await Move(s,target.RecordId,destination:to.PublicId))await Failure(retry,kind=="trashWinner"?404:409,kind=="trashWinner"?"not_found":"revision_conflict");Assert.Equal(before,await Snapshot(s));if(kind!="trashWinner"){var original=await Row(target.RecordId);using var current=await Move(s,target.RecordId,2,to.PublicId);await Moved(original,to,await Success<MoveRecordOutput>(current,200));}
    }
    [FunctionalFact]
    public async Task GivenDamagedOwnedCipher_WhenMoving_Then503WithoutMovingOrRepairingBytes()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using(var db=fixture.Context())await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"bad"u8.ToArray()));var before=await Snapshot(s);using var response=await Move(s,target.RecordId);await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false,false)][InlineData(CollectionGrantAccess.ReadOnly,false,true)][InlineData(CollectionGrantAccess.ReadOnly,true,false)][InlineData(CollectionGrantAccess.ReadOnly,true,true)][InlineData(CollectionGrantAccess.ReadWrite,false,false)][InlineData(CollectionGrantAccess.ReadWrite,false,true)][InlineData(CollectionGrantAccess.ReadWrite,true,false)][InlineData(CollectionGrantAccess.ReadWrite,true,true)]
    public async Task GivenActualNativeVisibleForeignScope_WhenMovingStaleCorruptTarget_ThenReadOnlyAndReadWriteBoth403(CollectionGrantAccess access,bool selected,bool inherited)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (c,_)=await Share(o,owner,s,client,access,inherited?[]:[target.RecordId],inherited?[root.Id]:[]);var p=await Profile(s,client,scoped,collections:[c.PublicId]);var actor=selected?s with{Access=await Open(s,p,scoped)}:s;await using(var db=fixture.Context())await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"bad"u8.ToArray()));var before=await Snapshot(o);var recipient=await Snapshot(s);using var response=await Move(actor,target.RecordId,99);await Failure(response,403,"vault_access_denied");Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenSelectedCollectionLinkRemovedAfterUnlock_WhenMovingForeignTarget_Then404WithoutExpandingScope()
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var (c,_)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.RecordId],[]);var p=await Profile(s,client,scoped,collections:[c.PublicId]);var actor=s with{Access=await Open(s,p,scoped)};await using(var db=fixture.Context())await db.ProfileCollections.Where(x=>x.ProfileId==p.Id).ExecuteDeleteAsync();var before=await Snapshot(o);using var response=await Move(actor,target.RecordId);await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));}
    [FunctionalTheory][InlineData("sequence")][InlineData("revision")][InlineData("purgeWithoutTrash")][InlineData("outage")]
    public async Task GivenCorruptMetadataOrPersistenceOutage_WhenMoving_Then503WithoutPartialOperation(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using var db=fixture.Context();if(kind=="sequence")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ServerSequence,0));if(kind=="revision")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,0));if(kind=="purgeWithoutTrash")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.PurgeAt,DateTimeOffset.UtcNow.AddDays(30)));var before=await Snapshot(s);if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.record RENAME TO fixture_unavailable_record");try{using var response=await Move(s,target.RecordId);await Failure(response,503,"persistence_unavailable");}finally{if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_record RENAME TO record");}Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenCancelledHttpCaller_WhenMoving_ThenPropagateAndPreserveRecord()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);using var ct=new CancellationTokenSource();ct.Cancel();using var req=PutFolder(s,"/api/records/"+target.RecordId,Bytes(new{expectedRevision=1,folderId=(Guid?)null}));await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Gateway.Client.SendAsync(req,ct.Token));Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData("missing")][InlineData("foreign")][InlineData("unselected")][InlineData("recordTrash")][InlineData("ancestorTrash")][InlineData("recordTerminal")][InlineData("ownerClosing")][InlineData("revoked")][InlineData("ancestorTerminal")][InlineData("ownerTerminal")][InlineData("collectionTrash")]
    public async Task GivenHiddenTargetWithBadCipherAndStaleRevision_WhenMoving_ThenNonrevealing404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=kind=="unselected"?o:await Setup(client);var folder=await Folder(o);var target=await Create(o,folder:folder.PublicId);CollectionGrant? grant=null;if(kind!="foreign"&&s.InternalId!=o.InternalId){var share=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.RecordId],[]);grant=share.Item2;}if(kind=="unselected"){var p=await Profile(s,owner,key);s=s with{Access=await Open(s,p,key)};}
        await using(var db=fixture.Context()){await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Envelope,"bad"u8.ToArray()).SetProperty(r=>r.DeletedAt,kind=="recordTrash"?(DateTimeOffset?)DateTimeOffset.UtcNow:null));if(kind=="ancestorTrash")await db.Folders.Where(x=>x.Id==folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.DeletedAt,DateTimeOffset.UtcNow));if(kind=="recordTerminal"){db.TerminalErasures.Add(new(){ResourceId=target.RecordId,ResourceKind="record",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==o.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="revoked")await db.CollectionGrants.Where(x=>x.Id==grant!.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));}
        await using(var db=fixture.Context()){if(grant is not null)await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind is "ancestorTerminal" or "ownerTerminal"){db.TerminalErasures.Add(new(){ResourceId=kind=="ancestorTerminal"?folder.PublicId:o.AccountId,ResourceKind=kind=="ancestorTerminal"?"folder":"account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}if(kind=="collectionTrash")await db.Collections.Where(x=>db.CollectionGrants.Any(g=>g.Id==grant!.Id&&g.CollectionId==x.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}
        var before=await Snapshot(o);using var response=await Move(s,kind=="missing"?Guid.NewGuid():target.RecordId,88);await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("bad")][InlineData("zero")][InlineData("uppercase")][InlineData("compact")][InlineData("braced")][InlineData("urn")]
    public async Task GivenNoncanonicalRoute_WhenMoving_Then400WithoutMutation(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var g=Guid.Parse("abcdefab-1234-4321-abcd-123456789abc");var id=kind switch{"bad"=>"bad","zero"=>Guid.Empty.ToString(),"uppercase"=>g.ToString().ToUpperInvariant(),"compact"=>g.ToString("N"),"braced"=>g.ToString("B"),_=>"urn:uuid:"+g};var before=await Snapshot(s);using var req=PutFolder(s,"/api/records/"+id,Bytes(new{expectedRevision=1,folderId=(Guid?)null}));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400,"validation_failed");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("query",400)][InlineData("duplicate",400)][InlineData("bad",400)][InlineData("missing",401)][InlineData("utf8",400)][InlineData("bom",400)][InlineData("compression",400)][InlineData("charset",400)][InlineData("oversized",413)]
    public async Task GivenInvalidTransportOrAccess_WhenMoving_ThenRejectWithoutMutation(string kind,int status)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);var raw=kind=="oversized"?Encoding.UTF8.GetBytes(new string(' ',65537)):kind=="utf8"?new byte[]{0xc3,0x28}:Bytes(new{expectedRevision=1,folderId=(Guid?)null});if(kind=="bom")raw=new byte[]{239,187,191}.Concat(raw).ToArray();using var req=PutFolder(s,"/api/records/"+target.RecordId+(kind=="query"?"?ownerId=secret":""),raw);if(kind=="missing")req.Headers.Remove("X-Cerberus-Vault-Access");if(kind=="bad"){req.Headers.Remove("X-Cerberus-Vault-Access");req.Headers.Add("X-Cerberus-Vault-Access","bad");}if(kind=="duplicate")req.Headers.TryAddWithoutValidation("X-Cerberus-Vault-Access",s.Access);if(kind=="compression")req.Content!.Headers.ContentEncoding.Add("gzip");if(kind=="charset")req.Content!.Headers.ContentType!.CharSet="utf-16";using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenRawEmptyAccessHeader_WhenMoving_Then400()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);using var host=new WebApplicationFactory<Program>();var raw=Bytes(new{expectedRevision=1,folderId=(Guid?)null});var context=await host.Server.SendAsync(c=>{c.Request.Method="PUT";c.Request.Path="/api/records/"+Guid.NewGuid()+"/folder";c.Request.Headers.Authorization="Bearer "+RegistrationApiFixture.Token(s.Actor);c.Request.Headers["X-Cerberus-Vault-Access"]="";c.Request.ContentType="application/json";c.Request.ContentLength=raw.Length;c.Request.Body=new MemoryStream(raw);});Assert.Equal(400,context.Response.StatusCode);Assert.Contains("no-store",context.Response.Headers.CacheControl.ToString());}
    [FunctionalTheory][InlineData("missing",401)][InlineData("scope",401)][InlineData("deleted",401)][InlineData("unavailable",503)]
    public async Task GivenInvalidCurrentIdentity_WhenMoving_ThenRejectWithoutPersistence(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);if(kind is "deleted" or "unavailable")fixture.Users[s.Actor+"@example.test"]=new(s.Actor,"fixture-password",Deleted:kind=="deleted",IdentityUnavailable:kind=="unavailable");var before=await Snapshot(s);using var req=PutFolder(s,"/api/records/"+target.RecordId,Bytes(new{expectedRevision=1,folderId=(Guid?)null}));if(kind=="missing")req.Headers.Authorization=null;if(kind=="scope")req.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor,Guid.NewGuid()));using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("closing",404)][InlineData("terminal",404)][InlineData("revoked",403)][InlineData("expired",403)][InlineData("future",403)][InlineData("policy",403)][InlineData("generation",403)][InlineData("dangling",403)]
    public async Task GivenInvalidCurrentActorState_WhenMoving_ThenNoMutation(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using(var db=fixture.Context()){var v=await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId);if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="dangling")v.ProfileId=long.MaxValue;if(kind=="closing")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);using var r=await Move(s,target.RecordId,1);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("grant",404)][InlineData("downgrade",403)][InlineData("member",404)][InlineData("move",404)]
    public async Task GivenCommittedSharedRelationshipChange_WhenMoving_ThenCurrentPermissionWins(string kind,int status)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[],[root.Id]);using(var get=await Read(s,"/api/records/"+target.RecordId))await Success<RecordDetailsOutput>(get,200);await using(var db=fixture.Context()){if(kind=="grant")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));if(kind=="downgrade")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.Access,CollectionGrantAccess.ReadOnly));if(kind=="member")await db.CollectionFolders.Where(x=>x.CollectionId==c.Id).ExecuteDeleteAsync();if(kind=="move")await db.Folders.Where(x=>x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.ParentFolderId,(long?)null));}var before=await Snapshot(o);using var r=await Move(s,target.RecordId,1);await Failure(r,status);Assert.Equal(before,await Snapshot(o));}
    [FunctionalTheory][InlineData("signature")][InlineData("numericString")][InlineData("pins")]
    public async Task GivenRelevantMalformedNativeAuthority_WhenMoving_Then503WithoutAnyContentChange(string kind)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.RecordId],[]);await using(var db=fixture.Context()){if(kind=="signature")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind=="numericString")await db.Collections.Where(x=>x.Id==c.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Envelope,Encoding.UTF8.GetBytes(Encoding.UTF8.GetString(c.Envelope).Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""))));if(kind=="pins")await db.VaultProtections.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Material,"bad"u8.ToArray()));}var before=await Snapshot(o);using var r=await Move(s,target.RecordId,1);await Failure(r,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));}    [FunctionalTheory][InlineData("missing",404)][InlineData("foreign",404)][InlineData("trash",404)][InlineData("ancestorTrash",404)][InlineData("terminal",404)][InlineData("ancestorTerminal",404)][InlineData("cycle",503)][InlineData("hiddenCycle",404)]
    public async Task GivenHiddenOrCyclicDestinationAndStaleExpectedRevision_WhenMoving_ThenCurrentScopePrecedesConflict(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var to=await Folder(s,root.Id);var target=await Create(s);if(kind=="foreign")to=await Folder(await Setup(owner));await using(var db=fixture.Context()){if(kind is "trash" or "ancestorTrash" or "hiddenCycle")await db.Folders.Where(x=>x.Id==(kind=="trash"?to.Id:root.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind is "terminal" or "ancestorTerminal"){db.TerminalErasures.Add(new(){ResourceKind="folder",ResourceId=kind=="terminal"?to.PublicId:root.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}if(kind is "cycle" or "hiddenCycle")await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,to.Id));}var before=await Snapshot(s);using var response=await Move(s,target.RecordId,99,kind=="missing"?Guid.NewGuid():to.PublicId);await Failure(response,status,status==503?"persistence_unavailable":"not_found");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("signature")][InlineData("pins")][InlineData("quotedEpoch")]
    public async Task GivenRequiredNewInheritedNativeEnvelopeIsInvalid_WhenOwnerMoves_Then503WithoutExposingContent(string kind)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var recipient=await Setup(client);var to=await Folder(o);var target=await Create(o);var (c,g)=await Share(o,owner,recipient,client,CollectionGrantAccess.ReadWrite,[],[to.Id]);await using(var db=fixture.Context()){if(kind=="signature")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind=="pins")await db.VaultProtections.Where(x=>x.AccountId==recipient.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,"bad"u8.ToArray()));if(kind=="quotedEpoch")await db.Collections.Where(x=>x.Id==c.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,Encoding.UTF8.GetBytes(Encoding.UTF8.GetString(c.Envelope).Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""))));}var before=await Snapshot(o);using var response=await Move(o,target.RecordId,destination:to.PublicId);await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));using var get=await Read(recipient,"/api/records/"+target.RecordId);await Failure(get,404,"not_found");}

    private static HttpRequestMessage PutFolder(State s,string path,byte[] body){var split=path.IndexOf('?');var uri=split<0?path+"/folder":path[..split]+"/folder"+path[split..];var r=Request(s,body,uri);r.Method=HttpMethod.Put;return r;}
    private async Task<HttpResponseMessage> Move(State s,Guid id,long revision=1,Guid? destination=null){using var req=PutFolder(s,"/api/records/"+id,Bytes(new{expectedRevision=revision,folderId=destination}));return await Gateway.Client.SendAsync(req);}
    private async Task<VaultRecord> Row(Guid id){await using var db=fixture.Context();return await db.Records.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task Moved(VaultRecord original,VaultFolder? destination,MoveRecordOutput output)
    {Fields(output,"recordId","folderId","revision","serverSequence");Assert.Equal(original.PublicId,output.RecordId);Assert.Equal(destination?.PublicId,output.FolderId);Assert.Equal(original.Revision+1,output.Revision);Assert.True(output.ServerSequence>original.ServerSequence);var row=await Row(original.PublicId);Assert.Equal(original.AccountId,row.AccountId);Assert.Equal(original.Envelope,row.Envelope);Assert.Equal(original.EditedAt,row.EditedAt);Assert.Equal(destination?.Id,row.FolderId);Assert.Equal(output.Revision,row.Revision);Assert.Equal(output.ServerSequence,row.ServerSequence);Assert.Null(row.DeletedAt);Assert.Null(row.PurgeAt);Assert.NotEqual(original.ConcurrencyStamp,row.ConcurrencyStamp);}
    private async Task<string> Links(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Protected=await Protected(s),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),CollectionRecords=await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),CollectionFolders=await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId&&p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>db.Collections.Any(c=>c.Id==x.CollectionId&&c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<RecordCreateInput> Create(State s,Guid[]? profiles=null,Guid? folder=null){var input=Input(profiles,folder);using var response=await Send(s,input);await Success<CreateRecordOutput>(response,201);return input;}
    private async Task<(VaultCollection,CollectionGrant)> Share(State owner,ProtectionFixture author,State recipient,ProtectionFixture recipientKeys,CollectionGrantAccess access,Guid[] records,long[] folders){await using var db=fixture.Context();var collection=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=owner.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(collection);await db.SaveChangesAsync();var grant=new CollectionGrant{PublicId=Guid.NewGuid(),CollectionId=collection.Id,RecipientAccountId=recipient.InternalId,Access=access};grant.RecipientKeyEnvelope=Bytes(author.WrapGrant(owner.AccountId,collection.PublicId,grant.PublicId,recipient.Actor,recipientKeys.Material.RecipientKey));db.CollectionGrants.Add(grant);foreach(var id in records){var record=await db.Records.SingleAsync(x=>x.PublicId==id);db.CollectionRecords.Add(new(){AccountId=owner.InternalId,CollectionId=collection.Id,RecordId=record.Id});}db.CollectionFolders.AddRange(folders.Select(id=>new CollectionFolder{AccountId=owner.InternalId,CollectionId=collection.Id,FolderId=id}));await db.SaveChangesAsync();return(collection,grant);}
    private sealed class BodyFeature:IHttpRequestBodyDetectionFeature{public bool CanHaveBody=>true;}
    private sealed record State(Guid Actor,Guid AccountId,long InternalId,string Access);
    private async Task<State> Setup(ProtectionFixture client)
    {var actor=Guid.NewGuid();fixture.Users[actor+"@example.test"]=new(actor,"fixture-password");await using var db=fixture.Context();var account=new Account{PublicId=Guid.NewGuid(),HeimdallPublicId=actor,DetailsEnvelope=Bytes(Envelope())};db.Accounts.Add(account);await db.SaveChangesAsync();var access=ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32));OpaqueAccessHandle.TryHash(access,out var verifier);db.VaultProtections.Add(new(){AccountId=account.Id,Material=Bytes(client.Material)});db.VaultAccessSessions.Add(new(){AccountId=account.Id,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return new(actor,account.PublicId,account.Id,access);}
    private async Task<VaultFolder> Folder(State s,long? parent=null){var f=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.Context();db.Folders.Add(f);await db.SaveChangesAsync();return f;}
    private async Task<Profile> Profile(State s,ProtectionFixture owner,ProtectionFixture scoped,VaultFolder? folder=null,string mode="Master",Guid[]? collections=null)
    {var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,scoped.Material.UnlockVerifier,owner.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?scoped.Material.PasswordWrapper:null),DateTimeOffset.UnixEpoch,[],folder is null?[]:[folder.PublicId],collections??[]);using var request=Request(s,Bytes(input),"/api/profiles");using var r=await Gateway.Client.SendAsync(request);Assert.Equal(HttpStatusCode.Created,r.StatusCode);await using var db=fixture.Context();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<string> Open(State s,Profile p,ProtectionFixture scoped)
    {await using var db=fixture.Context();var revision=(await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id)).Revision;var raw=Bytes(new{expectedRevision=revision});using var challengeRequest=Request(s,Bytes(new{expectedRevision=revision,requestHash=ProtocolBinary.Encode(SHA256.HashData(raw))}),"/api/profiles/"+p.PublicId+"/access/challenges");challengeRequest.Headers.Remove("X-Cerberus-Vault-Access");using var issued=await Gateway.Client.SendAsync(challengeRequest);var challenge=(await Success<IssueProfileAccessChallengeOutput>(issued,201)).Challenge;using var open=Request(s,raw,"/api/profiles/"+p.PublicId+"/access");open.Headers.Remove("X-Cerberus-Vault-Access");open.Headers.Add("X-Cerberus-Challenge-Id",challenge.ChallengeId.ToString());open.Headers.Add("X-Cerberus-Proof",scoped.Sign(challenge));using var response=await Gateway.Client.SendAsync(open);return (await Success<OpenProfileAccessOutput>(response,200)).VaultAccess;}
    private static RecordCreateInput Input(Guid[]? profiles=null,Guid? folder=null)=>new(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch.AddTicks(19),profiles??[],folder);
    private static EncryptedEnvelope Envelope(long epoch=1)=>new("cerberus-content-v1",epoch,ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(12)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(73)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(16)));
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
    
    private static HttpRequestMessage Request(State s,byte[] body,string path="/api/records"){var r=new HttpRequestMessage(HttpMethod.Post,path){Content=new ByteArrayContent(body)};r.Content.Headers.ContentType=new("application/json");r.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));r.Headers.Add("X-Cerberus-Vault-Access",s.Access);return r;}
    private async Task<HttpResponseMessage> Send(State s,RecordCreateInput input){using var request=Request(s,Bytes(input));return await Gateway.Client.SendAsync(request);}
    private async Task<HttpResponseMessage> Read(State s,string path){using var request=new HttpRequestMessage(HttpMethod.Get,path);request.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));request.Headers.Add("X-Cerberus-Vault-Access",s.Access);return await Gateway.Client.SendAsync(request);}
    private async Task<string> Protected(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Protection=await db.VaultProtections.AsNoTracking().SingleAsync(x=>x.AccountId==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<string> Snapshot(State s,bool skipMembers=false){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Protected=await Protected(s),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>x.RecipientAccountId==s.InternalId || db.Collections.Any(c=>c.Id==x.CollectionId && c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Members=skipMembers?[]:await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),CollectionFolders=await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId && p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),Operations=await db.TrashOperations.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Entries=await db.TrashEntries.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.Id==x.OperationId&&o.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Queue=await db.RetentionWorkItems.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.AccountId==s.InternalId&&x.OperationKey=="trash/"+o.PublicId)).OrderBy(x=>x.Id).ToArrayAsync(),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync()});}
    private static async Task<T> Success<T>(HttpResponseMessage r,int status) where T:class{Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);if(typeof(T)==typeof(MoveRecordOutput)){using var raw=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.Equal(new[]{"folderId","recordId","revision","serverSequence"},raw.RootElement.GetProperty("data").EnumerateObject().Select(x=>x.Name).Order());}var result=await r.Content.ReadFromJsonAsync<DataOutput<T>>();Assert.True(result!.Success);return Assert.IsType<T>(result.Data);}
    private static void Fields(object value,params string[] names){using var d=JsonDocument.Parse(JsonSerializer.Serialize(value,ProtectionFixture.Json));Assert.Equal(names.Order(),d.RootElement.EnumerateObject().Select(x=>x.Name).Order());}
    private static async Task Failure(HttpResponseMessage r,int status,string? error=null){Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);if(status==413){Assert.Equal("",await r.Content.ReadAsStringAsync());return;}using var d=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.False(d.RootElement.GetProperty("success").GetBoolean());if(d.RootElement.TryGetProperty("data",out var data))Assert.Equal(JsonValueKind.Null,data.ValueKind);if(error is not null)Assert.Contains(error,d.RootElement.GetProperty("errors").EnumerateArray().Select(x=>x.GetString()));}
}
