<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ArturRios.Data.PostgreSql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Domain/ArturRios.Cerberus.Domain/ArturRios.Cerberus.Domain.csproj" />
    <ProjectReference Include="../../Application/ArturRios.Cerberus.Shared/ArturRios.Cerberus.Shared.csproj" />
  </ItemGroup>
</Project>
