using System.Data.Common;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using ArturRios.Cerberus.Data.Profiles;
using ArturRios.Cerberus.Data.Protection;
using ArturRios.Cerberus.Data.Records;
using ArturRios.Cerberus.Data.Folders;
using ArturRios.Cerberus.Domain.Folders;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Records;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Domain.Trash;
using ArturRios.Cerberus.TestSupport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Npgsql;
namespace ArturRios.Cerberus.Data.Tests;

[Collection("PostgreSQL")]
public class FolderMoveStoreTests(PostgresFixture fixture)
{
    [FunctionalTheory][InlineData("missing","not_found")][InlineData("closing","not_found")][InlineData("terminal","not_found")][InlineData("access","vault_access_denied")][InlineData("revoked","vault_access_denied")][InlineData("expired","vault_access_denied")][InlineData("future","vault_access_denied")][InlineData("policy","vault_access_denied")][InlineData("generation","vault_access_denied")][InlineData("zeroPolicy","vault_access_denied")][InlineData("zeroGeneration","vault_access_denied")][InlineData("nullExpiry","vault_access_denied")][InlineData("disabledExpiry","vault_access_denied")][InlineData("noExpiry",null)][InlineData("selection","vault_access_denied")]
    public async Task GivenInvalidCurrentAuthority_WhenMoving_ThenFailClosed(string kind,string? error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);
        await using(var db=fixture.CreateContext()){var a=await db.Accounts.SingleAsync(x=>x.Id==s.InternalId);var v=await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==s.Verifier);if(kind=="closing")a.State=AccountState.ClosurePending;if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="zeroPolicy")v.PolicyRevision=0;if(kind=="zeroGeneration")v.RevocationGeneration=0;if(kind is "noExpiry" or "disabledExpiry")a.RenewalEnabled=false;if(kind is "nullExpiry" or "noExpiry")v.ExpiresAt=null;if(kind=="selection")v.ProfileId=long.MaxValue;await db.SaveChangesAsync();}
        var before=await Snapshot(s);var r=await Store().MoveAsync(new(kind=="missing"?Guid.NewGuid():s.Actor,kind=="access"?new string('a',64):s.Verifier,target.PublicId,1,null),default);Assert.Equal(error,r.Error);if(error is null)await Success(target,null,null,null,r);else Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("actor","authentication_required")][InlineData("id","validation_failed")][InlineData("destination","validation_failed")][InlineData("zero","validation_failed")][InlineData("unsafe","validation_failed")]
    public async Task GivenInvalidInternalRequest_WhenMoving_ThenRejectWithoutWrite(string kind,string error)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var before=await Snapshot(s);var r=await Store().MoveAsync(new(kind=="actor"?Guid.Empty:s.Actor,s.Verifier,kind=="id"?Guid.Empty:target.PublicId,kind=="zero"?0:kind=="unsafe"?ProtocolBinary.MaxInteger+1:1,kind=="destination"?Guid.Empty:null),default);Assert.Equal(error,r.Error);Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData("missing","not_found")][InlineData("foreign","not_found")][InlineData("trash","not_found")][InlineData("ancestorTrash","not_found")][InlineData("terminal","not_found")][InlineData("ancestorTerminal","not_found")][InlineData("cycle","persistence_unavailable")][InlineData("hiddenCycle","not_found")]
    public async Task GivenMissingHiddenOrCyclicDestination_WhenMovingWithStaleRevision_ThenCurrentDestinationStateWins(string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var to=await Folder(s,root.Id);var target=await Folder(s);
        if(kind=="foreign"){var other=await ProfileSetup.Create(fixture,owner);to=await Folder(other);}
        await using(var db=fixture.CreateContext()){
            if(kind is "trash" or "ancestorTrash" or "hiddenCycle")await db.Folders.Where(x=>x.Id==(kind=="trash"?to.Id:root.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));
            if(kind is "terminal" or "ancestorTerminal"){db.TerminalErasures.Add(new(){ResourceId=kind=="terminal"?to.PublicId:root.PublicId,ResourceKind="folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
            if(kind is "cycle" or "hiddenCycle")await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,to.Id));
        }
        var before=await Snapshot(s);Assert.Equal(error,(await Move(s,target,kind=="missing"?Guid.NewGuid():to.PublicId,99)).Error);Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("cipher","persistence_unavailable")][InlineData("zeroRevision","persistence_unavailable")][InlineData("zeroSequence","persistence_unavailable")][InlineData("unsafeSequence","persistence_unavailable")][InlineData("purge","persistence_unavailable")][InlineData("maxRevision","revision_conflict")][InlineData("stale","revision_conflict")]
    public async Task GivenCorruptOrConflictingVisibleTarget_WhenMoving_ThenPreserveEveryRow(string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var to=await Folder(s);
        await using(var db=fixture.CreateContext()){var row=await db.Folders.SingleAsync(x=>x.Id==target.Id);if(kind=="cipher")row.Envelope="bad"u8.ToArray();if(kind=="zeroRevision")row.Revision=0;if(kind=="maxRevision")row.Revision=ProtocolBinary.MaxInteger;if(kind=="zeroSequence")row.ServerSequence=0;if(kind=="unsafeSequence")row.ServerSequence=ProtocolBinary.MaxInteger+1;if(kind=="purge")row.PurgeAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();}
        var before=await Snapshot(s);Assert.Equal(error,(await Move(s,target,to.PublicId,kind=="stale"?99:kind=="maxRevision"?ProtocolBinary.MaxInteger:1)).Error);Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalTheory][InlineData(false,"zeroRevision","persistence_unavailable")][InlineData(true,"zeroRevision","persistence_unavailable")][InlineData(false,"zeroSequence","persistence_unavailable")][InlineData(true,"zeroSequence","persistence_unavailable")][InlineData(false,"maxRevision","revision_conflict")][InlineData(true,"maxRevision","revision_conflict")]
    public async Task GivenInvalidChangedImmediateParentMetadata_WhenMoving_ThenNoPartialRecordOrFolderUpdate(bool destination,string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Folder(s,from.Id);
        await using(var db=fixture.CreateContext()){var row=await db.Folders.SingleAsync(x=>x.Id==(destination?to.Id:from.Id));if(kind=="zeroRevision")row.Revision=0;if(kind=="zeroSequence")row.ServerSequence=0;if(kind=="maxRevision")row.Revision=ProtocolBinary.MaxInteger;await db.SaveChangesAsync();}
        var before=await Snapshot(s);Assert.Equal(error,(await Move(s,target,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalFact]
    public async Task GivenSameParentAtMaximumRevision_WhenNoopMoving_ThenAdvanceOnlyRecordAndRetryOldRevisionConflicts()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var to=await Folder(s);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==to.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,ProtocolBinary.MaxInteger));var beforeParent=await FolderRow(to.Id);var target=await Folder(s,to.Id);
        await Success(target,to,beforeParent,beforeParent,await Move(s,target,to.PublicId));var before=await Snapshot(s);Assert.Equal("revision_conflict",(await Move(s,target,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("signature")][InlineData("grantRevision")][InlineData("recipientPins")][InlineData("ownerPins")][InlineData("collectionEpoch")][InlineData("quotedEpoch")][InlineData("unknown")][InlineData("duplicate")][InlineData("wrongIdentity")]
    public async Task GivenMalformedRequiredResultingNativeEnvelope_WhenMovingIntoCollectionFolder_Then503NoMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var c=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var target=await Folder(s);await Members(s,a.Collection,[],[a.Folder.Id]);var g=await AssociationSetup.Grant(fixture,s,owner,c,client,a.Collection,CollectionGrantAccess.ReadWrite);
        await using(var db=fixture.CreateContext()){
            if(kind=="grantRevision")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,2));
            if(kind is "signature" or "unknown" or "duplicate" or "wrongIdentity"){var raw=JsonSerializer.Deserialize<RecipientEnvelope>(g.RecipientKeyEnvelope,ProtectionFixture.Json)!;var bytes=kind=="signature"?Bytes(raw with{Signature=ProtocolBinary.Encode(new byte[64])}):kind=="wrongIdentity"?Bytes(raw with{RecipientIdentityId=Guid.NewGuid()}):Malformed(g.RecipientKeyEnvelope,kind);await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,bytes));}
            if(kind is "recipientPins" or "ownerPins")await db.VaultProtections.Where(x=>x.AccountId==(kind=="recipientPins"?c.InternalId:s.InternalId)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,"bad"u8.ToArray()));
            if(kind=="collectionEpoch")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.KeyEpoch,2));if(kind=="quotedEpoch")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,Malformed(a.Collection.Envelope,"numericString")));
        }
        var before=await Snapshot(s);var recipient=await Snapshot(c);Assert.Equal("persistence_unavailable",(await Move(s,target,a.Folder.PublicId)).Error);Assert.Equal(before,await Snapshot(s));Assert.Equal(recipient,await Snapshot(c));
    }

    [FunctionalFact]
    public async Task GivenMalformedOldOnlyNativeRoute_WhenMovingOutOfIt_ThenRetainNoInvalidResultingEnvelopeAndRemoveAccess()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var c=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var target=await Folder(s,a.Folder.Id);await Members(s,a.Collection,[],[a.Folder.Id]);var g=await AssociationSetup.Grant(fixture,s,owner,c,client,a.Collection);
        await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));await Success(target,null,a.Folder,null,await Move(s,target,null));Assert.Equal("not_found",(await new FolderReadStore(fixture).ReadAsync(new(c.Actor,c.Verifier,target.PublicId),default)).Error);
    }

    [FunctionalFact]
    public async Task GivenCanceledCallerOrUnavailableFactory_WhenMoving_ThenPropagateCancellationOrSafe503()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var before=await Snapshot(s);using var cancel=new CancellationTokenSource();cancel.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Store().MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,null),cancel.Token));Assert.Equal(before,await Snapshot(s));
        var factory=new ProfileSetup.Factory(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql("Host=127.0.0.1;Port=1;Database=none;Username=none;Password=none;Timeout=1").Options);Assert.Equal("persistence_unavailable",(await new FolderMoveStore(factory).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,null),default)).Error);
    }

    [FunctionalFact]
    public async Task GivenConcurrentMovesAndLostSuccessRetry_WhenReplacingParent_ThenOneStructuralChangeAndNoDuplicateBumps()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Folder(s,from.Id);var tasks=new[]{Move(s,target,to.PublicId),Move(s,target,to.PublicId)};var results=await Task.WhenAll(tasks);Assert.Single(results,x=>x.Error is null);Assert.Single(results,x=>x.Error=="revision_conflict");await Success(target,to,from,to,results.Single(x=>x.Error is null));var before=await Snapshot(s);Assert.Equal("revision_conflict",(await Move(s,target,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));
        var row=await Row(target.Id);var nowFrom=await FolderRow(from.Id);var nowTo=await FolderRow(to.Id);await Success(row,to,nowFrom,nowTo,await Move(s,row,to.PublicId,2));
    }

    [FunctionalFact]
    public async Task GivenActualRecipientProtectionRotationAfterNativeValidation_WhenMoving_ThenStaleEvidenceConflictsAndFreshRetrySucceeds()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var target=await Folder(s);await Members(s,a.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);
        var change=new ProtectionChange(recipient.AccountId,1,1,"rotate-content",client.Rewrap(),[new("account",recipient.AccountId,1,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(recipient.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;
        var before=await Snapshot(s);var hook=new BeforeWrite(async()=>Assert.Null((await new VaultProtectionChangeStore(fixture).ChangeAsync(new(recipient.Actor,recipient.Verifier,challenge.ChallengeId,client.Sign(challenge),raw,change),default)).Error));
        Assert.Equal("revision_conflict",(await new FolderMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,a.Folder.PublicId),default)).Error);Assert.Equal(before,await Snapshot(s));await Success(target,a.Folder,null,a.Folder,await Move(s,target,a.Folder.PublicId));
    }

    [FunctionalFact]
    public async Task GivenActualOwnerRotationWaitsBehindMove_WhenMoveCommits_ThenStaleInventoryConflictsWithoutConsumingProof()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Folder(s,from.Id);var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),[new("account",s.AccountId,1,ProfileSetup.Envelope(2)),new("folder",target.PublicId,1,ProfileSetup.Envelope(2)),new("folder",from.PublicId,1,ProfileSetup.Envelope(2)),new("folder",to.PublicId,1,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var move=new FolderMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var rotation=new VaultProtectionChangeStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"account"))).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),ct.Token);
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(rotation.IsCompleted);}finally{release.TrySetResult();}await Success(target,to,from,to,await move);Assert.Equal("revision_conflict",(await rotation).Error);await using var db=fixture.CreateContext();Assert.False((await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==challenge.ChallengeId)).Consumed);Assert.Equal(1,(await db.VaultProtections.SingleAsync(x=>x.AccountId==s.InternalId)).Revision);
    }

    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenActualOwnerRotationBeforeOrAfterMove_WhenReloading_ThenRetainCurrentParentAndRespectEpochRevisionAndHandle(bool rotateFirst)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Folder(s,from.Id);
        if(!rotateFirst){await Success(target,to,from,to,await Move(s,target,to.PublicId));target=await Row(target.Id);from=await FolderRow(from.Id);to=await FolderRow(to.Id);}
        var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),[new("account",s.AccountId,1,ProfileSetup.Envelope(2)),new("folder",target.PublicId,target.Revision,ProfileSetup.Envelope(2)),new("folder",from.PublicId,from.Revision,ProfileSetup.Envelope(2)),new("folder",to.PublicId,to.Revision,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;Assert.Null((await new VaultProtectionChangeStore(fixture).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),default)).Error);
        Assert.Equal("vault_access_denied",(await Move(s,target,to.PublicId,1)).Error);var row=await Row(target.Id);Assert.Equal(rotateFirst?from.Id:to.Id,row.ParentFolderId);Assert.Equal(2,JsonSerializer.Deserialize<EncryptedEnvelope>(row.Envelope,ProtectionFixture.Json)!.KeyEpoch);
        if(rotateFirst){var verifier=Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));await using(var db=fixture.CreateContext()){var account=await db.Accounts.SingleAsync(x=>x.Id==s.InternalId);db.VaultAccessSessions.Add(new(){AccountId=s.InternalId,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=account.PolicyRevision,RevocationGeneration=account.RevocationGeneration});await db.SaveChangesAsync();}s=s with{Verifier=verifier};var before=await Snapshot(s);Assert.Equal("revision_conflict",(await Move(s,row,to.PublicId,1)).Error);Assert.Equal(before,await Snapshot(s));await Success(row,to,await FolderRow(from.Id),await FolderRow(to.Id),await Move(s,row,to.PublicId,row.Revision));}
    }

    [FunctionalTheory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)][InlineData(true,true)]
    public async Task GivenSequenceExhaustionOrRegressionAtTargetOrParent_WhenMoving_ThenRollbackAllStructuralChanges(bool parent,bool regression)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Folder(s,from.Id);var before=await Snapshot(s);await using var db=fixture.CreateContext();var previous=await db.Database.SqlQuery<long>($"SELECT nextval('cerberus.server_sequence') AS \"Value\"").SingleAsync();
        async Task Reset(){await using var other=fixture.CreateContext();await other.Database.ExecuteSqlRawAsync(regression?"SELECT setval('cerberus.server_sequence',1,false)":"SELECT setval('cerberus.server_sequence',9007199254740991,true)");}
        try{var store=parent?new FolderMoveStore(new ProfileSetup.Factory(fixture,new BeforeParent(Reset))):Store();if(!parent)await Reset();Assert.Equal(regression?"persistence_unavailable":"revision_conflict",(await store.MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),default)).Error);Assert.Equal(before,await Snapshot(s));}finally{await db.Database.ExecuteSqlInterpolatedAsync($"SELECT setval('cerberus.server_sequence',{previous},true)");}
    }

    [FunctionalTheory][InlineData("foreign")][InlineData("trash")][InlineData("terminal")]
    public async Task GivenInvalidSelectedProfile_WhenMoving_Then403WithoutBroadening(string kind)
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var p=await Profile(kind=="foreign"?await ProfileSetup.Create(fixture,owner):s,owner,key);s=s with{Verifier=await Selected(s,p.Id)};await using(var db=fixture.CreateContext()){if(kind=="trash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="terminal"){db.TerminalErasures.Add(new(){ResourceKind="profile",ResourceId=p.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}var before=await Snapshot(s);Assert.Equal("vault_access_denied",(await Move(s,target,null,99)).Error);Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenUnsafeImmediateParentSequence_WhenMoving_Then503WithNoPartialChanges(bool destination)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Folder(s,from.Id);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==(destination?to.Id:from.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ServerSequence,ProtocolBinary.MaxInteger+1));var before=await Snapshot(s);Assert.Equal("persistence_unavailable",(await Move(s,target,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));}

    [FunctionalFact]
    public async Task GivenExpiryAfterAllLocksBeforeFinalStatement_WhenMoving_Then403WithoutCommit()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);var store=new FolderMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(()=>Past(deadline))));Assert.Equal("vault_access_denied",(await store.MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,null),default)).Error);Assert.Equal(before,await Snapshot(s));}

    [FunctionalFact]
    public async Task GivenProviderInternalCancellationBeforeFinalStatement_WhenMoving_Then503WithoutMutation()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var before=await Snapshot(s);var store=new FolderMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(()=>throw new OperationCanceledException())));Assert.Equal("persistence_unavailable",(await store.MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,null),default)).Error);Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenActualNativeVisibleForeignFolder_WhenMovingStaleDamagedTarget_Then403AndNoGraphMutation(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var target=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,access);if(selected){var p=await Profile(s,client,key,collections:[a.Collection.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};}
        Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,target.PublicId),default)).Error);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged"u8.ToArray()));var before=await Snapshot(o);var recipient=await Snapshot(s);Assert.Equal("vault_access_denied",(await Move(s,target,Guid.NewGuid(),99)).Error);Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }

    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenActualNativeRecordOnlyMembership_WhenMovingItsContainingFolder_Then404AfterSuccessfulRecordRead(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var record=await Record(o,a.Folder.Id);await Members(o,a.Collection,[record.Id],[]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,access);if(selected){var p=await Profile(s,client,key,collections:[a.Collection.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};}
        Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);var before=await Snapshot(o);Assert.Equal("not_found",(await Move(s,a.Folder,null,99)).Error);Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalFact]
    public async Task GivenSelectedDirectRecordWithoutFolderMembership_WhenMovingContainer_Then404AfterSuccessfulRecordRead()
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var record=await Record(s,folder.Id);var p=await Profile(s,owner,key,records:[record.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);var before=await Snapshot(s);Assert.Equal("not_found",(await Move(s,folder,null,99)).Error);Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData("missing")][InlineData("foreign")][InlineData("unselected")][InlineData("trash")][InlineData("folderTerminal")][InlineData("ancestorTrash")][InlineData("ancestorTerminal")][InlineData("ownerClosing")][InlineData("ownerTerminal")][InlineData("grantRevoked")][InlineData("collectionTrash")][InlineData("removedMembership")]
    public async Task GivenHiddenTargetWithBadNativeAndStaleRevision_WhenMoving_Then404BeforeDisclosure(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=kind=="unselected"?o:await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var target=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[target.Id]);CollectionGrant? g=null;if(kind!="foreign" && s.InternalId!=o.InternalId)g=await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);if(kind=="unselected"){var p=await Profile(s,owner,scoped);s=s with{Verifier=await Selected(s,p.Id)};}
        await using(var db=fixture.CreateContext()){
            await db.Folders.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"bad"u8.ToArray()));
            if(g is not null)await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));
            if(kind=="trash")await db.Folders.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="ancestorTrash")await db.Folders.Where(x=>x.Id==a.Folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));
            if(kind.EndsWith("Terminal")){var id=kind=="folderTerminal"?target.PublicId:kind=="ancestorTerminal"?a.Folder.PublicId:o.AccountId;db.TerminalErasures.Add(new(){ResourceId=id,ResourceKind=kind=="folderTerminal"?"folder":kind=="ancestorTerminal"?"folder":"account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
            if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==o.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,AccountState.ClosurePending));if(kind=="grantRevoked")await db.CollectionGrants.Where(x=>x.Id==g!.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,CollectionGrantState.Revoked));if(kind=="collectionTrash")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="removedMembership")await db.CollectionFolders.Where(x=>x.FolderId==target.Id).ExecuteDeleteAsync();
        }
        var before=await Snapshot(o);Assert.Equal("not_found",(await Store().MoveAsync(new(s.Actor,s.Verifier,kind=="missing"?Guid.NewGuid():target.PublicId,99,null),default)).Error);Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalTheory][InlineData("signature")][InlineData("revision")][InlineData("epoch")][InlineData("numericString")][InlineData("unknown")][InlineData("duplicate")][InlineData("ownerPins")][InlineData("recipientPins")]
    public async Task GivenMalformedContributingNativeAuthority_WhenNonownerRequestsMove_Then503WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[],[a.Folder.Id]);var g=await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);await using(var db=fixture.CreateContext()){
            if(kind=="signature")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind=="revision")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,2));if(kind=="epoch")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.KeyEpoch,2));if(kind is "numericString" or "unknown" or "duplicate")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,Malformed(a.Collection.Envelope,kind)));if(kind is "ownerPins" or "recipientPins")await db.VaultProtections.Where(x=>x.AccountId==(kind=="ownerPins"?o.InternalId:s.InternalId)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,"bad"u8.ToArray()));}
        var before=await Snapshot(o);Assert.Equal("persistence_unavailable",(await Move(s,a.Folder,null,99)).Error);Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenOverlappingNativeAuthorityWithMalformedContributor_WhenNonownerMoves_ThenWholeDenialFailsClosed(bool invalidReadWrite)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var b=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[],[a.Folder.Id]);await Members(o,b.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,invalidReadWrite?CollectionGrantAccess.ReadOnly:CollectionGrantAccess.ReadWrite);var bad=await AssociationSetup.Grant(fixture,o,owner,s,client,b.Collection,invalidReadWrite?CollectionGrantAccess.ReadWrite:CollectionGrantAccess.ReadOnly);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(o);Assert.Equal("persistence_unavailable",(await Move(s,a.Folder,null)).Error);Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalTheory][InlineData("parent")][InlineData("sibling")]
    public async Task GivenNativeMemberLeafGrant_WhenMovingPrivateParentOrSibling_Then404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var leaf=await Folder(o,a.Folder.Id);var sibling=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[leaf.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,leaf.PublicId),default)).Error);var before=await Snapshot(o);Assert.Equal("not_found",(await Move(s,kind=="parent"?a.Folder:sibling,null,99)).Error);Assert.Equal(before,await Snapshot(o));
    }

    // Every case exercises persisted structure/authority: removing its guard, scope check,
    // retained-byte check, lock or rollback would change the literal expected result.
    [FunctionalTheory][InlineData("between")][InlineData("fromRoot")][InlineData("toRoot")][InlineData("same")][InlineData("rootNoop")]
    public async Task GivenDeepOwnedSubtree_WhenMoving_ThenOnlyRootAndDistinctChangedImmediateParentsAdvance(string route)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Folder(s,route is "fromRoot" or "rootNoop"?null:from.Id);var child=await Folder(s,target.Id);var leaf=await Folder(s,child.Id);var record=await Record(s,leaf.Id);var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[record.Id],[child.Id]);await Profile(s,owner,key,records:[record.PublicId],folders:[target.PublicId,leaf.PublicId]);
        var destination=route is "toRoot" or "rootNoop"?null:route=="same"?from:to;var ignored=route is "same" or "rootNoop"?new[]{target.Id}:new[]{target.Id,from.Id,to.Id};var stable=await Stable(s,ignored);
        await Success(target,destination,from,to,await Move(s,target,destination?.PublicId));Assert.Equal(stable,await Stable(s,ignored));
        Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,leaf.PublicId),default)).Error);Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);
    }
    [FunctionalTheory][InlineData("direct")][InlineData("ancestor")][InlineData("collection")][InlineData("collectionAncestor")]
    public async Task GivenCurrentOwnedSelectedFolderScope_WhenMovingWithinSameScope_ThenRetainHandleAndSubtree(string route)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var common=await Folder(s);var from=await Folder(s,common.Id);var to=await Folder(s,common.Id);var root=await Folder(s,from.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var a=await AssociationSetup.Items(fixture,s);
        if(route.StartsWith("collection"))await Members(s,a.Collection,[],route=="collection"?[root.Id,to.Id]:[common.Id]);
        var p=await Profile(s,owner,key,folders:route=="direct"?[root.PublicId,to.PublicId]:route=="ancestor"?[common.PublicId]:[],collections:route.StartsWith("collection")?[a.Collection.PublicId]:[]);s=s with{Verifier=await Selected(s,p.Id)};var stable=await Stable(s,root.Id,from.Id,to.Id);
        await Success(root,to,from,to,await Move(s,root,to.PublicId));Assert.Equal(stable,await Stable(s,root.Id,from.Id,to.Id));Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,child.PublicId),default)).Error);Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);
    }
    [FunctionalTheory][InlineData("profile","root",false)][InlineData("profile","child",false)][InlineData("profile","record",false)][InlineData("collection","root",false)][InlineData("collection","child",false)][InlineData("collection","record",false)][InlineData("profile","child",true)][InlineData("collection","record",true)]
    public async Task GivenVisibleDestinationWithOverlappingMemberDirectScopes_WhenSelectedMove_ThenRejectNewInheritedScopeWithoutMutation(string kind,string member,bool wide)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();using var other=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var root=await Folder(s,from.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var p=await Profile(s,owner,key,folders:[root.PublicId,to.PublicId]);var a=await AssociationSetup.Items(fixture,s);
        if(kind=="profile")await Profile(s,owner,other,folders:member=="child"?[child.PublicId,to.PublicId]:[to.PublicId],records:member=="record"?[record.PublicId]:[]);
        else await Members(s,a.Collection,member=="record"?[record.Id]:[],member=="child"?[child.Id,to.Id]:[to.Id]);
        if(!wide)s=s with{Verifier=await Selected(s,p.Id)};Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,root.PublicId),default)).Error);Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,to.PublicId),default)).Error);var before=await Snapshot(s);
        var result=await Move(s,root,to.PublicId);if(wide)await Success(root,to,from,to,result);else{Assert.Equal("not_found",result.Error);Assert.Equal(before,await Snapshot(s));}
    }
    [FunctionalTheory][InlineData("profile",false)][InlineData("collection",false)][InlineData("profile",true)][InlineData("collection",true)]
    public async Task GivenUnchangedOverlappingDirectAndNestedMemberScopesOrInactiveDestinationScope_WhenSelectedMoving_ThenNoSpuriousExpansion(string kind,bool inactive)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();using var other=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var root=await Folder(s,from.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var p=await Profile(s,owner,key,folders:[root.PublicId,to.PublicId]);var a=await AssociationSetup.Items(fixture,s);
        if(kind=="profile"){var q=await Profile(s,owner,other,folders:inactive?[to.PublicId]:[root.PublicId,to.PublicId],records:inactive?[]:[record.PublicId]);if(inactive)await using(var db=fixture.CreateContext())await db.Profiles.Where(x=>x.Id==q.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}
        else{await Members(s,a.Collection,inactive?[]:[record.Id],inactive?[to.Id]:[root.Id,child.Id,to.Id]);if(inactive)await using(var db=fixture.CreateContext())await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}
        s=s with{Verifier=await Selected(s,p.Id)};var stable=await Stable(s,root.Id,from.Id,to.Id);await Success(root,to,from,to,await Move(s,root,to.PublicId));Assert.Equal(stable,await Stable(s,root.Id,from.Id,to.Id));
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenSelectedMoveToRootRemovingAncestorScope_WhenMoving_ThenNarrowWithoutRevokingTheDirectSelectedRoute(bool collection)
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();using var other=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var root=await Folder(s,from.Id);await Folder(s,root.Id);var p=await Profile(s,owner,key,folders:[root.PublicId]);if(collection){var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[],[from.Id]);}else await Profile(s,owner,other,folders:[from.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};await Success(root,null,from,null,await Move(s,root,null));Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,root.PublicId),default)).Error);}
    [FunctionalTheory][InlineData("self","validation_failed")][InlineData("child","validation_failed")][InlineData("deep","validation_failed")][InlineData("hiddenChild","not_found")]
    public async Task GivenPotentialCycleDestination_WhenMovingWithStaleRevision_ThenRejectVisibleCycleWithoutHiddenTopologyOracle(string kind,string error)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var leaf=await Folder(s,child.Id);if(kind=="hiddenChild")await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));var destination=kind=="self"?root:kind=="deep"?leaf:child;var before=await Snapshot(s);Assert.Equal(error,(await Move(s,root,destination.PublicId,99)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenCorruptSourceCycle_WhenMoving_ThenRelevantActiveCycle503OrHidden404(bool hidden)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var parent=await Folder(s);var root=await Folder(s,parent.Id);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==parent.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,root.Id).SetProperty(v=>v.DeletedAt,hidden?(DateTimeOffset?)DateTimeOffset.UtcNow:null));var before=await Snapshot(s);Assert.Equal(hidden?"not_found":"persistence_unavailable",(await Move(s,root,null,99)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("folder")][InlineData("record")][InlineData("profile")][InlineData("collection")][InlineData("account")]
    public async Task GivenSameGuidTerminalForAnotherResourceKind_WhenMoving_ThenTypedIdentityDoesNotHideTheFolder(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var to=await Folder(s);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceKind=kind,ResourceId=root.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);var r=await Move(s,root,to.PublicId);if(kind=="folder"){Assert.Equal("not_found",r.Error);Assert.Equal(before,await Snapshot(s));}else await Success(root,to,null,to,r);}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeOldNewDirectSubtreeRoutes_WhenOwnerMoves_ThenGetAndListRecalculateForFoldersAndRecordsWithoutKeyChanges(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();using var oldKey=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var b=await AssociationSetup.Items(fixture,s);var direct=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);await Members(s,a.Collection,[],[a.Folder.Id]);await Members(s,b.Collection,[],[b.Folder.Id]);await Members(s,direct.Collection,[record.Id],[child.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection,access);await AssociationSetup.Grant(fixture,s,owner,recipient,client,b.Collection,access);await AssociationSetup.Grant(fixture,s,owner,recipient,client,direct.Collection,access);
        var old=await Profile(recipient,client,oldKey,collections:[a.Collection.PublicId]);var oldHandle=await Selected(recipient,old.Id);if(selected){var p=await Profile(recipient,client,key,collections:[a.Collection.PublicId,b.Collection.PublicId,direct.Collection.PublicId]);recipient=recipient with{Verifier=await Selected(recipient,p.Id)};}var recipientBefore=await Snapshot(recipient);var stable=await Stable(s,root.Id,a.Folder.Id,b.Folder.Id);
        Assert.Contains(a.Collection.PublicId,(await new FolderReadStore(fixture).ReadAsync(new(recipient.Actor,recipient.Verifier,child.PublicId),default)).Data!.CollectionIds);
        await Success(root,b.Folder,a.Folder,b.Folder,await Move(s,root,b.Folder.PublicId));Assert.Equal(stable,await Stable(s,root.Id,a.Folder.Id,b.Folder.Id));Assert.Equal(recipientBefore,await Snapshot(recipient));
        var f=(await new FolderReadStore(fixture).ReadAsync(new(recipient.Actor,recipient.Verifier,child.PublicId),default)).Data!;Assert.DoesNotContain(a.Collection.PublicId,f.CollectionIds);Assert.Contains(b.Collection.PublicId,f.CollectionIds);Assert.Contains(direct.Collection.PublicId,f.CollectionIds);var r=(await new RecordReadStore(fixture).ReadAsync(new(recipient.Actor,recipient.Verifier,record.PublicId),default)).Data!;Assert.DoesNotContain(a.Collection.PublicId,r.CollectionIds);Assert.Contains(b.Collection.PublicId,r.CollectionIds);Assert.Contains(direct.Collection.PublicId,r.CollectionIds);
        Assert.Contains((await new FolderListStore(fixture).ListAsync(new(recipient.Actor,recipient.Verifier,50,0,null),default)).Data!.Items,x=>x.FolderId==child.PublicId);Assert.Contains((await new RecordListStore(fixture).ListAsync(new(recipient.Actor,recipient.Verifier,50,0,null),default)).Data!.Items,x=>x.RecordId==record.PublicId);Assert.Equal("not_found",(await new FolderReadStore(fixture).ReadAsync(new(recipient.Actor,oldHandle,child.PublicId),default)).Error);Assert.Equal("not_found",(await new RecordReadStore(fixture).ReadAsync(new(recipient.Actor,oldHandle,record.PublicId),default)).Error);Assert.Equal(new[]{a.Folder.PublicId},(await new FolderListStore(fixture).ListAsync(new(recipient.Actor,oldHandle,50,0,null),default)).Data!.Items.Select(x=>x.FolderId));Assert.Empty((await new RecordListStore(fixture).ListAsync(new(recipient.Actor,oldHandle,50,0,null),default)).Data!.Items);
    }
    [FunctionalTheory][InlineData("directRecord")][InlineData("nestedFolder")]
    public async Task GivenCorruptRequiredNativeGrantOnlyOnDescendant_WhenMoving_Then503WithoutRootOrParentChange(string kind)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var to=await Folder(s);var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,kind=="directRecord"?[record.Id]:[],kind=="nestedFolder"?[child.Id]:[]);var grant=await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(s);Assert.Equal("persistence_unavailable",(await Move(s,root,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("irrelevant")][InlineData("revoked")][InlineData("inactiveRecipient")][InlineData("inactiveCollection")]
    public async Task GivenInvalidNativeGrantOutsideActiveResultRoutes_WhenMoving_ThenIgnoreNoncontributor(string kind)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var root=await Folder(s);var to=await Folder(s);var a=await AssociationSetup.Items(fixture,s);if(kind!="irrelevant")await Members(s,a.Collection,[],[to.Id]);var g=await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);await using(var db=fixture.CreateContext()){await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()).SetProperty(v=>v.State,kind=="revoked"?CollectionGrantState.Revoked:CollectionGrantState.Active));if(kind=="inactiveRecipient")await db.Accounts.Where(x=>x.Id==recipient.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,AccountState.ClosurePending));if(kind=="inactiveCollection")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}await Success(root,to,null,to,await Move(s,root,to.PublicId));}
    [FunctionalTheory][InlineData("folder")][InlineData("record")][InlineData("profile")][InlineData("collection")][InlineData("recordProfile")][InlineData("recordCollection")]
    public async Task GivenUncapturedExistingSubtreeMemberOrDirectLink_WhenMoving_ThenReloadRatherThanUseUnheldInventory(string kind)
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var to=await Folder(s);var outside=await Folder(s);var record=await Record(s,kind is "recordProfile" or "recordCollection"?root.Id:null);var p=await Profile(s,owner,key);var a=await AssociationSetup.Items(fixture,s);string? winning=null;var hook=new BeforeContent(async()=>{await using var db=fixture.CreateContext();switch(kind){case "folder":await db.Folders.Where(x=>x.Id==outside.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,root.Id));break;case "record":await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.FolderId,root.Id));break;case "profile":db.ProfileFolders.Add(new(){AccountId=s.InternalId,ProfileId=p.Id,FolderId=root.Id});break;case "collection":db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=a.Collection.Id,FolderId=root.Id});break;case "recordProfile":db.ProfileRecords.Add(new(){AccountId=s.InternalId,ProfileId=p.Id,RecordId=record.Id});break;default:db.CollectionRecords.Add(new(){AccountId=s.InternalId,CollectionId=a.Collection.Id,RecordId=record.Id});break;}await db.SaveChangesAsync();winning=await Snapshot(s);});var r=await new FolderMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),default);Assert.Equal("revision_conflict",r.Error);Assert.NotNull(winning);Assert.Equal(winning,await Snapshot(s));}
    [FunctionalTheory][InlineData("valid","revision_conflict")][InlineData("corrupt","persistence_unavailable")]
    public async Task GivenNewResultNativeGrantBeforeCapturedContentLocks_WhenMoving_ThenCurrentBindingAndInventoryWin(string kind,string error)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var root=await Folder(s);var to=await Folder(s);var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[],[to.Id]);string? winning=null;var hook=new BeforeContent(async()=>{var g=await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);if(kind=="corrupt")await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));winning=await Snapshot(s);});Assert.Equal(error,(await new FolderMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),default)).Error);Assert.Equal(winning,await Snapshot(s));}
    [FunctionalTheory][InlineData("root")][InlineData("firstParent")][InlineData("secondParent")]
    public async Task GivenFailureAfterActualFolderOrParentMutation_WhenMoving_ThenWholeGraphRollsBackAndRetrySucceeds(string stage)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var root=await Folder(s,from.Id);var child=await Folder(s,root.Id);await Record(s,child.Id);var before=await Snapshot(s);var fail=new Fail(stage);Assert.Equal("persistence_unavailable",(await new FolderMoveStore(new ProfileSetup.Factory(fixture,fail)).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),default)).Error);Assert.True(fail.Triggered);Assert.Equal(before,await Snapshot(s));await Success(root,to,from,to,await Move(s,root,to.PublicId));}
    [FunctionalTheory][InlineData("folder","revision")][InlineData("folder","sequence")][InlineData("folder","time")][InlineData("folder","purge")][InlineData("record","revision")][InlineData("record","sequence")][InlineData("record","time")][InlineData("record","purge")]
    public async Task GivenInvalidActiveMemberMetadata_WhenMoving_Then503BeforeAnyMutation(string kind,string field)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,root.Id);var to=await Folder(s);await using(var db=fixture.CreateContext()){if(kind=="folder"){var row=await db.Folders.SingleAsync(x=>x.Id==child.Id);if(field=="revision")row.Revision=0;if(field=="sequence")row.ServerSequence=ProtocolBinary.MaxInteger+1;if(field=="time")row.EditedAt=DateTimeOffset.MinValue;if(field=="purge")row.PurgeAt=DateTimeOffset.UtcNow;}else{var row=await db.Records.SingleAsync(x=>x.Id==record.Id);if(field=="revision")row.Revision=0;if(field=="sequence")row.ServerSequence=ProtocolBinary.MaxInteger+1;if(field=="time")row.EditedAt=DateTimeOffset.MinValue;if(field=="purge")row.PurgeAt=DateTimeOffset.UtcNow;}await db.SaveChangesAsync();}var before=await Snapshot(s);Assert.Equal("persistence_unavailable",(await Move(s,root,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(false,"time")][InlineData(true,"time")][InlineData(false,"purge")][InlineData(true,"purge")]
    public async Task GivenChangedParentInvalidTimeOrActivePurge_WhenMoving_Then503AndRollbackBothParents(bool destination,string field)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var root=await Folder(s,from.Id);await using(var db=fixture.CreateContext()){var row=await db.Folders.SingleAsync(x=>x.Id==(destination?to.Id:from.Id));if(field=="time")row.EditedAt=DateTimeOffset.MinValue;else row.PurgeAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();}var before=await Snapshot(s);Assert.Equal("persistence_unavailable",(await Move(s,root,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenDamagedDescendantOpaqueBytes_WhenMoving_ThenRetainThemExactlyWithoutParsingOrChangingMetadata()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var to=await Folder(s);await using(var db=fixture.CreateContext()){await db.Folders.Where(x=>x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"opaque-child"u8.ToArray()));await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"opaque-record"u8.ToArray()));}var stable=await Stable(s,root.Id,to.Id);await Success(root,to,null,to,await Move(s,root,to.PublicId));Assert.Equal(stable,await Stable(s,root.Id,to.Id));}
    [FunctionalFact]
    public async Task GivenActualIndependentTrashOperations_WhenMovingActiveAncestor_ThenEarlierMembershipAndDeadlinesStayExact()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var oldChild=await Folder(s,root.Id);var oldRecord=await Record(s,root.Id);var nestedRecord=await Record(s,oldChild.Id);var active=await Folder(s,root.Id);var to=await Folder(s);Assert.Null((await new RecordTrashStore(fixture).TrashAsync(new(s.Actor,s.Verifier,oldRecord.PublicId,1),default)).Error);Assert.Null((await new FolderTrashStore(fixture).TrashAsync(new(s.Actor,s.Verifier,oldChild.PublicId,1),default)).Error);root=await Row(root.Id);var stable=await Stable(s,root.Id,to.Id);await Success(root,to,null,to,await Move(s,root,to.PublicId,root.Revision));Assert.Equal(stable,await Stable(s,root.Id,to.Id));Assert.Null((await Row(active.Id)).DeletedAt);Assert.NotNull((await RecordRow(nestedRecord.Id)).PurgeAt);}
    [FunctionalTheory][InlineData("folder")][InlineData("record")]
    public async Task GivenTypedTerminalDescendantBranch_WhenMoving_ThenExcludedRowsAndLinksStayExact(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var to=await Folder(s);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceKind=kind,ResourceId=kind=="folder"?child.PublicId:record.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var stable=await Stable(s,root.Id,to.Id);await Success(root,to,null,to,await Move(s,root,to.PublicId));Assert.Equal(stable,await Stable(s,root.Id,to.Id));}
    [FunctionalTheory][InlineData("account")][InlineData("session")][InlineData("profile")][InlineData("collection")][InlineData("grant")][InlineData("folder")][InlineData("record")]
    public async Task GivenNaturalExpiryDuringEachSubtreeLockWait_WhenMovingWithStaleRevision_Then403BeforeConflict(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var from=await Folder(s);var root=await Folder(s,from.Id);var record=await Record(s,root.Id);var to=await Folder(s);var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[record.Id],[root.Id]);var grant=await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);var p=await Profile(s,owner,key,folders:[root.PublicId,to.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);
        await using var held=fixture.CreateContext();await using var tx=await held.Database.BeginTransactionAsync();var table=kind switch{"session"=>"vault_access_session","grant"=>"collection_grant",_=>kind};var id=kind switch{"account"=>s.InternalId,"profile"=>p.Id,"collection"=>a.Collection.Id,"grant"=>grant.Id,"folder"=>root.Id,_=>record.Id};await held.Database.ExecuteSqlRawAsync(kind=="session"?"SELECT FROM cerberus.vault_access_session WHERE handle_verifier={0} FOR UPDATE":"SELECT FROM cerberus."+table+" WHERE id={0} FOR UPDATE",kind=="session"?(object)s.Verifier:id);
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var pending=new FolderMoveStore(new ProfileSetup.Factory(fixture,new Signal(reached,table))).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,99,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);await Past(deadline);await tx.CommitAsync();Assert.Equal("vault_access_denied",(await pending).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("expiry","vault_access_denied")][InlineData("rootTerminal","not_found")][InlineData("actorTerminal","not_found")][InlineData("destinationTerminal","not_found")][InlineData("descendantTerminal","revision_conflict")][InlineData("recipientPins","persistence_unavailable")]
    public async Task GivenCurrentLifecycleOrNativePinChangeImmediatelyBeforeRootWrite_WhenMoving_ThenDenyWithoutPartialGraph(string kind,string error)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var next=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var root=await Folder(s);var child=await Folder(s,root.Id);var to=await Folder(s);var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[],[to.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);var before=await Snapshot(s);var hook=new BeforeWrite(async command=>{if(kind=="expiry"){await using var c=command.Connection!.CreateCommand();c.Transaction=command.Transaction;c.CommandText="UPDATE cerberus.vault_access_session SET expires_at=statement_timestamp()-interval '1 second' WHERE handle_verifier=@v";c.Parameters.Add(new NpgsqlParameter("v",s.Verifier));await c.ExecuteNonQueryAsync();return;}await using var db=fixture.CreateContext();if(kind=="recipientPins")await db.VaultProtections.Where(x=>x.AccountId==recipient.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,Bytes(next.Material)));else{db.TerminalErasures.Add(new(){ResourceKind=kind=="actorTerminal"?"account":"folder",ResourceId=kind=="actorTerminal"?s.AccountId:kind=="rootTerminal"?root.PublicId:kind=="destinationTerminal"?to.PublicId:child.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}});Assert.Equal(error,(await new FolderMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),default)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("folder")][InlineData("child")][InlineData("record")]
    [InlineData("folder",true)][InlineData("child",true)][InlineData("record",true)]
    public async Task GivenActualNativeRecipientEditAndOwnerMove_WhenEarlierCollectionLocksSerialize_ThenPreserveWinnerWithoutDeadlock(string resource,bool moveFirst=false)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var from=await Folder(s);var root=await Folder(s,from.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var to=await Folder(s);var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[],[from.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection,CollectionGrantAccess.ReadWrite);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));Task<VaultResult<FolderMoveDetails>> move;Task<string?> edit;var input=ProfileSetup.Envelope();
        async Task<string?> Edit(IDbContextFactory<AppDbContext> f)=>resource=="record"?(await new RecordUpdateStore(f).UpdateAsync(new(recipient.Actor,recipient.Verifier,record.PublicId,new(1,input,DateTimeOffset.UnixEpoch.AddDays(1))),ct.Token)).Error:(await new FolderUpdateStore(f).UpdateAsync(new(recipient.Actor,recipient.Verifier,resource=="child"?child.PublicId:root.PublicId,new(1,input,DateTimeOffset.UnixEpoch.AddDays(1))),ct.Token)).Error;
        if(moveFirst){move=new FolderMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));edit=Edit(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection")));}else{edit=Edit(new ProfileSetup.Factory(fixture,new PauseUpdate(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);})));await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));move=new FolderMoveStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection"))).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),ct.Token);}
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(moveFirst?edit.IsCompleted:move.IsCompleted);}finally{release.TrySetResult();}await Task.WhenAll(move,edit);if(moveFirst){await Success(root,to,from,to,move.Result);Assert.Equal("not_found",edit.Result);}else{Assert.Null(edit.Result);Assert.Equal("revision_conflict",move.Result.Error);Assert.Equal(from.Id,(await Row(root.Id)).ParentFolderId);Assert.Equal(2,resource=="record"?(await RecordRow(record.Id)).Revision:(await Row(resource=="child"?child.Id:root.Id)).Revision);Assert.Equal(Bytes(to),Bytes(await Row(to.Id)));}
    }
    [FunctionalTheory][InlineData("folderCreate")][InlineData("recordCreate")][InlineData("recordMove")][InlineData("association")][InlineData("trash")]
    public async Task GivenOwnerMoveHoldsAccount_WhenActualOwnerWriterStarts_ThenSerializeAndPreserveBothCurrentAuthorizedWrites(string writer)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var to=await Folder(s);var outside=await Record(s);var p=await Profile(s,owner,key,folders:[root.PublicId]);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));var move=new FolderMoveStore(new ProfileSetup.Factory(fixture,new BeforeContent(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var f=new ProfileSetup.Factory(fixture,new Signal(blocked,"account"));
        async Task<string?> Write()=>writer switch{"folderCreate"=>(await new FolderCreateStore(f).CreateAsync(new(s.Actor,s.Verifier,new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],root.PublicId)),ct.Token)).Error,"recordCreate"=>(await new RecordCreateStore(f).CreateAsync(new(s.Actor,s.Verifier,new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],root.PublicId)),ct.Token)).Error,"recordMove"=>(await new RecordMoveStore(f).MoveAsync(new(s.Actor,s.Verifier,outside.PublicId,1,root.PublicId),ct.Token)).Error,"trash"=>(await new FolderTrashStore(f).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),ct.Token)).Error,_=>(await new ProfileAssociationStore(f).SetAsync(new(s.Actor,s.Verifier,p.PublicId,new(p.Revision,[],[root.PublicId],[])),ct.Token)).Error};
        var pending=Write();try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);}finally{release.TrySetResult();}Assert.Null((await move).Error);Assert.Equal(writer=="trash"?"revision_conflict":null,await pending);Assert.Equal(to.Id,(await Row(root.Id)).ParentFolderId);if(writer=="recordMove")Assert.Equal(root.Id,(await RecordRow(outside.Id)).FolderId);
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenReciprocalConcurrentOwnerMoves_WhenReparenting_ThenOnlyFirstCanCommitAndNoCycleOrDeadlock(bool reverse)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await Folder(s);var b=await Folder(s);var first=reverse?b:a;var second=reverse?a:b;var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var one=new FolderMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).MoveAsync(new(s.Actor,s.Verifier,first.PublicId,1,second.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var two=new FolderMoveStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"account"))).MoveAsync(new(s.Actor,s.Verifier,second.PublicId,1,first.PublicId),ct.Token);try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(two.IsCompleted);}finally{release.TrySetResult();}Assert.Null((await one).Error);Assert.Equal("validation_failed",(await two).Error);Assert.Equal(second.Id,(await Row(first.Id)).ParentFolderId);Assert.Null((await Row(second.Id)).ParentFolderId);}
    [FunctionalTheory][InlineData("cancel")][InlineData("timeout")][InlineData("db")][InlineData("dbUpdate")][InlineData("json")][InlineData("format")][InlineData("wrapped")]
    public async Task GivenNecessaryProviderFailure_WhenMoving_Then503WithoutExceptionDetails(string kind)
    {Exception e=kind switch{"cancel"=>new OperationCanceledException(),"timeout"=>new TimeoutException(),"db"=>new NpgsqlException("private-database"),"dbUpdate"=>new DbUpdateException(),"json"=>new JsonException(),"format"=>new FormatException(),_=>new InvalidOperationException("private",new TimeoutException())};Assert.Equal("persistence_unavailable",(await new FolderMoveStore(new ThrowingFactory(e)).MoveAsync(new(Guid.NewGuid(),new string('a',64),Guid.NewGuid(),1,null),default)).Error);}
    [FunctionalFact]
    public async Task GivenTwoHundredUnrelatedFolders_WhenMovingSmallSubtree_ThenBoundedRootPathsAndExactOwnedLockSet()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,client);var upper=await Folder(s);var from=await Folder(s,upper.Id);var root=await Folder(s,from.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var destUpper=await Folder(s);var to=await Folder(s,destUpper.Id);foreach(var account in new[]{s,foreign}){long? prior=null;for(var i=0;i<50;i++){var f=await Folder(account,prior);prior=f.Id;}for(var i=0;i<50;i++)await Folder(account);}
        var capture=new Capture(fixture,true);await Success(root,to,from,to,await new FolderMoveStore(new ProfileSetup.Factory(fixture,capture)).MoveAsync(new(s.Actor,s.Verifier,root.PublicId,1,to.PublicId),default));Assert.NotNull(capture.Plan);using var doc=JsonDocument.Parse(capture.Plan!);var nodes=Nodes(doc.RootElement[0].GetProperty("Plan")).ToArray();Assert.Equal(1d,Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var n)&&n.GetString()=="CTE candidates").GetProperty("Actual Rows").GetDouble());Assert.Equal(3d,Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var n)&&n.GetString()=="CTE ancestry").GetProperty("Actual Rows").GetDouble());Assert.Equal(new[]{from.Id,root.Id,child.Id,to.Id}.Order(),Assert.Single(capture.FolderIds).Order());Assert.Equal(new[]{record.Id},Assert.Single(capture.RecordIds));Assert.Single(capture.Locks,x=>x.Contains("FROM cerberus.account"));Assert.DoesNotContain(capture.Locks,x=>x.Contains("heimdall_public_id")&&!x.Contains("FROM cerberus.account"));Assert.Equal(upper.Revision,(await Row(upper.Id)).Revision);Assert.Equal(destUpper.Revision,(await Row(destUpper.Id)).Revision);
    }

    [FunctionalTheory][InlineData("sourceHidden","not_found")][InlineData("destinationHidden","not_found")][InlineData("destinationCycle","persistence_unavailable")][InlineData("ownerTerminal","not_found")]
    public async Task GivenCompleteAncestryOrTerminalChangeBeforeWrite_WhenMoving_ThenCurrentRecursiveStatementDenies(string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var sourceRoot=await Folder(s);var from=await Folder(s,sourceRoot.Id);var destinationRoot=await Folder(s);var to=await Folder(s,destinationRoot.Id);var hidden=await Folder(s);var target=await Folder(s,from.Id);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==hidden.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));
        var hook=new BeforeWrite(async()=>{await using var db=fixture.CreateContext();if(kind=="ownerTerminal"){db.TerminalErasures.Add(new(){ResourceKind="account",ResourceId=s.AccountId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}else{var id=kind=="sourceHidden"?sourceRoot.Id:destinationRoot.Id;await db.Folders.Where(x=>x.Id==id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,kind=="destinationCycle"?to.Id:hidden.Id));}});
        Assert.Equal(error,(await new FolderMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),default)).Error);Assert.Equal(Bytes(target),Bytes(await Row(target.Id)));Assert.Equal(Bytes(from),Bytes(await FolderRow(from.Id)));Assert.Equal(Bytes(to),Bytes(await FolderRow(to.Id)));
    }

    private FolderMoveStore Store()=>new(fixture);
    private Task<VaultResult<FolderMoveDetails>> Move(ProfileSetup.State s,VaultFolder target,Guid? destination,long expected=1)=>Store().MoveAsync(new(s.Actor,s.Verifier,target.PublicId,expected,destination),default);
    private async Task Success(VaultFolder before,VaultFolder? destination,VaultFolder? from,VaultFolder? to,VaultResult<FolderMoveDetails> result)
    {
        Assert.Null(result.Error);var d=Assert.IsType<FolderMoveDetails>(result.Data);Assert.Equal(before.PublicId,d.FolderId);Assert.Equal(destination?.PublicId,d.ParentFolderId);Assert.Equal(before.Revision+1,d.Revision);Assert.True(d.ServerSequence>before.ServerSequence);Assert.InRange(d.ServerSequence,1,ProtocolBinary.MaxInteger);
        var row=await Row(before.Id);Assert.Equal(destination?.Id,row.ParentFolderId);Assert.Equal(before.Envelope,row.Envelope);Assert.Equal(before.EditedAt,row.EditedAt);Assert.Equal(before.AccountId,row.AccountId);Assert.Equal(d.Revision,row.Revision);Assert.Equal(d.ServerSequence,row.ServerSequence);Assert.NotEqual(before.ConcurrencyStamp,row.ConcurrencyStamp);Assert.Null(row.DeletedAt);Assert.Null(row.PurgeAt);
        foreach(var parent in new[]{from,to}.OfType<VaultFolder>().DistinctBy(x=>x.Id)){
            var current=await Row(parent.Id);var changed=before.ParentFolderId!=destination?.Id && (parent.Id==before.ParentFolderId || parent.Id==destination?.Id);Assert.Equal(parent.Revision+(changed?1:0),current.Revision);if(changed){Assert.True(current.ServerSequence>parent.ServerSequence);Assert.InRange(current.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.NotEqual(parent.ConcurrencyStamp,current.ConcurrencyStamp);}else{Assert.Equal(parent.ServerSequence,current.ServerSequence);Assert.Equal(parent.ConcurrencyStamp,current.ConcurrencyStamp);}Assert.Equal(parent.Envelope,current.Envelope);Assert.Equal(parent.EditedAt,current.EditedAt);Assert.Equal(parent.ParentFolderId,current.ParentFolderId);Assert.Equal(parent.PurgeAt,current.PurgeAt);Assert.Equal(parent.DeletedAt,current.DeletedAt);
        }
        await using var db=fixture.CreateContext();Assert.False(await db.TrashEntries.AnyAsync(x=>x.ResourceKind=="folder" && x.ResourceId==before.PublicId));
    }
    private Task<VaultFolder> FolderRow(long id)=>Row(id);
    private async Task<VaultRecord> RecordRow(long id){await using var db=fixture.CreateContext();return await db.Records.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task<string> Stable(ProfileSetup.State s,params long[] ignored){var node=System.Text.Json.Nodes.JsonNode.Parse(await Snapshot(s))!.AsObject();var array=node["Folders"]!.AsArray();foreach(var row in array.ToArray())if(ignored.Contains(row!["Id"]!.GetValue<long>()))array.Remove(row);return node.ToJsonString();}
    private static bool IsWrite(DbCommand c)=>c.CommandText.Contains("UPDATE cerberus.folder AS root");
    private sealed class BeforeWrite:DbCommandInterceptor
    {
        private readonly Func<DbCommand,Task> action;private bool used;
        public BeforeWrite(Func<Task> value):this(_=>value()){}public BeforeWrite(Func<DbCommand,Task> value)=>action=value;
        public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> result,CancellationToken ct=default){if(!used&&IsWrite(c)){used=true;await action(c);}return result;}
    }
    private sealed class BeforeContent(Func<Task> action):DbCommandInterceptor
    {private bool used;private async Task Check(DbCommand c){if(!used&&c.CommandText.Contains("FROM cerberus.folder")&&c.CommandText.Contains("FOR UPDATE")){used=true;await action();}}public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){await Check(c);return r;}public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){await Check(c);return r;}}
    private sealed class BeforeParent(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&c.CommandText.StartsWith("UPDATE cerberus.folder SET")){used=true;await action();}return r;}}
    private sealed class PauseUpdate(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&(c.CommandText.Contains("UPDATE cerberus.folder AS r")||c.CommandText.Contains("UPDATE cerberus.record AS r"))){used=true;await action();}return r;}}
    private sealed class Fail(string stage):DbCommandInterceptor
    {
        public bool Triggered{get;private set;}private bool rootDone;private int parentsDone;
        private void Check(){if(!Triggered&&(stage=="root"&&rootDone||stage=="firstParent"&&parentsDone>=1||stage=="secondParent"&&parentsDone>=2)){Triggered=true;throw new TimeoutException("controlled folder move outage after actual mutation");}}
        public override ValueTask<int> NonQueryExecutedAsync(DbCommand c,CommandExecutedEventData d,int r,CancellationToken ct=default){if(r>0&&IsWrite(c))rootDone=true;if(r>0&&c.CommandText.StartsWith("UPDATE cerberus.folder SET"))parentsDone++;return ValueTask.FromResult(r);}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check();return ValueTask.FromResult(r);}
        public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check();return ValueTask.FromResult(r);}
    }
    private sealed class Signal(TaskCompletionSource reached,string table):DbCommandInterceptor
    {private void Check(DbCommand c){if(c.CommandText.Contains("cerberus."+table)&&c.CommandText.Contains("FOR "))reached.TrySetResult();}public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}}
    private sealed class Capture(PostgresFixture fixture,bool analyze=false):DbCommandInterceptor
    {
        public List<string> Locks{get;}=[];public List<long[]> FolderIds{get;}=[];public List<long[]> RecordIds{get;}=[];public string? Plan{get;private set;}
        private void Note(DbCommand c){if(c.CommandText.Contains("FOR UPDATE")||c.CommandText.Contains("FOR NO KEY UPDATE")||c.CommandText.Contains("FOR SHARE")){Locks.Add(c.CommandText);if(c.CommandText.Contains("FROM cerberus.folder")&&c.CommandText.Contains("FOR UPDATE"))FolderIds.Add(c.Parameters.Cast<NpgsqlParameter>().Select(x=>x.Value).OfType<long[]>().Single());if(c.CommandText.Contains("FROM cerberus.record")&&c.CommandText.Contains("FOR UPDATE"))RecordIds.Add(c.Parameters.Cast<NpgsqlParameter>().Select(x=>x.Value).OfType<long[]>().Single());}}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Note(c);return ValueTask.FromResult(r);}
        public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Note(c);if(analyze&&Plan is null&&c.CommandText.StartsWith("WITH RECURSIVE")){await using var db=fixture.CreateContext();await db.Database.OpenConnectionAsync(ct);await using var cmd=db.Database.GetDbConnection().CreateCommand();cmd.CommandText="EXPLAIN (ANALYZE, FORMAT JSON) "+c.CommandText;foreach(var p in c.Parameters.Cast<NpgsqlParameter>())cmd.Parameters.Add(p.Clone());Plan=(string)(await cmd.ExecuteScalarAsync(ct))!;await System.IO.File.WriteAllTextAsync("/tmp/cerberus-uc28-explain.json",Plan,ct);}return r;}
    }
    private static IEnumerable<JsonElement> Nodes(JsonElement n){yield return n;if(n.TryGetProperty("Plans",out var ps))foreach(var p in ps.EnumerateArray())foreach(var x in Nodes(p))yield return x;}
    private static async Task Past(DateTimeOffset deadline){var delay=deadline-DateTimeOffset.UtcNow;if(delay>TimeSpan.Zero)await Task.Delay(delay+TimeSpan.FromMilliseconds(100));}
    private sealed class ThrowingFactory(Exception exception):IDbContextFactory<AppDbContext>{public AppDbContext CreateDbContext()=>throw exception;public Task<AppDbContext> CreateDbContextAsync(CancellationToken ct=default)=>Task.FromException<AppDbContext>(exception);}

    private async Task<string> Snapshot(ProfileSetup.State s){await using var db=fixture.CreateContext();return JsonSerializer.Serialize(new{Accounts=await db.Accounts.AsNoTracking().Where(x=>x.Id==s.InternalId).ToArrayAsync(),Protection=await db.VaultProtections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId&&p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),CollectionFolders=await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>x.RecipientAccountId==s.InternalId||db.Collections.Any(c=>c.Id==x.CollectionId&&c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Links=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),Members=await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),Operations=await db.TrashOperations.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Entries=await db.TrashEntries.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.Id==x.OperationId&&o.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Queue=await db.RetentionWorkItems.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.AccountId==s.InternalId&&x.OperationKey=="trash/"+o.PublicId)).OrderBy(x=>x.Id).ToArrayAsync(),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<VaultFolder> Row(long id){await using var db=fixture.CreateContext();return await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task<VaultRecord> Record(ProfileSetup.State s,long? folder=null){var row=new VaultRecord{PublicId=Guid.NewGuid(),AccountId=s.InternalId,FolderId=folder,Envelope=Bytes(ProfileSetup.Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.CreateContext();db.Records.Add(row);await db.SaveChangesAsync();return row;}
    private async Task<VaultFolder> Folder(ProfileSetup.State s,long? parent=null){var row=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(ProfileSetup.Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.CreateContext();db.Folders.Add(row);await db.SaveChangesAsync();return row;}
    private async Task<Profile> Profile(ProfileSetup.State s,ProtectionFixture owner,ProtectionFixture scoped,Guid[]? records=null,Guid[]? folders=null,Guid[]? collections=null){var input=ProfileSetup.Input(s,owner,scoped) with{RecordIds=records??[],FolderIds=folders??[],CollectionIds=collections??[]};Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==input.ProfileId);}
    private async Task Members(ProfileSetup.State s,VaultCollection collection,long[] records,long[] folders){await using var db=fixture.CreateContext();db.CollectionRecords.AddRange(records.Select(x=>new CollectionRecord{AccountId=s.InternalId,CollectionId=collection.Id,RecordId=x}));db.CollectionFolders.AddRange(folders.Select(x=>new CollectionFolder{AccountId=s.InternalId,CollectionId=collection.Id,FolderId=x}));await db.SaveChangesAsync();}
    private async Task<string> Selected(ProfileSetup.State s,long profile){var verifier=Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));await using var db=fixture.CreateContext();db.VaultAccessSessions.Add(new(){AccountId=s.InternalId,ProfileId=profile,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return verifier;}
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
    private static byte[] Malformed(byte[] raw,string kind){var s=Encoding.UTF8.GetString(raw);return Encoding.UTF8.GetBytes(kind switch{"numericString"=>s.Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""),"unknown"=>s.Replace("{","{\"secret\":1,"),"duplicate"=>s.Replace("{","{\"keyEpoch\":1,"),_=>s.Replace("\"format\"","\"Format\"")});}
}
