using System.Data.Common;
using System.Security.Cryptography;
using System.Text.Json;
using Npgsql;
using Xunit.Abstractions;
using ArturRios.Cerberus.Data.Records;
using ArturRios.Cerberus.Data.Folders;
using ArturRios.Cerberus.Data.Profiles;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Records;
using ArturRios.Cerberus.Domain.Folders;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.TestSupport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace ArturRios.Cerberus.Data.Tests;

[Collection("PostgreSQL")]
public class FolderListStoreTests(PostgresFixture fixture, ITestOutputHelper output)
{
    [FunctionalFact]
    public async Task GivenForeignTrashAndTerminalRows_WhenPaging_ThenFilterBeforeTakeAndKeepInitialBoundary()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,owner);var trash=await Folder(s);await Folder(foreign);var terminal=await Folder(s);var first=await Folder(s);var second=await Folder(s);
        await using(var db=fixture.CreateContext()){await db.Folders.Where(x=>x.Id==trash.Id).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.DeletedAt,DateTimeOffset.UtcNow));db.TerminalErasures.Add(new(){ResourceId=terminal.PublicId,ResourceKind="folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
        var before=await Snapshot(s);var page=await List(s,1);Assert.Null(page.Error);Assert.Equal(first.PublicId,Assert.Single(page.Data!.Items).FolderId);Assert.True(page.Data.HasMore);Assert.Equal(second.ServerSequence,page.Data.Boundary);Assert.Equal(before,await Snapshot(s));var later=await Folder(s);var next=await List(s,1,first.ServerSequence,page.Data.Boundary);Assert.Null(next.Error);Assert.Equal(second.PublicId,Assert.Single(next.Data!.Items).FolderId);Assert.False(next.Data.HasMore);Assert.DoesNotContain(next.Data.Items,x=>x.FolderId==later.PublicId);Assert.Equal(first.Envelope,page.Data.Items[0].Envelope);
    }
    [FunctionalTheory][InlineData("revoked")][InlineData("wrongRecipient")][InlineData("unknownAccess")][InlineData("zeroRevision")][InlineData("unsafeRevision")][InlineData("grantTerminal")][InlineData("collectionTrash")][InlineData("collectionTerminal")][InlineData("ownerClosing")][InlineData("ownerTerminal")][InlineData("folderTrash")][InlineData("folderTerminal")][InlineData("ancestorTrash")][InlineData("ancestorTerminal")]
    public async Task GivenHiddenSharedAuthorityOrContent_WhenListing_ThenOmitBeforePaginationWithoutNativeInspection(string kind)
    {
        using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var items=await AssociationSetup.Items(fixture,foreign);var included=await Folder(foreign,items.Folder.Id);var grant=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,items.Collection);await Members(foreign,items.Collection,[included.Id],[]);
        await using(var db=fixture.CreateContext()){var g=await db.CollectionGrants.SingleAsync(x=>x.Id==grant.Id);g.RecipientKeyEnvelope="bad"u8.ToArray();if(kind=="revoked")g.State=CollectionGrantState.Revoked;if(kind=="wrongRecipient")g.RecipientAccountId=foreign.InternalId;if(kind=="unknownAccess")g.Access=(CollectionGrantAccess)99;if(kind=="zeroRevision")g.Revision=0;if(kind=="unsafeRevision")g.Revision=ProtocolBinary.MaxInteger+1;if(kind=="collectionTrash")await db.Collections.Where(x=>x.Id==items.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.DeletedAt,DateTimeOffset.UtcNow));if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==foreign.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="folderTrash")await db.Folders.Where(x=>x.Id==included.Id).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.DeletedAt,DateTimeOffset.UtcNow));if(kind=="ancestorTrash")await db.Folders.Where(x=>x.Id==items.Folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.DeletedAt,DateTimeOffset.UtcNow));if(kind.EndsWith("Terminal",StringComparison.Ordinal))db.TerminalErasures.Add(new(){ResourceId=kind=="grantTerminal"?grant.PublicId:kind=="collectionTerminal"?items.Collection.PublicId:kind=="ownerTerminal"?foreign.AccountId:kind=="folderTerminal"?included.PublicId:items.Folder.PublicId,ResourceKind=kind=="grantTerminal"?"grant":kind=="collectionTerminal"?"collection":kind=="ownerTerminal"?"account":kind=="folderTerminal"?"folder":kind=="profileTerminal"?"profile":"folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
        var r=await List(s,1);Assert.Null(r.Error);Assert.Empty(r.Data!.Items);Assert.False(r.Data.HasMore);Assert.Equal(0,r.Data.Boundary);
    }
    [FunctionalTheory][InlineData("blob")][InlineData("signature")][InlineData("owner")][InlineData("collection")][InlineData("grant")][InlineData("recipient")][InlineData("revision")][InlineData("epoch")][InlineData("collectionEnvelope")][InlineData("ownerPins")][InlineData("recipientPins")][InlineData("missingOwnerPins")][InlineData("missingRecipientPins")][InlineData("collectionNumericString")]
    public async Task GivenCorruptRelevantNativeGrant_WhenListing_Then503WithoutPartialContent(string kind)
    {
        using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var items=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,items.Collection);await Members(foreign,items.Collection,[items.Folder.Id],[]);await Folder(s);
        await using(var db=fixture.CreateContext()){var g=await db.CollectionGrants.SingleAsync(x=>x.Id==grant.Id);if(kind=="blob")g.RecipientKeyEnvelope="bad"u8.ToArray();if(kind is "owner" or "collection" or "grant" or "recipient")g.RecipientKeyEnvelope=Bytes(owner.WrapGrant(kind=="owner"?Guid.NewGuid():foreign.AccountId,kind=="collection"?Guid.NewGuid():items.Collection.PublicId,kind=="grant"?Guid.NewGuid():grant.PublicId,kind=="recipient"?Guid.NewGuid():s.Actor,recipient.Material.RecipientKey));if(kind=="signature"){var wrapper=JsonSerializer.Deserialize<RecipientEnvelope>(g.RecipientKeyEnvelope,ProtectionFixture.Json)!;ProtocolBinary.TryDecode(wrapper.Signature,null,out var bytes);bytes[0]^=1;g.RecipientKeyEnvelope=Bytes(wrapper with{Signature=ProtocolBinary.Encode(bytes)});}if(kind=="revision")g.Revision=2;if(kind=="epoch")await db.Collections.Where(x=>x.Id==items.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.KeyEpoch,2));if(kind=="collectionNumericString")await db.Collections.Where(x=>x.Id==items.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Envelope,System.Text.Encoding.UTF8.GetBytes(System.Text.Encoding.UTF8.GetString(items.Collection.Envelope).Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""))));if(kind=="collectionEnvelope")await db.Collections.Where(x=>x.Id==items.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Envelope,"bad"u8.ToArray()));if(kind is "ownerPins" or "recipientPins")await db.VaultProtections.Where(x=>x.AccountId==(kind=="ownerPins"?foreign.InternalId:s.InternalId)).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Material,"bad"u8.ToArray()));if(kind is "missingOwnerPins" or "missingRecipientPins")await db.VaultProtections.Where(x=>x.AccountId==(kind=="missingOwnerPins"?foreign.InternalId:s.InternalId)).ExecuteDeleteAsync();await db.SaveChangesAsync();}
        var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var r=await List(s,1);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));
    }
    [FunctionalFact]
    public async Task GivenUnselectedGrantedCollectionWithCorruptWrapper_WhenListing_ThenDoNotDiscloseOrDenySelectedOwnContent()
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var items=await AssociationSetup.Items(fixture,foreign);var g=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,items.Collection);await Members(foreign,items.Collection,[items.Folder.Id],[]);var visible=await Folder(s);var p=await Profile(s,recipient,scoped,[visible.PublicId]);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));var r=await List(s with{Verifier=await Selected(s,p.Id)});Assert.Null(r.Error);Assert.Equal(visible.PublicId,Assert.Single(r.Data!.Items).FolderId);}
    [FunctionalTheory][InlineData("missing","not_found")][InlineData("closing","not_found")][InlineData("terminal","not_found")][InlineData("access","vault_access_denied")][InlineData("revoked","vault_access_denied")][InlineData("expired","vault_access_denied")][InlineData("future","vault_access_denied")][InlineData("policy","vault_access_denied")][InlineData("generation","vault_access_denied")][InlineData("zeroPolicy","vault_access_denied")][InlineData("zeroGeneration","vault_access_denied")][InlineData("nullExpiry","vault_access_denied")][InlineData("disabledExpiry","vault_access_denied")][InlineData("noExpiry",null)]
    public async Task GivenCurrentAccountOrSessionState_WhenListing_ThenRevalidateWithoutMutation(string kind,string? error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var record=await Folder(s);await using(var db=fixture.CreateContext()){var a=await db.Accounts.SingleAsync(x=>x.Id==s.InternalId);var v=await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==s.Verifier);if(kind=="closing")a.State=AccountState.ClosurePending;if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddSeconds(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="zeroPolicy")v.PolicyRevision=0;if(kind=="zeroGeneration")v.RevocationGeneration=0;if(kind is "noExpiry" or "disabledExpiry")a.RenewalEnabled=false;if(kind is "noExpiry" or "nullExpiry")v.ExpiresAt=null;await db.SaveChangesAsync();}var before=await Snapshot(s);var r=await List(s with{Actor=kind=="missing"?Guid.NewGuid():s.Actor,Verifier=kind=="access"?new string('a',64):s.Verifier});Assert.Equal(error,r.Error);if(error is null)Assert.Equal(record.PublicId,Assert.Single(r.Data!.Items).FolderId);else Assert.Null(r.Data);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("valid",null)][InlineData("dangling","vault_access_denied")][InlineData("foreign","vault_access_denied")][InlineData("trash","vault_access_denied")][InlineData("terminal","vault_access_denied")]
    public async Task GivenSelectedProfileLifecycle_WhenListing_ThenRequireCurrentOwnedActiveSelection(string kind,string? error)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,owner);var own=await Folder(s);var p=await Profile(kind=="foreign"?foreign:s,owner,scoped,kind=="foreign"?[]:[own.PublicId]);var verifier=await Selected(s,kind=="dangling"?long.MaxValue:p.Id);await using(var db=fixture.CreateContext()){if(kind=="trash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.DeletedAt,DateTimeOffset.UtcNow));if(kind=="terminal"){db.TerminalErasures.Add(new(){ResourceId=p.PublicId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}var r=await List(s with{Verifier=verifier});Assert.Equal(error,r.Error);if(error is null)Assert.Equal(own.PublicId,Assert.Single(r.Data!.Items).FolderId);else Assert.Null(r.Data);}
    [FunctionalTheory][InlineData("zero")][InlineData("negative")][InlineData("unsafe")][InlineData("duplicate")]
    public async Task GivenCorruptPermittedOrdering_WhenListing_Then503BeforeKeysetCanHideOrSplitIt(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var first=await Folder(s);var second=await Folder(s);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==second.Id).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.ServerSequence,kind=="zero"?0:kind=="negative"?-1:kind=="unsafe"?ProtocolBinary.MaxInteger+1:first.ServerSequence));var r=await List(s,1);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenCorruptHiddenOrdering_WhenListing_ThenDoNotInspectOutOfScopeOrTrashedRows(bool selected)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,owner);var hidden=await Folder(s);var unrelated=await Folder(foreign);var visible=await Folder(s);var p=await Profile(s,owner,scoped,[visible.PublicId]);await using(var db=fixture.CreateContext()){await db.Folders.Where(x=>x.Id==hidden.Id).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.ServerSequence,0).SetProperty(r=>r.DeletedAt,selected?(DateTimeOffset?)null:DateTimeOffset.UtcNow));await db.Folders.Where(x=>x.Id==unrelated.Id).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.ServerSequence,0));}var r=await List(selected?s with{Verifier=await Selected(s,p.Id)}:s,1);Assert.Null(r.Error);Assert.Equal(visible.PublicId,Assert.Single(r.Data!.Items).FolderId);}
    [FunctionalTheory][InlineData("trash")][InlineData("terminal")]
    public async Task GivenHiddenOwnedAncestor_WhenListingDirectlyLinkedFolder_ThenOmitInconsistentActiveDescendant(string kind)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var hidden=await Folder(s,child.Id);var visible=await Folder(s);var p=await Profile(s,owner,scoped,[hidden.PublicId,visible.PublicId],[root.PublicId]);await using(var db=fixture.CreateContext()){if(kind=="trash")await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.DeletedAt,DateTimeOffset.UtcNow));else{db.TerminalErasures.Add(new(){ResourceId=root.PublicId,ResourceKind="folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}var r=await List(s with{Verifier=await Selected(s,p.Id)});Assert.Null(r.Error);Assert.Equal(visible.PublicId,Assert.Single(r.Data!.Items).FolderId);}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenRelevantCyclicAncestry_WhenListing_Then503WithoutHanging(bool selected)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);await Folder(s,child.Id);var p=await Profile(s,owner,scoped,folders:[root.PublicId]);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.ParentFolderId,child.Id));using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(10));var r=await Store().ListAsync(new(s.Actor,selected?await Selected(s,p.Id):s.Verifier,10,0,null),ct.Token);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);}
    [FunctionalFact]
    public async Task GivenUnrelatedCyclicAncestry_WhenListingSelection_ThenOmitWithoutAvailabilityOracle()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);await Folder(s,root.Id);var visible=await Folder(s);var p=await Profile(s,owner,scoped,[visible.PublicId]);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.ParentFolderId,root.Id));var r=await List(s with{Verifier=await Selected(s,p.Id)});Assert.Null(r.Error);Assert.Equal(visible.PublicId,Assert.Single(r.Data!.Items).FolderId);}
    [FunctionalTheory][InlineData("grant")][InlineData("member")][InlineData("profileCollection")][InlineData("session")]
    public async Task GivenRevocationBetweenPages_WhenContinuing_ThenApplyCurrentPermissionWithoutFillingWithHiddenRows(string kind)
    {
        using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var items=await AssociationSetup.Items(fixture,foreign);var second=await Folder(foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,items.Collection);await Members(foreign,items.Collection,[items.Folder.Id,second.Id],[]);var p=await Profile(s,recipient,scoped,collections:[items.Collection.PublicId]);var selected=s with{Verifier=await Selected(s,p.Id)};var page=(await List(selected,1)).Data!;Assert.True(page.HasMore);
        await using(var db=fixture.CreateContext()){if(kind=="grant")await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));if(kind=="member")await db.CollectionFolders.Where(x=>x.CollectionId==items.Collection.Id && x.FolderId==second.Id).ExecuteDeleteAsync();if(kind=="profileCollection")await db.ProfileCollections.Where(x=>x.ProfileId==p.Id).ExecuteDeleteAsync();if(kind=="session")await db.VaultAccessSessions.Where(x=>x.HandleVerifier==selected.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revoked,true));}
        var r=await List(selected,1,page.Items[0].ServerSequence,page.Boundary);if(kind=="session"){Assert.Equal("vault_access_denied",r.Error);Assert.Null(r.Data);}else{Assert.Null(r.Error);Assert.Empty(r.Data!.Items);Assert.False(r.Data.HasMore);Assert.Equal(page.Boundary,r.Data.Boundary);}
    }
    [FunctionalFact]
    public async Task GivenNativeSharedContent_WhenReading_ThenUseOneSqlSnapshotEvenIfGrantRevokesAfterStatement()
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var items=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,items.Collection);await Members(foreign,items.Collection,[items.Folder.Id],[]);var interceptor=new RevokeAfterRead(fixture,grant.Id);var store=new FolderListStore(new ProfileSetup.Factory(fixture,interceptor));var r=await store.ListAsync(new(s.Actor,s.Verifier,10,0,null),default);Assert.Null(r.Error);Assert.Equal(items.Folder.PublicId,Assert.Single(r.Data!.Items).FolderId);Assert.Equal(1,interceptor.Readers);var next=await List(s);Assert.Null(next.Error);Assert.Empty(next.Data!.Items);}
    [FunctionalFact]
    public async Task GivenExpiryImmediatelyBeforeSql_WhenListing_ThenDatabaseTimeDeniesWithoutMutation()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);await Folder(s);var deadline=DateTimeOffset.UtcNow.AddSeconds(1);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);var r=await new FolderListStore(new ProfileSetup.Factory(fixture,new ExpireBeforeRead(deadline))).ListAsync(new(s.Actor,s.Verifier,10,0,null),default);Assert.Equal("vault_access_denied",r.Error);Assert.Null(r.Data);Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenEmptyInventoryOrMaximumPageSize_WhenListing_ThenReturnFiniteFinalPageWithoutOverflow()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var empty=await List(s);Assert.Null(empty.Error);Assert.Empty(empty.Data!.Items);Assert.Equal(0,empty.Data.Boundary);Assert.False(empty.Data.HasMore);var first=await Folder(s);var r=await List(s,int.MaxValue);Assert.Null(r.Error);Assert.Equal(first.PublicId,Assert.Single(r.Data!.Items).FolderId);Assert.False(r.Data.HasMore);}
    [FunctionalTheory][InlineData("actor","authentication_required")][InlineData("size","validation_failed")][InlineData("after","validation_failed")][InlineData("boundary","validation_failed")]
    public async Task GivenInvalidTrustedRequest_WhenListing_ThenRejectBeforeUnavailableDependency(string kind,string error)
    {var r=new FolderListRequest(kind=="actor"?Guid.Empty:Guid.NewGuid(),new string('a',64),kind=="size"?0:10,kind=="after"?-1:0,kind=="boundary"?-1:null);var dead=new FolderListStore(new ProfileSetup.Factory(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql("Host=127.0.0.1;Port=1;Database=unavailable;Username=none;Timeout=1;Pooling=false").Options));Assert.Equal(error,(await dead.ListAsync(r,default)).Error);}
    [FunctionalFact]
    public async Task GivenUnavailableMembershipTable_WhenListing_Then503AndRestoreDependency()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var before=await Snapshot(s);await using var db=fixture.CreateContext();await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.collection_folder RENAME TO fixture_unavailable_collection_folder");try{var r=await List(s);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);}finally{await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_collection_folder RENAME TO collection_folder");}Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenCancelledCaller_WhenListing_ThenPropagateWithoutChangingState()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var before=await Snapshot(s);using var ct=new CancellationTokenSource();ct.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Store().ListAsync(new(s.Actor,s.Verifier,10,0,null),ct.Token));Assert.Equal(before,await Snapshot(s));}

    [FunctionalTheory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)][InlineData(true,true)]
    public async Task GivenHiddenAncestorAndCycle_WhenListing_ThenOmitBeforeInspectingCorruption(bool selected,bool terminal)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var hidden=await Folder(s,child.Id);var visible=await Folder(s);var p=await Profile(s,owner,scoped,[hidden.PublicId,visible.PublicId],[root.PublicId]);await using(var db=fixture.CreateContext()){await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.ParentFolderId,child.Id).SetProperty(f=>f.DeletedAt,terminal?(DateTimeOffset?)null:DateTimeOffset.UtcNow));if(terminal){db.TerminalErasures.Add(new(){ResourceId=root.PublicId,ResourceKind="folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}var r=await List(selected?s with{Verifier=await Selected(s,p.Id)}:s);Assert.Null(r.Error);Assert.Equal(visible.PublicId,Assert.Single(r.Data!.Items).FolderId);}

    [FunctionalTheory][InlineData(false,true,false)][InlineData(true,true,false)][InlineData(true,false,false)][InlineData(true,true,true)]
    public async Task GivenUnrelatedDeepFolderInventory_WhenListingOnePermittedFolder_ThenDoNotAdmitOrTraverseUnrelatedRows(bool selected,bool foreign,bool shared)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);
        var unrelated=foreign?await ProfileSetup.Create(fixture,owner):s;var visible=await Folder(shared?unrelated:s);Guid[] collections=[];
        if(shared){var resources=await AssociationSetup.Items(fixture,unrelated);await AssociationSetup.Grant(fixture,unrelated,owner,s,owner,resources.Collection);await Members(unrelated,resources.Collection,[visible.Id],[]);collections=[resources.Collection.PublicId];}
        var p=await Profile(s,owner,scoped,shared?[]:[visible.PublicId],collections:collections);
        long? parent=null;for(var depth=0;depth<100;depth++){var folder=await Folder(unrelated,parent);await Folder(unrelated,folder.Id);parent=folder.Id;}
        var capture=new CapturePlan();var store=new FolderListStore(new ProfileSetup.Factory(fixture,capture));
        var result=await store.ListAsync(new(s.Actor,selected?await Selected(s,p.Id):s.Verifier,1,0,null),default);
        Assert.Null(result.Error);Assert.Equal(visible.PublicId,Assert.Single(result.Data!.Items).FolderId);Assert.False(result.Data.HasMore);Assert.Equal(1,capture.Readers);
        await using var db=fixture.CreateContext();await db.Database.OpenConnectionAsync();await using var command=db.Database.GetDbConnection().CreateCommand();
        command.CommandText="EXPLAIN (ANALYZE, FORMAT JSON) "+capture.Sql;foreach(var parameter in capture.Parameters)command.Parameters.Add(parameter.Clone());
        using var plan=JsonDocument.Parse((string)(await command.ExecuteScalarAsync())!);output.WriteLine(plan.RootElement.GetRawText());
        static IEnumerable<JsonElement> Nodes(JsonElement node){yield return node;if(node.TryGetProperty("Plans",out var children))foreach(var child in children.EnumerateArray())foreach(var descendant in Nodes(child))yield return descendant;}
        var nodes=Nodes(plan.RootElement[0].GetProperty("Plan")).ToArray();
        var candidates=Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var name)&&name.GetString()=="CTE candidates");
        var ancestry=Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var name)&&name.GetString()=="CTE ancestry");
        Assert.Equal(1d,candidates.GetProperty("Actual Rows").GetDouble());Assert.Equal(1d,ancestry.GetProperty("Actual Rows").GetDouble());
    }
    private sealed class CapturePlan:DbCommandInterceptor
    {
        public int Readers{get;private set;}public string Sql{get;private set;}="";public NpgsqlParameter[] Parameters{get;private set;}=[];
        public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand command,CommandEventData data,InterceptionResult<DbDataReader> result,CancellationToken ct=default)
        {Readers++;Sql=command.CommandText;Parameters=command.Parameters.Cast<NpgsqlParameter>().Select(x=>x.Clone()).ToArray();return ValueTask.FromResult(result);}
    }


    [FunctionalFact]
    public async Task GivenSelectedDirectAndDescendantFolders_WhenListing_ThenExposeOnlyOwnedSelectionOnce()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var direct=await Folder(s);var outside=await Folder(s);var p=await Profile(s,owner,scoped,[direct.PublicId,child.PublicId],[root.PublicId]);await Profile(s,owner,otherKey,[outside.PublicId]);var selected=s with{Verifier=await Selected(s,p.Id)};var before=await Snapshot(s);var r=await List(selected);Assert.Null(r.Error);Assert.Equal(new[]{root.PublicId,child.PublicId,direct.PublicId}.Order(),r.Data!.Items.Select(x=>x.FolderId).Order());Assert.Equal(3,r.Data.Items.Count);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeMemberRootAndOverlappingLeaf_WhenListing_ThenIncludeOnlyGrantedDescendantsWithoutParentOrSibling(CollectionGrantAccess access,bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var resources=await AssociationSetup.Items(fixture,foreign);var parent=await Folder(foreign);var root=await Folder(foreign,parent.Id);var child=await Folder(foreign,root.Id);var leaf=await Folder(foreign,child.Id);await Folder(foreign,parent.Id);var own=await Folder(s);await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,resources.Collection,access);await Members(foreign,resources.Collection,[root.Id],[child.Id]);var p=await Profile(s,recipient,scoped,collections:[resources.Collection.PublicId]);var request=selected?s with{Verifier=await Selected(s,p.Id)}:s;var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var r=await List(request);Assert.Null(r.Error);Assert.Equal((selected?new[]{root.PublicId,child.PublicId,leaf.PublicId}:new[]{root.PublicId,child.PublicId,leaf.PublicId,own.PublicId}).Order(),r.Data!.Items.Select(x=>x.FolderId).Order());Assert.Equal(leaf.Envelope,r.Data.Items.Single(x=>x.FolderId==leaf.PublicId).Envelope);Assert.DoesNotContain(r.Data.Items,x=>x.FolderId==parent.PublicId||x.FolderId==resources.Folder.PublicId);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalFact]
    public async Task GivenSelectedOwnedCollection_WhenListing_ThenIncludeMemberAndDescendantsWithoutDirectProfileFolders()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var resources=await AssociationSetup.Items(fixture,s);var child=await Folder(s,resources.Folder.Id);await Folder(s);await Members(s,resources.Collection,[],[resources.Folder.Id]);var p=await Profile(s,owner,scoped,collections:[resources.Collection.PublicId]);var r=await List(s with{Verifier=await Selected(s,p.Id)});Assert.Null(r.Error);Assert.Equal(new[]{resources.Folder.PublicId,child.PublicId}.Order(),r.Data!.Items.Select(x=>x.FolderId).Order());}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeRecordOnlyGrant_WhenListingFolders_ThenDoNotExposeContainingFolderOrInspectItsUnusedGrant(CollectionGrantAccess access,bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var resources=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,resources.Collection,access);await using(var db=fixture.CreateContext()){await db.Records.Where(x=>x.Id==resources.Record.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.FolderId,resources.Folder.Id));db.CollectionRecords.Add(new(){AccountId=foreign.InternalId,CollectionId=resources.Collection.Id,RecordId=resources.Record.Id});await db.SaveChangesAsync();}var p=await Profile(s,recipient,scoped,collections:[resources.Collection.PublicId]);var request=selected?s with{Verifier=await Selected(s,p.Id)}:s;var records=await new RecordListStore(fixture).ListAsync(new(request.Actor,request.Verifier,10,0,null),default);Assert.Null(records.Error);Assert.Equal(resources.Record.PublicId,Assert.Single(records.Data!.Items).RecordId);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.RecipientKeyEnvelope,"unused corrupt grant"u8.ToArray()));var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var r=await List(request);Assert.Null(r.Error);Assert.Empty(r.Data!.Items);Assert.Equal(0,r.Data.Boundary);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalFact]
    public async Task GivenSelectedProfileRecordOnly_WhenListingFolders_ThenDoNotWidenToContainingFolder()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var resources=await AssociationSetup.Items(fixture,s);await using(var db=fixture.CreateContext())await db.Records.Where(x=>x.Id==resources.Record.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.FolderId,resources.Folder.Id));var input=ProfileSetup.Input(s,owner,scoped) with{RecordIds=[resources.Record.PublicId],FolderIds=[],CollectionIds=[]};Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);await using var context=fixture.CreateContext();var p=await context.Profiles.SingleAsync(x=>x.PublicId==input.ProfileId);var selected=s with{Verifier=await Selected(s,p.Id)};var records=await new RecordListStore(fixture).ListAsync(new(selected.Actor,selected.Verifier,10,0,null),default);Assert.Equal(resources.Record.PublicId,Assert.Single(records.Data!.Items).RecordId);var before=await Snapshot(s);var r=await List(selected);Assert.Null(r.Error);Assert.Empty(r.Data!.Items);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("record")][InlineData("profile")][InlineData("collection")][InlineData("grant")][InlineData("account")][InlineData("folder")]
    public async Task GivenSameUuidTerminalKind_WhenListing_ThenOnlyFolderMarkerHidesFolder(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceId=folder.PublicId,ResourceKind=kind,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var r=await List(s);Assert.Null(r.Error);Assert.Equal(kind=="folder"?0:1,r.Data!.Items.Count);if(kind!="folder")Assert.Equal(folder.PublicId,Assert.Single(r.Data.Items).FolderId);}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenCorruptOverlappingOrNonpageContributor_WhenListing_Then503BeforeAnyPartialPage(bool nonpage)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);await Folder(s);var first=await AssociationSetup.Items(fixture,foreign);var second=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,first.Collection);var bad=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,second.Collection);await Members(foreign,first.Collection,[],[first.Folder.Id]);await Members(foreign,second.Collection,[],[nonpage?second.Folder.Id:first.Folder.Id]);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var r=await List(s,1);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenSeveralValidContributingGrants_WhenListing_ThenVerifyAllWithSharedAccountPins(bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var ids=new List<Guid>();var folders=new List<Guid>();for(var n=0;n<3;n++){var resources=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,resources.Collection);await Members(foreign,resources.Collection,[],[resources.Folder.Id]);ids.Add(resources.Collection.PublicId);folders.Add(resources.Folder.PublicId);}var p=await Profile(s,recipient,scoped,collections:ids.ToArray());var r=await List(selected?s with{Verifier=await Selected(s,p.Id)}:s);Assert.Null(r.Error);Assert.Equal(folders.Order(),r.Data!.Items.Select(x=>x.FolderId).Order());}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenInternalCancellationOrTimeout_WhenListing_Then503WithoutReadMutation(bool cancellation)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);await Folder(s);var before=await Snapshot(s);var r=await new FolderListStore(new ProfileSetup.Factory(fixture,new FailRead(cancellation))).ListAsync(new(s.Actor,s.Verifier,10,0,null),default);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);Assert.Equal(before,await Snapshot(s));}
    private sealed class FailRead(bool cancellation):DbCommandInterceptor
    {public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData e,InterceptionResult<DbDataReader> result,CancellationToken ct=default){if(cancellation)throw new OperationCanceledException();throw new TimeoutException();}}

    private FolderListStore Store()=>new(fixture);
    private Task<VaultResult<FolderListPage>> List(ProfileSetup.State s,int size=100,long after=0,long? boundary=null)=>Store().ListAsync(new(s.Actor,s.Verifier,size,after,boundary),default);
    private async Task<VaultFolder> Folder(ProfileSetup.State s,long? parent=null){var row=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(ProfileSetup.Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.CreateContext();db.Folders.Add(row);await db.SaveChangesAsync();return row;}
    private async Task<Profile> Profile(ProfileSetup.State s,ProtectionFixture owner,ProtectionFixture scoped,Guid[]? direct=null,Guid[]? folders=null,Guid[]? collections=null){var input=ProfileSetup.Input(s,owner,scoped) with{RecordIds=[],FolderIds=(direct??[]).Concat(folders??[]).Distinct().ToArray(),CollectionIds=collections??[]};Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==input.ProfileId);}
    private async Task Members(ProfileSetup.State s,VaultCollection collection,long[] direct,long[] folders){await using var db=fixture.CreateContext();db.CollectionFolders.AddRange(direct.Concat(folders).Distinct().Select(x=>new CollectionFolder{AccountId=s.InternalId,CollectionId=collection.Id,FolderId=x}));await db.SaveChangesAsync();}
    private async Task<string> Selected(ProfileSetup.State s,long profile){var verifier=Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));await using var db=fixture.CreateContext();db.VaultAccessSessions.Add(new(){AccountId=s.InternalId,ProfileId=profile,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return verifier;}
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
    private async Task<string> Snapshot(ProfileSetup.State s){await using var db=fixture.CreateContext();return JsonSerializer.Serialize(new{Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Protection=await db.VaultProtections.AsNoTracking().SingleOrDefaultAsync(x=>x.AccountId==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId && p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),CollectionRecords=await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),CollectionFolders=await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>x.RecipientAccountId==s.InternalId || db.Collections.Any(c=>c.Id==x.CollectionId && c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync()});}
    private sealed class RevokeAfterRead(PostgresFixture fixture,long grant):DbCommandInterceptor
    {public int Readers{get;private set;}public override async ValueTask<DbDataReader> ReaderExecutedAsync(DbCommand c,CommandExecutedEventData e,DbDataReader reader,CancellationToken ct=default){Readers++;if(Readers==1){await using var db=fixture.CreateContext();await db.CollectionGrants.Where(x=>x.Id==grant).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked),ct);}return reader;}}
    private sealed class ExpireBeforeRead(DateTimeOffset deadline):DbCommandInterceptor
    {public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData e,InterceptionResult<DbDataReader> result,CancellationToken ct=default){var wait=deadline-DateTimeOffset.UtcNow;if(wait>TimeSpan.Zero)await Task.Delay(wait+TimeSpan.FromMilliseconds(100),ct);return result;}}
}
