using System.Data.Common;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using ArturRios.Cerberus.Data.Profiles;
using ArturRios.Cerberus.Data.Protection;
using ArturRios.Cerberus.Data.Records;
using ArturRios.Cerberus.Data.Folders;
using ArturRios.Cerberus.Domain.Folders;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Records;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Domain.Trash;
using ArturRios.Cerberus.TestSupport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Npgsql;
namespace ArturRios.Cerberus.Data.Tests;

[Collection("PostgreSQL")]
public class FolderTrashStoreTests(PostgresFixture fixture)
{
    [FunctionalTheory][InlineData("wide")][InlineData("direct")][InlineData("ancestor")][InlineData("collection")][InlineData("collectionAncestor")]
    public async Task GivenCurrentOwnedFolderScope_WhenTrashing_ThenOneRetainedCascadeAndUnchangedHandle(string route)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);
        if(route.StartsWith("collection"))await Members(s,a.Collection,[],[route=="collection"?root.Id:a.Folder.Id]);
        if(route!="wide"){var p=await Profile(s,owner,key,folders:route=="direct"?[root.PublicId]:route=="ancestor"?[a.Folder.PublicId]:[],collections:route.StartsWith("collection")?[a.Collection.PublicId]:[]);s=s with{Verifier=await Selected(s,p.Id)};}
        var result=await Trash(s,root);await Success(s,root,[root,child],[record],result);await using var db=fixture.CreateContext();Assert.False((await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==s.Verifier)).Revoked);Assert.Null((await db.Folders.SingleAsync(x=>x.Id==a.Folder.Id)).DeletedAt);
        Assert.Equal("not_found",(await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,child.PublicId),default)).Error);Assert.Equal("not_found",(await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);
    }
    [FunctionalFact]
    public async Task GivenDeepCascadeWithOverlappingInactiveLinksAndRecipient_WhenTrashing_ThenSnapshotEveryMemberAndBumpEachActiveExternalParentOnce()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();using var key2=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);var child=await Folder(s,root.Id);var leaf=await Folder(s,child.Id);var r1=await Record(s,root.Id);var r2=await Record(s,leaf.Id);var p=await Profile(s,owner,key,records:[r1.PublicId,r2.PublicId],folders:[root.PublicId,child.PublicId]);var inactive=await Profile(s,owner,key2,records:[r2.PublicId],folders:[leaf.PublicId]);var b=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[r1.Id,r2.Id],[root.Id,leaf.Id]);await Members(s,b.Collection,[r2.Id],[child.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection,CollectionGrantAccess.ReadWrite);
        await using(var db=fixture.CreateContext()){await db.Profiles.Where(x=>x.Id==inactive.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));await db.Collections.Where(x=>x.Id==b.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));}
        p=await ProfileRow(p.Id);inactive=await ProfileRow(inactive.Id);var parent=await Row(a.Folder.Id);var other=Bytes(a.Record);var recipientBefore=await Snapshot(recipient);var result=await Trash(s,root);await Success(s,root,[root,child,leaf],[r1,r2],result);
        await using(var db=fixture.CreateContext()){
            var nowP=await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id);Assert.Equal(p.Revision+1,nowP.Revision);Assert.True(nowP.ServerSequence>p.ServerSequence);Assert.Equal(p.Envelope,nowP.Envelope);Assert.Equal(p.KeyWrappers,nowP.KeyWrappers);Assert.Equal(p.EditedAt,nowP.EditedAt);Assert.Equal(Bytes(inactive),Bytes(await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==inactive.Id)));
            var nowC=await db.Collections.AsNoTracking().SingleAsync(x=>x.Id==a.Collection.Id);Assert.Equal(a.Collection.Revision+1,nowC.Revision);Assert.True(nowC.ServerSequence>a.Collection.ServerSequence);Assert.Equal(a.Collection.Envelope,nowC.Envelope);Assert.Equal(a.Collection.KeyEpoch,nowC.KeyEpoch);Assert.Equal(b.Collection.Revision,(await db.Collections.SingleAsync(x=>x.Id==b.Collection.Id)).Revision);
            var nowParent=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==parent.Id);Assert.Equal(parent.Revision+1,nowParent.Revision);Assert.Equal(parent.Envelope,nowParent.Envelope);Assert.Equal(parent.EditedAt,nowParent.EditedAt);Assert.Equal(other,Bytes(await db.Records.AsNoTracking().SingleAsync(x=>x.Id==a.Record.Id)));
            var fs=JsonSerializer.Deserialize<FolderAssociationSnapshot>((await db.TrashEntries.SingleAsync(x=>x.ResourceKind=="folder"&&x.ResourceId==leaf.PublicId)).AssociationSnapshot,ProtectionFixture.Json)!;Assert.Equal(child.PublicId,fs.ParentFolderId);Assert.Equal(new[]{inactive.PublicId},fs.ProfileIds);Assert.Equal(new[]{a.Collection.PublicId},fs.CollectionIds);
            var rs=JsonSerializer.Deserialize<RecordAssociationSnapshot>((await db.TrashEntries.SingleAsync(x=>x.ResourceKind=="record"&&x.ResourceId==r2.PublicId)).AssociationSnapshot,ProtectionFixture.Json)!;Assert.Equal(leaf.PublicId,rs.FolderId);Assert.Equal(new[]{p.PublicId,inactive.PublicId}.Order(),rs.ProfileIds);Assert.Equal(new[]{a.Collection.PublicId,b.Collection.PublicId}.Order(),rs.CollectionIds);
            Assert.True(await db.CollectionGrants.AnyAsync(x=>x.CollectionId==a.Collection.Id&&x.State==CollectionGrantState.Active));
        }
        Assert.Equal(recipientBefore,await Snapshot(recipient));Assert.Equal("not_found",(await new FolderReadStore(fixture).ReadAsync(new(recipient.Actor,recipient.Verifier,leaf.PublicId),default)).Error);Assert.Equal("not_found",(await new RecordReadStore(fixture).ReadAsync(new(recipient.Actor,recipient.Verifier,r2.PublicId),default)).Error);
    }
    [FunctionalFact]
    public async Task GivenActualIndependentRecordAndFolderTrash_WhenLaterTrashingRoot_ThenPreserveEarlierOperationsAndDeadlines()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var independent=await Folder(s,root.Id);var previousRecord=await Record(s,root.Id);var previousChildRecord=await Record(s,independent.Id);var child=await Folder(s,root.Id);var activeRecord=await Record(s,child.Id);
        var first=await new RecordTrashStore(fixture).TrashAsync(new(s.Actor,s.Verifier,previousRecord.PublicId,1),default);Assert.Null(first.Error);var second=await Trash(s,independent);await Success(s,independent,[independent],[previousChildRecord],second);root=await Row(root.Id);var oldFolder=Bytes(await Row(independent.Id));var oldRecord=Bytes(await RecordRow(previousRecord.Id));var oldChildRecord=Bytes(await RecordRow(previousChildRecord.Id));
        await using var db=fixture.CreateContext();var oldOps=Bytes(await db.TrashOperations.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync());var oldEntries=Bytes(await db.TrashEntries.AsNoTracking().Where(x=>x.ResourceId==previousRecord.PublicId||x.ResourceId==independent.PublicId||x.ResourceId==previousChildRecord.PublicId).OrderBy(x=>x.Id).ToArrayAsync());await Success(s,root,[root,child],[activeRecord],await Trash(s,root,root.Revision));
        Assert.Equal(oldFolder,Bytes(await Row(independent.Id)));Assert.Equal(oldRecord,Bytes(await RecordRow(previousRecord.Id)));Assert.Equal(oldChildRecord,Bytes(await RecordRow(previousChildRecord.Id)));Assert.Equal(oldEntries,Bytes(await db.TrashEntries.AsNoTracking().Where(x=>x.ResourceId==previousRecord.PublicId||x.ResourceId==independent.PublicId||x.ResourceId==previousChildRecord.PublicId).OrderBy(x=>x.Id).ToArrayAsync()));Assert.Equal(oldOps,Bytes(await db.TrashOperations.AsNoTracking().Where(x=>x.PublicId==first.Data!.TrashOperationId||x.PublicId==second.Data!.TrashOperationId).OrderBy(x=>x.Id).ToArrayAsync()));
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenActualNativeVisibleForeignFolder_WhenDeletingStaleDamagedTarget_Then403AndNoGraphMutation(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var target=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,access);if(selected){var p=await Profile(s,client,key,collections:[a.Collection.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};}
        Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,target.PublicId),default)).Error);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged"u8.ToArray()));var before=await Snapshot(o);var recipient=await Snapshot(s);Assert.Equal("vault_access_denied",(await Trash(s,target,99)).Error);Assert.Equal(before,await Snapshot(o));Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenActualNativeRecordOnlyMembership_WhenDeletingItsContainingFolder_Then404AfterSuccessfulRecordRead(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var record=await Record(o,a.Folder.Id);await Members(o,a.Collection,[record.Id],[]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,access);if(selected){var p=await Profile(s,client,key,collections:[a.Collection.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};}
        Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);var before=await Snapshot(o);Assert.Equal("not_found",(await Trash(s,a.Folder,99)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalFact]
    public async Task GivenSelectedDirectRecordWithoutFolderMembership_WhenDeletingContainer_Then404AfterSuccessfulRecordRead()
    {using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var record=await Record(s,folder.Id);var p=await Profile(s,owner,key,records:[record.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};Assert.Null((await new RecordReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,record.PublicId),default)).Error);var before=await Snapshot(s);Assert.Equal("not_found",(await Trash(s,folder,99)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("missing","not_found")][InlineData("closing","not_found")][InlineData("terminal","not_found")][InlineData("access","vault_access_denied")][InlineData("revoked","vault_access_denied")][InlineData("expired","vault_access_denied")][InlineData("future","vault_access_denied")][InlineData("policy","vault_access_denied")][InlineData("generation","vault_access_denied")][InlineData("zeroPolicy","vault_access_denied")][InlineData("zeroGeneration","vault_access_denied")][InlineData("nullExpiry","vault_access_denied")][InlineData("disabledExpiry","vault_access_denied")][InlineData("noExpiry",null)][InlineData("selection","vault_access_denied")]
    public async Task GivenInvalidCurrentAuthority_WhenTrashing_ThenFailClosed(string kind,string? error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);await using(var db=fixture.CreateContext()){var a=await db.Accounts.SingleAsync(x=>x.Id==s.InternalId);var v=await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==s.Verifier);if(kind=="closing")a.State=AccountState.ClosurePending;if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="zeroPolicy")v.PolicyRevision=0;if(kind=="zeroGeneration")v.RevocationGeneration=0;if(kind is "noExpiry" or "disabledExpiry")a.RenewalEnabled=false;if(kind is "nullExpiry" or "noExpiry")v.ExpiresAt=null;if(kind=="selection")v.ProfileId=long.MaxValue;await db.SaveChangesAsync();}
        var before=await Snapshot(s);var r=await Store().TrashAsync(new(kind=="missing"?Guid.NewGuid():s.Actor,kind=="access"?new string('a',64):s.Verifier,target.PublicId,1),default);Assert.Equal(error,r.Error);if(error is null)await Success(s,target,[target],[],r);else Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("actor","authentication_required")][InlineData("id","validation_failed")][InlineData("zero","validation_failed")][InlineData("unsafe","validation_failed")]
    public async Task GivenInvalidInternalRequest_WhenTrashing_ThenRejectWithoutWrite(string kind,string error)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var before=await Snapshot(s);var r=await Store().TrashAsync(new(kind=="actor"?Guid.Empty:s.Actor,s.Verifier,kind=="id"?Guid.Empty:target.PublicId,kind=="zero"?0:kind=="unsafe"?ProtocolBinary.MaxInteger+1:1),default);Assert.Equal(error,r.Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("self",false)][InlineData("long",false)][InlineData("self",true)]
    public async Task GivenRelevantCyclicOrHiddenAncestry_WhenTrashing_ThenBounded503OrHidden404(string kind,bool hidden)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var target=await Folder(s,root.Id);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,(long?)(kind=="self"?root.Id:target.Id)).SetProperty(v=>v.DeletedAt,hidden?(DateTimeOffset?)DateTimeOffset.UtcNow:null));var before=await Snapshot(s);Assert.Equal(hidden?"not_found":"persistence_unavailable",(await Trash(s,target)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("account")][InlineData("profile")][InlineData("record")][InlineData("folder")][InlineData("collection")][InlineData("grant")]
    public async Task GivenTerminalAliasWithDifferentKind_WhenDeletingFolder_ThenOnlyMatchingFolderKindHidesIt(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceKind=kind,ResourceId=target.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);var r=await Trash(s,target);if(kind=="folder"){Assert.Equal("not_found",r.Error);Assert.Equal(before,await Snapshot(s));}else await Success(s,target,[target],[],r);}
    [FunctionalTheory][InlineData("folder","zeroRevision","persistence_unavailable")][InlineData("folder","zeroSequence","persistence_unavailable")][InlineData("folder","maxRevision","revision_conflict")][InlineData("folder","purge","persistence_unavailable")][InlineData("folder","oldEntry","revision_conflict")][InlineData("child","zeroRevision","persistence_unavailable")][InlineData("child","unsafeSequence","persistence_unavailable")][InlineData("child","maxRevision","revision_conflict")][InlineData("child","purge","persistence_unavailable")][InlineData("child","oldEntry","revision_conflict")][InlineData("record","zeroRevision","persistence_unavailable")][InlineData("record","zeroSequence","persistence_unavailable")][InlineData("record","maxRevision","revision_conflict")][InlineData("record","purge","persistence_unavailable")][InlineData("record","oldEntry","revision_conflict")]
    public async Task GivenCorruptOrConflictingCascadeMember_WhenTrashing_ThenNoPartialOperation(string member,string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var id=member=="folder"?root.PublicId:member=="child"?child.PublicId:record.PublicId;await using(var db=fixture.CreateContext()){
            if(member=="record"){var r=await db.Records.SingleAsync(x=>x.Id==record.Id);if(kind=="zeroRevision")r.Revision=0;if(kind=="zeroSequence")r.ServerSequence=0;if(kind=="maxRevision")r.Revision=ProtocolBinary.MaxInteger;if(kind=="purge")r.PurgeAt=DateTimeOffset.UtcNow.AddDays(30);}
            else{var f=await db.Folders.SingleAsync(x=>x.PublicId==id);if(kind=="zeroRevision")f.Revision=0;if(kind=="zeroSequence")f.ServerSequence=0;if(kind=="unsafeSequence")f.ServerSequence=ProtocolBinary.MaxInteger+1;if(kind=="maxRevision")f.Revision=ProtocolBinary.MaxInteger;if(kind=="purge")f.PurgeAt=DateTimeOffset.UtcNow.AddDays(30);}
            if(kind=="oldEntry"){var op=new TrashOperation{AccountId=s.InternalId,RootResourceKind=member=="record"?"record":"folder",RootResourceId=id,DeletedAt=DateTimeOffset.UtcNow,PurgeAt=DateTimeOffset.UtcNow.AddDays(30)};db.TrashOperations.Add(op);await db.SaveChangesAsync();db.TrashEntries.Add(new(){OperationId=op.Id,ResourceKind=op.RootResourceKind,ResourceId=id,AssociationSnapshot="{}"u8.ToArray()});}await db.SaveChangesAsync();}
        var before=await Snapshot(s);Assert.Equal(error,(await Trash(s,root,member=="folder"&&kind=="maxRevision"?ProtocolBinary.MaxInteger:1)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenDamagedOwnedCascadeCipher_WhenTrashing_ThenRetainOpaqueBytesWithoutParsing()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);await using(var db=fixture.CreateContext()){await db.Folders.Where(x=>x.Id==root.Id||x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged-folder"u8.ToArray()));await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"damaged-record"u8.ToArray()));}root=await Row(root.Id);child=await Row(child.Id);record=await RecordRow(record.Id);await Success(s,root,[root,child],[record],await Trash(s,root));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenConcurrentTrashOrLostSuccessRetry_WhenDeleting_ThenExactlyOneOperationAndUnchangedDeadline(bool concurrent)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var results=concurrent?await Task.WhenAll(Trash(s,root),Trash(s,root)):new[]{await Trash(s,root),await Trash(s,root)};await Success(s,root,[root,child],[record],Assert.Single(results,x=>x.Error is null));Assert.Equal("not_found",Assert.Single(results,x=>x.Error is not null).Error);var before=await Snapshot(s);Assert.Equal("not_found",(await Trash(s,root)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenStaleRootRevision_WhenDeleting_ThenConflictPreservesCompleteGraph()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);await Folder(s,root.Id);var before=await Snapshot(s);Assert.Equal("revision_conflict",(await Trash(s,root,2)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("missing")][InlineData("foreign")][InlineData("unselected")][InlineData("trash")][InlineData("folderTerminal")][InlineData("ancestorTrash")][InlineData("ancestorTerminal")][InlineData("ownerClosing")][InlineData("ownerTerminal")][InlineData("grantRevoked")][InlineData("collectionTrash")][InlineData("removedMembership")]
    public async Task GivenHiddenTargetWithBadNativeAndStaleRevision_WhenTrashing_Then404BeforeDisclosure(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=kind=="unselected"?o:await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var target=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[target.Id]);CollectionGrant? g=null;if(kind!="foreign" && s.InternalId!=o.InternalId)g=await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);if(kind=="unselected"){var p=await Profile(s,owner,scoped);s=s with{Verifier=await Selected(s,p.Id)};}
        await using(var db=fixture.CreateContext()){
            await db.Folders.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"bad"u8.ToArray()));
            if(g is not null)await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));
            if(kind=="trash")await db.Folders.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="ancestorTrash")await db.Folders.Where(x=>x.Id==a.Folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));
            if(kind.EndsWith("Terminal")){var id=kind=="folderTerminal"?target.PublicId:kind=="ancestorTerminal"?a.Folder.PublicId:o.AccountId;db.TerminalErasures.Add(new(){ResourceId=id,ResourceKind=kind=="folderTerminal"?"folder":kind=="ancestorTerminal"?"folder":"account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
            if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==o.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,AccountState.ClosurePending));if(kind=="grantRevoked")await db.CollectionGrants.Where(x=>x.Id==g!.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,CollectionGrantState.Revoked));if(kind=="collectionTrash")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="removedMembership")await db.CollectionFolders.Where(x=>x.FolderId==target.Id).ExecuteDeleteAsync();
        }
        var before=await Snapshot(o);Assert.Equal("not_found",(await Store().TrashAsync(new(s.Actor,s.Verifier,kind=="missing"?Guid.NewGuid():target.PublicId,99),default)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("signature")][InlineData("revision")][InlineData("epoch")][InlineData("numericString")][InlineData("unknown")][InlineData("duplicate")][InlineData("ownerPins")][InlineData("recipientPins")]
    public async Task GivenMalformedContributingNativeAuthority_WhenNonownerRequestsTrash_Then503WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[],[a.Folder.Id]);var g=await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);await using(var db=fixture.CreateContext()){
            if(kind=="signature")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind=="revision")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,2));if(kind=="epoch")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.KeyEpoch,2));if(kind is "numericString" or "unknown" or "duplicate")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,Malformed(a.Collection.Envelope,kind)));if(kind is "ownerPins" or "recipientPins")await db.VaultProtections.Where(x=>x.AccountId==(kind=="ownerPins"?o.InternalId:s.InternalId)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,"bad"u8.ToArray()));}
        var before=await Snapshot(o);Assert.Equal("persistence_unavailable",(await Trash(s,a.Folder,99)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("foreign")][InlineData("trash")][InlineData("terminal")]
    public async Task GivenInvalidSelectedProfile_WhenTrashingOwnedFolder_ThenDenyWithoutBroadening(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=await Folder(s);var other=kind=="foreign"?await ProfileSetup.Create(fixture,owner):s;var p=await Profile(other,owner,scoped);s=s with{Verifier=await Selected(s,p.Id)};await using(var db=fixture.CreateContext()){if(kind=="trash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="terminal"){db.TerminalErasures.Add(new(){ResourceId=p.PublicId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}var before=await Snapshot(s);Assert.Equal("vault_access_denied",(await Trash(s,target)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenOverlappingNativeAuthorityWithMalformedContributor_WhenNonownerDeletes_ThenWholeDenialFailsClosed(bool invalidReadWrite)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var b=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[],[a.Folder.Id]);await Members(o,b.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,invalidReadWrite?CollectionGrantAccess.ReadOnly:CollectionGrantAccess.ReadWrite);var bad=await AssociationSetup.Grant(fixture,o,owner,s,client,b.Collection,invalidReadWrite?CollectionGrantAccess.ReadWrite:CollectionGrantAccess.ReadOnly);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(o);Assert.Equal("persistence_unavailable",(await Trash(s,a.Folder)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("account")][InlineData("session")][InlineData("profile")][InlineData("collection")][InlineData("folder")][InlineData("record")]
    public async Task GivenNaturalExpiryDuringEachCascadeLockWait_WhenDeleting_Then403BeforeStaleRevisionAndNoMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s);var record=await Record(s,root.Id);await Members(s,a.Collection,[record.Id],[root.Id]);var p=await Profile(s,owner,key,folders:[root.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);
        await using var held=fixture.CreateContext();await using var tx=await held.Database.BeginTransactionAsync();var id=kind switch{"account"=>s.InternalId,"profile"=>p.Id,"collection"=>a.Collection.Id,"folder"=>root.Id,_=>record.Id};var table=kind=="session"?"vault_access_session":kind;await held.Database.ExecuteSqlRawAsync(kind=="session"?"SELECT FROM cerberus.vault_access_session WHERE handle_verifier={0} FOR UPDATE":"SELECT FROM cerberus."+table+" WHERE id={0} FOR UPDATE",kind=="session"?(object)s.Verifier:id);
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var pending=new FolderTrashStore(new ProfileSetup.Factory(fixture,new Signal(reached,table))).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,99),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);await Past(deadline);await tx.CommitAsync();Assert.Equal("vault_access_denied",(await pending).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("expiry","vault_access_denied")][InlineData("folderTerminal","not_found")][InlineData("actorTerminal","not_found")]
    public async Task GivenChangeImmediatelyBeforeRootGuard_WhenDeleting_ThenDenyWithoutPartialCascade(string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var deadline=DateTimeOffset.UtcNow.AddSeconds(2);if(kind=="expiry")await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);var hook=new BeforeRoot(async()=>{if(kind=="expiry"){await Past(deadline);return;}await using var db=fixture.CreateContext();db.TerminalErasures.Add(new(){ResourceKind=kind=="folderTerminal"?"folder":"account",ResourceId=kind=="folderTerminal"?root.PublicId:s.AccountId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();});Assert.Equal(error,(await new FolderTrashStore(new ProfileSetup.Factory(fixture,hook)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("folder")][InlineData("record")][InlineData("profile")][InlineData("collection")]
    public async Task GivenUncapturedExistingItemOrAssociationBeforeContentLock_WhenDeleting_Then409PreservesNewInventory(string kind)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var outside=await Folder(s);var record=await Record(s);var p=await Profile(s,owner,key);var a=await AssociationSetup.Items(fixture,s);string? winning=null;var hook=new BeforeContent(async()=>{await using var db=fixture.CreateContext();if(kind=="folder")await db.Folders.Where(x=>x.Id==outside.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,(long?)root.Id));else if(kind=="record")await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.FolderId,(long?)root.Id));else{if(kind=="profile")db.ProfileFolders.Add(new(){AccountId=s.InternalId,ProfileId=p.Id,FolderId=root.Id});else db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=a.Collection.Id,FolderId=root.Id});await db.SaveChangesAsync();}winning=await Snapshot(s);});Assert.Equal("revision_conflict",(await new FolderTrashStore(new ProfileSetup.Factory(fixture,hook)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.NotNull(winning);Assert.Equal(winning,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("root")][InlineData("child")][InlineData("record")][InlineData("links")][InlineData("parent")][InlineData("operation")][InlineData("entry")][InlineData("queue")]
    public async Task GivenFaultAfterPartialCascadeWork_WhenDeleting_ThenRollbackEveryMemberAndRetrySucceeds(string stage)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);await Members(s,a.Collection,[record.Id],[root.Id]);await Profile(s,owner,key,folders:[root.PublicId],records:[record.PublicId]);var before=await Snapshot(s);var fail=new Fail(stage);Assert.Equal("persistence_unavailable",(await new FolderTrashStore(new ProfileSetup.Factory(fixture,fail)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.True(fail.Triggered);Assert.Equal(before,await Snapshot(s));await Success(s,root,[root,child],[record],await Trash(s,root));
    }
    [FunctionalTheory][InlineData("root",false)][InlineData("root",true)][InlineData("child",false)][InlineData("child",true)][InlineData("parent",false)][InlineData("parent",true)]
    public async Task GivenExhaustedOrRegressedSequenceAtDifferentCascadeStages_WhenDeleting_ThenRollbackAllContent(string stage,bool regression)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);await Folder(s,root.Id);await Profile(s,owner,key,folders:[root.PublicId]);var before=await Snapshot(s);await using var db=fixture.CreateContext();var previous=await db.Database.SqlQuery<long>($"SELECT nextval('cerberus.server_sequence') AS \"Value\"").SingleAsync();var hook=new AtWrite(stage,async()=>{await using var other=fixture.CreateContext();await other.Database.ExecuteSqlRawAsync(regression?"SELECT setval('cerberus.server_sequence',1,false)":"SELECT setval('cerberus.server_sequence',9007199254740991,true)");});try{Assert.Equal(regression?"persistence_unavailable":"revision_conflict",(await new FolderTrashStore(new ProfileSetup.Factory(fixture,hook)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default)).Error);Assert.True(hook.Triggered);Assert.Equal(before,await Snapshot(s));}finally{await db.Database.ExecuteSqlInterpolatedAsync($"SELECT setval('cerberus.server_sequence',{previous},true)");}
    }
    [FunctionalTheory][InlineData("folder",false)][InlineData("folder",true)][InlineData("record",false)][InlineData("record",true)]
    public async Task GivenActualRecipientContentEditAndOwnerCascade_WhenCompeting_ThenOneWinnerWithoutCollectionContentLockCycle(string resource,bool trashFirst)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var root=await Folder(o);var record=await Record(o,root.Id);await Members(o,a.Collection,[],[root.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));Task<VaultResult<FolderTrashDetails>> trash;Task<string?> edit;
        async Task<string?> Edit(IDbContextFactory<AppDbContext> f){return resource=="folder"?(await new FolderUpdateStore(f).UpdateAsync(new(s.Actor,s.Verifier,root.PublicId,new(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch)),ct.Token)).Error:(await new RecordUpdateStore(f).UpdateAsync(new(s.Actor,s.Verifier,record.PublicId,new(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch)),ct.Token)).Error;}
        if(trashFirst){trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new BeforeContent(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(o.Actor,o.Verifier,root.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));edit=Edit(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection")));}
        else{edit=Edit(new ProfileSetup.Factory(fixture,new PauseUpdate(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);})));await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection"))).TrashAsync(new(o.Actor,o.Verifier,root.PublicId,1),ct.Token);}
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(trashFirst?edit.IsCompleted:trash.IsCompleted);}finally{release.TrySetResult();}await Task.WhenAll(trash,edit);
        if(trashFirst){Assert.Null(trash.Result.Error);Assert.Equal("not_found",edit.Result);}else{Assert.Null(edit.Result);Assert.Equal("revision_conflict",trash.Result.Error);await using var db=fixture.CreateContext();Assert.False(await db.TrashOperations.AnyAsync(x=>x.AccountId==o.InternalId));Assert.Null((await Row(root.Id)).DeletedAt);Assert.Equal(2,resource=="folder"?(await Row(root.Id)).Revision:(await RecordRow(record.Id)).Revision);}
    }
    [FunctionalTheory][InlineData("folderCreate")][InlineData("recordCreate")][InlineData("recordMove")][InlineData("association")]
    public async Task GivenCascadeOwnsAccountBeforeContentLocks_WhenActualOwnerWriterStarts_ThenSerializeWithoutDeadlock(string writer)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var outside=await Record(s);var p=await Profile(s,owner,key,folders:[root.PublicId]);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));var trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new BeforeContent(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var f=new ProfileSetup.Factory(fixture,new Signal(blocked,"account"));
        async Task<string?> Write()=>writer switch{"folderCreate"=>(await new FolderCreateStore(f).CreateAsync(new(s.Actor,s.Verifier,new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],root.PublicId)),ct.Token)).Error,"recordCreate"=>(await new RecordCreateStore(f).CreateAsync(new(s.Actor,s.Verifier,new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],root.PublicId)),ct.Token)).Error,"recordMove"=>(await new RecordMoveStore(f).MoveAsync(new(s.Actor,s.Verifier,outside.PublicId,1,root.PublicId),ct.Token)).Error,_=>(await new ProfileAssociationStore(f).SetAsync(new(s.Actor,s.Verifier,p.PublicId,new(p.Revision,[],[],[])),ct.Token)).Error};
        var pending=Write();try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);}finally{release.TrySetResult();}Assert.Null((await trash).Error);Assert.Equal(writer=="association"?"revision_conflict":"not_found",await pending);Assert.Equal(Bytes(outside),Bytes(await RecordRow(outside.Id)));
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenRetainedFolderCascade_WhenNativeRotatingProtection_ThenRequireCompleteRetainedInventoryAndPreserveTrash(bool omit)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var trash=await Trash(s,root);Assert.Null(trash.Error);var all=new[]{new ContentReplacement("account",s.AccountId,1,ProfileSetup.Envelope(2)),new ContentReplacement("folder",root.PublicId,2,ProfileSetup.Envelope(2)),new ContentReplacement("folder",child.PublicId,2,ProfileSetup.Envelope(2)),new ContentReplacement("record",record.PublicId,2,ProfileSetup.Envelope(2))};var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),omit?all[..3]:all);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;var result=await new VaultProtectionChangeStore(fixture).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),default);Assert.Equal(omit?"validation_failed":null,result.Error);
        await using var db=fixture.CreateContext();foreach(var id in new[]{root.Id,child.Id}){var row=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==id);Assert.Equal(trash.Data!.DeletedAt,row.DeletedAt);Assert.Equal(trash.Data.PurgeAt,row.PurgeAt);Assert.Equal(omit?2:3,row.Revision);}var rr=await RecordRow(record.Id);Assert.Equal(trash.Data!.PurgeAt,rr.PurgeAt);Assert.Equal(omit?2:3,rr.Revision);Assert.Equal(3,await db.TrashEntries.CountAsync(x=>x.OperationId==db.TrashOperations.Single(o=>o.PublicId==trash.Data.TrashOperationId).Id));
    }
    [FunctionalTheory][InlineData("cancel")][InlineData("timeout")][InlineData("db")][InlineData("dbUpdate")][InlineData("json")][InlineData("format")][InlineData("wrapped")]
    public async Task GivenNecessaryProviderFailure_WhenDeleting_Then503WithNoLeakedException(string kind)
    {Exception e=kind switch{"cancel"=>new OperationCanceledException(),"timeout"=>new TimeoutException(),"db"=>new NpgsqlException("private-database"),"dbUpdate"=>new DbUpdateException(),"json"=>new JsonException(),"format"=>new FormatException(),_=>new InvalidOperationException("private",new TimeoutException())};Assert.Equal("persistence_unavailable",(await new FolderTrashStore(new ThrowingFactory(e)).TrashAsync(new(Guid.NewGuid(),new string('a',64),Guid.NewGuid(),1),default)).Error);}
    [FunctionalFact]
    public async Task GivenActualProviderOutageOrCancelledCaller_WhenDeleting_Then503OrExactCancellation()
    {var request=new FolderTrashRequest(Guid.NewGuid(),new string('a',64),Guid.NewGuid(),1);var dead=new ProfileSetup.Factory(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql("Host=127.0.0.1;Port=1;Database=absent;Username=fixture;Password=fixture;Timeout=1").Options);Assert.Equal("persistence_unavailable",(await new FolderTrashStore(dead).TrashAsync(request,default)).Error);using var ct=new CancellationTokenSource();ct.Cancel();var e=await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Store().TrashAsync(request,ct.Token));Assert.Equal(ct.Token,e.CancellationToken);}
    private sealed class ThrowingFactory(Exception exception):IDbContextFactory<AppDbContext>{public AppDbContext CreateDbContext()=>throw exception;public Task<AppDbContext> CreateDbContextAsync(CancellationToken ct=default)=>Task.FromException<AppDbContext>(exception);}
    private static byte[] Malformed(byte[] raw,string kind){var s=Encoding.UTF8.GetString(raw);return Encoding.UTF8.GetBytes(kind switch{"numericString"=>s.Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""),"unknown"=>s.Replace("{","{\"secret\":1,"),"duplicate"=>s.Replace("{","{\"keyEpoch\":1,"),_=>s.Replace("\"format\"","\"Format\"")});}
    private static async Task Past(DateTimeOffset t){var delay=t-DateTimeOffset.UtcNow;if(delay>TimeSpan.Zero)await Task.Delay(delay+TimeSpan.FromMilliseconds(100));}
    private static bool RootWrite(DbCommand c)=>c.CommandText.Contains("UPDATE cerberus.folder AS root");
    private static bool ChildWrite(DbCommand c)=>c.CommandText.Contains("UPDATE cerberus.folder AS child");
    private static bool RecordWrite(DbCommand c)=>c.CommandText.Contains("UPDATE cerberus.record AS child");
    private static bool ParentWrite(DbCommand c)=>c.CommandText.StartsWith("UPDATE cerberus.profile SET")||c.CommandText.StartsWith("UPDATE cerberus.collection SET")||c.CommandText.StartsWith("UPDATE cerberus.folder SET");
    private sealed class Signal(TaskCompletionSource reached,string table):DbCommandInterceptor
    {private void Check(DbCommand c){if(c.CommandText.Contains("cerberus."+table)&&c.CommandText.Contains("FOR "))reached.TrySetResult();}public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}}
    private sealed class BeforeRoot(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&RootWrite(c)){used=true;await action();}return r;}}
    private sealed class BeforeContent(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&c.CommandText.Contains("cerberus.folder")&&c.CommandText.Contains("FOR UPDATE")){used=true;await action();}return r;}}
    private sealed class PauseUpdate(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&(c.CommandText.Contains("UPDATE cerberus.folder AS r")||c.CommandText.Contains("UPDATE cerberus.record AS r"))){used=true;await action();}return r;}}
    private sealed class AtWrite(string stage,Func<Task> action):DbCommandInterceptor
    {public bool Triggered{get;private set;}public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!Triggered&&(stage=="root"&&RootWrite(c)||stage=="child"&&ChildWrite(c)||stage=="parent"&&ParentWrite(c))){Triggered=true;await action();}return r;}}
    private sealed class Fail(string stage):DbCommandInterceptor
    {
        public bool Triggered{get;private set;}private bool written;
        private void Check(DbCommand c){if(Triggered)return;var sql=c.CommandText;var hit=written||stage=="links"&&(sql.Contains("DELETE FROM cerberus.profile_folder")||sql.Contains("DELETE FROM cerberus.collection_folder"))||stage=="parent"&&ParentWrite(c)||stage=="operation"&&sql.Contains("INSERT INTO cerberus.trash_operation")||stage=="entry"&&sql.Contains("INSERT INTO cerberus.trash_entry")||stage=="queue"&&sql.Contains("INSERT INTO cerberus.retention_work_item");if(hit){Triggered=true;throw new TimeoutException("synthetic cascade outage");}}
        public override ValueTask<int> NonQueryExecutedAsync(DbCommand c,CommandExecutedEventData d,int r,CancellationToken ct=default){if(r>0&&(stage=="root"&&RootWrite(c)||stage=="child"&&ChildWrite(c)||stage=="record"&&RecordWrite(c)))written=true;return ValueTask.FromResult(r);}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}
        public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}
    }

    [FunctionalTheory][InlineData("profile",false)][InlineData("profile",true)][InlineData("collection",false)][InlineData("collection",true)][InlineData("folder",false)][InlineData("folder",true)]
    public async Task GivenCorruptOrExhaustedActiveExternalParent_WhenDeleting_ThenRollbackCompleteGraph(string kind,bool exhausted)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var a=await AssociationSetup.Items(fixture,s);var root=await Folder(s,a.Folder.Id);await Members(s,a.Collection,[],[root.Id]);var p=await Profile(s,owner,key,folders:[root.PublicId]);await using(var db=fixture.CreateContext()){if(kind=="profile")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,exhausted?ProtocolBinary.MaxInteger:0));if(kind=="collection")await db.Collections.Where(x=>x.Id==a.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,exhausted?ProtocolBinary.MaxInteger:0));if(kind=="folder")await db.Folders.Where(x=>x.Id==a.Folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,exhausted?ProtocolBinary.MaxInteger:0));}var before=await Snapshot(s);Assert.Equal(exhausted?"revision_conflict":"persistence_unavailable",(await Trash(s,root)).Error);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("folder")][InlineData("record")]
    public async Task GivenUnrepresentableStoredCascadeEditTime_WhenDeleting_Then503BeforeAnyMutation(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var record=await Record(s,root.Id);await using(var db=fixture.CreateContext()){if(kind=="folder")await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.EditedAt,DateTimeOffset.MinValue));else await db.Records.Where(x=>x.Id==record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.EditedAt,DateTimeOffset.MinValue));}var before=await Snapshot(s);Assert.Equal("persistence_unavailable",(await Trash(s,root)).Error);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("folder")][InlineData("record")]
    public async Task GivenTypedTerminalDescendant_WhenTrashingRoot_ThenExcludeTerminalBranchWithoutChangingRetainedRows(string kind)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var active=await Record(s,root.Id);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceKind=kind,ResourceId=kind=="folder"?child.PublicId:record.PublicId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var previousChild=Bytes(await Row(child.Id));var previousRecord=Bytes(await RecordRow(record.Id));await Success(s,root,kind=="folder"?[root]:[root,child],[active],await Trash(s,root));Assert.Equal(previousRecord,Bytes(await RecordRow(record.Id)));if(kind=="folder")Assert.Equal(previousChild,Bytes(await Row(child.Id)));
    }
    [FunctionalTheory][InlineData("parent")][InlineData("sibling")]
    public async Task GivenNativeMemberLeafGrant_WhenDeletingPrivateParentOrSibling_Then404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var leaf=await Folder(o,a.Folder.Id);var sibling=await Folder(o,a.Folder.Id);await Members(o,a.Collection,[],[leaf.Id]);await AssociationSetup.Grant(fixture,o,owner,s,client,a.Collection,CollectionGrantAccess.ReadWrite);Assert.Null((await new FolderReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,leaf.PublicId),default)).Error);var before=await Snapshot(o);Assert.Equal("not_found",(await Trash(s,kind=="parent"?a.Folder:sibling,99)).Error);Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalFact]
    public async Task GivenActualOwnerRotationWaitsForCascadeAccount_WhenTrashCommits_ThenStaleInventoryConflictsAndProofSurvives()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),[new("account",s.AccountId,1,ProfileSetup.Envelope(2)),new("folder",root.PublicId,1,ProfileSetup.Envelope(2)),new("folder",child.PublicId,1,ProfileSetup.Envelope(2)),new("record",record.PublicId,1,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(25));var trash=new FolderTrashStore(new ProfileSetup.Factory(fixture,new BeforeContent(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var rotation=new VaultProtectionChangeStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"account"))).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),ct.Token);try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(rotation.IsCompleted);}finally{release.TrySetResult();}await Success(s,root,[root,child],[record],await trash);Assert.Equal("revision_conflict",(await rotation).Error);await using var db=fixture.CreateContext();Assert.False((await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==challenge.ChallengeId)).Consumed);Assert.Equal(1,(await db.VaultProtections.SingleAsync(x=>x.AccountId==s.InternalId)).Revision);
    }
    [FunctionalFact]
    public async Task GivenDeepUnrelatedInventories_WhenTrashingSmallSubtree_ThenBoundedRootAndOnlyCapturedStructuralLocks()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,client);var upper=await Folder(s);var parent=await Folder(s,upper.Id);var root=await Folder(s,parent.Id);var child=await Folder(s,root.Id);var record=await Record(s,child.Id);foreach(var state in new[]{s,foreign}){long? previous=null;for(var i=0;i<50;i++){var f=await Folder(state,previous);previous=f.Id;}for(var i=0;i<50;i++)await Folder(state);}
        var capture=new Capture(fixture);await Success(s,root,[root,child],[record],await new FolderTrashStore(new ProfileSetup.Factory(fixture,capture)).TrashAsync(new(s.Actor,s.Verifier,root.PublicId,1),default));Assert.NotNull(capture.Plan);using var doc=JsonDocument.Parse(capture.Plan!);var nodes=Nodes(doc.RootElement[0].GetProperty("Plan")).ToArray();Assert.Equal(1d,Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var n)&&n.GetString()=="CTE candidates").GetProperty("Actual Rows").GetDouble());Assert.Equal(3d,Assert.Single(nodes,x=>x.TryGetProperty("Subplan Name",out var n)&&n.GetString()=="CTE ancestry").GetProperty("Actual Rows").GetDouble());Assert.Single(capture.Locks,x=>x.Contains("FROM cerberus.account"));Assert.DoesNotContain(capture.Locks,x=>x.Contains("cerberus.collection_grant"));var folders=Assert.Single(capture.Locks,x=>x.Contains("FROM cerberus.folder")&&x.Contains("FOR UPDATE"));Assert.Contains("ORDER BY",folders);Assert.Equal(new[]{parent.Id,root.Id,child.Id}.Order(),Assert.Single(capture.FolderLockIds).Order());Assert.Single(capture.Locks,x=>x.Contains("FROM cerberus.record")&&x.Contains("FOR UPDATE"));Assert.Null((await Row(upper.Id)).DeletedAt);Assert.Equal(upper.Revision,(await Row(upper.Id)).Revision);
    }
    private static IEnumerable<JsonElement> Nodes(JsonElement node){yield return node;if(node.TryGetProperty("Plans",out var children))foreach(var c in children.EnumerateArray())foreach(var n in Nodes(c))yield return n;}
    private sealed class Capture(PostgresFixture fixture):DbCommandInterceptor
    {
        public List<string> Locks{get;}=[];public List<long[]> FolderLockIds{get;}=[];public string? Plan{get;private set;}
        private void Note(DbCommand c){if(c.CommandText.Contains("FROM cerberus.folder")&&c.CommandText.Contains("FOR UPDATE"))FolderLockIds.Add(c.Parameters.Cast<NpgsqlParameter>().Select(x=>x.Value).OfType<long[]>().Single());if(c.CommandText.Contains("FOR UPDATE")||c.CommandText.Contains("FOR NO KEY UPDATE")||c.CommandText.Contains("FOR SHARE"))Locks.Add(c.CommandText);}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Note(c);return ValueTask.FromResult(r);}
        public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Note(c);if(Plan is null&&c.CommandText.StartsWith("WITH RECURSIVE")){await using var db=fixture.CreateContext();await db.Database.OpenConnectionAsync(ct);await using var cmd=db.Database.GetDbConnection().CreateCommand();cmd.CommandText="EXPLAIN (ANALYZE, FORMAT JSON) "+c.CommandText;foreach(var p in c.Parameters.Cast<NpgsqlParameter>())cmd.Parameters.Add(p.Clone());Plan=(string)(await cmd.ExecuteScalarAsync(ct))!;await System.IO.File.WriteAllTextAsync("/tmp/cerberus-uc27-explain.json",Plan,ct);}return r;}
    }

    private FolderTrashStore Store()=>new(fixture);
    private Task<VaultResult<FolderTrashDetails>> Trash(ProfileSetup.State s,VaultFolder folder,long revision=1)=>Store().TrashAsync(new(s.Actor,s.Verifier,folder.PublicId,revision),default);
    private async Task<Profile> ProfileRow(long id){await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task<VaultRecord> RecordRow(long id){await using var db=fixture.CreateContext();return await db.Records.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task Success(ProfileSetup.State s,VaultFolder original,VaultFolder[] folders,VaultRecord[] records,VaultResult<FolderTrashDetails> result)
    {
        Assert.Null(result.Error);var d=result.Data!;Assert.Equal(original.PublicId,d.FolderId);Assert.NotEqual(Guid.Empty,d.TrashOperationId);Assert.Equal(original.Revision+1,d.Revision);Assert.True(d.ServerSequence>original.ServerSequence);Assert.InRange(d.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.Equal(TimeSpan.Zero,d.DeletedAt.Offset);Assert.Equal(0,d.DeletedAt.Ticks%10);Assert.Equal(TimeSpan.FromDays(30),d.PurgeAt-d.DeletedAt);Assert.Equal(TimeSpan.Zero,d.PurgeAt.Offset);
        await using var db=fixture.CreateContext();var op=await db.TrashOperations.AsNoTracking().SingleAsync(x=>x.PublicId==d.TrashOperationId);Assert.Equal("folder",op.RootResourceKind);Assert.Equal(s.InternalId,op.AccountId);Assert.Equal(original.PublicId,op.RootResourceId);Assert.Equal(d.DeletedAt,op.DeletedAt);Assert.Equal(d.PurgeAt,op.PurgeAt);var entries=await db.TrashEntries.AsNoTracking().Where(x=>x.OperationId==op.Id).ToListAsync();Assert.Equal(folders.Length+records.Length,entries.Count);Assert.Equal(folders.Select(x=>x.PublicId).Order(),entries.Where(x=>x.ResourceKind=="folder").Select(x=>x.ResourceId).Order());Assert.Equal(records.Select(x=>x.PublicId).Order(),entries.Where(x=>x.ResourceKind=="record").Select(x=>x.ResourceId).Order());var q=Assert.Single(await db.RetentionWorkItems.AsNoTracking().Where(x=>x.OperationKey=="trash/"+op.PublicId).ToListAsync());Assert.Equal(d.PurgeAt,q.DueAt);Assert.Null(q.CompletedAt);
        foreach(var f in folders){var row=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==f.Id);Assert.Equal(f.Envelope,row.Envelope);Assert.Equal(f.EditedAt,row.EditedAt);Assert.Equal(f.AccountId,row.AccountId);Assert.Null(row.ParentFolderId);Assert.Equal(f.Revision+1,row.Revision);Assert.True(row.ServerSequence>f.ServerSequence);Assert.InRange(row.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.Equal(d.DeletedAt,row.DeletedAt);Assert.Equal(d.PurgeAt,row.PurgeAt);Assert.NotEqual(f.ConcurrencyStamp,row.ConcurrencyStamp);Assert.False(await db.ProfileFolders.AnyAsync(x=>x.FolderId==f.Id));Assert.False(await db.CollectionFolders.AnyAsync(x=>x.FolderId==f.Id));}
        foreach(var r in records){var row=await db.Records.AsNoTracking().SingleAsync(x=>x.Id==r.Id);Assert.Equal(r.Envelope,row.Envelope);Assert.Equal(r.EditedAt,row.EditedAt);Assert.Equal(r.AccountId,row.AccountId);Assert.Null(row.FolderId);Assert.Equal(r.Revision+1,row.Revision);Assert.True(row.ServerSequence>r.ServerSequence);Assert.InRange(row.ServerSequence,1,ProtocolBinary.MaxInteger);Assert.Equal(d.DeletedAt,row.DeletedAt);Assert.Equal(d.PurgeAt,row.PurgeAt);Assert.NotEqual(r.ConcurrencyStamp,row.ConcurrencyStamp);Assert.False(await db.ProfileRecords.AnyAsync(x=>x.RecordId==r.Id));Assert.False(await db.CollectionRecords.AnyAsync(x=>x.RecordId==r.Id));}
    }

    private async Task<VaultFolder> Row(long id){await using var db=fixture.CreateContext();return await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task<VaultRecord> Record(ProfileSetup.State s,long? folder=null){var row=new VaultRecord{PublicId=Guid.NewGuid(),AccountId=s.InternalId,FolderId=folder,Envelope=Bytes(ProfileSetup.Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.CreateContext();db.Records.Add(row);await db.SaveChangesAsync();return row;}
    private async Task<VaultFolder> Folder(ProfileSetup.State s,long? parent=null){var row=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(ProfileSetup.Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.CreateContext();db.Folders.Add(row);await db.SaveChangesAsync();return row;}
    private async Task<Profile> Profile(ProfileSetup.State s,ProtectionFixture owner,ProtectionFixture scoped,Guid[]? records=null,Guid[]? folders=null,Guid[]? collections=null){var input=ProfileSetup.Input(s,owner,scoped) with{RecordIds=records??[],FolderIds=folders??[],CollectionIds=collections??[]};Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==input.ProfileId);}
    private async Task Members(ProfileSetup.State s,VaultCollection collection,long[] records,long[] folders){await using var db=fixture.CreateContext();db.CollectionRecords.AddRange(records.Select(x=>new CollectionRecord{AccountId=s.InternalId,CollectionId=collection.Id,RecordId=x}));db.CollectionFolders.AddRange(folders.Select(x=>new CollectionFolder{AccountId=s.InternalId,CollectionId=collection.Id,FolderId=x}));await db.SaveChangesAsync();}
    private async Task<string> Selected(ProfileSetup.State s,long profile){var verifier=Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));await using var db=fixture.CreateContext();db.VaultAccessSessions.Add(new(){AccountId=s.InternalId,ProfileId=profile,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return verifier;}
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
    private async Task<string> Snapshot(ProfileSetup.State s){await using var db=fixture.CreateContext();return JsonSerializer.Serialize(new{Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Protection=await db.VaultProtections.AsNoTracking().SingleOrDefaultAsync(x=>x.AccountId==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId && p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),CollectionRecords=await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),CollectionFolders=await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),Operations=await db.TrashOperations.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Entries=await db.TrashEntries.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.Id==x.OperationId&&o.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync(),Queue=await db.RetentionWorkItems.AsNoTracking().Where(x=>db.TrashOperations.Any(o=>o.AccountId==s.InternalId&&x.OperationKey=="trash/"+o.PublicId)).OrderBy(x=>x.Id).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>x.RecipientAccountId==s.InternalId || db.Collections.Any(c=>c.Id==x.CollectionId && c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync()});}

}
