using System.Data.Common;
using System.Text.Json;
using ArturRios.Cerberus.Data.Profiles;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.TestSupport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
namespace ArturRios.Cerberus.Data.Tests;

[Collection("PostgreSQL")]
public class ProfileAssociationStoreTests(PostgresFixture fixture)
{
    [FunctionalTheory][InlineData("foreign")][InlineData("trash")][InlineData("erased")][InlineData("missing")]
    public async Task GivenHiddenTarget_WhenSettingAssociationsWithStaleRevision_ThenNotFoundBeforeConflictAndNoMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var target=kind=="foreign"?await ProfileSetup.Create(fixture,owner):s;var i=await Add(target,owner,scoped);
        await using(var db=fixture.CreateContext()){if(kind=="trash")await db.Profiles.Where(x=>x.PublicId==i.ProfileId).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.DeletedAt,DateTimeOffset.UtcNow));if(kind=="erased"){db.TerminalErasures.Add(new(){ResourceId=i.ProfileId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}
        var before=await Snapshot(i.ProfileId);var r=await Store().SetAsync(new(s.Actor,s.Verifier,kind=="missing"?Guid.NewGuid():i.ProfileId,Input(22)),default);Assert.Equal("not_found",r.Error);Assert.Null(r.Data);Assert.Equal(before,await Snapshot(i.ProfileId));
    }
    [FunctionalTheory][InlineData("valid",null)][InlineData("otherTarget","not_found")][InlineData("missing","vault_access_denied")][InlineData("foreign","vault_access_denied")][InlineData("trash","vault_access_denied")][InlineData("erased","vault_access_denied")]
    public async Task GivenSelectedSession_WhenSettingAssociations_ThenOnlyCurrentOwnedSelectionPermitted(string kind,string? error)
    {
        using var additionalScoped1=new ProtectionFixture();
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var i=await Add(s,owner,scoped);var two=await Add(s,owner,additionalScoped1);var foreign=await ProfileSetup.Create(fixture,owner);var other=await Add(foreign,owner,scoped);
        await using(var db=fixture.CreateContext()){var p=await db.Profiles.SingleAsync(x=>x.PublicId==(kind=="foreign"?other.ProfileId:i.ProfileId));await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ProfileId,kind=="missing"?long.MaxValue:p.Id));if(kind=="trash"){p.DeletedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();}if(kind=="erased"){db.TerminalErasures.Add(new(){ResourceId=p.PublicId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}
        var target=kind=="otherTarget"?two.ProfileId:i.ProfileId;var before=await Snapshot(target);var r=await Store().SetAsync(new(s.Actor,s.Verifier,target,Input()),default);Assert.Equal(error,r.Error);if(error is not null){Assert.Null(r.Data);Assert.Equal(before,await Snapshot(target));}else Assert.Equal(2,r.Data!.Revision);
    }
    [FunctionalTheory][InlineData("missing","not_found")][InlineData("closing","not_found")][InlineData("erased","not_found")]
    [InlineData("access","vault_access_denied")][InlineData("revoked","vault_access_denied")][InlineData("expired","vault_access_denied")][InlineData("future","vault_access_denied")][InlineData("policy","vault_access_denied")][InlineData("generation","vault_access_denied")][InlineData("zeroPolicy","vault_access_denied")][InlineData("zeroGeneration","vault_access_denied")][InlineData("nullExpiry","vault_access_denied")][InlineData("disabledExpiry","vault_access_denied")][InlineData("noExpiry",null)]
    public async Task GivenInvalidCurrentAccountOrSession_WhenSettingAssociations_ThenFailClosed(string kind,string? error)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var i=await Add(s,owner,scoped);
        await using(var db=fixture.CreateContext()){var a=await db.Accounts.SingleAsync(x=>x.Id==s.InternalId);var v=await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==s.Verifier);if(kind=="closing")a.State=AccountState.ClosurePending;if(kind=="erased")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="zeroPolicy")v.PolicyRevision=0;if(kind=="zeroGeneration")v.RevocationGeneration=0;if(kind is "noExpiry" or "disabledExpiry")a.RenewalEnabled=false;if(kind is "nullExpiry" or "noExpiry")v.ExpiresAt=null;await db.SaveChangesAsync();}
        var before=await Snapshot(i.ProfileId);var r=await Store().SetAsync(new(kind=="missing"?Guid.NewGuid():s.Actor,kind=="access"?new string('a',64):s.Verifier,i.ProfileId,Input()),default);Assert.Equal(error,r.Error);if(error is not null){Assert.Null(r.Data);Assert.Equal(before,await Snapshot(i.ProfileId));}
    }
    [FunctionalFact]
    public async Task GivenExpiryImmediatelyBeforeWrite_WhenSettingAssociations_ThenStatementTimeDenies()
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var i=await Add(s,owner,scoped);var before=await Snapshot(i.ProfileId);var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var r=await new ProfileAssociationStore(new ProfileSetup.Factory(fixture,new Expire(deadline))).SetAsync(new(s.Actor,s.Verifier,i.ProfileId,Input()),default);Assert.Equal("vault_access_denied",r.Error);Assert.Equal(before,await Snapshot(i.ProfileId));
    }
    [FunctionalFact]
    public async Task GivenSequenceExhaustion_WhenSettingAssociations_ThenConflictAndRollback()
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var i=await Add(s,owner,scoped);var before=await Snapshot(i.ProfileId);await using var db=fixture.CreateContext();var previous=await db.Database.SqlQuery<long>($"SELECT nextval('cerberus.server_sequence') AS \"Value\"").SingleAsync();try{await db.Database.ExecuteSqlRawAsync("SELECT setval('cerberus.server_sequence',9007199254740991,true)");Assert.Equal("revision_conflict",(await Store().SetAsync(new(s.Actor,s.Verifier,i.ProfileId,Input()),default)).Error);Assert.Equal(before,await Snapshot(i.ProfileId));}finally{await db.Database.ExecuteSqlInterpolatedAsync($"SELECT setval('cerberus.server_sequence',{previous},true)");}
    }
    [FunctionalFact]
    public async Task GivenOutageOrCancellation_WhenSettingAssociations_ThenMapOutageAndPropagateCallerCancellation()
    {
        var request=new ProfileAssociationRequest(Guid.NewGuid(),new string('a',64),Guid.NewGuid(),Input());var dead=new ProfileSetup.Factory(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql("Host=127.0.0.1;Port=1;Database=absent;Username=fixture;Password=fixture;Timeout=1").Options);Assert.Equal("persistence_unavailable",(await new ProfileAssociationStore(dead).SetAsync(request,default)).Error);using var c=new CancellationTokenSource();c.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Store().SetAsync(request,c.Token));
    }
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenOwnedTypedItemsAndTwoProfiles_WhenReplacing_ThenAdvanceOneProfileAndPreserveContentAndOtherLinks(bool sameGuid)
    {
        using var additionalScoped1=new ProtectionFixture();
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,owner);var one=await Add(state,owner,scoped);var two=await Add(state,owner,additionalScoped1);var items=await AssociationSetup.Items(fixture,state,sameGuid?Guid.NewGuid():null);var input=For(items);var original=await Row(one.ProfileId);var resourceBytes=await Resources(items);var r=await Store().SetAsync(new(state.Actor,state.Verifier,one.ProfileId,input),default);Assert.Null(r.Error);Assert.Equal(2,r.Data!.Revision);Assert.True(r.Data.ServerSequence>original.ServerSequence);Assert.Equal(input.RecordIds,r.Data.RecordIds);Assert.Equal(input.FolderIds,r.Data.FolderIds);Assert.Equal(input.CollectionIds,r.Data.CollectionIds);Assert.Null((await Store().SetAsync(new(state.Actor,state.Verifier,two.ProfileId,input),default)).Error);
        var current=await Row(one.ProfileId);Assert.Equal(original.Envelope,current.Envelope);Assert.Equal(original.KeyWrappers,current.KeyWrappers);Assert.Equal(original.EditedAt,current.EditedAt);Assert.Equal(resourceBytes,await Resources(items));var cleared=await Store().SetAsync(new(state.Actor,state.Verifier,one.ProfileId,Input(2)),default);Assert.Null(cleared.Error);Assert.Equal(3,cleared.Data!.Revision);Assert.True(cleared.Data.ServerSequence>r.Data.ServerSequence);Assert.Empty(cleared.Data.RecordIds);await using var db=fixture.CreateContext();Assert.False(await db.ProfileRecords.AnyAsync(x=>x.ProfileId==original.Id));Assert.False(await db.ProfileFolders.AnyAsync(x=>x.ProfileId==original.Id));Assert.False(await db.ProfileCollections.AnyAsync(x=>x.ProfileId==original.Id));Assert.Single(await db.ProfileRecords.Where(x=>x.RecordId==items.Record.Id).ToArrayAsync());Assert.Equal(resourceBytes,await Resources(items));
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly)][InlineData(CollectionGrantAccess.ReadWrite)]
    public async Task GivenNativeActiveSharedCollection_WhenOrganizingRecipientProfile_ThenPermitBothGrantLevelsWithoutChangingOwnership(CollectionGrantAccess access)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var other=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var profile=await Add(state,client,scoped);var items=await AssociationSetup.Items(fixture,other);var grant=await AssociationSetup.Grant(fixture,other,owner,state,client,items.Collection,access);var resources=await Resources(items);var result=await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,new(1,[],[],[items.Collection.PublicId])),default);Assert.Null(result.Error);Assert.Equal(new[]{items.Collection.PublicId},result.Data!.CollectionIds);Assert.Equal(resources,await Resources(items));await using var db=fixture.CreateContext();var actual=await db.CollectionGrants.SingleAsync(x=>x.Id==grant.Id);Assert.Equal(grant.RecipientKeyEnvelope,actual.RecipientKeyEnvelope);Assert.Equal(1,actual.Revision);Assert.Equal(access,actual.Access);Assert.Equal(other.InternalId,(await db.Collections.SingleAsync(x=>x.Id==items.Collection.Id)).AccountId);
    }
    [FunctionalTheory][InlineData("recordForeign")][InlineData("folderForeign")][InlineData("recordTrash")][InlineData("folderTrash")][InlineData("recordErased")][InlineData("folderErased")][InlineData("recordMissing")][InlineData("folderMissing")][InlineData("collectionMissing")]
    public async Task GivenHiddenAssociationTarget_WhenReplacing_Then404WithoutPartialLinks(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,owner);var profile=await Add(state,owner,scoped);var items=await AssociationSetup.Items(fixture,state);var foreignItems=kind.Contains("Foreign")?await AssociationSetup.Items(fixture,foreign):null;await using(var db=fixture.CreateContext()){if(kind=="recordTrash")await db.Records.Where(x=>x.Id==items.Record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="folderTrash")await db.Folders.Where(x=>x.Id==items.Folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind.Contains("Erased")){db.TerminalErasures.Add(new(){ResourceId=kind.StartsWith("record")?items.Record.PublicId:items.Folder.PublicId,ResourceKind=kind.StartsWith("record")?"record":"folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}
        var input=For(items);if(kind=="recordForeign")input=input with {RecordIds=[foreignItems!.Record.PublicId]};if(kind=="folderForeign")input=input with {FolderIds=[foreignItems!.Folder.PublicId]};if(kind=="recordMissing")input=input with {RecordIds=[Guid.NewGuid()]};if(kind=="folderMissing")input=input with {FolderIds=[Guid.NewGuid()]};if(kind=="collectionMissing")input=input with {CollectionIds=[Guid.NewGuid()]};var before=await Snapshot(profile.ProfileId);Assert.Equal("not_found",(await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,input),default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);
    }
    [FunctionalTheory][InlineData("revoked","not_found")][InlineData("missing","not_found")][InlineData("recipient","not_found")][InlineData("access","not_found")][InlineData("state","not_found")][InlineData("zeroRevision","not_found")][InlineData("trash","not_found")][InlineData("erased","not_found")][InlineData("closing","not_found")][InlineData("ownerErased","not_found")][InlineData("signature","persistence_unavailable")][InlineData("identity","persistence_unavailable")][InlineData("epoch","persistence_unavailable")][InlineData("grantId","persistence_unavailable")][InlineData("grantRevision","persistence_unavailable")][InlineData("author","persistence_unavailable")][InlineData("blob","persistence_unavailable")][InlineData("ownerPins","persistence_unavailable")][InlineData("recipientPins","persistence_unavailable")][InlineData("collectionEpoch","persistence_unavailable")][InlineData("collectionEnvelope","persistence_unavailable")]
    public async Task GivenUnavailableOrCorruptSharedGrant_WhenReplacing_ThenFailClosedAndPreserveState(string kind,string error)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var profile=await Add(state,client,scoped);var items=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,items.Collection);await using(var db=fixture.CreateContext()){var g=await db.CollectionGrants.SingleAsync(x=>x.Id==grant.Id);if(kind=="revoked")g.State=CollectionGrantState.Revoked;if(kind=="missing")db.CollectionGrants.Remove(g);if(kind=="recipient")g.RecipientAccountId=foreign.InternalId;if(kind=="access")g.Access=(CollectionGrantAccess)99;if(kind=="state")g.State=(CollectionGrantState)99;if(kind=="zeroRevision")g.Revision=0;if(kind=="collectionEpoch")await db.Collections.Where(x=>x.Id==items.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.KeyEpoch,2));if(kind=="collectionEnvelope")await db.Collections.Where(x=>x.Id==items.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,new byte[]{1}));if(kind=="trash")await db.Collections.Where(x=>x.Id==items.Collection.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="erased"||kind=="ownerErased")db.TerminalErasures.Add(new(){ResourceId=kind=="erased"?items.Collection.PublicId:foreign.AccountId,ResourceKind=kind=="erased"?"collection":"account",DeletedAt=DateTimeOffset.UtcNow});if(kind=="closing")await db.Accounts.Where(x=>x.Id==foreign.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,AccountState.ClosurePending));if(kind is "ownerPins" or "recipientPins")await db.VaultProtections.Where(x=>x.AccountId==(kind=="ownerPins"?foreign.InternalId:state.InternalId)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,new byte[]{1}));
            if(kind is "signature" or "identity" or "epoch" or "grantId" or "grantRevision" or "author"){var w=JsonSerializer.Deserialize<RecipientEnvelope>(g.RecipientKeyEnvelope,ProtectionFixture.Json)!;w=kind switch {"signature"=>w with {Signature=ProtectionFixture.Encode(new byte[64])},"identity"=>w with {RecipientIdentityId=Guid.NewGuid()},"epoch"=>w with {KeyEpoch=2},"grantId"=>w with {GrantId=Guid.NewGuid()},"grantRevision"=>w with {GrantRevision=2},_=>w with {AuthorKeyFingerprint=client.Material.AuthorKey.Fingerprint()}};g.RecipientKeyEnvelope=JsonSerializer.SerializeToUtf8Bytes(w,ProtectionFixture.Json);}if(kind=="blob")g.RecipientKeyEnvelope=[1];await db.SaveChangesAsync();}
        var before=await Snapshot(profile.ProfileId);Assert.Equal(error,(await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,new(1,[],[],[items.Collection.PublicId])),default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);
    }
    [FunctionalTheory][InlineData("record")][InlineData("folder")][InlineData("collection")]
    public async Task GivenSelectedProfile_WhenAddingOutsideCurrentAssociationSet_Then404WithoutScopeExpansion(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,owner);var profile=await Add(state,owner,scoped);var first=await AssociationSetup.Items(fixture,state);var next=await AssociationSetup.Items(fixture,state);Assert.Null((await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,For(first)),default)).Error);await using(var db=fixture.CreateContext()){var row=await db.Profiles.SingleAsync(x=>x.PublicId==profile.ProfileId);await db.VaultAccessSessions.Where(x=>x.HandleVerifier==state.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ProfileId,row.Id));}var input=For(first,2);input=kind switch {"record"=>input with {RecordIds=[first.Record.PublicId,next.Record.PublicId]},"folder"=>input with {FolderIds=[first.Folder.PublicId,next.Folder.PublicId]},_=>input with {CollectionIds=[first.Collection.PublicId,next.Collection.PublicId]}};var before=await Snapshot(profile.ProfileId);Assert.Equal("not_found",(await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,input),default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));var subset=For(first,2) with {FolderIds=[],CollectionIds=[]};Assert.Null((await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,subset),default)).Error);Assert.Null((await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,Input(3)),default)).Error);
    }
    [FunctionalTheory][InlineData("grant")][InlineData("ownerPins")][InlineData("recipientPins")]
    public async Task GivenSelectedProfileAndCorruptGrantOutsideSelection_WhenAddingCollection_ThenNotFoundWithoutChangingProfileOrLinks(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();
        var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);
        var profile=await Add(state,client,scoped);var own=await AssociationSetup.Items(fixture,state);var shared=await AssociationSetup.Items(fixture,foreign);
        var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);
        Assert.Null((await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,For(own)),default)).Error);
        var row=await Row(profile.ProfileId);
        await using(var db=fixture.CreateContext())
        {
            await db.VaultAccessSessions.Where(x=>x.HandleVerifier==state.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ProfileId,row.Id));
            if(kind=="grant")await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,new byte[]{1}));
            else await db.VaultProtections.Where(x=>x.AccountId==(kind=="ownerPins"?foreign.InternalId:state.InternalId)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Material,new byte[]{1}));
        }
        var before=await Snapshot(profile.ProfileId);
        var result=await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,For(own,2) with {CollectionIds=[own.Collection.PublicId,shared.Collection.PublicId]}),default);
        Assert.Equal("not_found",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(profile.ProfileId));
        await using var actual=fixture.CreateContext();
        Assert.Equal(own.Record.Id,(await actual.ProfileRecords.SingleAsync(x=>x.ProfileId==row.Id)).RecordId);
        Assert.Equal(own.Folder.Id,(await actual.ProfileFolders.SingleAsync(x=>x.ProfileId==row.Id)).FolderId);
        Assert.Equal(own.Collection.Id,(await actual.ProfileCollections.SingleAsync(x=>x.ProfileId==row.Id)).CollectionId);
    }
    [FunctionalTheory][InlineData("edit")][InlineData("trash")][InlineData("same")]
    public async Task GivenConcurrentReplacementAndOtherWrite_WhenCommitting_ThenOneWinnerAndStableRetry(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,owner);var profile=await Add(state,owner,scoped);var items=await AssociationSetup.Items(fixture,state);var request=new ProfileAssociationRequest(state.Actor,state.Verifier,profile.ProfileId,For(items));var set=Store().SetAsync(request,default);Task other;string? otherError;if(kind=="edit"){var op=new ProfileUpdateStore(fixture).UpdateAsync(new(state.Actor,state.Verifier,profile.ProfileId,new(1,ProfileSetup.Envelope(),profile.EditedAt)),default);other=op;await Task.WhenAll(set,other);otherError=op.Result.Error;}else if(kind=="trash"){var op=new ProfileTrashStore(fixture).TrashAsync(new(state.Actor,state.Verifier,profile.ProfileId,1),default);other=op;await Task.WhenAll(set,other);otherError=op.Result.Error;}else{var op=Store().SetAsync(request,default);other=op;await Task.WhenAll(set,other);otherError=op.Result.Error;}Assert.True((set.Result.Error is null)^(otherError is null));if(set.Result.Error is not null)Assert.Equal(kind=="trash"?"not_found":"revision_conflict",set.Result.Error);else Assert.Equal("revision_conflict",otherError);var before=await Snapshot(profile.ProfileId);Assert.Equal((await Row(profile.ProfileId)).DeletedAt is null?"revision_conflict":"not_found",(await Store().SetAsync(request,default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));Assert.Equal(2,(await Row(profile.ProfileId)).Revision);
    }
    [FunctionalTheory][InlineData("account",1)][InlineData("session",1)][InlineData("profile",1)][InlineData("profile",22)][InlineData("collection",1)][InlineData("grant",1)]
    public async Task GivenNaturalExpiryDuringAnyLockWait_WhenSettingAssociations_ThenDenyBeforeRevisionOrWrites(string kind,long revision)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var profile=await Add(state,client,scoped);var items=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,items.Collection);var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==state.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));await using var holder=fixture.CreateContext();await using var tx=await holder.Database.BeginTransactionAsync();if(kind=="account")await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.account WHERE id={state.InternalId} FOR UPDATE");else if(kind=="session")await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.vault_access_session WHERE handle_verifier={state.Verifier} FOR UPDATE");else if(kind=="profile")await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.profile WHERE public_id={profile.ProfileId} FOR UPDATE");else if(kind=="collection")await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.collection WHERE id={items.Collection.Id} FOR UPDATE");else await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.collection_grant WHERE id={grant.Id} FOR UPDATE");var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var before=await Snapshot(profile.ProfileId);var pending=new ProfileAssociationStore(new ProfileSetup.Factory(fixture,new LockSignal(reached,kind))).SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,new(revision,[],[],[items.Collection.PublicId])),default);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);var remaining=deadline-DateTimeOffset.UtcNow;if(remaining>TimeSpan.Zero)await Task.Delay(remaining+TimeSpan.FromMilliseconds(100));await tx.CommitAsync();Assert.Equal("vault_access_denied",(await pending).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);
    }
    [FunctionalFact]
    public async Task GivenGrantRevokedWhileWaitingForItsLock_WhenSettingAssociations_ThenObserveRevocationAndPersistNothing()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var profile=await Add(state,client,scoped);var items=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,items.Collection);await using var holder=fixture.CreateContext();await using var tx=await holder.Database.BeginTransactionAsync();await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.collection_grant WHERE id={grant.Id} FOR UPDATE");var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var before=await Snapshot(profile.ProfileId);var pending=new ProfileAssociationStore(new ProfileSetup.Factory(fixture,new LockSignal(reached,"grant"))).SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,new(1,[],[],[items.Collection.PublicId])),default);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);await holder.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));await tx.CommitAsync();Assert.Equal("not_found",(await pending).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);
    }
    [FunctionalTheory][InlineData("ownerClosing")][InlineData("recordTrash")]
    public async Task GivenPermissionChangesImmediatelyBeforeWrite_WhenSettingAssociations_ThenFinalStatementRejects(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var profile=await Add(state,client,scoped);var own=await AssociationSetup.Items(fixture,state);var shared=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);var before=await Snapshot(profile.ProfileId);var r=await new ProfileAssociationStore(new ProfileSetup.Factory(fixture,new ChangeBeforeWrite(fixture,kind,foreign.InternalId,own.Record.Id))).SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,new(1,[own.Record.PublicId],[],[shared.Collection.PublicId])),default);Assert.Equal("not_found",r.Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);
    }
    [FunctionalTheory][InlineData("write")][InlineData("delete")][InlineData("insert")]
    public async Task GivenFailureDuringReplacement_WhenSettingAssociations_ThenRollbackOldLinksAndMetadataAndRetrySucceeds(string stage)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,owner);var profile=await Add(state,owner,scoped);var old=await AssociationSetup.Items(fixture,state);var next=await AssociationSetup.Items(fixture,state);Assert.Null((await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,For(old)),default)).Error);var before=await Snapshot(profile.ProfileId);var request=new ProfileAssociationRequest(state.Actor,state.Verifier,profile.ProfileId,For(next,2));Assert.Equal("persistence_unavailable",(await new ProfileAssociationStore(new ProfileSetup.Factory(fixture,new Fail(stage))).SetAsync(request,default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await using(var db=fixture.CreateContext()){var pid=(await Row(profile.ProfileId)).Id;Assert.Equal(old.Record.Id,(await db.ProfileRecords.SingleAsync(x=>x.ProfileId==pid)).RecordId);Assert.Equal(old.Folder.Id,(await db.ProfileFolders.SingleAsync(x=>x.ProfileId==pid)).FolderId);Assert.Equal(old.Collection.Id,(await db.ProfileCollections.SingleAsync(x=>x.ProfileId==pid)).CollectionId);}Assert.Null((await Store().SetAsync(request,default)).Error);
    }
    [FunctionalTheory][InlineData("zeroRevision","persistence_unavailable")][InlineData("zeroSequence","persistence_unavailable")][InlineData("unsafeSequence","persistence_unavailable")][InlineData("maxRevision","revision_conflict")][InlineData("unsafeRevision","persistence_unavailable")]
    public async Task GivenCorruptOrExhaustedProfileMetadata_WhenSettingAssociations_ThenNoMutation(string kind,string error)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,owner);var profile=await Add(state,owner,scoped);await using(var db=fixture.CreateContext()){var row=await db.Profiles.SingleAsync(x=>x.PublicId==profile.ProfileId);if(kind=="zeroRevision")row.Revision=0;if(kind=="zeroSequence")row.ServerSequence=0;if(kind=="unsafeSequence")row.ServerSequence=9007199254740992;if(kind=="maxRevision")row.Revision=9007199254740991;if(kind=="unsafeRevision")row.Revision=9007199254740992;await db.SaveChangesAsync();}var before=await Snapshot(profile.ProfileId);Assert.Equal(error,(await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,Input(kind=="maxRevision"?9007199254740991:1)),default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);
    }
    [FunctionalTheory][InlineData("actor","authentication_required")][InlineData("id","validation_failed")][InlineData("input","validation_failed")][InlineData("revision","validation_failed")][InlineData("array","validation_failed")]
    public async Task GivenInvalidInternalInput_WhenSettingAssociations_ThenRejectBeforeMutation(string kind,string error)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,owner);var profile=await Add(state,owner,scoped);var input=Input();if(kind=="input")input=null!;if(kind=="revision")input=input with {ExpectedRevision=0};if(kind=="array")input=input with {RecordIds=null!};var before=await Snapshot(profile.ProfileId);Assert.Equal(error,(await Store().SetAsync(new(kind=="actor"?Guid.Empty:state.Actor,state.Verifier,kind=="id"?Guid.Empty:profile.ProfileId,input),default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);}
    [FunctionalFact]
    public async Task GivenSelectedHandleAndNewSharedCollectionGrant_WhenAddingIt_Then404WithoutExpandingSelectedScope()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var profile=await Add(state,client,scoped);var items=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,state,client,items.Collection,CollectionGrantAccess.ReadWrite);await using(var db=fixture.CreateContext()){var p=await db.Profiles.SingleAsync(x=>x.PublicId==profile.ProfileId);await db.VaultAccessSessions.Where(x=>x.HandleVerifier==state.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ProfileId,p.Id));}var before=await Snapshot(profile.ProfileId);Assert.Equal("not_found",(await Store().SetAsync(new(state.Actor,state.Verifier,profile.ProfileId,new(1,[],[],[items.Collection.PublicId])),default)).Error);Assert.Equal(before,await Snapshot(profile.ProfileId));await NoLinks(profile.ProfileId);
    }
    private static ProfileAssociationInput For(AssociationSetup.ResourceSet items,long revision=1)=>new(revision,[items.Record.PublicId],[items.Folder.PublicId],[items.Collection.PublicId]);
    private async Task<string> Resources(AssociationSetup.ResourceSet items){await using var db=fixture.CreateContext();return JsonSerializer.Serialize(new{R=await db.Records.AsNoTracking().SingleAsync(x=>x.Id==items.Record.Id),F=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==items.Folder.Id),C=await db.Collections.AsNoTracking().SingleAsync(x=>x.Id==items.Collection.Id)});}
    private async Task NoLinks(Guid id){var p=await Row(id);await using var db=fixture.CreateContext();Assert.False(await db.ProfileRecords.AnyAsync(x=>x.ProfileId==p.Id));Assert.False(await db.ProfileFolders.AnyAsync(x=>x.ProfileId==p.Id));Assert.False(await db.ProfileCollections.AnyAsync(x=>x.ProfileId==p.Id));}
    private sealed class LockSignal(TaskCompletionSource reached,string kind):DbCommandInterceptor
    {private void Check(DbCommand c){var table=kind switch {"account"=>"cerberus.account","session"=>"cerberus.vault_access_session","profile"=>"cerberus.profile","collection"=>"cerberus.collection ",_=>"cerberus.collection_grant"};if((c.CommandText.Contains("FOR UPDATE")||c.CommandText.Contains("FOR SHARE"))&&c.CommandText.Contains(table))reached.TrySetResult();}public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}}
    private sealed class ChangeBeforeWrite(PostgresFixture fixture,string kind,long owner,long record):DbCommandInterceptor
    {public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(c.CommandText.Contains("UPDATE cerberus.profile")){await using var db=fixture.CreateContext();if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==owner).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending),ct);else await db.Records.Where(x=>x.Id==record).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.DeletedAt,DateTimeOffset.UtcNow),ct);}return r;}}
    private sealed class Fail(string stage):DbCommandInterceptor
    {private bool written;public override ValueTask<int> NonQueryExecutedAsync(DbCommand c,CommandExecutedEventData d,int r,CancellationToken ct=default){if(c.CommandText.Contains("UPDATE cerberus.profile"))written=true;return ValueTask.FromResult(r);}public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(stage=="delete"&&c.CommandText.Contains("DELETE FROM cerberus.profile_record"))throw new TimeoutException("synthetic link delete failure");return ValueTask.FromResult(r);}public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){if(stage=="write"&&written || stage=="insert"&&c.CommandText.Contains("INSERT INTO cerberus.profile_record"))throw new TimeoutException("synthetic replacement failure");return ValueTask.FromResult(r);}}
    private ProfileAssociationStore Store()=>new(fixture);
    private static ProfileAssociationInput Input(long revision=1)=>new(revision,[],[],[]);
    private async Task<ProfileCreateInput> Add(ProfileSetup.State s,ProtectionFixture owner,ProtectionFixture scoped,string mode="Master"){var i=ProfileSetup.Input(s,owner,scoped,mode);Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,i),default)).Error);return i;}
    private async Task<Profile> Row(Guid id){await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<string> Snapshot(Guid id)=>JsonSerializer.Serialize(await Row(id));
    private sealed class Signal(TaskCompletionSource reached,string kind):DbCommandInterceptor
    {public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(c.CommandText.Contains("FOR UPDATE")&&c.CommandText.Contains(kind switch {"account"=>"cerberus.account","session"=>"cerberus.vault_access_session",_=>"cerberus.profile"}))reached.TrySetResult();return ValueTask.FromResult(r);}}
    private sealed class Expire(DateTimeOffset deadline):DbCommandInterceptor
    {public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(c.CommandText.Contains("UPDATE cerberus.profile")){var wait=deadline-DateTimeOffset.UtcNow;if(wait>TimeSpan.Zero)await Task.Delay(wait+TimeSpan.FromMilliseconds(100),ct);}return r;}}
}
