using System.Data.Common;
using System.Text.Json;
using ArturRios.Cerberus.Data.Profiles;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Domain.Trash;
using ArturRios.Cerberus.TestSupport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
namespace ArturRios.Cerberus.Data.Tests;

[Collection("PostgreSQL")]
public class ProfileAssociationIntegrationTests(PostgresFixture fixture)
{
    [FunctionalFact]
    public async Task GivenOwnedAndGrantedIdentifiers_WhenCreatingProfile_ThenPersistRealLinksAndReadThemInOneSnapshot()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var own=await AssociationSetup.Items(fixture,state);var shared=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);var input=ProfileSetup.Input(state,client,scoped) with {RecordIds=[own.Record.PublicId],FolderIds=[own.Folder.PublicId],CollectionIds=[own.Collection.PublicId,shared.Collection.PublicId]};var r=await new ProfileCreateStore(fixture).CreateAsync(new(state.Actor,state.Verifier,input),default);Assert.Null(r.Error);Assert.Equal(1,r.Data!.Revision);await Visible(state,input.ProfileId,[own.Record.PublicId],[own.Folder.PublicId],[own.Collection.PublicId,shared.Collection.PublicId]);await using var db=fixture.CreateContext();var p=await db.Profiles.SingleAsync(x=>x.PublicId==input.ProfileId);Assert.Single(await db.ProfileRecords.Where(x=>x.ProfileId==p.Id).ToArrayAsync());Assert.Single(await db.ProfileFolders.Where(x=>x.ProfileId==p.Id).ToArrayAsync());Assert.Equal(2,await db.ProfileCollections.CountAsync(x=>x.ProfileId==p.Id));
    }
    [FunctionalFact]
    public async Task GivenNonemptyPersistedSets_WhenGettingAndListing_ThenProjectActualTypedArraysWithOneCommandEach()
    {
        using var client=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,client);var items=await AssociationSetup.Items(fixture,state);var p=await Profile(state,client);Assert.Null((await new ProfileAssociationStore(fixture).SetAsync(new(state.Actor,state.Verifier,p.PublicId,new(1,[items.Record.PublicId],[items.Folder.PublicId],[items.Collection.PublicId])),default)).Error);await Visible(state,p.PublicId,[items.Record.PublicId],[items.Folder.PublicId],[items.Collection.PublicId]);
    }
    [FunctionalTheory][InlineData("recordTrash")][InlineData("recordErased")][InlineData("folderTrash")][InlineData("folderErased")][InlineData("ownCollectionTrash")][InlineData("ownCollectionErased")][InlineData("sharedTrash")][InlineData("sharedErased")][InlineData("revoked")][InlineData("missingGrant")][InlineData("ownerClosing")][InlineData("ownerErased")][InlineData("grantAccess")][InlineData("grantState")][InlineData("grantRevision")][InlineData("grantErased")]
    public async Task GivenAssociationBecomesInaccessible_WhenGettingAndListing_ThenOmitOnlyHiddenLinks(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var own=await AssociationSetup.Items(fixture,state);var shared=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);var p=await Profile(state,client);Assert.Null((await new ProfileAssociationStore(fixture).SetAsync(new(state.Actor,state.Verifier,p.PublicId,new(1,[own.Record.PublicId],[own.Folder.PublicId],[own.Collection.PublicId,shared.Collection.PublicId])),default)).Error);
        await using(var db=fixture.CreateContext()){if(kind=="recordTrash")await db.Records.Where(x=>x.Id==own.Record.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="folderTrash")await db.Folders.Where(x=>x.Id==own.Folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind is "ownCollectionTrash" or "sharedTrash")await db.Collections.Where(x=>x.Id==(kind=="sharedTrash"?shared.Collection.Id:own.Collection.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="revoked")await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,CollectionGrantState.Revoked));if(kind=="missingGrant")await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteDeleteAsync();if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==foreign.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,AccountState.ClosurePending));if(kind=="grantAccess")await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Access,(CollectionGrantAccess)99));if(kind=="grantState")await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,(CollectionGrantState)99));if(kind=="grantRevision")await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,0));if(kind.Contains("Erased")){var id=kind switch {"recordErased"=>own.Record.PublicId,"folderErased"=>own.Folder.PublicId,"ownCollectionErased"=>own.Collection.PublicId,"sharedErased"=>shared.Collection.PublicId,"grantErased"=>grant.PublicId,_=>foreign.AccountId};db.TerminalErasures.Add(new(){ResourceId=id,ResourceKind=kind=="recordErased"?"record":kind=="folderErased"?"folder":kind is "ownCollectionErased" or "sharedErased"?"collection":kind=="grantErased"?"grant":"account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}}
        var records=kind.StartsWith("record")?Array.Empty<Guid>():[own.Record.PublicId];var folders=kind.StartsWith("folder")?Array.Empty<Guid>():[own.Folder.PublicId];var collections=new List<Guid>();if(!kind.StartsWith("ownCollection"))collections.Add(own.Collection.PublicId);if(kind.StartsWith("record")||kind.StartsWith("folder")||kind.StartsWith("ownCollection"))collections.Add(shared.Collection.PublicId);await Visible(state,p.PublicId,records,folders,collections.ToArray());
    }
    [FunctionalFact]
    public async Task GivenGrantRevokedAfterStatementSnapshot_WhenGetting_ThenReturnCoherentSnapshotAndOmitOnNextRead()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var shared=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);var p=await Profile(state,client);Assert.Null((await new ProfileAssociationStore(fixture).SetAsync(new(state.Actor,state.Verifier,p.PublicId,new(1,[],[],[shared.Collection.PublicId])),default)).Error);var counter=new RevokeAfterSnapshot(fixture,grant.Id);var r=await new ProfileReadStore(new ProfileSetup.Factory(fixture,counter)).ReadAsync(new(state.Actor,state.Verifier,p.PublicId),default);Assert.Null(r.Error);Assert.Equal(new[]{shared.Collection.PublicId},r.Data!.CollectionIds);Assert.Equal(1,counter.Commands);var next=await new ProfileReadStore(fixture).ReadAsync(new(state.Actor,state.Verifier,p.PublicId),default);Assert.Null(next.Error);Assert.Empty(next.Data!.CollectionIds);
    }
    [FunctionalFact]
    public async Task GivenManyTypedLinks_WhenGettingAndListing_ThenAllSetsRemainCompleteInOneCommand()
    {
        using var client=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,client);var p=await Profile(state,client);var sets=new List<AssociationSetup.ResourceSet>();for(var n=0;n<20;n++)sets.Add(await AssociationSetup.Items(fixture,state));var records=sets.Select(x=>x.Record.PublicId).ToArray();var folders=sets.Select(x=>x.Folder.PublicId).ToArray();var collections=sets.Select(x=>x.Collection.PublicId).ToArray();Assert.Null((await new ProfileAssociationStore(fixture).SetAsync(new(state.Actor,state.Verifier,p.PublicId,new(1,records,folders,collections)),default)).Error);await Visible(state,p.PublicId,records,folders,collections);
    }
    [FunctionalFact]
    public async Task GivenTwoProfilesWithOwnedAndSharedLinks_WhenTrashingOne_ThenSnapshotActualSetsAndRetainUnderlyingContentGrantsAndOtherLinks()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var own=await AssociationSetup.Items(fixture,state);var shared=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);var one=await Profile(state,client);var two=await Profile(state,client);var input=new ProfileAssociationInput(1,[own.Record.PublicId],[own.Folder.PublicId],[own.Collection.PublicId,shared.Collection.PublicId]);foreach(var p in new[]{one,two})Assert.Null((await new ProfileAssociationStore(fixture).SetAsync(new(state.Actor,state.Verifier,p.PublicId,input),default)).Error);var bytes=await ResourceSnapshot(own,shared,grant);var r=await new ProfileTrashStore(fixture).TrashAsync(new(state.Actor,state.Verifier,one.PublicId,2),default);Assert.Null(r.Error);await using var db=fixture.CreateContext();var operation=await db.TrashOperations.SingleAsync(x=>x.PublicId==r.Data!.TrashOperationId);var entry=await db.TrashEntries.SingleAsync(x=>x.OperationId==operation.Id);var snapshot=JsonSerializer.Deserialize<ProfileAssociationSnapshot>(entry.AssociationSnapshot,ProtectionFixture.Json)!;Assert.Equal(input.RecordIds,snapshot.RecordIds);Assert.Equal(input.FolderIds,snapshot.FolderIds);Assert.Equal(input.CollectionIds.Order(),snapshot.CollectionIds.Order());Assert.False(await db.ProfileRecords.AnyAsync(x=>x.ProfileId==one.Id));Assert.False(await db.ProfileFolders.AnyAsync(x=>x.ProfileId==one.Id));Assert.False(await db.ProfileCollections.AnyAsync(x=>x.ProfileId==one.Id));Assert.Equal(bytes,await ResourceSnapshot(own,shared,grant));Assert.Single(await db.ProfileRecords.Where(x=>x.ProfileId==two.Id).ToArrayAsync());Assert.Single(await db.ProfileFolders.Where(x=>x.ProfileId==two.Id).ToArrayAsync());Assert.Equal(2,await db.ProfileCollections.CountAsync(x=>x.ProfileId==two.Id));await Visible(state,two.PublicId,input.RecordIds,input.FolderIds,input.CollectionIds);
    }
    [FunctionalFact]
    public async Task GivenTrashQueueFailureAfterLinkRemoval_WhenTrashing_ThenRollbackActualMembershipAndAllowRetry()
    {
        using var client=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,client);var own=await AssociationSetup.Items(fixture,state);var p=await Profile(state,client);Assert.Null((await new ProfileAssociationStore(fixture).SetAsync(new(state.Actor,state.Verifier,p.PublicId,new(1,[own.Record.PublicId],[own.Folder.PublicId],[own.Collection.PublicId])),default)).Error);Assert.Equal("persistence_unavailable",(await new ProfileTrashStore(new ProfileSetup.Factory(fixture,new FailInsert("retention_work_item"))).TrashAsync(new(state.Actor,state.Verifier,p.PublicId,2),default)).Error);await using(var db=fixture.CreateContext()){Assert.Null((await db.Profiles.SingleAsync(x=>x.Id==p.Id)).DeletedAt);Assert.Single(await db.ProfileRecords.Where(x=>x.ProfileId==p.Id).ToArrayAsync());Assert.Single(await db.ProfileFolders.Where(x=>x.ProfileId==p.Id).ToArrayAsync());Assert.Single(await db.ProfileCollections.Where(x=>x.ProfileId==p.Id).ToArrayAsync());Assert.False(await db.TrashOperations.AnyAsync(x=>x.RootResourceId==p.PublicId));}Assert.Null((await new ProfileTrashStore(fixture).TrashAsync(new(state.Actor,state.Verifier,p.PublicId,2),default)).Error);
    }
    [FunctionalFact]
    public async Task GivenLinkInsertFailureDuringCreation_WhenCreating_ThenRollbackProfileAndLinksAndAllowRetry()
    {
        using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var state=await ProfileSetup.Create(fixture,client);var own=await AssociationSetup.Items(fixture,state);var i=ProfileSetup.Input(state,client,scoped) with {RecordIds=[own.Record.PublicId],FolderIds=[own.Folder.PublicId],CollectionIds=[own.Collection.PublicId]};Assert.Equal("persistence_unavailable",(await new ProfileCreateStore(new ProfileSetup.Factory(fixture,new FailInsert("profile_record"))).CreateAsync(new(state.Actor,state.Verifier,i),default)).Error);await using(var db=fixture.CreateContext())Assert.False(await db.Profiles.AnyAsync(x=>x.PublicId==i.ProfileId));Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(state.Actor,state.Verifier,i),default)).Error);await Visible(state,i.ProfileId,i.RecordIds,i.FolderIds,i.CollectionIds);
    }
    [FunctionalFact]
    public async Task GivenForeignOwnerClosesImmediatelyBeforeProfileInsert_WhenCreatingWithSharedCollection_Then404AndNoProfile()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var shared=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);var i=ProfileSetup.Input(state,client,scoped) with {CollectionIds=[shared.Collection.PublicId]};Assert.Equal("not_found",(await new ProfileCreateStore(new ProfileSetup.Factory(fixture,new CloseBeforeInsert(fixture,foreign.InternalId))).CreateAsync(new(state.Actor,state.Verifier,i),default)).Error);await using var db=fixture.CreateContext();Assert.False(await db.Profiles.AnyAsync(x=>x.PublicId==i.ProfileId));
    }
    [FunctionalTheory][InlineData("collection")][InlineData("grant")]
    public async Task GivenAccessExpiresDuringAssociationLockWait_WhenCreating_ThenNoProfileOrLinks(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var state=await ProfileSetup.Create(fixture,client);var shared=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,state,client,shared.Collection);var i=ProfileSetup.Input(state,client,scoped) with {CollectionIds=[shared.Collection.PublicId]};var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==state.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(s=>s.ExpiresAt,deadline));await using var holder=fixture.CreateContext();await using var tx=await holder.Database.BeginTransactionAsync();if(kind=="collection")await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.collection WHERE id={shared.Collection.Id} FOR UPDATE");else await holder.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.collection_grant WHERE id={grant.Id} FOR UPDATE");var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var pending=new ProfileCreateStore(new ProfileSetup.Factory(fixture,new Signal(reached,kind))).CreateAsync(new(state.Actor,state.Verifier,i),default);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);var wait=deadline-DateTimeOffset.UtcNow;if(wait>TimeSpan.Zero)await Task.Delay(wait+TimeSpan.FromMilliseconds(100));await tx.CommitAsync();Assert.Equal("vault_access_denied",(await pending).Error);await using var check=fixture.CreateContext();Assert.False(await check.Profiles.AnyAsync(x=>x.PublicId==i.ProfileId));
    }
    private async Task<Profile> Profile(ProfileSetup.State state,ProtectionFixture client){var id=await AssociationSetup.Profile(fixture,state,client);await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==id);}
    private async Task Visible(ProfileSetup.State state,Guid id,Guid[] records,Guid[] folders,Guid[] collections)
    {
        var counter=new Counter();var factory=new ProfileSetup.Factory(fixture,counter);var read=await new ProfileReadStore(factory).ReadAsync(new(state.Actor,state.Verifier,id),default);Assert.Null(read.Error);Assert.Equal(records.Order(),read.Data!.RecordIds.Order());Assert.Equal(folders.Order(),read.Data.FolderIds.Order());Assert.Equal(collections.Order(),read.Data.CollectionIds.Order());Assert.Equal(1,counter.Commands);counter.Commands=0;var list=await new ProfileListStore(factory).ListAsync(new(state.Actor,state.Verifier,50,0,null),default);Assert.Null(list.Error);var row=Assert.Single(list.Data!.Items,x=>x.ProfileId==id);using var doc=JsonDocument.Parse(JsonSerializer.Serialize(row,ProtectionFixture.Json));foreach(var pair in new[]{("recordIds",records),("folderIds",folders),("collectionIds",collections)}){Assert.True(doc.RootElement.TryGetProperty(pair.Item1,out var ids));Assert.Equal(pair.Item2.Order(),ids.EnumerateArray().Select(x=>x.GetGuid()).Order());}Assert.Equal(1,counter.Commands);
    }
    private async Task<string> ResourceSnapshot(AssociationSetup.ResourceSet own,AssociationSetup.ResourceSet shared,CollectionGrant grant){await using var db=fixture.CreateContext();return JsonSerializer.Serialize(new{Records=await db.Records.AsNoTracking().Where(x=>x.Id==own.Record.Id || x.Id==shared.Record.Id).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.Id==own.Folder.Id || x.Id==shared.Folder.Id).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>x.Id==own.Collection.Id || x.Id==shared.Collection.Id).OrderBy(x=>x.Id).ToArrayAsync(),Grant=await db.CollectionGrants.AsNoTracking().SingleAsync(x=>x.Id==grant.Id)});}
    private class Counter:DbCommandInterceptor
    {public int Commands;public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Commands++;return ValueTask.FromResult(r);}}
    private sealed class RevokeAfterSnapshot(PostgresFixture fixture,long grant):Counter
    {public override async ValueTask<DbDataReader> ReaderExecutedAsync(DbCommand c,CommandExecutedEventData d,DbDataReader r,CancellationToken ct=default){await using var db=fixture.CreateContext();await db.CollectionGrants.Where(x=>x.Id==grant).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked),ct);return r;}}
    private sealed class FailInsert(string table):DbCommandInterceptor
    {public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){if(c.CommandText.Contains("INSERT INTO cerberus."+table))throw new TimeoutException("synthetic membership transaction failure");return ValueTask.FromResult(r);}}
    private sealed class CloseBeforeInsert(PostgresFixture fixture,long owner):DbCommandInterceptor
    {public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(c.CommandText.Contains("INSERT INTO cerberus.profile")){await using var db=fixture.CreateContext();await db.Accounts.Where(x=>x.Id==owner).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending),ct);}return r;}}
    private sealed class Signal(TaskCompletionSource reached,string kind):DbCommandInterceptor
    {public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){if(c.CommandText.Contains("FOR SHARE")&&c.CommandText.Contains(kind=="grant"?"cerberus.collection_grant":"cerberus.collection "))reached.TrySetResult();return ValueTask.FromResult(r);}}
}
