using System.Data.Common;
using System.Security.Cryptography;
using System.Text.Json;
using ArturRios.Cerberus.Data.Records;
using ArturRios.Cerberus.Data.Profiles;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Records;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.TestSupport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
namespace ArturRios.Cerberus.Data.Tests;

[Collection("PostgreSQL")]
public class RecordCreateStoreTests(PostgresFixture fixture)
{
    [FunctionalTheory][InlineData(0,false)][InlineData(0,true)][InlineData(2,false)][InlineData(2,true)]
    public async Task GivenAccountWideAccess_WhenCreatingWithOwnedRelationships_ThenPersistOnlyNewCiphertextLinksAndParentMetadata(int profiles,bool folder)
    {
        using var owner=new ProtectionFixture();using var first=new ProtectionFixture();using var second=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var f=folder?await Folder(s):null;var parents=new List<Profile>();if(profiles>0){parents.Add(await Profile(s,owner,first,f));parents.Add(await Profile(s,owner,second,f));}var input=Input(parents.Select(p=>p.PublicId).ToArray(),f?.PublicId);var protectedBefore=await Protected(s);var result=await Store().CreateAsync(new(s.Actor,s.Verifier,input),default);
        Assert.Null(result.Error);Assert.Equal(input.RecordId,result.Data!.RecordId);Assert.Equal(1,result.Data.Revision);Assert.True(result.Data.ServerSequence>0);Assert.Equal(Normalize(input.EditedAt),result.Data.EditedAt);Assert.Equal(protectedBefore,await Protected(s));await using var db=fixture.CreateContext();var row=await db.Records.SingleAsync(x=>x.PublicId==input.RecordId);Assert.Equal(s.InternalId,row.AccountId);Assert.Equal(JsonSerializer.SerializeToUtf8Bytes(input.Envelope,ProtectionFixture.Json),row.Envelope);Assert.Equal(f?.Id,row.FolderId);Assert.Equal(result.Data.ServerSequence,row.ServerSequence);Assert.Null(row.DeletedAt);Assert.Null(row.PurgeAt);Assert.Equal(parents.Select(p=>p.Id).Order(),await db.ProfileRecords.Where(x=>x.RecordId==row.Id).OrderBy(x=>x.ProfileId).Select(x=>x.ProfileId).ToArrayAsync());
        foreach(var p in parents){var current=await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id);Assert.Equal(p.Revision+1,current.Revision);Assert.True(current.ServerSequence>p.ServerSequence);Assert.Equal(p.EditedAt,current.EditedAt);Assert.Equal(p.Envelope,current.Envelope);Assert.Equal(p.KeyWrappers,current.KeyWrappers);var view=await new ProfileReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,p.PublicId),default);Assert.Contains(input.RecordId,view.Data!.RecordIds);Assert.Equal(f is null?Array.Empty<Guid>():[f.PublicId],view.Data.FolderIds);}
        if(f is not null){var current=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==f.Id);Assert.Equal(f.Revision+1,current.Revision);Assert.True(current.ServerSequence>f.ServerSequence);Assert.Equal(f.Envelope,current.Envelope);Assert.Equal(f.EditedAt,current.EditedAt);}
    }
    [FunctionalTheory][InlineData("none")][InlineData("direct")][InlineData("descendant")]
    public async Task GivenSelectedAccess_WhenCreatingWithinSelection_ThenAttachNewRecordOnlyToSelectedProfile(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var target=kind=="descendant"?await Folder(s,root.Id):root;var p=await Profile(s,owner,scoped,root);var other=await Profile(s,owner,otherKey);var verifier=await Selected(s,p.Id);var beforeOther=JsonSerializer.Serialize(other);var input=Input([p.PublicId],kind=="none"?null:target.PublicId);var result=await Store().CreateAsync(new(s.Actor,verifier,input),default);Assert.Null(result.Error);await using var db=fixture.CreateContext();var record=await db.Records.SingleAsync(x=>x.PublicId==input.RecordId);Assert.Equal(p.Id,Assert.Single(await db.ProfileRecords.Where(x=>x.RecordId==record.Id).ToArrayAsync()).ProfileId);Assert.Equal(beforeOther,JsonSerializer.Serialize(await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==other.Id)));Assert.Equal(input.RecordId,Assert.Single((await new ProfileReadStore(fixture).ReadAsync(new(s.Actor,verifier,p.PublicId),default)).Data!.RecordIds));Assert.Equal("not_found",(await new ProfileReadStore(fixture).ReadAsync(new(s.Actor,verifier,other.PublicId),default)).Error);
    }
    [FunctionalTheory][InlineData("unlinked",403)][InlineData("otherProfile",404)][InlineData("multipleProfiles",404)][InlineData("outsideFolder",404)][InlineData("corruptOutsideFolder",404)]
    public async Task GivenSelectedAccess_WhenAttemptingScopeExpansion_ThenDenyWithoutMutation(string kind,int status)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var p=await Profile(s,owner,scoped);var other=await Profile(s,owner,otherKey);var folder=await Folder(s);var verifier=await Selected(s,p.Id);if(kind=="corruptOutsideFolder"){await using var db=fixture.CreateContext();await db.Folders.Where(x=>x.Id==folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,0));}var input=Input(kind=="unlinked"?[]:kind=="otherProfile"?[other.PublicId]:kind=="multipleProfiles"?[p.PublicId,other.PublicId]:[p.PublicId],kind is "outsideFolder" or "corruptOutsideFolder"?folder.PublicId:null);var before=await Snapshot(s);var result=await Store().CreateAsync(new(s.Actor,verifier,input),default);Assert.Equal(status==403?"vault_access_denied":"not_found",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("profileForeign")][InlineData("profileMissing")][InlineData("profileTrash")][InlineData("profileTerminal")][InlineData("folderForeign")][InlineData("folderMissing")][InlineData("folderTrash")][InlineData("folderTerminal")][InlineData("ancestorTrash")][InlineData("ancestorTerminal")][InlineData("closing")][InlineData("accountTerminal")][InlineData("accountMissing")]
    public async Task GivenHiddenTargetOrAccount_WhenCreating_ThenNonrevealing404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,owner);var p=await Profile(kind=="profileForeign"?foreign:s,owner,scoped);var root=await Folder(kind=="folderForeign"?foreign:s);var folder=kind.StartsWith("ancestor",StringComparison.Ordinal)?await Folder(s,root.Id):root;var input=Input([kind=="profileMissing"?Guid.NewGuid():p.PublicId],kind=="folderMissing"?Guid.NewGuid():folder.PublicId);var actor=s.Actor;
        await using(var db=fixture.CreateContext()){if(kind=="profileTrash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind is "folderTrash" or "ancestorTrash")await db.Folders.Where(x=>x.Id==(kind=="folderTrash"?folder.Id:root.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="closing")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.State,AccountState.ClosurePending));if(kind is "profileTerminal" or "folderTerminal" or "ancestorTerminal" or "accountTerminal")db.TerminalErasures.Add(new(){ResourceId=kind=="profileTerminal"?p.PublicId:kind=="accountTerminal"?s.AccountId:kind=="ancestorTerminal"?root.PublicId:folder.PublicId,ResourceKind=kind=="profileTerminal"?"profile":kind=="accountTerminal"?"account":"folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();if(kind=="accountMissing")actor=Guid.NewGuid();}
        var before=await Snapshot(s);var result=await Store().CreateAsync(new(actor,s.Verifier,input),default);Assert.Equal("not_found",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly)][InlineData(CollectionGrantAccess.ReadWrite)]
    public async Task GivenRecipientGrant_WhenCreatingInForeignFolder_ThenCannotCreateForAnotherOwner(CollectionGrantAccess access)
    {
        using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var items=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,items.Collection,access);var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var result=await Store().CreateAsync(new(s.Actor,s.Verifier,Input([],items.Folder.PublicId)),default);Assert.Equal("not_found",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));
    }
    [FunctionalTheory][InlineData("missing")][InlineData("revoked")][InlineData("expired")][InlineData("future")][InlineData("policy")][InlineData("generation")][InlineData("danglingSelection")][InlineData("foreignSelection")][InlineData("trashedSelection")][InlineData("terminalSelection")][InlineData("disabledWithExpiry")]
    public async Task GivenInvalidCurrentSession_WhenCreating_Then403WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var foreign=await ProfileSetup.Create(fixture,owner);var p=await Profile(kind=="foreignSelection"?foreign:s,owner,scoped);var verifier=s.Verifier;
        await using(var db=fixture.CreateContext()){var v=await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId);if(kind=="missing")verifier="missing";if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddSeconds(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddHours(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="danglingSelection")v.ProfileId=long.MaxValue;if(kind is "foreignSelection" or "trashedSelection" or "terminalSelection")v.ProfileId=p.Id;if(kind=="trashedSelection")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind=="terminalSelection")db.TerminalErasures.Add(new(){ResourceId=p.PublicId,ResourceKind="profile",DeletedAt=DateTimeOffset.UtcNow});if(kind=="disabledWithExpiry")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.RenewalEnabled,false));await db.SaveChangesAsync();}
        var before=await Snapshot(s);var result=await Store().CreateAsync(new(s.Actor,verifier,Input([p.PublicId])),default);Assert.Equal("vault_access_denied",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenDisabledRenewalWithNullExpiry_WhenCreating_ThenAcceptCurrentAuthority()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);await using(var db=fixture.CreateContext()){await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.RenewalEnabled,false));await db.VaultAccessSessions.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,(DateTimeOffset?)null));}Assert.Null((await Store().CreateAsync(new(s.Actor,s.Verifier,Input()),default)).Error);}
    [FunctionalTheory][InlineData("profileRevision",0,503)][InlineData("profileRevision",9007199254740992,503)][InlineData("profileRevision",9007199254740991,409)][InlineData("profileSequence",0,503)][InlineData("profileSequence",9007199254740992,503)][InlineData("folderRevision",0,503)][InlineData("folderRevision",9007199254740992,503)][InlineData("folderRevision",9007199254740991,409)][InlineData("folderSequence",0,503)][InlineData("folderSequence",9007199254740992,503)]
    public async Task GivenCorruptOrSaturatedParentCounters_WhenCreating_ThenFailWithoutPartialWrites(string kind,long value,int status)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var p=await Profile(s,owner,scoped,folder);await using(var db=fixture.CreateContext()){if(kind=="profileRevision")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,value));if(kind=="profileSequence")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ServerSequence,value));if(kind=="folderRevision")await db.Folders.Where(x=>x.Id==folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Revision,value));if(kind=="folderSequence")await db.Folders.Where(x=>x.Id==folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ServerSequence,value));}var before=await Snapshot(s);var result=await Store().CreateAsync(new(s.Actor,s.Verifier,Input([p.PublicId],folder.PublicId)),default);Assert.Equal(status==409?"revision_conflict":"persistence_unavailable",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenCyclicOwnedFolderAncestry_WhenCreating_Then503EvenIfDirectFolderIsSelected(bool selected)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var p=await Profile(s,owner,scoped,root);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,child.Id));var verifier=selected?await Selected(s,p.Id):s.Verifier;var before=await Snapshot(s);var result=await Store().CreateAsync(new(s.Actor,verifier,Input([p.PublicId],root.PublicId)),default);Assert.Equal("persistence_unavailable",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("active")][InlineData("trash")][InlineData("foreign")][InlineData("terminal")]
    public async Task GivenReservedRecordIdentifier_WhenCreating_Then409PreservesWinnerAndRelationships(string kind)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var other=kind=="foreign"?await ProfileSetup.Create(fixture,owner):s;var p=await Profile(s,owner,scoped);var input=Input([p.PublicId]);await using(var db=fixture.CreateContext()){if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=input.RecordId,ResourceKind="record",DeletedAt=DateTimeOffset.UtcNow});else db.Records.Add(new(){PublicId=input.RecordId,AccountId=other.InternalId,Envelope=JsonSerializer.SerializeToUtf8Bytes(ProfileSetup.Envelope(),ProtectionFixture.Json),EditedAt=DateTimeOffset.UnixEpoch,DeletedAt=kind=="trash"?DateTimeOffset.UtcNow:null});await db.SaveChangesAsync();}var before=await Snapshot(s);var result=await Store().CreateAsync(new(s.Actor,s.Verifier,input),default);Assert.Equal("revision_conflict",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenRecordIdEqualToActiveOtherKinds_WhenCreating_ThenKeepTypedResourcesIndependent()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var p=await Profile(s,owner,scoped);var result=await Store().CreateAsync(new(s.Actor,s.Verifier,Input([p.PublicId],folder.PublicId) with{RecordId=p.PublicId}),default);Assert.Null(result.Error);await using var db=fixture.CreateContext();Assert.True(await db.Profiles.AnyAsync(x=>x.PublicId==p.PublicId));Assert.True(await db.Records.AnyAsync(x=>x.PublicId==p.PublicId));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenConcurrentDuplicateIds_WhenCreating_ThenOneWinnerAndNoLosingLinks(bool differentOwners)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var other=differentOwners?await ProfileSetup.Create(fixture,owner):s;var input=Input();var results=await Task.WhenAll(Store().CreateAsync(new(s.Actor,s.Verifier,input),default),Store().CreateAsync(new(other.Actor,other.Verifier,input),default));Assert.Single(results,x=>x.Error is null);Assert.Equal("revision_conflict",Assert.Single(results,x=>x.Error is not null).Error);await using var db=fixture.CreateContext();Assert.Single(await db.Records.Where(x=>x.PublicId==input.RecordId).ToArrayAsync());}
    [FunctionalFact]
    public async Task GivenConcurrentAssociationReplacement_WhenCreating_ThenNewLinkCannotBeSilentlyLost()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var p=await Profile(s,owner,scoped);var input=Input([p.PublicId]);var create=Store().CreateAsync(new(s.Actor,s.Verifier,input),default);var replace=new ProfileAssociationStore(fixture).SetAsync(new(s.Actor,s.Verifier,p.PublicId,new(1,[],[],[])),default);await Task.WhenAll(create,replace);Assert.Null(create.Result.Error);Assert.True(replace.Result.Error is null or "revision_conflict");var view=await new ProfileReadStore(fixture).ReadAsync(new(s.Actor,s.Verifier,p.PublicId),default);Assert.Contains(input.RecordId,view.Data!.RecordIds);Assert.Equal(replace.Result.Error is null?3:2,view.Data.Profile.Revision);}
    [FunctionalFact]
    public async Task GivenConcurrentProfileTrash_WhenCreating_ThenEitherWholeCreationOrWholeTrashWins()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var p=await Profile(s,owner,scoped);var input=Input([p.PublicId]);var create=Store().CreateAsync(new(s.Actor,s.Verifier,input),default);var trash=new ProfileTrashStore(fixture).TrashAsync(new(s.Actor,s.Verifier,p.PublicId,1),default);await Task.WhenAll(create,trash);await using var db=fixture.CreateContext();if(create.Result.Error is null){Assert.Equal("revision_conflict",trash.Result.Error);Assert.True(await db.ProfileRecords.AnyAsync(x=>x.ProfileId==p.Id));Assert.Null((await db.Profiles.SingleAsync(x=>x.Id==p.Id)).DeletedAt);}else{Assert.Equal("not_found",create.Result.Error);Assert.Null(trash.Result.Error);Assert.False(await db.Records.AnyAsync(x=>x.PublicId==input.RecordId));}}
    [FunctionalTheory][InlineData("minimum")][InlineData("precision")][InlineData("pre2000")]
    public async Task GivenSupportedUtcTimestamp_WhenCreating_ThenNormalizeBeforePostgresBinding(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var input=Input() with{EditedAt=kind=="minimum"?new(10,TimeSpan.Zero):kind=="pre2000"?new DateTimeOffset(1999,12,31,23,59,59,TimeSpan.Zero).AddTicks(19):DateTimeOffset.UnixEpoch.AddTicks(19)};var result=await Store().CreateAsync(new(s.Actor,s.Verifier,input),default);Assert.Null(result.Error);Assert.Equal(Normalize(input.EditedAt),result.Data!.EditedAt);await using var db=fixture.CreateContext();Assert.Equal(Normalize(input.EditedAt),(await db.Records.SingleAsync(x=>x.PublicId==input.RecordId)).EditedAt);}
    [FunctionalTheory][InlineData("account")][InlineData("session")][InlineData("profile")][InlineData("folder")]
    public async Task GivenAccessExpiresDuringLockWait_WhenCreating_Then403AndNoWrites(string kind)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var p=await Profile(s,owner,scoped,folder);var deadline=await Short(s);var before=await Snapshot(s);await using var held=fixture.CreateContext();await using var tx=await held.Database.BeginTransactionAsync();if(kind=="account")await held.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.account WHERE id={s.InternalId} FOR UPDATE");if(kind=="session")await held.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.vault_access_session WHERE account_id={s.InternalId} FOR UPDATE");if(kind=="profile")await held.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.profile WHERE id={p.Id} FOR UPDATE");if(kind=="folder")await held.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM cerberus.folder WHERE id={folder.Id} FOR UPDATE");var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var pending=new RecordCreateStore(new ProfileSetup.Factory(fixture,new Signal(reached,kind))).CreateAsync(new(s.Actor,s.Verifier,Input([p.PublicId],folder.PublicId)),default);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);await Past(deadline);await tx.CommitAsync();var result=await pending;Assert.Equal("vault_access_denied",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenExpiryImmediatelyBeforeInsert_WhenCreating_ThenFinalStatementRejectsWithoutWrites()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var deadline=await Short(s);var before=await Snapshot(s);var result=await new RecordCreateStore(new ProfileSetup.Factory(fixture,new Expire(deadline))).CreateAsync(new(s.Actor,s.Verifier,Input()),default);Assert.Equal("vault_access_denied",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("account",404)][InlineData("profile",404)][InlineData("folder",404)][InlineData("record",409)]
    public async Task GivenTerminalReservationAtFinalInsert_WhenCreating_ThenFailClosedWithoutRecordOrParentChanges(string kind,int status)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var p=await Profile(s,owner,scoped,folder);var input=Input([p.PublicId],folder.PublicId);var before=await Snapshot(s);var id=kind=="account"?s.AccountId:kind=="profile"?p.PublicId:kind=="folder"?folder.PublicId:input.RecordId;var result=await new RecordCreateStore(new ProfileSetup.Factory(fixture,new Terminal(fixture,id,kind))).CreateAsync(new(s.Actor,s.Verifier,input),default);Assert.Equal(status==409?"revision_conflict":"not_found",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("afterInsert")][InlineData("afterParent")][InlineData("link")]
    public async Task GivenPostInsertFailure_WhenCreating_ThenRollbackRecordLinksAndParentsAndRetrySameId(string kind)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);var p=await Profile(s,owner,scoped,folder);var input=Input([p.PublicId],folder.PublicId);var before=await Snapshot(s);await using var db=fixture.CreateContext();if(kind=="link")await db.Database.ExecuteSqlRawAsync("CREATE FUNCTION cerberus.reject_record_create_fixture() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic link failure' USING ERRCODE='08006'; END $$; CREATE TRIGGER reject_record_create_fixture BEFORE INSERT ON cerberus.profile_record FOR EACH ROW EXECUTE FUNCTION cerberus.reject_record_create_fixture();");try{var store=kind=="link"?Store():new RecordCreateStore(new ProfileSetup.Factory(fixture,new Fail(kind)));var result=await store.CreateAsync(new(s.Actor,s.Verifier,input),default);Assert.Equal("persistence_unavailable",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}finally{if(kind=="link")await db.Database.ExecuteSqlRawAsync("DROP TRIGGER IF EXISTS reject_record_create_fixture ON cerberus.profile_record; DROP FUNCTION IF EXISTS cerberus.reject_record_create_fixture();");}Assert.Null((await Store().CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenInvalidGlobalSequence_WhenCreating_ThenRollbackAndReturnStableFailure(bool exhausted)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var p=await Profile(s,owner,scoped);var before=await Snapshot(s);await using var db=fixture.CreateContext();var previous=await db.Database.SqlQuery<long>($"SELECT last_value AS \"Value\" FROM cerberus.server_sequence").SingleAsync();await db.Database.ExecuteSqlInterpolatedAsync($"SELECT setval('cerberus.server_sequence',{(exhausted?ProtocolBinary.MaxInteger:1)},true)");try{var result=await Store().CreateAsync(new(s.Actor,s.Verifier,Input([p.PublicId])),default);Assert.Equal(exhausted?"revision_conflict":"persistence_unavailable",result.Error);Assert.Null(result.Data);Assert.Equal(before,await Snapshot(s));}finally{await db.Database.ExecuteSqlInterpolatedAsync($"SELECT setval('cerberus.server_sequence',{previous},true)");}}
    [FunctionalTheory][InlineData("actor")][InlineData("id")][InlineData("null")][InlineData("time")][InlineData("profiles")]
    public async Task GivenInvalidTrustedInput_WhenCreating_ThenRejectBeforeDeadDependency(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var input=Input();input=kind switch{"id"=>input with{RecordId=Guid.Empty},"null"=>null!,"time"=>input with{EditedAt=new(9,TimeSpan.Zero)},"profiles"=>input with{ProfileIds=null!},_=>input};var result=await Dead().CreateAsync(new(kind=="actor"?Guid.Empty:s.Actor,s.Verifier,input),default);Assert.Equal(kind=="actor"?"authentication_required":"validation_failed",result.Error);Assert.Null(result.Data);}
    [FunctionalFact]
    public async Task GivenUnavailablePersistenceOrCancelledCaller_WhenCreating_ThenFailClosedOrPropagateCancellation()
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var before=await Snapshot(s);var r=await Dead().CreateAsync(new(s.Actor,s.Verifier,Input()),default);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);using var source=new CancellationTokenSource();source.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Store().CreateAsync(new(s.Actor,s.Verifier,Input()),source.Token));Assert.Equal(before,await Snapshot(s));}
    private RecordCreateStore Store()=>new(fixture);
    private static RecordCreateStore Dead()=>new(new ProfileSetup.Factory(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql("Host=127.0.0.1;Port=1;Database=unavailable;Username=none;Timeout=1;Pooling=false").Options));
    private static RecordCreateInput Input(Guid[]? profiles=null,Guid? folder=null)=>new(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch.AddTicks(19),profiles??[],folder);
    private static DateTimeOffset Normalize(DateTimeOffset value)=>value.AddTicks(-(value.Ticks%TimeSpan.TicksPerMicrosecond));
    private async Task<Profile> Profile(ProfileSetup.State s,ProtectionFixture owner,ProtectionFixture scoped,VaultFolder? folder=null){var input=ProfileSetup.Input(s,owner,scoped);if(folder is not null)input=input with{FolderIds=[folder.PublicId]};Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==input.ProfileId);}
    private async Task<VaultFolder> Folder(ProfileSetup.State s,long? parent=null){var folder=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=JsonSerializer.SerializeToUtf8Bytes(ProfileSetup.Envelope(),ProtectionFixture.Json),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.CreateContext();db.Folders.Add(folder);await db.SaveChangesAsync();return folder;}
    private async Task<string> Selected(ProfileSetup.State s,long id){var verifier=Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));await using var db=fixture.CreateContext();db.VaultAccessSessions.Add(new(){AccountId=s.InternalId,ProfileId=id,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return verifier;}
    private async Task<DateTimeOffset> Short(ProfileSetup.State s){var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using var db=fixture.CreateContext();await db.VaultAccessSessions.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));return deadline;}
    private static async Task Past(DateTimeOffset deadline){var remaining=deadline-DateTimeOffset.UtcNow;if(remaining>TimeSpan.Zero)await Task.Delay(remaining+TimeSpan.FromMilliseconds(120));}
    private async Task<string> Protected(ProfileSetup.State s){await using var db=fixture.CreateContext();return JsonSerializer.Serialize(new{Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Protection=await db.VaultProtections.AsNoTracking().SingleAsync(x=>x.AccountId==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<string> Snapshot(ProfileSetup.State s){await using var db=fixture.CreateContext();return JsonSerializer.Serialize(new{Protected=await Protected(s),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync()});}
    private sealed class Signal(TaskCompletionSource reached,string kind):DbCommandInterceptor{public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData e,InterceptionResult<int> r,CancellationToken ct=default){if(c.CommandText.Contains("FOR UPDATE") && c.CommandText.Contains(kind=="account"?"cerberus.account":kind=="session"?"cerberus.vault_access_session":kind=="profile"?"cerberus.profile":"cerberus.folder"))reached.TrySetResult();return ValueTask.FromResult(r);}}
    private sealed class Expire(DateTimeOffset deadline):DbCommandInterceptor{public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData e,InterceptionResult<int> r,CancellationToken ct=default){if(c.CommandText.Contains("INSERT INTO cerberus.record"))await Past(deadline);return r;}}
    private sealed class Terminal(PostgresFixture fixture,Guid id,string kind):DbCommandInterceptor{public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData e,InterceptionResult<int> r,CancellationToken ct=default){if(c.CommandText.Contains("INSERT INTO cerberus.record")){await using var db=fixture.CreateContext();db.TerminalErasures.Add(new(){ResourceId=id,ResourceKind=kind,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync(ct);}return r;}}
    private sealed class Fail(string kind):DbCommandInterceptor
    {
        private bool inserted;
        public override ValueTask<int> NonQueryExecutedAsync(DbCommand c,CommandExecutedEventData e,int result,CancellationToken ct=default){if(c.CommandText.Contains("INSERT INTO cerberus.record"))inserted=true;if(kind=="afterParent" && c.CommandText.Contains("UPDATE cerberus.profile") && result>0)throw new TimeoutException("synthetic post-parent failure");return ValueTask.FromResult(result);}
        public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData e,InterceptionResult<DbDataReader> r,CancellationToken ct=default){if(kind=="afterInsert" && inserted)throw new TimeoutException("synthetic post-insert failure");return ValueTask.FromResult(r);}
    }
}
