from pathlib import Path
root=Path('/tmp/cerberus-uc19-worktree')
old=(root/'tests/Presentation/ArturRios.Cerberus.WebApi.Tests/RecordReadHttpTests.cs').read_text()
s=old[:old.index('[Collection("Registration host")]')].replace('using System.Text.Json;','using System.Text.Json;\nusing System.Text.Json.Nodes;')
s+=r'''[Collection("Registration host")]
public class RecordUpdateHttpTests(RegistrationApiFixture fixture):WebApiTest<Program>(EnvironmentType.Local)
{
    [FunctionalTheory][InlineData("wide",false)][InlineData("Master",false)][InlineData("PerProfile",false)][InlineData("Master",true)][InlineData("PerProfile",true)]
    public async Task GivenNativeCurrentOwnedAccess_WhenReplacing_ThenOnlyRecordContentAndFourMetadataFieldsChange(string mode,bool folderRoute)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var child=await Folder(s,root.Id);var p=await Profile(s,owner,key,folderRoute?root:null,mode=="wide"?"Master":mode);var target=await Create(s,folderRoute?[]:[p.PublicId],child.PublicId);var actor=mode=="wide"?s:s with{Access=await Open(s,p,key)};var before=await Unrelated(s,target.RecordId);var input=Replacement();
        using var response=await Update(actor,target.RecordId,input);var data=await Success<UpdateRecordOutput>(response,200);Fields(data,"recordId","revision","serverSequence","editedAt");Assert.Contains("record_updated",await response.Content.ReadAsStringAsync());await Changed(s,target,input,data);Assert.Equal(before,await Unrelated(s,target.RecordId));
        using var get=await Read(actor,"/api/records/"+target.RecordId);Assert.Equal(input.Envelope,(await Success<RecordDetailsOutput>(get,200)).Envelope);
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false,false)][InlineData(CollectionGrantAccess.ReadOnly,true,true)][InlineData(CollectionGrantAccess.ReadWrite,false,false)][InlineData(CollectionGrantAccess.ReadWrite,true,false)][InlineData(CollectionGrantAccess.ReadWrite,false,true)][InlineData(CollectionGrantAccess.ReadWrite,true,true)]
    public async Task GivenNativeSharedGrant_WhenReplacing_ThenReadOnly403AndReadWriteUpdatesOriginalOwner(CollectionGrantAccess access,bool selected,bool folderRoute)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (collection,_)=await Share(o,owner,s,client,access,folderRoute?[]:[target.RecordId],folderRoute?[root.Id]:[]);var p=await Profile(s,client,key,collections:[collection.PublicId]);var actor=selected?s with{Access=await Open(s,p,key)}:s;var before=await Snapshot(o);var unrelated=await Unrelated(o,target.RecordId);var recipient=await Snapshot(s);var input=Replacement(access==CollectionGrantAccess.ReadOnly?99:1);
        using var response=await Update(actor,target.RecordId,input);if(access==CollectionGrantAccess.ReadOnly){await Failure(response,403,"vault_access_denied");Assert.Equal(before,await Snapshot(o));}else{var data=await Success<UpdateRecordOutput>(response,200);Fields(data,"recordId","revision","serverSequence","editedAt");await Changed(o,target,input,data);Assert.Equal(unrelated,await Unrelated(o,target.RecordId));}Assert.Equal(recipient,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("missing")][InlineData("foreign")][InlineData("unselected")][InlineData("recordTrash")][InlineData("ancestorTrash")][InlineData("recordTerminal")][InlineData("ownerClosing")][InlineData("revoked")]
    public async Task GivenHiddenTargetWithBadCipherAndStaleRevision_WhenReplacing_ThenNonrevealing404WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var key=new ProtectionFixture();var o=await Setup(owner);var s=kind=="unselected"?o:await Setup(client);var folder=await Folder(o);var target=await Create(o,folder:folder.PublicId);CollectionGrant? grant=null;if(kind!="foreign"&&s.InternalId!=o.InternalId){var share=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.RecordId],[]);grant=share.Item2;}if(kind=="unselected"){var p=await Profile(s,owner,key);s=s with{Access=await Open(s,p,key)};}
        await using(var db=fixture.Context()){await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Envelope,"bad"u8.ToArray()).SetProperty(r=>r.DeletedAt,kind=="recordTrash"?(DateTimeOffset?)DateTimeOffset.UtcNow:null));if(kind=="ancestorTrash")await db.Folders.Where(x=>x.Id==folder.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.DeletedAt,DateTimeOffset.UtcNow));if(kind=="recordTerminal"){db.TerminalErasures.Add(new(){ResourceId=target.RecordId,ResourceKind="record",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}if(kind=="ownerClosing")await db.Accounts.Where(x=>x.Id==o.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="revoked")await db.CollectionGrants.Where(x=>x.Id==grant!.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));}
        var before=await Snapshot(o);using var response=await Update(s,kind=="missing"?Guid.NewGuid():target.RecordId,Replacement(88));await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(o));
    }
    [FunctionalTheory][InlineData("bad")][InlineData("zero")][InlineData("uppercase")][InlineData("compact")][InlineData("braced")][InlineData("urn")]
    public async Task GivenNoncanonicalRoute_WhenReplacing_Then400WithoutMutation(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var g=Guid.Parse("abcdefab-1234-4321-abcd-123456789abc");var id=kind switch{"bad"=>"bad","zero"=>Guid.Empty.ToString(),"uppercase"=>g.ToString().ToUpperInvariant(),"compact"=>g.ToString("N"),"braced"=>g.ToString("B"),_=>"urn:uuid:"+g};var before=await Snapshot(s);using var req=Put(s,"/api/records/"+id,Bytes(Replacement()));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400,"validation_failed");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("unknown")][InlineData("owner")][InlineData("record")][InlineData("profile")][InlineData("folder")][InlineData("collection")][InlineData("name")][InlineData("duplicate")][InlineData("case")][InlineData("numericRevision")][InlineData("numericEpoch")][InlineData("missingRevision")][InlineData("missingEnvelope")][InlineData("missingTime")][InlineData("null")][InlineData("empty")][InlineData("format")][InlineData("epoch")][InlineData("revision")][InlineData("unsafeRevision")][InlineData("time")][InlineData("offset")][InlineData("saltReuse")][InlineData("nonceReuse")]
    public async Task GivenInvalidOrForgedBody_WhenReplacing_Then400AndNoChanges(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var i=Replacement();if(kind=="format")i=i with{Envelope=i.Envelope with{Format="unknown"}};if(kind=="epoch")i=i with{Envelope=i.Envelope with{KeyEpoch=2}};if(kind=="revision")i=i with{ExpectedRevision=0};if(kind=="unsafeRevision")i=i with{ExpectedRevision=ProtocolBinary.MaxInteger+1};if(kind=="time")i=i with{EditedAt=new(9,TimeSpan.Zero)};if(kind=="offset")i=i with{EditedAt=i.EditedAt.ToOffset(TimeSpan.FromHours(1))};if(kind=="saltReuse")i=i with{Envelope=i.Envelope with{KeySalt=target.Envelope.KeySalt}};if(kind=="nonceReuse")i=i with{Envelope=i.Envelope with{Nonce=target.Envelope.Nonce}};
        var body=JsonSerializer.SerializeToNode(i,ProtectionFixture.Json)!.AsObject();if(kind=="missingRevision")body.Remove("expectedRevision");if(kind=="missingEnvelope")body.Remove("envelope");if(kind=="missingTime")body.Remove("editedAt");var field=kind switch{"unknown"=>"secret","owner"=>"ownerId","record"=>"recordId","profile"=>"profileIds","folder"=>"folderId","collection"=>"collectionIds","name"=>"name",_=>null};if(field is not null)body[field]=null;var raw=body.ToJsonString();raw=kind switch{"null"=>"null","empty"=>"{}","duplicate"=>raw.Insert(1,"\"expectedRevision\":1,"),"case"=>raw.Replace("expectedRevision","ExpectedRevision"),"numericRevision"=>raw.Replace("\"expectedRevision\":1","\"expectedRevision\":\"1\""),"numericEpoch"=>raw.Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""),_=>raw};
        var before=await Snapshot(s);using var request=Put(s,"/api/records/"+target.RecordId,Encoding.UTF8.GetBytes(raw));using var r=await Gateway.Client.SendAsync(request);await Failure(r,400);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("query",400)][InlineData("duplicate",400)][InlineData("bad",400)][InlineData("missing",401)][InlineData("utf8",400)][InlineData("bom",400)][InlineData("compression",400)][InlineData("charset",400)][InlineData("oversized",413)]
    public async Task GivenInvalidTransportOrAccess_WhenReplacing_ThenRejectWithoutMutation(string kind,int status)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);var raw=kind=="oversized"?Encoding.UTF8.GetBytes(new string(' ',65537)):kind=="utf8"?new byte[]{0xc3,0x28}:Bytes(Replacement());if(kind=="bom")raw=new byte[]{239,187,191}.Concat(raw).ToArray();using var req=Put(s,"/api/records/"+target.RecordId+(kind=="query"?"?ownerId=secret":""),raw);if(kind=="missing")req.Headers.Remove("X-Cerberus-Vault-Access");if(kind=="bad"){req.Headers.Remove("X-Cerberus-Vault-Access");req.Headers.Add("X-Cerberus-Vault-Access","bad");}if(kind=="duplicate")req.Headers.TryAddWithoutValidation("X-Cerberus-Vault-Access",s.Access);if(kind=="compression")req.Content!.Headers.ContentEncoding.Add("gzip");if(kind=="charset")req.Content!.Headers.ContentType!.CharSet="utf-16";using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalFact]
    public async Task GivenRawEmptyAccessHeader_WhenReplacing_Then400()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);using var host=new WebApplicationFactory<Program>();var raw=Bytes(Replacement());var context=await host.Server.SendAsync(c=>{c.Request.Method="PUT";c.Request.Path="/api/records/"+Guid.NewGuid();c.Request.Headers.Authorization="Bearer "+RegistrationApiFixture.Token(s.Actor);c.Request.Headers["X-Cerberus-Vault-Access"]="";c.Request.ContentType="application/json";c.Request.ContentLength=raw.Length;c.Request.Body=new MemoryStream(raw);});Assert.Equal(400,context.Response.StatusCode);Assert.Contains("no-store",context.Response.Headers.CacheControl.ToString());}
    [FunctionalTheory][InlineData("missing",401)][InlineData("scope",401)][InlineData("deleted",401)][InlineData("unavailable",503)]
    public async Task GivenInvalidCurrentIdentity_WhenReplacing_ThenRejectWithoutPersistence(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);if(kind is "deleted" or "unavailable")fixture.Users[s.Actor+"@example.test"]=new(s.Actor,"fixture-password",Deleted:kind=="deleted",IdentityUnavailable:kind=="unavailable");var before=await Snapshot(s);using var req=Put(s,"/api/records/"+target.RecordId,Bytes(Replacement()));if(kind=="missing")req.Headers.Authorization=null;if(kind=="scope")req.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor,Guid.NewGuid()));using var r=await Gateway.Client.SendAsync(req);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("closing",404)][InlineData("terminal",404)][InlineData("revoked",403)][InlineData("expired",403)][InlineData("future",403)][InlineData("policy",403)][InlineData("generation",403)][InlineData("dangling",403)]
    public async Task GivenInvalidCurrentActorState_WhenReplacing_ThenNoMutation(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using(var db=fixture.Context()){var v=await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId);if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddMinutes(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="dangling")v.ProfileId=long.MaxValue;if(kind=="closing")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);using var r=await Update(s,target.RecordId,Replacement());await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("grant",404)][InlineData("downgrade",403)][InlineData("member",404)][InlineData("move",404)]
    public async Task GivenCommittedSharedRelationshipChange_WhenReplacing_ThenCurrentPermissionWins(string kind,int status)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var root=await Folder(o);var child=await Folder(o,root.Id);var target=await Create(o,folder:child.PublicId);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[],[root.Id]);using(var get=await Read(s,"/api/records/"+target.RecordId))await Success<RecordDetailsOutput>(get,200);await using(var db=fixture.Context()){if(kind=="grant")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.State,CollectionGrantState.Revoked));if(kind=="downgrade")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.Access,CollectionGrantAccess.ReadOnly));if(kind=="member")await db.CollectionFolders.Where(x=>x.CollectionId==c.Id).ExecuteDeleteAsync();if(kind=="move")await db.Folders.Where(x=>x.Id==child.Id).ExecuteUpdateAsync(x=>x.SetProperty(f=>f.ParentFolderId,(long?)null));}var before=await Snapshot(o);using var r=await Update(s,target.RecordId,Replacement());await Failure(r,status);Assert.Equal(before,await Snapshot(o));}
    [FunctionalTheory][InlineData("signature")][InlineData("numericString")][InlineData("pins")]
    public async Task GivenRelevantMalformedNativeAuthority_WhenReplacing_Then503WithoutAnyContentChange(string kind)
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var target=await Create(o);var (c,g)=await Share(o,owner,s,client,CollectionGrantAccess.ReadWrite,[target.RecordId],[]);await using(var db=fixture.Context()){if(kind=="signature")await db.CollectionGrants.Where(x=>x.Id==g.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.RecipientKeyEnvelope,"bad"u8.ToArray()));if(kind=="numericString")await db.Collections.Where(x=>x.Id==c.Id).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Envelope,Encoding.UTF8.GetBytes(Encoding.UTF8.GetString(c.Envelope).Replace("\"keyEpoch\":1","\"keyEpoch\":\"1\""))));if(kind=="pins")await db.VaultProtections.Where(x=>x.AccountId==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Material,"bad"u8.ToArray()));}var before=await Snapshot(o);using var r=await Update(s,target.RecordId,Replacement());await Failure(r,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(o));}
    [FunctionalTheory][InlineData("envelope")][InlineData("sequence")][InlineData("revision")][InlineData("outage")]
    public async Task GivenCorruptVisibleTargetOrUnavailableDatabase_WhenReplacing_Then503WithoutPartialPayload(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using var db=fixture.Context();if(kind=="envelope")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Envelope,"bad"u8.ToArray()));if(kind=="sequence")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.ServerSequence,0));if(kind=="revision")await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Revision,0));var before=await Snapshot(s);if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.record RENAME TO fixture_unavailable_record");try{using var r=await Update(s,target.RecordId,Replacement());await Failure(r,503,"persistence_unavailable");}finally{if(kind=="outage")await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_record RENAME TO record");}Assert.Equal(before,await Snapshot(s));}
    [FunctionalFact]
    public async Task GivenLostSuccessRetryAndStaleRevision_WhenReplacing_Then409PreservesWinner()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var input=Replacement();using(var r=await Update(s,target.RecordId,input))await Changed(s,target,input,await Success<UpdateRecordOutput>(r,200));var before=await Snapshot(s);using var retry=await Update(s,target.RecordId,input);await Failure(retry,409,"revision_conflict");using var other=await Update(s,target.RecordId,Replacement());await Failure(other,409,"revision_conflict");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(1,400)][InlineData(9,400)][InlineData(10,200)]
    public async Task GivenTimestampAtStorageMinimum_WhenReplacing_ThenRejectUnrepresentableAndPreserveGetContract(long ticks,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var before=await Snapshot(s);var input=Replacement() with{EditedAt=new(ticks,TimeSpan.Zero)};using var r=await Update(s,target.RecordId,input);if(status==400){await Failure(r,status);Assert.Equal(before,await Snapshot(s));}else await Changed(s,target,input,await Success<UpdateRecordOutput>(r,200));using var get=await Read(s,"/api/records/"+target.RecordId);await Success<RecordDetailsOutput>(get,200);}

    private static RecordUpdateInput Replacement(long revision=1)=>new(revision,Envelope(),DateTimeOffset.Parse("2026-10-09T00:00:00Z").AddTicks(19));
    private static HttpRequestMessage Put(State s,string path,byte[] body){var r=Request(s,body,path);r.Method=HttpMethod.Put;return r;}
    private async Task<HttpResponseMessage> Update(State s,Guid id,RecordUpdateInput input){using var req=Put(s,"/api/records/"+id,Bytes(input));return await Gateway.Client.SendAsync(req);}
    private async Task Changed(State owner,RecordCreateInput target,RecordUpdateInput input,UpdateRecordOutput output){Assert.Equal(target.RecordId,output.RecordId);Assert.Equal(input.ExpectedRevision+1,output.Revision);Assert.Equal(Normalize(input.EditedAt),output.EditedAt);await using var db=fixture.Context();var row=await db.Records.SingleAsync(x=>x.PublicId==target.RecordId);Assert.Equal(owner.InternalId,row.AccountId);Assert.Equal(output.Revision,row.Revision);Assert.Equal(output.ServerSequence,row.ServerSequence);Assert.True(output.ServerSequence>0);Assert.Equal(output.EditedAt,row.EditedAt);Assert.Equal(input.Envelope,JsonSerializer.Deserialize<EncryptedEnvelope>(row.Envelope,ProtectionFixture.Json));if(target.FolderId is null)Assert.Null(row.FolderId);else Assert.Equal(target.FolderId,(await db.Folders.SingleAsync(x=>x.Id==row.FolderId)).PublicId);}
    private async Task<string> Unrelated(State s,Guid target){var node=JsonNode.Parse(await Snapshot(s))!.AsObject();var rows=node["Records"]!.AsArray();node["Records"]=new JsonArray(rows.Where(r=>r!["PublicId"]!.GetValue<Guid>()!=target).Select(r=>r!.DeepClone()).ToArray());return node.ToJsonString();}
'''
s+=old[old.index('    private async Task<RecordCreateInput> Create('):]
(root/'tests/Presentation/ArturRios.Cerberus.WebApi.Tests/RecordUpdateHttpTests.cs').write_text(s)
print('UC19 actual HTTP failing matrix written before route/DI.')
