using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using ArturRios.Cerberus.Command.Profiles;
using ArturRios.Cerberus.Command.Folders;
using ArturRios.Cerberus.Domain.Access;
using ArturRios.Cerberus.Domain.Accounts;
using ArturRios.Cerberus.Domain.Profiles;
using ArturRios.Cerberus.Domain.Protection;
using ArturRios.Cerberus.Domain.Folders;
using ArturRios.Cerberus.Domain.Resources;
using ArturRios.Cerberus.Query.Profiles;
using ArturRios.Cerberus.TestSupport;
using ArturRios.Configuration.Enums;
using ArturRios.Output;
using ArturRios.Util.Test.Functional;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;

namespace ArturRios.Cerberus.WebApi.Tests;

[Collection("Registration host")]
public class FolderCreateHttpTests(RegistrationApiFixture fixture):WebApiTest<Program>(EnvironmentType.Local)
{
    [FunctionalTheory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)][InlineData(true,true)]
    public async Task GivenAccountWideHandle_WhenCreatingOpaqueFolder_ThenPersistOwnedContentAndReturnOnlyMetadata(bool profiles,bool folder)
    {
        using var owner=new ProtectionFixture();using var first=new ProtectionFixture();using var second=new ProtectionFixture();var s=await Setup(owner);var f=folder?await Folder(s):null;var parents=profiles?new[]{await Profile(s,owner,first,f),await Profile(s,owner,second,f)}:[];var input=Input(parents.Select(x=>x.PublicId).ToArray(),f?.PublicId);var protectedBefore=await Protected(s);
        using var response=await Send(s,input);var result=await Success<CreateFolderOutput>(response,201);Fields(result,"folderId","revision","serverSequence","editedAt");Assert.Equal(input.FolderId,result.FolderId);Assert.Equal(1,result.Revision);Assert.True(result.ServerSequence>0);Assert.Equal(Normalize(input.EditedAt),result.EditedAt);Assert.Equal(protectedBefore,await Protected(s));
        await using var db=fixture.Context();var row=await db.Folders.SingleAsync(x=>x.PublicId==input.FolderId);Assert.Equal(s.InternalId,row.AccountId);Assert.Equal(Bytes(input.Envelope),row.Envelope);Assert.Equal(f?.Id,row.ParentFolderId);Assert.Equal(result.ServerSequence,row.ServerSequence);Assert.Equal(result.EditedAt,row.EditedAt);
        foreach(var p in parents){using var get=await Read(s,"/api/profiles/"+p.PublicId);var detail=await Success<ProfileDetailsOutput>(get,200);Assert.Contains(input.FolderId,detail.FolderIds);Assert.Equal(2,detail.Revision);var current=await db.Profiles.AsNoTracking().SingleAsync(x=>x.Id==p.Id);Assert.Equal(p.Envelope,current.Envelope);Assert.Equal(p.KeyWrappers,current.KeyWrappers);Assert.Equal(p.EditedAt,current.EditedAt);}
        using var list=await Read(s,"/api/profiles");var visible=await Success<ProfileListOutput>(list,200);foreach(var p in parents)Assert.Contains(input.FolderId,visible.Items.Single(x=>x.ProfileId==p.PublicId).FolderIds);
        if(f is not null){var current=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==f.Id);Assert.Equal(2,current.Revision);Assert.Equal(f.EditedAt,current.EditedAt);Assert.Equal(f.Envelope,current.Envelope);}
    }
    [FunctionalTheory][InlineData("Master","none")][InlineData("Master","direct")][InlineData("Master","descendant")][InlineData("PerProfile","none")][InlineData("PerProfile","direct")][InlineData("PerProfile","descendant")]
    public async Task GivenFreshNativeSelectedHandle_WhenCreating_ThenOnlyNewContentInsideSelectionBecomesVisible(string mode,string placement)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var target=placement=="descendant"?await Folder(s,root.Id):root;var p=await Profile(s,owner,scoped,root,mode);var other=await Profile(s,owner,otherKey);var access=await Open(s,p,scoped);var selected=s with{Access=access};var input=Input([p.PublicId],placement=="none"?null:target.PublicId);using var response=await Send(selected,input);await Success<CreateFolderOutput>(response,201);
        using var get=await Read(selected,"/api/profiles/"+p.PublicId);var detail=await Success<ProfileDetailsOutput>(get,200);Assert.Contains(input.FolderId,detail.FolderIds);Assert.Equal(new[]{root.PublicId,input.FolderId}.Order(),detail.FolderIds.Order());Assert.Equal(2,detail.Revision);using var list=await Read(selected,"/api/profiles");var item=Assert.Single((await Success<ProfileListOutput>(list,200)).Items);Assert.Equal(p.PublicId,item.ProfileId);Assert.Contains(input.FolderId,item.FolderIds);using var outside=await Read(selected,"/api/profiles/"+other.PublicId);await Failure(outside,404);
        await using var db=fixture.Context();OpaqueAccessHandle.TryHash(access,out var verifier);Assert.Equal(p.Id,(await db.VaultAccessSessions.SingleAsync(x=>x.HandleVerifier==verifier)).ProfileId);Assert.Equal(1,(await db.Profiles.SingleAsync(x=>x.Id==other.Id)).Revision);
    }
    [FunctionalTheory][InlineData("empty",403)][InlineData("other",404)][InlineData("multiple",404)][InlineData("folder",404)]
    public async Task GivenNativeSelectedHandle_WhenExpandingSelection_ThenRejectWithoutMutation(string kind,int status)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await Setup(owner);var p=await Profile(s,owner,scoped);var other=await Profile(s,owner,otherKey);var f=await Folder(s);s=s with{Access=await Open(s,p,scoped)};var input=Input(kind=="empty"?[]:kind=="other"?[other.PublicId]:kind=="multiple"?[p.PublicId,other.PublicId]:[p.PublicId],kind=="folder"?f.PublicId:null);var before=await Snapshot(s);using var r=await Send(s,input);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly)][InlineData(CollectionGrantAccess.ReadWrite)]
    public async Task GivenForeignCollectionGrant_WhenCreatingInForeignFolder_ThenOwnershipStillDeniesCreation(CollectionGrantAccess access)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await Setup(owner);var s=await Setup(recipient);var f=await Folder(foreign);await using(var db=fixture.Context()){var collection=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=foreign.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(collection);await db.SaveChangesAsync();var id=Guid.NewGuid();db.CollectionGrants.Add(new(){PublicId=id,CollectionId=collection.Id,RecipientAccountId=s.InternalId,Access=access,RecipientKeyEnvelope=Bytes(owner.WrapGrant(foreign.AccountId,collection.PublicId,id,s.Actor,recipient.Material.RecipientKey))});await db.SaveChangesAsync();}var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);using var r=await Send(s,Input([],f.PublicId));await Failure(r,404);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalTheory][InlineData("profileMissing")][InlineData("profileForeign")][InlineData("profileTrash")][InlineData("profileTerminal")][InlineData("folderMissing")][InlineData("folderForeign")][InlineData("folderTrash")][InlineData("folderTerminal")][InlineData("ancestorTrash")][InlineData("ancestorTerminal")]
    public async Task GivenHiddenRelationship_WhenCreating_Then404WithoutPartialChanges(string kind)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var foreign=await Setup(owner);var p=await Profile(kind=="profileForeign"?foreign:s,owner,scoped);var root=await Folder(kind=="folderForeign"?foreign:s);var folder=kind.StartsWith("ancestor",StringComparison.Ordinal)?await Folder(s,root.Id):root;var input=Input([kind=="profileMissing"?Guid.NewGuid():p.PublicId],kind=="folderMissing"?Guid.NewGuid():folder.PublicId);
        await using(var db=fixture.Context()){if(kind=="profileTrash")await db.Profiles.Where(x=>x.Id==p.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind is "folderTrash" or "ancestorTrash")await db.Folders.Where(x=>x.Id==(kind=="folderTrash"?folder.Id:root.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));if(kind.EndsWith("Terminal",StringComparison.Ordinal))db.TerminalErasures.Add(new(){ResourceId=kind=="profileTerminal"?p.PublicId:kind=="ancestorTerminal"?root.PublicId:folder.PublicId,ResourceKind=kind=="profileTerminal"?"profile":"folder",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
        var before=await Snapshot(s);using var r=await Send(s,input);await Failure(r,404,"not_found");Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("missing",404)][InlineData("closing",404)][InlineData("terminal",404)][InlineData("revoked",403)][InlineData("expired",403)][InlineData("future",403)][InlineData("policy",403)][InlineData("generation",403)][InlineData("dangling",403)]
    public async Task GivenInvalidLifecycleOrSession_WhenCreating_ThenFailClosed(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);await using(var db=fixture.Context()){var v=await db.VaultAccessSessions.SingleAsync(x=>x.AccountId==s.InternalId);if(kind=="revoked")v.Revoked=true;if(kind=="expired")v.ExpiresAt=DateTimeOffset.UtcNow.AddSeconds(-1);if(kind=="future")v.IssuedAt=DateTimeOffset.UtcNow.AddHours(1);if(kind=="policy")v.PolicyRevision++;if(kind=="generation")v.RevocationGeneration++;if(kind=="dangling")v.ProfileId=long.MaxValue;if(kind=="closing")await db.Accounts.Where(x=>x.Id==s.InternalId).ExecuteUpdateAsync(x=>x.SetProperty(a=>a.State,AccountState.ClosurePending));if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=s.AccountId,ResourceKind="account",DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);if(kind=="missing"){var actor=Guid.NewGuid();fixture.Users[actor+"@example.test"]=new(actor,"fixture-password");s=s with{Actor=actor};}using var r=await Send(s,Input());await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("missing",401)][InlineData("wrongScope",401)][InlineData("deleted",401)][InlineData("unavailable",503)]
    public async Task GivenInvalidCurrentIdentity_WhenCreating_ThenRejectWithoutPersistence(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);if(kind is "deleted" or "unavailable")fixture.Users[s.Actor+"@example.test"]=new(s.Actor,"fixture-password",Deleted:kind=="deleted",IdentityUnavailable:kind=="unavailable");var before=await Snapshot(s);using var request=Request(s,Bytes(Input()));request.Headers.Authorization=kind=="missing"?null:new("Bearer",RegistrationApiFixture.Token(s.Actor,kind=="wrongScope"?Guid.NewGuid():null));using var r=await Gateway.Client.SendAsync(request);await Failure(r,status);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("active")][InlineData("trash")][InlineData("foreign")][InlineData("terminal")]
    public async Task GivenReservedFolderId_WhenCreating_Then409PreservesWinningState(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var other=kind=="foreign"?await Setup(owner):s;var input=Input();await using(var db=fixture.Context()){if(kind=="terminal")db.TerminalErasures.Add(new(){ResourceId=input.FolderId,ResourceKind="folder",DeletedAt=DateTimeOffset.UtcNow});else db.Folders.Add(new(){PublicId=input.FolderId,AccountId=other.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch,DeletedAt=kind=="trash"?DateTimeOffset.UtcNow:null});await db.SaveChangesAsync();}var before=await Snapshot(s);using var r=await Send(s,input);await Failure(r,409,"revision_conflict");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenConcurrentDuplicateRequests_WhenCreating_ThenExactlyOneHttpWinner(bool differentOwners)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var other=differentOwners?await Setup(owner):s;var input=Input();var responses=await Task.WhenAll(Send(s,input),Send(other,input));try{await Success<CreateFolderOutput>(Assert.Single(responses,x=>x.StatusCode==HttpStatusCode.Created),201);await Failure(Assert.Single(responses,x=>x.StatusCode!=HttpStatusCode.Created),409);}finally{foreach(var r in responses)r.Dispose();}await using var db=fixture.Context();Assert.Single(await db.Folders.Where(x=>x.PublicId==input.FolderId).ToArrayAsync());}
    [FunctionalFact]
    public async Task GivenLinkWriteOutage_WhenCreating_Then503RollsBackAndSameIdCanRetry()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var p=await Profile(s,owner,scoped);var input=Input([p.PublicId]);var before=await Snapshot(s);await using var db=fixture.Context();await db.Database.ExecuteSqlRawAsync("CREATE FUNCTION cerberus.reject_http_folder_fixture() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic folder link outage' USING ERRCODE='08006'; END $$; CREATE TRIGGER reject_http_folder_fixture BEFORE INSERT ON cerberus.profile_folder FOR EACH ROW EXECUTE FUNCTION cerberus.reject_http_folder_fixture();");try{using var failed=await Send(s,input);await Failure(failed,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(s));}finally{await db.Database.ExecuteSqlRawAsync("DROP TRIGGER IF EXISTS reject_http_folder_fixture ON cerberus.profile_folder; DROP FUNCTION IF EXISTS cerberus.reject_http_folder_fixture();");}using var retry=await Send(s,input);await Success<CreateFolderOutput>(retry,201);}
    [FunctionalFact]
    public async Task GivenUnavailableFolderTable_WhenCreating_Then503AndNoParentChanges()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var before=await Snapshot(s);await using var db=fixture.Context();await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.folder RENAME TO fixture_unavailable_folder");try{using var r=await Send(s,Input());await Failure(r,503,"persistence_unavailable");}finally{await db.Database.ExecuteSqlRawAsync("ALTER TABLE cerberus.fixture_unavailable_folder RENAME TO folder");}Assert.Equal(before,await Snapshot(s));}
    public static TheoryData<string> InvalidBodies=>new("missingFolderId","missingEnvelope","missingEditedAt","missingProfileIds","nullEnvelope","nullProfiles","emptyId","emptyFolder","selfParent","duplicateProfiles","zeroProfile","badFormat","epoch0","epoch2","badSalt","paddedNonce","emptyCiphertext","badTag","timeOffset","timeDefault","time9Ticks","actor","accountId","vaultAccess","name","fields","templateId","collectionIds","unknown","duplicate","case","numeric","fraction","nestedUnknown","uppercaseId","invalidUtf8","bom","gzip","charset","oversized","null","array");
    [FunctionalTheory][MemberData(nameof(InvalidBodies))]
    public async Task GivenMalformedOrForgedBody_WhenCreating_ThenRejectWithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var input=Input();var body=JsonSerializer.SerializeToNode(input,ProtectionFixture.Json)!.AsObject();var envelope=body["envelope"]!.AsObject();
        var missing=kind switch{"missingFolderId"=>"folderId","missingEnvelope"=>"envelope","missingEditedAt"=>"editedAt","missingProfileIds"=>"profileIds",_=>null};if(missing is not null)body.Remove(missing);
        if(kind=="nullEnvelope")body["envelope"]=null;if(kind=="nullProfiles")body["profileIds"]=null;if(kind=="emptyId")body["folderId"]=Guid.Empty;if(kind=="emptyFolder")body["parentFolderId"]=Guid.Empty;if(kind=="selfParent")body["parentFolderId"]=input.FolderId;if(kind=="duplicateProfiles")body["profileIds"]=new JsonArray(JsonValue.Create(s.Actor),JsonValue.Create(s.Actor));if(kind=="zeroProfile")body["profileIds"]=new JsonArray(JsonValue.Create(Guid.Empty));
        if(kind=="badFormat")envelope["format"]="unknown";if(kind is "epoch0" or "epoch2")envelope["keyEpoch"]=kind=="epoch0"?0:2;if(kind=="badSalt")envelope["keySalt"]="bad";if(kind=="paddedNonce")envelope["nonce"]=envelope["nonce"]!.GetValue<string>()+"=";if(kind=="emptyCiphertext")envelope["ciphertext"]="";if(kind=="badTag")envelope["tag"]="bad";
        if(kind=="timeOffset")body["editedAt"]=DateTimeOffset.UnixEpoch.ToOffset(TimeSpan.FromHours(1));if(kind=="timeDefault")body["editedAt"]=default(DateTimeOffset);if(kind=="time9Ticks")body["editedAt"]=new DateTimeOffset(9,TimeSpan.Zero);if(kind is "actor" or "accountId" or "vaultAccess" or "name" or "fields" or "templateId" or "collectionIds" or "unknown")body[kind]=null;if(kind=="nestedUnknown")envelope["name"]="plaintext";if(kind=="numeric")envelope["keyEpoch"]="1";if(kind=="fraction")envelope["keyEpoch"]=1.5;if(kind=="uppercaseId")body["folderId"]="ABCDEFAB-1234-1234-1234-ABCDEFABCDEF";
        var raw=body.ToJsonString();if(kind=="duplicate")raw=raw.Insert(1,"\"profileIds\":[],");if(kind=="case")raw=raw.Replace("profileIds","ProfileIds");if(kind=="null")raw="null";if(kind=="array")raw="[]";if(kind=="oversized")raw=new string(' ',65537)+raw;var bytes=kind=="invalidUtf8"?new byte[]{255}:kind=="bom"?new byte[]{239,187,191}.Concat(Encoding.UTF8.GetBytes(raw)).ToArray():Encoding.UTF8.GetBytes(raw);var before=await Snapshot(s);using var request=Request(s,bytes);if(kind=="gzip")request.Content!.Headers.ContentEncoding.Add("gzip");if(kind=="charset")request.Content!.Headers.ContentType!.CharSet="iso-8859-1";using var r=await Gateway.Client.SendAsync(request);await Failure(r,kind=="oversized"?413:400,kind=="oversized"?null:"validation_failed");Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("missing",401)][InlineData("bad",400)][InlineData("duplicate",400)][InlineData("empty",400)][InlineData("query",400)]
    public async Task GivenMalformedAccessHeaderOrQuery_WhenCreating_ThenRejectWithoutMutation(string kind,int status)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var before=await Snapshot(s);var raw=Bytes(Input());if(kind=="empty"){using var host=new WebApplicationFactory<Program>();var context=await host.Server.SendAsync(c=>{c.Request.Method="POST";c.Request.Path="/api/folders";c.Request.Headers.Authorization="Bearer "+RegistrationApiFixture.Token(s.Actor);c.Request.Headers["X-Cerberus-Vault-Access"]="";c.Request.ContentType="application/json";c.Request.Body=new MemoryStream(raw);c.Request.ContentLength=raw.Length;});Assert.Equal(status,context.Response.StatusCode);Assert.Contains("no-store",context.Response.Headers.CacheControl.ToString());}else{using var request=Request(s,raw,kind=="query"?"/api/folders?unexpected=1":"/api/folders");if(kind=="missing")request.Headers.Remove("X-Cerberus-Vault-Access");if(kind=="bad"){request.Headers.Remove("X-Cerberus-Vault-Access");request.Headers.TryAddWithoutValidation("X-Cerberus-Vault-Access","bad");}if(kind=="duplicate")request.Headers.TryAddWithoutValidation("X-Cerberus-Vault-Access",s.Access);using var r=await Gateway.Client.SendAsync(request);await Failure(r,status);}Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("minimum")][InlineData("pre2000")][InlineData("maximum")][InlineData("precision")]
    public async Task GivenSupportedTimestamp_WhenCreatingThroughHttp_ThenReturnStoredMicrosecondFloor(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var input=Input() with{EditedAt=kind=="maximum"?DateTimeOffset.MaxValue:kind=="minimum"?new(10,TimeSpan.Zero):kind=="pre2000"?new DateTimeOffset(1999,12,31,23,59,59,TimeSpan.Zero).AddTicks(19):DateTimeOffset.UnixEpoch.AddTicks(19)};using var r=await Send(s,input);var result=await Success<CreateFolderOutput>(r,201);Assert.Equal(Normalize(input.EditedAt),result.EditedAt);await using var db=fixture.Context();Assert.Equal(result.EditedAt,(await db.Folders.SingleAsync(x=>x.PublicId==input.FolderId)).EditedAt);}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenHttpCreatedFolder_WhenRotatingContent_ThenRequireCompleteInventoryAndPreserveEditedAt(bool complete)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var input=Input();using(var created=await Send(s,input))await Success<CreateFolderOutput>(created,201);var content=new List<ContentReplacement>{new("account",s.AccountId,1,Envelope(2))};if(complete)content.Add(new("folder",input.FolderId,1,Envelope(2)));var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),content.ToArray());var raw=Bytes(change);
        using var challengeRequest=new HttpRequestMessage(HttpMethod.Post,"/api/vault/challenges"){Content=JsonContent.Create(new{operation="change-protection",requestHash=ProtocolBinary.Encode(SHA256.HashData(raw))})};challengeRequest.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));using var issued=await Gateway.Client.SendAsync(challengeRequest);Assert.Equal(HttpStatusCode.Created,issued.StatusCode);using var document=JsonDocument.Parse(await issued.Content.ReadAsStringAsync());var challenge=document.RootElement.GetProperty("data").GetProperty("challenge").Deserialize<VaultProofChallenge>(ProtectionFixture.Json)!;var before=await Snapshot(s);
        using var request=Request(s,raw,"/api/vault/protection");request.Method=HttpMethod.Put;request.Headers.Add("X-Cerberus-Challenge-Id",challenge.ChallengeId.ToString());request.Headers.Add("X-Cerberus-Proof",owner.Sign(challenge));using var response=await Gateway.Client.SendAsync(request);if(!complete){await Failure(response,400,"validation_failed");Assert.Equal(before,await Snapshot(s));}else{Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.True(response.Headers.CacheControl?.NoStore);await using var db=fixture.Context();var folder=await db.Folders.SingleAsync(x=>x.PublicId==input.FolderId);Assert.Equal(2,folder.Revision);Assert.Equal(Bytes(content[1].Envelope),folder.Envelope);Assert.Equal(Normalize(input.EditedAt),folder.EditedAt);Assert.True((await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==challenge.ChallengeId)).Consumed);using var stale=await Send(s,Input());await Failure(stale,403);}
    }
    private sealed record State(Guid Actor,Guid AccountId,long InternalId,string Access);
    private async Task<State> Setup(ProtectionFixture client)
    {var actor=Guid.NewGuid();fixture.Users[actor+"@example.test"]=new(actor,"fixture-password");await using var db=fixture.Context();var account=new Account{PublicId=Guid.NewGuid(),HeimdallPublicId=actor,DetailsEnvelope=Bytes(Envelope())};db.Accounts.Add(account);await db.SaveChangesAsync();var access=ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32));OpaqueAccessHandle.TryHash(access,out var verifier);db.VaultProtections.Add(new(){AccountId=account.Id,Material=Bytes(client.Material)});db.VaultAccessSessions.Add(new(){AccountId=account.Id,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return new(actor,account.PublicId,account.Id,access);}
    private async Task<VaultFolder> Folder(State s,long? parent=null){var f=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.Context();db.Folders.Add(f);await db.SaveChangesAsync();return f;}
    private async Task<Profile> Profile(State s,ProtectionFixture owner,ProtectionFixture scoped,VaultFolder? folder=null,string mode="Master")
    {var id=Guid.NewGuid();var input=new ProfileCreateInput(id,Envelope(),new(mode,scoped.Material.UnlockVerifier,owner.Wrap(s.AccountId,"profile",id,s.Actor),mode=="PerProfile"?scoped.Material.PasswordWrapper:null),DateTimeOffset.UnixEpoch,[],folder is null?[]:[folder.PublicId],[]);using var request=Request(s,Bytes(input),"/api/profiles");using var r=await Gateway.Client.SendAsync(request);Assert.Equal(HttpStatusCode.Created,r.StatusCode);await using var db=fixture.Context();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task<string> Open(State s,Profile p,ProtectionFixture scoped)
    {var raw=Bytes(new{expectedRevision=1});using var challengeRequest=Request(s,Bytes(new{expectedRevision=1,requestHash=ProtocolBinary.Encode(SHA256.HashData(raw))}),"/api/profiles/"+p.PublicId+"/access/challenges");challengeRequest.Headers.Remove("X-Cerberus-Vault-Access");using var issued=await Gateway.Client.SendAsync(challengeRequest);var challenge=(await Success<IssueProfileAccessChallengeOutput>(issued,201)).Challenge;using var open=Request(s,raw,"/api/profiles/"+p.PublicId+"/access");open.Headers.Remove("X-Cerberus-Vault-Access");open.Headers.Add("X-Cerberus-Challenge-Id",challenge.ChallengeId.ToString());open.Headers.Add("X-Cerberus-Proof",scoped.Sign(challenge));using var response=await Gateway.Client.SendAsync(open);return (await Success<OpenProfileAccessOutput>(response,200)).VaultAccess;}
    private static FolderCreateInput Input(Guid[]? profiles=null,Guid? folder=null)=>new(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch.AddTicks(19),profiles??[],folder);
    private static EncryptedEnvelope Envelope(long epoch=1)=>new("cerberus-content-v1",epoch,ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(32)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(12)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(73)),ProtocolBinary.Encode(RandomNumberGenerator.GetBytes(16)));
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
    private static DateTimeOffset Normalize(DateTimeOffset value)=>value.AddTicks(-(value.Ticks%10));
    private static HttpRequestMessage Request(State s,byte[] body,string path="/api/folders"){var r=new HttpRequestMessage(HttpMethod.Post,path){Content=new ByteArrayContent(body)};r.Content.Headers.ContentType=new("application/json");r.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));r.Headers.Add("X-Cerberus-Vault-Access",s.Access);return r;}
    private async Task<HttpResponseMessage> Send(State s,FolderCreateInput input){using var request=Request(s,Bytes(input));return await Gateway.Client.SendAsync(request);}
    private async Task<HttpResponseMessage> Read(State s,string path){using var request=new HttpRequestMessage(HttpMethod.Get,path);request.Headers.Authorization=new("Bearer",RegistrationApiFixture.Token(s.Actor));request.Headers.Add("X-Cerberus-Vault-Access",s.Access);return await Gateway.Client.SendAsync(request);}
    private async Task<string> Protected(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Account=await db.Accounts.AsNoTracking().SingleAsync(x=>x.Id==s.InternalId),Protection=await db.VaultProtections.AsNoTracking().SingleAsync(x=>x.AccountId==s.InternalId),Sessions=await db.VaultAccessSessions.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync()});}
    private async Task<string> Snapshot(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Protected=await Protected(s),Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync()});}
    private static async Task<T> Success<T>(HttpResponseMessage r,int status) where T:class{Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);var result=await r.Content.ReadFromJsonAsync<DataOutput<T>>();Assert.True(result!.Success);return Assert.IsType<T>(result.Data);}
    private static void Fields(object value,params string[] names){using var d=JsonDocument.Parse(JsonSerializer.Serialize(value,ProtectionFixture.Json));Assert.Equal(names.Order(),d.RootElement.EnumerateObject().Select(x=>x.Name).Order());}
    private static async Task Failure(HttpResponseMessage r,int status,string? error=null){Assert.Equal((HttpStatusCode)status,r.StatusCode);Assert.True(r.Headers.CacheControl?.NoStore);if(status==413){Assert.Equal("",await r.Content.ReadAsStringAsync());return;}using var d=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.False(d.RootElement.GetProperty("success").GetBoolean());if(d.RootElement.TryGetProperty("data",out var data))Assert.Equal(JsonValueKind.Null,data.ValueKind);if(error is not null)Assert.Contains(error,d.RootElement.GetProperty("errors").EnumerateArray().Select(x=>x.GetString()));}
}
