from pathlib import Path
import re
s=Path('/tmp/cerberus-uc22-worktree/tests/Infrastructure/ArturRios.Cerberus.Data.Tests/RecordCreateStoreTests.cs').read_text()
s=s.replace('Domain.Records','Domain.Folders').replace('Data.Records','Data.Folders').replace('RecordCreate','FolderCreate')
s=re.sub(r'\bRecordId\b','NewFolderId',s)
s=re.sub(r'\bFolderId\b','ParentFolderId',s)
s=re.sub(r'\bNewFolderId\b','FolderId',s)
s=s.replace('RecordIds','FolderIds').replace('ProfileRecords','ProfileFolders').replace('db.Records','db.Folders')
s=s.replace('cerberus.profile_record','cerberus.profile_folder').replace('cerberus.record','cerberus.folder').replace('reject_record_create_fixture','reject_folder_create_fixture')
s=s.replace('ResourceKind="record"','ResourceKind="folder"').replace('[InlineData("record",409)]','[InlineData("newFolder",409)]')
s=s.replace('new Terminal(fixture,id,kind)','new Terminal(fixture,id,kind=="newFolder"?"folder":kind)')
s=s.replace('Record','Folder').replace('record','newFolder')
s=s.replace('Assert.Equal(f is null?Array.Empty<Guid>():[f.PublicId],view.Data.FolderIds);','Assert.Equal((f is null?new[]{input.FolderId}:new[]{f.PublicId,input.FolderId}).Order(),view.Data.FolderIds.Order());')
s=s.replace('Folders=await db.Folders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=', 'Records=await db.Records.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Profiles=')
s=s.replace('ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileFolders=', 'ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),ProfileFolders=')
s=s.replace('[InlineData("pre2000")]','[InlineData("pre2000")][InlineData("maximum")]')
s=s.replace('EditedAt=kind=="minimum"?new(10,TimeSpan.Zero):','EditedAt=kind=="maximum"?DateTimeOffset.MaxValue:kind=="minimum"?new(10,TimeSpan.Zero):')
Path('/tmp/cerberus-uc23-data-tests.cs').write_text(s)
print('Prepared folder Data behavioral draft from established real PostgreSQL creation scenarios.')
