from pathlib import Path
import json,subprocess,hashlib,shutil
w=Path('/tmp/cerberus-uc28-worktree');primary=Path('/root/repositories/cerberus-api');p=primary/'.superpowers/checkpoints';d=json.loads((p/'open-issues-2026-10-08.json').read_text());assert d['nextUseCase']=='UC-28';previous=json.loads((p/'uc-27-2026-10-09-complete/cerberus-uc27-dod.json').read_text());assert previous['tests']==6110 and all(x['passed'] for x in previous['definitionOfDone']);base=previous['mergeCommit'];git=lambda *a:subprocess.check_output(['git',*a],cwd=w,text=True).strip();assert git('rev-parse','HEAD')==base and git('rev-parse','origin/develop')==base and git('branch','--show-current')=='feature/uc-28-move-folder' and not git('status','--porcelain');assert git('rev-parse','HEAD^{tree}')==git('rev-parse',previous['testedHead']+'^{tree}')
for f,s in d['preservedUserFilesSha256'].items():assert hashlib.sha256((primary/f).read_bytes()).hexdigest()==s
issue=json.loads(Path('/tmp/cerberus-uc28-issue.json').read_text());assert issue['number']==29 and issue['state']=='OPEN' and 'FR-FD-07, FR-FD-08' in issue['body']
rulings=[
'Ruling: Reuse freshly verified UC27 merged/tested baseline6110 with exact-headCI — new checkout tree equals tested5bff5e8 and all9DoD verified; final fresh newcheckout fullsuite remains mandatory — cost if wrong: environment/path differences require the fresh final run.',
'Ruling: Required nullable parentFolderId plus expectedRevision and four public output fields — follows UC21 structural move contract with explicit nullable parent serialization/no new proof challenge — cost if wrong: clients must send explicit null and use separate detail calls.',
'Ruling: Source folder-only PF/CF owner admission precedes destination/stale/cipher probing — all relevant native foreign contributors validate before403; record-only scope cannot admit a container — cost if wrong: corrupted overlapping authority can503 and record-only clients lack container navigation.',
'Ruling: Owner-visible root admits structural move of its active owned subtree but selected scope checks EACH typed member — every resulting profile AND collection set must be a subset of its own original set; account-wide access permits intentional expansion — cost if wrong: selected moves can require account-wide access even when both roots appear visible.',
'Ruling: Same-owner currently visible destination and explicit null only; visible self/descendant input400, hidden404, stored active cycle503 — invalid visible topology is input validation before stale metadata, without an inaccessible topology oracle — cost if wrong: clients must distinguish input correction from revision retry.',
'Ruling: Existing current native result collection/grant envelopes satisfy server AF06 binding requirements — verify every active resulting recipient binding/pins/epoch/revision, reject missing persisted envelope503; no new key input or usable server key/decryption claim — cost if wrong: external clients may need additional opaque provisioning before release.',
'Ruling: Strong own account lock plus all captured members and ordered collections/grants before content — serializes current owner topology/new entity FK and aligns recipient editors; no foreign account/profile/upward chain — cost if wrong: contention increases and BEFOREUC35 recipient-FK audit remains mandatory.',
'Ruling: Capture complete active subtree/direct links/per-member current-result scope/native evidence and compare again in final guard — new existing-row growth or unheld evidence needs409 reload rather than expanding captured locks after content — cost if wrong: harmless descendant edits or no-op races can require retry.',
'Ruling: Only moved root and distinct changed immediate old/new parents advance structural counters — direct links/ciphertext and descendant/profile/collection metadata remain unchanged; current GET/list recalculates inheritance — cost if wrong: UC48 must supply durable inherited visibility events before release.',
'Ruling: Current same-parent/null-to-null move advances root only and skips unchanged-parent counter validation — follows UC21 no-op behavior, while current member/native scope checks still apply — cost if wrong: callers can get a new root revision even when no organization changes.',
'Ruling: Independently trashed/typed terminal branches remain outside active move inventory — preserve original operations/deadlines/snapshots and typed reserved identities — cost if wrong: later restore must revalidate saved parent/membership against the changed active hierarchy.',
'Ruling: Validate supported target envelope and member structural metadata while retaining descendant opaque bytes — target matches existing structural move validation; descendants are not decrypted or rewritten — cost if wrong: damaged target content can block reorganization and damaged descendants may remain unreadable.',
'Ruling: Final guarded root write is statement-time atomic authorization boundary — recheck after every wait/current native evidence and complete scope, held locks allow completing after later natural expiry — cost if wrong: expiry after authorization does not cancel completion and out-of-band writers need their own audit.',
'Ruling: Target and changed-parent writes commit once or whole graph rolls back; global sequence gaps allowed — each committed changed row strictly advances and lost-success retry409 preserves the winner — cost if wrong: clients cannot assume contiguous numbering or replay stale expected revisions.',
'Ruling: Independent formal security/protocol/client approval remains development-only deferred — explicit user scope preserves ordinary ONEreview/native/audits/fullsuite/exactCI and release gates — cost if wrong: latent security/client integration defects still require independent qualification.',
]
assert len(rulings)==15
spec=w/'docs/superpowers/specs/2026-10-09-uc-28-move-folder.md';plan=w/'docs/superpowers/plans/2026-10-09-uc-28-move-folder.md';assert not spec.exists() and not plan.exists()
s=Path('/tmp/cerberus-uc28-spec.md').read_text().replace('This draft is prepared outside the checkout while UC27 is in CI; it must be verified against freshly loaded UC28 checkout specs after UC27 delivery before installation or runtime code.','The design was prepared outside the prior checkout, then verified against freshly loaded UC28 specifications after actual UC27 delivery. New checkout baseline equals the tested6110/green-CI merged tree; final fresh current suite remains mandatory.').replace('M03 20 /26','M03 20 / 26');spec.write_text(s)
s=Path('/tmp/cerberus-uc28-plan.md').read_text().replace('**20 /26closed**','**20 / 26 closed**');plan.write_text(s)
for s in (spec.read_text(),plan.read_text()):assert not any(x in s for x in ('TODO','TBD','FIXME','{{'))
script='/root/.codex/plugins/cache/openai-curated-remote/superpowers/6.4.2/skills/subagent-driven-development/scripts/sdd-workspace';workspace=Path(subprocess.check_output([script,str(plan)],cwd=w,text=True).strip());ledger=workspace/'progress.md';assert not ledger.exists();text='\n'.join(rulings)+'\n';Path('/tmp/cerberus-uc28-initial-rulings.txt').write_text(text)
ledger.write_text(f'# SDD ledger — plan: {plan}\n\nBase:{base}\nBranch:feature/uc-28-move-folder\nIssue29/UC28MoveFolder; authorized wholebatch automated gates/inlineTDD/ONEfinalreview.\n\n'+text+'\nPre-flight Task1→Task2: FolderMoveRequest(GuidActor,stringVerifier,GuidFolderId,longExpectedRevision,Guid?ParentFolderId), FolderMoveDetails(GuidFolderId,Guid?ParentFolderId,longRevision,longServerSequence), IFolderMoveStore.MoveAsync VResultDetails agree.\nPre-flight Task1+Task2→Task3: MoveFolderCommand/Handler/Validator/Output/Messages and FolderMoveStore explicitthreeDI agree; requirednullableparent+revision/fourpublicoutput.\nGate1: fresh issue29/UC28main+ALLAF01..06/FRFD07+08/BR07/current owner authorization+lifecycle/testing/technology/operations loaded from newcheckout. All9docbytes verified against draft source; spec/plan selfreview no placeholders/conflicting interfaces/undecided scope; per-member subset/current nativeAF06/5ReviewFocus have assigned tests. Three independently testable test-first tasks; proportionchecked. Baseline mergedtree==tested6110/exactCI/freshbase/4primarySHA; lockedrestore setup runs next. No runtime product/test implementation yet.\n')
a=p/'batch-review-decisions-2026-10-08.md';a.write_text(a.read_text()+'\n## UC28 initial decisions\n\n'+text)
x=next((x for x in d['useCases'] if x['id']=='UC-28'),None)
if x is None:x={'id':'UC-28','issue':{k:issue[k] for k in ('number','title','url','milestone')}};d['useCases'].append(x)
x.update({'status':'implementing','branch':'feature/uc-28-move-folder','worktree':str(w),'baseCommit':base,'ledger':str(ledger),'spec':str(spec),'plan':str(plan),'rulingCount':15,'completedTasks':[],'currentTask':'Task1 command RED after lockedrestore'});d.update({'currentUseCase':'UC-28','currentWorktree':str(w),'currentBranch':'feature/uc-28-move-folder','currentLedger':str(ledger),'currentHead':base,'status':'implementing'})
resume='UC27COMPLETE PR88merge5c56159/issue28Closed9DoD+Done/remoteabsent/tested6110tree/all32Rulings3Minors ownarchiveSHA verified beforeUC27SDD cleanup;28UCsDone. UC28 newworktree /tmp/cerberus-uc28-worktree branchfeature/uc-28-move-folder base5c5615935786da2ecc8d82b447fbb6d99d85c481, freshall9specdocbytecheck/main+AF01..06/Gate1/selfreview done. Spec+plan installed/all15initialRulings+ledger/aggregate. Lockedrestore setup then issue29InProgress/taskstart1/fullbrief/installed genuine missing-contract RED BEFOREproduct. NoUC28runtime/testfiles yet; finalwhole6suite/ONEreview/exactCI remain mandatory. 4primarySHA untouched. Preserve independentdevelopment-only deferrals.'
for k in ('currentTask','resumeInstruction','requiredToResume'):d[k]=resume
for k in ('activeExecSession','activeTestLog'):d.pop(k,None)
(p/'open-issues-2026-10-08.json').write_text(json.dumps(d,indent=2)+'\n');print('UC28 freshspec/plan/selfreview/Gate1/all15Rulings/ledger/checkpoint initialized; no runtime/test code.')
