from pathlib import Path
import subprocess,json,re
w=Path('/tmp/cerberus-uc28-worktree');base='5c5615935786da2ecc8d82b447fbb6d99d85c481'
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip();plan=w/'docs/superpowers/plans/2026-10-09-uc-28-move-folder.md';spec=w/'docs/superpowers/specs/2026-10-09-uc-28-move-folder.md';ledger=w/'.superpowers/sdd/2026-10-09-uc-28-move-folder/progress.md'
assert 'Task 3: complete' in ledger.read_text(),'Review cannot start before all3tasks complete.'
focus=plan.read_text().split('## Review Focus\n',1)[1].split('\n### Task 1:',1)[0].strip()
script='/root/.codex/plugins/cache/openai-curated-remote/superpowers/6.4.2/skills/subagent-driven-development/scripts/review-package'
print(subprocess.check_output([script,str(plan),base,head],cwd=w,text=True))
template=Path('/root/.codex/plugins/cache/openai-curated-remote/superpowers/6.4.2/skills/requesting-code-review/code-reviewer.md').read_text()
context=f'''Exactly ONE fresh ordinary whole-branch review of UC28MoveFolder(issue29). Worktree {w}, branchfeature/uc-28-move-folder. ALL3 inlineTDDtasks complete. Base {base}; Head {head}.
Spec: {spec}\nPlan: {plan}\nLedger ALL Ruling lines: {ledger}\nAll initial18Rulings must be weighed, including actual test-fixture corrections and the explicit scope-algebra derivation. The derivation does NOT remove production per-member checks: before/result PF/PR/CF/CR/PC collection+profile subsets are correlated by typed(kind,memberid). A root-passes/descendant-only new inherited scope is impossible under stable current inheritance because descendants inherit root sets and direct links are unchanged. Independently judge this; flag a genuine counterexample rather than accept the author's statement. Tests exercise actual destination expansion with descendant/directrecord overlaps and required native grants applying only to descendants. Original five Review Focus lines are copied below verbatim.
What implemented: strict requiredrevision+explicitnullableparentfolderId command/fourfield output/real canonical serializerfixture; dedicated FolderMoveStore current folder-only owner root/destination scope, completeactive mixedsubtree/typedterminal exclusions, simulatedbefore/resultpermemberpaths+two subsetsets, all current active resulting nativebindings with perpin cache, strong ownaccount/session thenselectedprofile/sortedcollections+grants beforecapturedfolders/records/directlinks, currentauth afterwaits/fullstableinventory and finalrootguard, root+distinctchangedimmediateparent metadataonly/atomicrollback/nooprootonly; strictnative PUT /api/folders/{{id}}/parent + exactly3DI, explicitdocumentation/release limits/OpenAPI. No migration/newdependencies/keys/serverdecrypt.
Fresh actual fullcoverage log /tmp/cerberus-uc28-coverage.log, Summary {w}/docs/coverage-report/Summary.json and /tmp/cerberus-uc28-coverage-evidence.json: expected6558 but actual audit must agree. FamiliesDomain361 Shared125 Query411 Command1076 Data2456 WebApi2129; all0fail0skip/all6productionassemblies>=90line/aggregatebranch reported. Focus89Command/211Data/148HTTP. Actual taskfamilyfull1076+2456 and exactstore/testSHA audit. No productruntimecorrection: genuine missingtypesCommandRED then87/2 plainserializerfixture failure fixedusingactualsourceLinkedCanonicalGuidConverter; Data207initial202PASS/5FAIL solely record-growthfixture alreadycontained +old-onlyfolderlistretainsunmovedparent, actual211(after4fullancestryguard cases)PASS; HTTP148RED147missingroute404+1oversizePASS eachcasegraded no native prerequisitesfailed, actual148 firstpostendpointGREEN. Logs /tmp/cerberus-uc28-*. No tests disabled/removed.
Native races: ownerfolder/recordcreate/recordmove/profileassociation/trash/rotation serialization, recipientrootfolder/childfolder/containedrecordedit bothcollectionorders, reciprocalmoves inbothorders, expiryatsevenue waits+finalrootguard, capturedexistingmember/typedlinkgrowth andnewvalidunheldgrant409/newcorrupt503, actualrecipientnativeproofrotation beforeguard validchangedevidence409, fullgraph faults AFTERactualroot/firstparent/secondparentmutation(assertTriggered) andsequenceexhaustion/regressiontarget/parent, prioractualRecordTrash+FolderTrash independentdeadlines/snapshots, preciseimmutable fullgraphs. EXPLAIN actualroot1/sourceancestry3/destination1+2/tree2/members3/current+resultpaths11 among200unrelated and exact capturedfolder+parent/recordlocksets; bounded evidence, no productionload qualification.
Formal independent security/crypto/protocol and external-client qualification explicitly development-only deferred by user; retain ordinary code security review, nativechecks/audits/exactCI and release/main/tag gates. Existing supported native envelopes establishAF06 persistedbinding; no usable key/provisioning/decryption certification claimed. UC48 durableinheritedvisibility and UC50..53 revalidatedtrashrestore/physicalexpiry remainlaterrelease obligations. BEFOREUC35 implicitrecipient-account FK KEYSHARE vsstrongaccountwriters ismandatoryfutureaudit, notcertifiednewwriter safety.
Shared OpenAPI accessheader/requestbody optional/outputrequired[]/nullablewrapping and actualempty413advertisedProblemDetails are inheritedreleasefindings; re-grade practicaleffects. Input2requiredfields and parentnullableschema/8statuses/retainedroutes actual shapePASS. PriorUC27externalPurgeAtinventoryMinor outside thisdiff retained; this newstorechecks changedparentactivePurgeAt/time/counters and skipsisunchangedparents fornoop. Other priorUC25ctorrecordId/UC23 narrowfixtures/UC22permissionoutage500/UC21blank remainoutside-diffdeferred. Grade ordinary concrete user effects, no formalqualificationclaim.
Read-only review, no edits/checkouts/commits/branches/index mutations, no new reviewer/subagents/independent formal audit. No redundantfullsuite: inspectfresh output/evidence; targetedread-onlyreproduction if a concreteconcernneedsit. Cite actualfile:line and gradeCritical/Important/Minor byeffect. Give EVERYDeclinedtojudge line beforeverdict withreason; executor mustruleoneach. Save fullreport /tmp/cerberus-uc28-final-review.md. This is the solewholebranchreview; no re-review.
Verbatim Review Focus:\n{focus}\n\nALL current Rulings:\n'''+ '\n'.join(x for x in ledger.read_text().splitlines() if 'Ruling:' in x)
Path('/tmp/cerberus-uc28-review-prompt.md').write_text(template+'\n\n## Concrete UC28 package and evidence\n\n'+context+'\n')
print('Prompt prepared AFTERalltasks:',head,'Rulings:',sum('Ruling:' in x for x in ledger.read_text().splitlines()))
