from pathlib import Path
import json,hashlib,subprocess,re
w=Path('/tmp/cerberus-uc28-worktree');primary=Path('/root/repositories/cerberus-api');v=json.loads(Path('/tmp/cerberus-uc28-final-coverage-evidence.json').read_text());assert v['tests']==6559 and v['counts']['WebApi']==2130
for name,sha in json.loads(Path('/tmp/cerberus-uc28-final-tested-files-sha.json').read_text()).items():assert hashlib.sha256((w/name).read_bytes()).hexdigest()==sha,name
subprocess.run(['python3','/tmp/cerberus-uc28-verify-review-fix.py'],check=True)
subprocess.run(['git','diff','5c5615935786da2ecc8d82b447fbb6d99d85c481','--check'],cwd=w,check=True)
p=w/'.superpowers/sdd/2026-10-09-uc-28-move-folder/progress.md';s=p.read_text();assert 'Final: fixed' not in s
fixed=f'Final: fixed Important ineffective strict-body HTTP fixture — GivenUnmodifiedStrictBodyFixture_WhenMoving_ThenAcceptValidBodyAndReturnExactMetadata genuine realnative REDexpected200/actual400→GREEN with8fixturetyposcorrected; all38negativecases retained/focused149PASS; freshsuite6559/6559PASS0fail0skip ({v["lineCoverage"]}%line/{v["branchCoverage"]}%branch/all6asms>=90line). Productruntime unchanged. ONEfixpasscomplete/no secondreview.'
s+='\n'+fixed+'\nFinal review: ONE /root/uc28_final_review gpt6astra HIGHfreshfork complete; one Important verification defect fixed via actualcontrolRED→GREEN/freshfullsuite; two Minorsdeferred, all14declinedjudgments ruled withreasoncost. Ready for authorizeddevelopdelivery subject to exact-headCI and actualDoD.\n';p.write_text(s)
rulings=[x for x in s.splitlines() if 'Ruling:' in x];minors=[x for x in s.splitlines() if 'minor (deferred):' in x];assert len(rulings)==32 and len(minors)==2
validation={'tests':v['tests'],'families':v['counts'],'line':v['lineCoverage'],'branch':v['branchCoverage'],'log':'/tmp/cerberus-uc28-final-coverage.log','assemblies':v['assemblies']};Path('/tmp/cerberus-uc28-validation.json').write_text(json.dumps(validation,indent=2)+'\n')
text='\n'.join([
f'- Fresh post-correction unfiltered **{v["tests"]} PASS, zero failures/skips**: '+', '.join(f'{k} {n}' for k,n in v['counts'].items())+'.',
f'- Actual production coverage **{v["lineCoverage"]}% line / {v["branchCoverage"]}% aggregate branch**, all six assemblies at least90%line.',
'- Focused Command89/Data211/HTTP149. Genuine missing-contract/store RED before products; pre-endpointHTTP147missingroute404+1middlewarePASS. Task1/2 serializer/detached-record/old-route-list fixture corrections are recorded without claiming runtime product fixes.',
'- The sole fresh review found one Important verification defect: strict-body fixture used parentParentFolderId, so most prior38passes did not prove intended input checks. Added real valid-body control through the same fixture: genuine expected200/actual400 RED; corrected8fieldnames only, retained all38negativecases, actual149GREEN. Fresh whole6559PASS follows. No production runtime correction or second reviewer.',
'- Actual source/destination visibility, per-typed-member profile+collection subsets and native bindings needed ONLY by descendants/contained records, current recipient GET/list route changes, seven wait expiry phases/finalguard, captured member/link/grant growth and complete native protection inventory pass. Sole reviewer independently accepted the stable-inheritance algebra ruling while confirming each-member production checks remain.',
'- Controlled current owner create/move/association/trash/rotation, native recipient root/child/record edits inbothorders, reciprocal moves, fullgraph faults AFTERactualroot/firstparent/secondparent writes, sequenceexhaustion/regression and prior actual independent RecordTrash+FolderTrash deadlines/snapshots pass.',
'- Actual EXPLAIN target1/sourceancestry3/destination1+2/tree2/members3/current+resultpaths11 among200unrelated and exactcapturedfolder+parent/recordlocksets. Boundedshape evidence, no productionload certification.',
'- Fresh lockedrestore/direct+transitiveNuGet/nativeOSV153zero/nativecorpus322×4/helpers36+23/specs107FR55UC29BR/OpenAPIwrite+drift+exactshape/fullrangediffincludingnewfiles pass.',
'- ONE whole-branch review and ONE TDD correction pass complete; all14declined judgments have explicit final reason/cost dispositions and both inherited OpenAPI Minors are retained below. LatestexactHEAD branch-policy/test/docker remain mandatory delivery gates.',
])
body=Path('/tmp/cerberus-uc28-pr-body-draft.md').read_text().replace('{{VALIDATION}}',text).replace('{{RULINGS}}','\n\n'.join('- '+x for x in rulings)).replace('{{MINORS}}','\n\n'.join('- '+x for x in minors));assert '{{' not in body and all(x in body for x in rulings+minors);Path('/tmp/cerberus-uc28-pr-body.md').write_text(body);Path('/tmp/cerberus-uc28-rulings.txt').write_text('\n'.join(rulings+minors)+'\n')
p=primary/'.superpowers/checkpoints/batch-review-decisions-2026-10-08.md';p.write_text(p.read_text()+'\nUC28 Important correction evidence:\n\n'+fixed+'\n')
p=primary/'.superpowers/checkpoints/open-issues-2026-10-08.json';d=json.loads(p.read_text());x=next(x for x in d['useCases'] if x['id']=='UC-28');x.update({'status':'verified','reviewVerdict':'oneImportantfixtureFixedTDD_noRemainingBlockers','totalTests':v['tests'],'lineCoverage':v['lineCoverage'],'branchCoverage':v['branchCoverage'],'rulingCount':32,'deferredMinorCount':2,'currentTask':'commit verifiedfixturefix/normalpush/PR/exactCI delivery pending'});d['currentTask']=d['resumeInstruction']='UC28final6559PASS/focused149/oneImportantfixturecorrectedTDD/32allRulings+2Minors exhaustivePRbody+aggregate; commitfix/testedHEAD thenauthorizednormaldelivery/exactCI. UC29draftoutsideonly.';p.write_text(json.dumps(d,indent=2)+'\n')
print('Verified final6559PASS;32Rulings/2Minors/ImportantTDDproof exhaustive; fixcommit and authorized delivery next.')
