from pathlib import Path
import json,subprocess
w=Path('/tmp/cerberus-uc26-worktree');head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip();base=Path('/tmp/cerberus-uc26-base.txt').read_text().strip();workspace=w/'.superpowers/sdd/2026-10-09-uc-26-update-folder';l=(workspace/'progress.md').read_text();assert all(f'Task {n}: complete' in l for n in range(1,4));rulings=[x for x in l.splitlines() if 'Ruling:' in x];assert len(rulings)==10
v=json.loads(Path('/tmp/cerberus-uc26-validation.json').read_text());assert v['tests']==5780;assert not subprocess.check_output(['git','status','--porcelain'],cwd=w,text=True).strip();plan=w/'docs/superpowers/plans/2026-10-09-uc-26-update-folder.md';spec=w/'docs/superpowers/specs/2026-10-09-uc-26-update-folder.md';focus=plan.read_text().split('## Review Focus\n',1)[1].split('### Task 1:',1)[0];packages=list(workspace.glob('review-*.diff'));assert len(packages)==1
old=Path('/tmp/cerberus-uc25-review-prompt.md').read_text();tail=old.split('\n## Git Range to Review\n',1)[1].replace('955ca9db39753d27fda5cf2637f6e3970cfd6a1b',base).replace('36f93bc185fac8c8e31d47956216146101ad9c1d',head)
prompt=f'''You are a Senior Code Reviewer with expertise in software architecture,
design patterns, and best practices. Your job is to review completed work
against its plan or requirements and identify issues before they cascade.

## What Was Implemented

UC26 encrypted folder content replacement. PUT /api/folders/{{id}} requires current identity/vault access, canonical public path, no query and strict bounded JSON expectedRevision/envelope/editedAt. Exact four result fields folderId/revision/serverSequence/editedAt. Current owners/native RW recipients only, never record-only folder authority. Target+self complete same-owner ancestry, current database-time session/selection/typed lifecycle scope. Own account NO KEY UPDATE/session+selection UPDATE, ordered eligible collections/grants SHARE and only target folder NO KEY UPDATE; no foreign account/profile or upward/descendant locks. Reload after waits and verify every overlapping eligible native contributor with party pins once. Final recursive UPDATE guards full current write authority, expected revision/original envelope/old sequence and held verified contributor subsets. Target ciphertext/time/rev/globalseq/stamp change only; parent/children/records/profiles/collections/links/ownership unchanged. Hidden404 precedes content/native/stale; RO403, conflicts409, necessary corruption503, caller cancellation propagates. Same epoch; changed cipher requires fresh salt AND nonce; same cipher/older client time allowed. Row rollback for faults; sequence gaps allowed. No schema/dependency/crypto algorithm changes.

## Requirements / Plan

Read only {w}. Binding spec {spec}; completed plan {plan}; ledger {workspace}/progress.md; complete package {packages[0]}. All three tasks complete. Actual /tmp/cerberus-uc26-validation.json and coverage.log show fresh unfiltered5780PASS zero fail/skip: {json.dumps(v['families'])}; actual Summary {v['line']}%line/{v['branch']}%branch, all six production assemblies>=90line. Focused Command71/Data127/HTTP108, whole Command912/Data2098. Actual genuine missing-contract/store CS0246 and installed missing-PUT99fail/5middlewarepass104cases BEFORE production endpoint/DI. Initial Command implementation compile typo replaced two C# record keywords mechanically; restored only keywords, retained failure log; no runtime correction or separate RED claim. Initial Data duplicate namespace installation error excluded from genuineRED; corrected word-boundary draft rename and reran missing-storeRED. HTTPRED validator initially expected99 enum strings but actual98enum+1numeric405; interpretation corrected without product/test edit. First focused Data111 and HTTP104 green; sixteen Data and four HTTP extra boundary-confidence tests then extended already implemented behavior with no independentRED claims or product changes. Inspect real evidence, do not rerun builds/tests. Actual native/strict input/permission/concurrency behavior matters more than doc claims.

This is exactly ONE ordinary whole-branch review required by executing-plans. User deferred independent formal security/protocol/crypto and real external-client operability approval ONLY for develop; release/main/tag gates remain. Review current concrete ownership/native use/input/output/transactions/lifecycle/races, not formal certification or deployment. Ordinary locked restore/NuGet/native OSV153no findings/corpus322x4/helpers36+23/specs/OpenAPIwrite+drift+shape/range whitespace logs under /tmp/cerberus-uc26-*. Python helper printed89.9/90/94.7 are sample fixtures, not production Summary. Shared schema accessHeader/requestBody optional, allthree inner input required, four output fields required[] and actualempty413 advertisedProblemDetails are release follow-ups; grade actual effects explicitly. Inherited UC25 query ctor recordId parameter, UC23 narrowed grant/post-parent-failure fixtures, UC22 permission-outage500 classification and UC21 formatting blank remain outside this diff with recorded dispositions. UC26 actual record-only fixtures install real containing-folder associations and prove native record read/GET before folder denial. Native collection membership fixtures install real CF, creation race invokes actual FolderCreateStore and preserves its winning parent revision, rotation uses complete actual account/record/folder/collection/grant native inventory. Actual EXPLAIN asserts one candidate/three ancestry rows among100+ unrelated folders, one target folder lock and own account only. Defensive incomplete/cross-owner ancestry guard is SQL/schema assessed, no deliberate integrity-bypass fixture claimed. Production workloads unspecified; bounded traversal is not load certification. Durable ordered offline inherited visibility remains UC48 and real-client key provisioning/decryption requires release qualification. Future move/trash/restore/purge/physical erasure and mandatory BEFORE UC35 implicit recipient-account FK audit remain later gates. Historical UC25 baseline reused verified merged/tested tree+5474PASS/exactCI, then current UC26 fresh suite; executor provenance is not reviewer remote certification. Every behavior set aside belongs in Declined to judge with reason. No checkout/index/HEAD/branch edits, builds/test reruns, subagents or GitHub actions/approvals. Write ONLY /tmp/cerberus-uc26-final-review.md outside worktree, then return clear verdict and findings by actual effect with file:line. No second/duplicate reviewer.

Verbatim Review Focus:
{focus}
ALL rulings with reasons/costs:
'''+ '\n'.join(rulings)+'\n\n## Git Range to Review\n'+tail
assert '[HEAD_SHA]' not in prompt and '[BASE_SHA]' not in prompt;Path('/tmp/cerberus-uc26-review-prompt.md').write_text(prompt);Path('/tmp/cerberus-uc26-tested-head.txt').write_text(head+'\n');print('ONE review prompt complete:',head,'all10Rulings and actual5780PASS evidence')
