from pathlib import Path
import re
w=Path('/tmp/cerberus-uc24-worktree');src=(w/'tests/Presentation/ArturRios.Cerberus.WebApi.Tests/RecordListHttpTests.cs').read_text()
a=src.index('    [FunctionalFact]');b=src.index('    private async Task<RecordCreateInput> Create(')
prefix=src[:a].replace('RecordListHttpTests','FolderListHttpTests')
prefix=prefix.replace('using ArturRios.Cerberus.Command.Records;','using ArturRios.Cerberus.Command.Records;\nusing ArturRios.Cerberus.Command.Folders;').replace('using ArturRios.Cerberus.Domain.Records;','using ArturRios.Cerberus.Domain.Records;\nusing ArturRios.Cerberus.Domain.Folders;').replace('using ArturRios.Cerberus.Query.Records;','using ArturRios.Cerberus.Query.Records;\nusing ArturRios.Cerberus.Query.Folders;')
skip=('GivenFreshNativeSelectedHandle','GivenNativeRecipientCollectionGrant')
common=''
for s in re.split(r'(?m)(?=    \[Functional)',src[a:b]):
 if any(x in s for x in skip):continue
 s=s.replace('Record','Folder').replace('recordId','folderId').replace('/api/records','/api/folders').replace('"record"','"folder"').replace('collection_record','collection_folder')
 common+=s
helpers=src[b:]
start=helpers.index('    private async Task<(VaultCollection,CollectionGrant)> Share(');end=helpers.index('    private sealed class BodyFeature',start)
share=r'''    private async Task<(VaultCollection,CollectionGrant)> Share(State owner,ProtectionFixture author,State recipient,ProtectionFixture recipientKeys,CollectionGrantAccess access,Guid[] direct,long[] folders)
    {await using var db=fixture.Context();var collection=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=owner.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(collection);await db.SaveChangesAsync();var grant=new CollectionGrant{PublicId=Guid.NewGuid(),CollectionId=collection.Id,RecipientAccountId=recipient.InternalId,Access=access};grant.RecipientKeyEnvelope=Bytes(author.WrapGrant(owner.AccountId,collection.PublicId,grant.PublicId,recipient.Actor,recipientKeys.Material.RecipientKey));db.CollectionGrants.Add(grant);var ids=(await db.Folders.Where(x=>direct.Contains(x.PublicId)).Select(x=>x.Id).ToArrayAsync()).Concat(folders).Distinct();db.CollectionFolders.AddRange(ids.Select(id=>new CollectionFolder{AccountId=owner.InternalId,CollectionId=collection.Id,FolderId=id}));await db.SaveChangesAsync();return(collection,grant);}
'''
helpers=helpers[:start]+share+helpers[end:]
snap_start=helpers.index('    private async Task<string> Snapshot(');snap_end=helpers.index('    private static async Task<T> Success',snap_start)
snapshot=helpers[snap_start:snap_end]
snapshot=snapshot.replace('Members=skipMembers?[]:await db.CollectionRecords','Members=await db.CollectionRecords').replace('CollectionFolders=await db.CollectionFolders','CollectionFolders=skipMembers?[]:await db.CollectionFolders')
snapshot=snapshot.replace('ProfileRecords=await db.ProfileRecords','ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileRecords=await db.ProfileRecords')
helpers=helpers[:snap_start]+helpers[snap_end:]
helpers=helpers.replace('Record','Folder').replace('recordId','folderId').replace('/api/records','/api/folders')
# Preserve the contextual C# record keyword and raw complete-state snapshot.
assert 'private sealed record State' in helpers
needle='string mode="Master",Guid[]? collections=null)';assert needle in helpers;helpers=helpers.replace(needle,'string mode="Master",Guid[]? collections=null,Guid[]? records=null)')
needle='DateTimeOffset.UnixEpoch,[],folder is null?[]:[folder.PublicId]';assert needle in helpers;helpers=helpers.replace(needle,'DateTimeOffset.UnixEpoch,records??[],folder is null?[]:[folder.PublicId]')
extra=r'''
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenFreshNativeSelectedHandle_WhenListingFolders_ThenResolveDirectAndDescendantScopeWithoutOtherProfileLeakage(string mode)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var child=await Folder(s,root.Id);var p=await Profile(s,owner,scoped,root,mode);var other=await Profile(s,owner,otherKey);var direct=await Create(s,[p.PublicId]);var descendant=await Create(s,[],child.PublicId);await Create(s,[other.PublicId]);await Create(s);var selected=s with{Access=await Open(s,p,scoped)};var before=await Snapshot(s);using var r=await Read(selected,"/api/folders");var list=await Success<FolderListOutput>(r,200);Assert.Equal(new[]{root.PublicId,child.PublicId,direct.FolderId,descendant.FolderId}.Order(),list.Items.Select(x=>x.FolderId).Order());Assert.Equal(before,await Snapshot(s));foreach(var item in list.Items)Fields(item,"folderId","revision","serverSequence","editedAt","envelope");}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeGrantedFolderRootAndOverlappingLeaf_WhenListing_ThenDoNotExposeUnsharedParentOrSibling(CollectionGrantAccess access,bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await Setup(owner);var s=await Setup(recipient);var parent=await Folder(foreign);var root=await Folder(foreign,parent.Id);var child=await Folder(foreign,root.Id);var leaf=await Create(foreign,[],child.PublicId);await Folder(foreign,parent.Id);var own=await Create(s);var(collection,_)=await Share(foreign,owner,s,recipient,access,[root.PublicId,leaf.FolderId],[root.Id]);var p=await Profile(s,recipient,scoped,collections:[collection.PublicId]);var request=selected?s with{Access=await Open(s,p,scoped)}:s;var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);using var r=await Read(request,"/api/folders");var list=await Success<FolderListOutput>(r,200);Assert.Equal((selected?new[]{root.PublicId,child.PublicId,leaf.FolderId}:new[]{root.PublicId,child.PublicId,leaf.FolderId,own.FolderId}).Order(),list.Items.Select(x=>x.FolderId).Order());Assert.DoesNotContain(list.Items,x=>x.FolderId==parent.PublicId);Assert.Equal(leaf.Envelope,list.Items.Single(x=>x.FolderId==leaf.FolderId).Envelope);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenSelectedOwnedCollection_WhenListing_ThenIncludeOnlyMemberFolderAndDescendants(string mode)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var child=await Folder(s,root.Id);await Create(s);await using var db=fixture.Context();var collection=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=s.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(collection);await db.SaveChangesAsync();db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=collection.Id,FolderId=root.Id});await db.SaveChangesAsync();var p=await Profile(s,owner,scoped,mode:mode,collections:[collection.PublicId]);var selected=s with{Access=await Open(s,p,scoped)};var before=await Snapshot(s);using var r=await Read(selected,"/api/folders");var page=await Success<FolderListOutput>(r,200);Assert.Equal(new[]{root.PublicId,child.PublicId}.Order(),page.Items.Select(x=>x.FolderId).Order());Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeRecordOnlyGrant_WhenListingFolders_ThenOmitContainingFolderAndUnusedCorruptGrant(CollectionGrantAccess access,bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await Setup(owner);var s=await Setup(recipient);var folder=await Folder(foreign);var input=new RecordCreateInput(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch,[],folder.PublicId);using(var request=Request(foreign,Bytes(input),"/api/records")){using var created=await Gateway.Client.SendAsync(request);await Success<CreateRecordOutput>(created,201);}var(collection,grant)=await Share(foreign,owner,s,recipient,access,[],[]);await using(var db=fixture.Context()){var record=await db.Records.SingleAsync(x=>x.PublicId==input.RecordId);db.CollectionRecords.Add(new(){AccountId=foreign.InternalId,CollectionId=collection.Id,RecordId=record.Id});await db.SaveChangesAsync();}var p=await Profile(s,recipient,scoped,collections:[collection.PublicId]);var requestState=selected?s with{Access=await Open(s,p,scoped)}:s;using(var records=await Read(requestState,"/api/records")){var page=await Success<RecordListOutput>(records,200);Assert.Equal(input.RecordId,Assert.Single(page.Items).RecordId);}await using(var db=fixture.Context())await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.RecipientKeyEnvelope,new byte[]{1}));var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);using var response=await Read(requestState,"/api/folders");var folders=await Success<FolderListOutput>(response,200);Assert.Empty(folders.Items);Assert.Null(folders.NextCursor);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenNativeSelectedRecordOnlyProfile_WhenListingFolders_ThenDoNotExposeContainingFolder(string mode)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var folder=await Folder(s);var input=new RecordCreateInput(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch,[],folder.PublicId);using(var request=Request(s,Bytes(input),"/api/records")){using var created=await Gateway.Client.SendAsync(request);await Success<CreateRecordOutput>(created,201);}var p=await Profile(s,owner,scoped,mode:mode,records:[input.RecordId]);var selected=s with{Access=await Open(s,p,scoped)};using(var records=await Read(selected,"/api/records"))Assert.Equal(input.RecordId,Assert.Single((await Success<RecordListOutput>(records,200)).Items).RecordId);var before=await Snapshot(s);using var r=await Read(selected,"/api/folders");var page=await Success<FolderListOutput>(r,200);Assert.Empty(page.Items);Assert.Null(page.NextCursor);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("record")][InlineData("profile")]
    public async Task GivenRealOtherResourceCursor_WhenListingFolders_ThenRejectItsPurpose(string kind)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await Setup(owner);if(kind=="record"){for(var n=0;n<2;n++){using var request=Request(s,Bytes(new RecordCreateInput(Guid.NewGuid(),Envelope(),DateTimeOffset.UnixEpoch,[],null)),"/api/records");using var r=await Gateway.Client.SendAsync(request);await Success<CreateRecordOutput>(r,201);}}else{await Profile(s,owner,scoped);await Profile(s,owner,otherKey);}string cursor;using(var initial=await Read(s,kind=="record"?"/api/records?pageSize=1":"/api/profiles?pageSize=1")){Assert.Equal(HttpStatusCode.OK,initial.StatusCode);using var json=JsonDocument.Parse(await initial.Content.ReadAsStringAsync());cursor=json.RootElement.GetProperty("data").GetProperty("nextCursor").GetString()!;Assert.NotEmpty(cursor);}var before=await Snapshot(s);using var response=await Read(s,"/api/folders?pageSize=1&cursor="+cursor);await Failure(response,400,"validation_failed");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenCorruptOverlappingOrNonpageGrant_WhenListing_Then503WithoutOwnedOrSharedPartialContent(bool nonpage)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await Setup(owner);var s=await Setup(recipient);await Create(s);var first=await Create(foreign);var second=await Create(foreign);await Share(foreign,owner,s,recipient,CollectionGrantAccess.ReadOnly,[first.FolderId],[]);var(_,bad)=await Share(foreign,owner,s,recipient,CollectionGrantAccess.ReadOnly,[nonpage?second.FolderId:first.FolderId],[]);await using(var db=fixture.Context())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.RecipientKeyEnvelope,new byte[]{1}));var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);using var r=await Read(s,"/api/folders?pageSize=1");await Failure(r,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalTheory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)][InlineData(true,true)]
    public async Task GivenVisibleCycleOrHiddenCyclicAncestor_WhenListing_ThenFailOnlyForRelevantVisibleCorruption(bool selected,bool hidden)
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);await Folder(s,root.Id);var p=await Profile(s,owner,scoped,root);var visible=await Create(s,[p.PublicId]);var request=selected?s with{Access=await Open(s,p,scoped)}:s;await using(var db=fixture.Context())await db.Folders.Where(x=>x.Id==root.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.ParentFolderId,root.Id).SetProperty(x=>x.DeletedAt,hidden?DateTimeOffset.UtcNow:(DateTimeOffset?)null));var before=await Snapshot(s);using var response=await Read(request,"/api/folders");if(hidden){var page=await Success<FolderListOutput>(response,200);Assert.Equal(visible.FolderId,Assert.Single(page.Items).FolderId);}else await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("record")][InlineData("profile")][InlineData("collection")][InlineData("grant")][InlineData("account")][InlineData("folder")]
    public async Task GivenSameUuidTerminalKind_WhenListing_ThenOnlyFolderMarkerOmitsFolder(string kind)
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var input=await Create(s);await using(var db=fixture.Context()){db.TerminalErasures.Add(new(){ResourceId=input.FolderId,ResourceKind=kind,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var before=await Snapshot(s);using var response=await Read(s,"/api/folders");var page=await Success<FolderListOutput>(response,200);Assert.Equal(kind=="folder"?0:1,page.Items.Count);Assert.Equal(before,await Snapshot(s));}
'''
out=prefix+common+extra+helpers[:-2]+snapshot+'}\n'
assert out.count('private sealed record State')==1
assert 'public sealed folder' not in out and 'private sealed folder' not in out
assert 'Members=await db.CollectionRecords' in out and 'ProfileFolders=await db.ProfileFolders' in out
Path('/tmp/cerberus-uc24-http-tests.cs').write_text(out)
print('Prepared HTTP draft ONLY under/tmp; no route/DI/tests installed while Task2 whole Data runs.')
