from pathlib import Path
import re
w=Path('/tmp/cerberus-uc24-worktree')
src=(w/'tests/Infrastructure/ArturRios.Cerberus.Data.Tests/RecordListStoreTests.cs').read_text()
a=src.index('    [FunctionalFact]');b=src.index('    private RecordListStore Store()')
prefix=src[:a].replace('RecordListStoreTests','FolderListStoreTests')
prefix=prefix.replace('using ArturRios.Cerberus.Data.Records;','using ArturRios.Cerberus.Data.Records;\nusing ArturRios.Cerberus.Data.Folders;').replace('using ArturRios.Cerberus.Domain.Records;','using ArturRios.Cerberus.Domain.Records;\nusing ArturRios.Cerberus.Domain.Folders;')
skip=('GivenSelectedDirectAndFolderDescendantLinks','GivenNativeRecipientGrant','GivenSelectedOwnedCollection')
chunks=re.split(r'(?m)(?=    \[Functional)',src[a:b]);common=''
for s in chunks:
 if any(x in s for x in skip):continue
 s=s.replace('Record','Folder').replace('"record"','"folder"').replace('"recordTrash"','"folderTrash"').replace('"recordTerminal"','"folderTerminal"')
 s=s.replace('records:', 'direct:').replace('collection_record','collection_folder')
 s=s.replace('Assert.Equal(0d,ancestry.GetProperty("Actual Rows").GetDouble())','Assert.Equal(1d,ancestry.GetProperty("Actual Rows").GetDouble())')
 common+=s
snapshot_start=src.index('    private async Task<string> Snapshot(');snapshot_end=src.index('    private sealed class RevokeAfterRead',snapshot_start)
snapshot=src[snapshot_start:snapshot_end]
helpers=r'''
    private FolderListStore Store()=>new(fixture);
    private Task<VaultResult<FolderListPage>> List(ProfileSetup.State s,int size=100,long after=0,long? boundary=null)=>Store().ListAsync(new(s.Actor,s.Verifier,size,after,boundary),default);
    private async Task<VaultFolder> Folder(ProfileSetup.State s,long? parent=null){var row=new VaultFolder{PublicId=Guid.NewGuid(),AccountId=s.InternalId,ParentFolderId=parent,Envelope=Bytes(ProfileSetup.Envelope()),EditedAt=DateTimeOffset.UnixEpoch};await using var db=fixture.CreateContext();db.Folders.Add(row);await db.SaveChangesAsync();return row;}
    private async Task<Profile> Profile(ProfileSetup.State s,ProtectionFixture owner,ProtectionFixture scoped,Guid[]? direct=null,Guid[]? folders=null,Guid[]? collections=null){var input=ProfileSetup.Input(s,owner,scoped) with{RecordIds=[],FolderIds=(direct??[]).Concat(folders??[]).Distinct().ToArray(),CollectionIds=collections??[]};Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);await using var db=fixture.CreateContext();return await db.Profiles.AsNoTracking().SingleAsync(x=>x.PublicId==input.ProfileId);}
    private async Task Members(ProfileSetup.State s,VaultCollection collection,long[] direct,long[] folders){await using var db=fixture.CreateContext();db.CollectionFolders.AddRange(direct.Concat(folders).Distinct().Select(x=>new CollectionFolder{AccountId=s.InternalId,CollectionId=collection.Id,FolderId=x}));await db.SaveChangesAsync();}
    private async Task<string> Selected(ProfileSetup.State s,long profile){var verifier=Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));await using var db=fixture.CreateContext();db.VaultAccessSessions.Add(new(){AccountId=s.InternalId,ProfileId=profile,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=1,RevocationGeneration=1});await db.SaveChangesAsync();return verifier;}
    private static byte[] Bytes<T>(T value)=>JsonSerializer.SerializeToUtf8Bytes(value,ProtectionFixture.Json);
'''
interceptors=src[snapshot_end:].replace('private sealed class RevokeAfterRead','private sealed class RevokeAfterRead')
extra=r'''
    [FunctionalFact]
    public async Task GivenSelectedDirectAndDescendantFolders_WhenListing_ThenExposeOnlyOwnedSelectionOnce()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var root=await Folder(s);var child=await Folder(s,root.Id);var direct=await Folder(s);var outside=await Folder(s);var p=await Profile(s,owner,scoped,[direct.PublicId,child.PublicId],[root.PublicId]);await Profile(s,owner,otherKey,[outside.PublicId]);var selected=s with{Verifier=await Selected(s,p.Id)};var before=await Snapshot(s);var r=await List(selected);Assert.Null(r.Error);Assert.Equal(new[]{root.PublicId,child.PublicId,direct.PublicId}.Order(),r.Data!.Items.Select(x=>x.FolderId).Order());Assert.Equal(3,r.Data.Items.Count);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeMemberRootAndOverlappingLeaf_WhenListing_ThenIncludeOnlyGrantedDescendantsWithoutParentOrSibling(CollectionGrantAccess access,bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var resources=await AssociationSetup.Items(fixture,foreign);var parent=await Folder(foreign);var root=await Folder(foreign,parent.Id);var child=await Folder(foreign,root.Id);var leaf=await Folder(foreign,child.Id);await Folder(foreign,parent.Id);var own=await Folder(s);await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,resources.Collection,access);await Members(foreign,resources.Collection,[root.Id],[child.Id]);var p=await Profile(s,recipient,scoped,collections:[resources.Collection.PublicId]);var request=selected?s with{Verifier=await Selected(s,p.Id)}:s;var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var r=await List(request);Assert.Null(r.Error);Assert.Equal((selected?new[]{root.PublicId,child.PublicId,leaf.PublicId}:new[]{root.PublicId,child.PublicId,leaf.PublicId,own.PublicId}).Order(),r.Data!.Items.Select(x=>x.FolderId).Order());Assert.Equal(leaf.Envelope,r.Data.Items.Single(x=>x.FolderId==leaf.PublicId).Envelope);Assert.DoesNotContain(r.Data.Items,x=>x.FolderId==parent.PublicId||x.FolderId==resources.Folder.PublicId);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalFact]
    public async Task GivenSelectedOwnedCollection_WhenListing_ThenIncludeMemberAndDescendantsWithoutDirectProfileFolders()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var resources=await AssociationSetup.Items(fixture,s);var child=await Folder(s,resources.Folder.Id);await Folder(s);await Members(s,resources.Collection,[],[resources.Folder.Id]);var p=await Profile(s,owner,scoped,collections:[resources.Collection.PublicId]);var r=await List(s with{Verifier=await Selected(s,p.Id)});Assert.Null(r.Error);Assert.Equal(new[]{resources.Folder.PublicId,child.PublicId}.Order(),r.Data!.Items.Select(x=>x.FolderId).Order());}
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeRecordOnlyGrant_WhenListingFolders_ThenDoNotExposeContainingFolderOrInspectItsUnusedGrant(CollectionGrantAccess access,bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var resources=await AssociationSetup.Items(fixture,foreign);var grant=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,resources.Collection,access);await using(var db=fixture.CreateContext()){await db.Records.Where(x=>x.Id==resources.Record.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.FolderId,resources.Folder.Id));db.CollectionRecords.Add(new(){AccountId=foreign.InternalId,CollectionId=resources.Collection.Id,RecordId=resources.Record.Id});await db.SaveChangesAsync();}var p=await Profile(s,recipient,scoped,collections:[resources.Collection.PublicId]);var request=selected?s with{Verifier=await Selected(s,p.Id)}:s;var records=await new RecordListStore(fixture).ListAsync(new(request.Actor,request.Verifier,10,0,null),default);Assert.Null(records.Error);Assert.Equal(resources.Record.PublicId,Assert.Single(records.Data!.Items).RecordId);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==grant.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.RecipientKeyEnvelope,"unused corrupt grant"u8.ToArray()));var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var r=await List(request);Assert.Null(r.Error);Assert.Empty(r.Data!.Items);Assert.Equal(0,r.Data.Boundary);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalFact]
    public async Task GivenSelectedProfileRecordOnly_WhenListingFolders_ThenDoNotWidenToContainingFolder()
    {using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var resources=await AssociationSetup.Items(fixture,s);await using(var db=fixture.CreateContext())await db.Records.Where(x=>x.Id==resources.Record.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.FolderId,resources.Folder.Id));var input=ProfileSetup.Input(s,owner,scoped) with{RecordIds=[resources.Record.PublicId],FolderIds=[],CollectionIds=[]};Assert.Null((await new ProfileCreateStore(fixture).CreateAsync(new(s.Actor,s.Verifier,input),default)).Error);await using var context=fixture.CreateContext();var p=await context.Profiles.SingleAsync(x=>x.PublicId==input.ProfileId);var selected=s with{Verifier=await Selected(s,p.Id)};var records=await new RecordListStore(fixture).ListAsync(new(selected.Actor,selected.Verifier,10,0,null),default);Assert.Equal(resources.Record.PublicId,Assert.Single(records.Data!.Items).RecordId);var before=await Snapshot(s);var r=await List(selected);Assert.Null(r.Error);Assert.Empty(r.Data!.Items);Assert.Equal(before,await Snapshot(s));}
    [FunctionalTheory][InlineData("record")][InlineData("profile")][InlineData("collection")][InlineData("grant")][InlineData("account")][InlineData("folder")]
    public async Task GivenSameUuidTerminalKind_WhenListing_ThenOnlyFolderMarkerHidesFolder(string kind)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var folder=await Folder(s);await using(var db=fixture.CreateContext()){db.TerminalErasures.Add(new(){ResourceId=folder.PublicId,ResourceKind=kind,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}var r=await List(s);Assert.Null(r.Error);Assert.Equal(kind=="folder"?0:1,r.Data!.Items.Count);if(kind!="folder")Assert.Equal(folder.PublicId,Assert.Single(r.Data.Items).FolderId);}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenCorruptOverlappingOrNonpageContributor_WhenListing_Then503BeforeAnyPartialPage(bool nonpage)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);await Folder(s);var first=await AssociationSetup.Items(fixture,foreign);var second=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,first.Collection);var bad=await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,second.Collection);await Members(foreign,first.Collection,[],[first.Folder.Id]);await Members(foreign,second.Collection,[],[nonpage?second.Folder.Id:first.Folder.Id]);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(x=>x.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(s);var foreignBefore=await Snapshot(foreign);var r=await List(s,1);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);Assert.Equal(before,await Snapshot(s));Assert.Equal(foreignBefore,await Snapshot(foreign));}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenSeveralValidContributingGrants_WhenListing_ThenVerifyAllWithSharedAccountPins(bool selected)
    {using var owner=new ProtectionFixture();using var recipient=new ProtectionFixture();using var scoped=new ProtectionFixture();var foreign=await ProfileSetup.Create(fixture,owner);var s=await ProfileSetup.Create(fixture,recipient);var ids=new List<Guid>();var folders=new List<Guid>();for(var n=0;n<3;n++){var resources=await AssociationSetup.Items(fixture,foreign);await AssociationSetup.Grant(fixture,foreign,owner,s,recipient,resources.Collection);await Members(foreign,resources.Collection,[],[resources.Folder.Id]);ids.Add(resources.Collection.PublicId);folders.Add(resources.Folder.PublicId);}var p=await Profile(s,recipient,scoped,collections:ids.ToArray());var r=await List(selected?s with{Verifier=await Selected(s,p.Id)}:s);Assert.Null(r.Error);Assert.Equal(folders.Order(),r.Data!.Items.Select(x=>x.FolderId).Order());}
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenInternalCancellationOrTimeout_WhenListing_Then503WithoutReadMutation(bool cancellation)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);await Folder(s);var before=await Snapshot(s);var r=await new FolderListStore(new ProfileSetup.Factory(fixture,new FailRead(cancellation))).ListAsync(new(s.Actor,s.Verifier,10,0,null),default);Assert.Equal("persistence_unavailable",r.Error);Assert.Null(r.Data);Assert.Equal(before,await Snapshot(s));}
    private sealed class FailRead(bool cancellation):DbCommandInterceptor
    {public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData e,InterceptionResult<DbDataReader> result,CancellationToken ct=default){if(cancellation)throw new OperationCanceledException();throw new TimeoutException();}}
'''
out=prefix+common+extra+helpers+snapshot+interceptors
assert out.count('private async Task<VaultFolder> Folder(')==1
assert 'resources.Record' in out and 'RecordListStore(fixture)' in out
p=w/'tests/Infrastructure/ArturRios.Cerberus.Data.Tests/FolderListStoreTests.cs';assert not p.exists();p.write_text(out)
print('Installed real PostgreSQL folder-specific permission/native/snapshot/ordering tests BEFORE FolderListStore. Actual member links and record-only negatives included; snapshots preserve records too.')
