import json,subprocess
from pathlib import Path
w=Path('/tmp/cerberus-uc24-worktree');head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip();base='fc4bda98a88eef28851486cd404537da663f227e'
workspace=w/'.superpowers/sdd/2026-10-09-uc-24-list-folders';l=(workspace/'progress.md').read_text();assert all(f'Task {n}: complete' in l for n in range(1,4))
rulings=[x for x in l.splitlines() if 'Ruling:' in x];assert len(rulings)==8
validation=json.loads(Path('/tmp/cerberus-uc24-validation.json').read_text());assert validation['tests']==5209
assert not subprocess.check_output(['git','status','--porcelain'],cwd=w,text=True).strip()
plan=w/'docs/superpowers/plans/2026-10-09-uc-24-list-folders.md';s=plan.read_text();focus=s.split('## Review Focus\n',1)[1].split('### Task 1:',1)[0]
packages=list(workspace.glob('review-*.diff'));assert len(packages)==1
old=Path('/tmp/cerberus-uc23-review-prompt.md').read_text();tail=old.split('\n## Git Range to Review\n',1)[1].replace('d72d92072eaba28509597c545f4833a8ef58faa6',base).replace('3bf6b37c211447cfc74ca277defa75910bcae7ec',head)
prompt=f'''You are a Senior Code Reviewer with expertise in software architecture,
design patterns, and best practices. Your job is to review completed work
against its plan or requirements and identify issues before they cascade.

## What Was Implemented

UC24 encrypted folder listing. GET /api/folders accepts only canonical optional pageSize/cursor and one current vault access header, no GET body; exact five folder fields within items/nextCursor. Dedicated authenticated encrypted folder cursor binds actor/hashhandle/size/position/highwater and rejects record/profile purposes. One SQL current permission snapshot admits owned or selected/direct/native member descendant folders BEFORE complete self/upward ancestry and pagination; no record-only route expands to a containing folder. Hidden ancestry is omitted, visible active cycles503. Current active typed/lifecycle/session/database-time/selected own or foreign RO/RW collection scope; every visible contributing foreign native binding/signature verified with each distinct account pin parsed once. Ordering corruption checked before keyset; no writes or locks, no schema/dependency/crypto algorithm changes. 97 query,104 actual PostgreSQL and89 actual native HTTP new tests across three tasks.

## Requirements / Plan

Review ONLY workdir {w}. Binding spec {w}/docs/superpowers/specs/2026-10-09-uc-24-list-folders.md; plan {plan}; ledger {workspace}/progress.md; complete branch review package {packages[0]}. All three tasks complete. Fresh unfiltered six families5209 passed, zero failures/skips; actual validation /tmp/cerberus-uc24-validation.json and full log /tmp/cerberus-uc24-coverage.log: {json.dumps(validation['families'])}; actual coverage {validation['line']}% line/{validation['branch']}% branch; all six production assemblies>=90% line. Evidence query-red/green/whole.log, data-red/green/whole.log and http-red/green.log plus actual OpenAPI-shape/drift, locked restore/dependency/native/helpers/spec logs under /tmp/cerberus-uc24-*. Read actual evidence/code; do not rerun builds/tests. A failed Data installer assertion produced zero matching tests and is explicitly NOT RED evidence (data-installation-attempt.log); corrected installed Data matrix produced missing FolderListStore compile RED BEFORE store, then first GREEN build exposed test-only FailRead throw-expression typo masked by missing type, corrected before runtime104PASS. Actual HTTP89 installed cases produced84 missing-GET405 failures/5 prior-middleware passes BEFORE GET/DI, then89PASS. Source DI belongs to Startup.cs, recorded Ruling8 and corrected plan before registrations.

This is the ONE ordinary whole-branch review required by executing-plans. User explicitly deferred independent formal security/protocol/crypto and real external-client operability approval for develop; main/tag/release gates remain mandatory. Review current concrete ownership, native use, safe handling, snapshot/expiry/cursor and current product correctness; do not perform or certify deferred independent audits or release/deployment. Observed shared OpenAPI missing access-header/output requiredness, nullable items and advertised ProblemDetails for actual empty413 remain release follow-ups; current effects must be graded explicitly. Prior UC23 narrowed foreign-grant and post-parent-failure fixtures, UC22 permission-outage500 classification and UC21 formatting blank remain inherited unchanged outside this diff, with recorded later dispositions. UC24 grant fixtures actually include CollectionFolder links and record-only negatives prove native record visibility before verifying no folder expansion. Existing real-client content-key provisioning/decryption and ordered inherited visibility sync remain before-release qualification/integration prerequisites. Future folder get/update/trash/moves/restore/purge, other physical erasure and BEFORE UC35 implicit recipient-account FK audit retain later gates; do not certify nonexistent future writers. Production workload targets are unspecified; actual query-plan evidence is ordinary bounded-admission validation, not load certification. Record every behavior set aside in Declined to judge with reason. Read-only checkout/index/HEAD/branches; no edits, subagents, approvals, remote GitHub actions or review submissions. Write only final report outside worktree to /tmp/cerberus-uc24-final-review.md, then return verdict and severity-by-actual-effect findings with file:line. No duplicate reviewer or rerun.

Verbatim Review Focus:
{focus}
ALL rulings, with reasons and costs (do not silently drop):
'''+ '\n'.join(rulings)+'\n\n## Git Range to Review\n'+tail
assert '[HEAD_SHA]' not in prompt and '[BASE_SHA]' not in prompt
Path('/tmp/cerberus-uc24-review-prompt.md').write_text(prompt);Path('/tmp/cerberus-uc24-tested-head.txt').write_text(head+'\n');print('Complete reviewer prompt prepared for',head,'with all8Rulings, five verbatim focus lines and actual5209PASS evidence.')
