from pathlib import Path
import json,subprocess
w=Path('/tmp/cerberus-uc25-worktree');head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip();base=Path('/tmp/cerberus-uc25-base.txt').read_text().strip()
workspace=w/'.superpowers/sdd/2026-10-09-uc-25-get-folder';l=(workspace/'progress.md').read_text();assert all(f'Task {n}: complete' in l for n in range(1,4))
rulings=[x for x in l.splitlines() if 'Ruling:' in x];assert len(rulings)==8
v=json.loads(Path('/tmp/cerberus-uc25-validation.json').read_text());assert v['tests']==5474
assert not subprocess.check_output(['git','status','--porcelain'],cwd=w,text=True).strip()
plan=w/'docs/superpowers/plans/2026-10-09-uc-25-get-folder.md';spec=w/'docs/superpowers/specs/2026-10-09-uc-25-get-folder.md';focus=plan.read_text().split('## Review Focus\n',1)[1].split('### Task 1:',1)[0]
packages=list(workspace.glob('review-*.diff'));assert len(packages)==1
old=Path('/tmp/cerberus-uc24-review-prompt.md').read_text();tail=old.split('\n## Git Range to Review\n',1)[1].replace('fc4bda98a88eef28851486cd404537da663f227e',base).replace('484d7b80e0c79b114959c507c019e639f64ba291',head)
prompt=f'''You are a Senior Code Reviewer with expertise in software architecture,
design patterns, and best practices. Your job is to review completed work
against its plan or requirements and identify issues before they cascade.

## What Was Implemented

UC25 encrypted folder detail. GET /api/folders/{{id}} requires canonical lowercase dashed nonzero target ID, current identity and one vault access header, no query or GET body. Exact eight fields: folderId/revision/serverSequence/editedAt/envelope/profileIds/parentFolderId/collectionIds. Existing folder projection validates all metadata/native envelope and entire details shape before output. One target-first SQL current permission snapshot admits at most the requested folder BEFORE complete self/upward ancestry, scoped inclusion, visible references and native evidence. No record-only scope route. Direct profile refs only own/current selection; effective collection refs only actually included eligible collections; immediate parent visible only via independent ancestry routes excluding target itself. Hidden/incomplete404 before corruption/native; needed active cycles503; all foreign target contributors verified with one owner+recipient pin parse. Current database-time session/selection/typed lifecycle checks, no reads after snapshot, locks or mutations. No schema/dependency/crypto algorithm changes. Three inline tasks added55 query/127 actual PostgreSQL/83 actual native HTTP cases.

## Requirements / Plan

Read only {w}. Binding spec {spec}; completed plan {plan}; ledger {workspace}/progress.md; complete branch package {packages[0]}. All three implementation tasks complete. Fresh unfiltered six families5474PASS zero failures/skips, actual /tmp/cerberus-uc25-validation.json and /tmp/cerberus-uc25-coverage.log: {json.dumps(v['families'])}; actual Summary {v['line']}% line/{v['branch']}% branch, all six production assemblies>=90% line. Focused query55, Data127, HTTP83 plus wholeQuery411/wholeData1971 passed after observed missing-type/store RED and actual missing-detail-route404 failures82/1middlewarePASS before GET/DI. A temporary SQL installer overbroad alias substitution was caught by its own assertion BEFORE product installation and corrected to exact alias; no zero-match or runtime/product correction was counted from it. No product runtime fix needed. Read actual code/evidence, do not rerun builds/tests. Ordinary locked restore/NuGet direct+transitive audit/native OSV153no findings/corpus322x4/helpers36+23/specs/OpenAPIwrite+drift+shape/full-range whitespace logs under/tmp/cerberus-uc25-*. Python helper printed89.9/90/94.7 are test fixtures, NOT actual production coverage.

This is exactly ONE ordinary whole-branch review required by executing-plans. User explicitly deferred independent formal security/protocol/cryptographic and real external-client operability approval for develop; main/tag/release gates remain mandatory. Review current concrete ownership, native use, safe handling, visibility/parent, snapshot/expiry and runtime correctness; do not perform/certify the deferred independent audits or release/deployment. Shared generated access-header/output requiredness, nullable profileIds/collectionIds and ProblemDetails for actual empty413 remain current release follow-ups; explicitly grade actual effects. Inherited UC23 narrowed foreign-grant/post-parent-failure fixtures, UC22 permission-outage500 classification and UC21 formatting blank remain unchanged outside this diff with recorded later dispositions. UC25's own actual foreign folder fixtures install real CollectionFolder membership; record-only negatives first demonstrate actual native RecordReadStore/record HTTP access before folder404. Actual plans admit1/ancestry3 against100 unrelated deep folders. Existing real-client keys/decryption, ordered durable offline inherited visibility, future folder writers/trash/moves/restore/purge, other physical erasure and mandatory BEFORE UC35 implicit recipient-account FK audit remain later gates. Production workload targets are unspecified; bounded plans are not load certification. Baseline reused verified UC24 merged/tested tree plus5209PASS/latestCI, followed by fresh UC25 suite; historical provenance is executor evidence. Every behavior set aside belongs in Declined to judge with reason. No checkout/index/HEAD/branch edits, builds, test reruns, subagents, remote GitHub actions or approvals. Write ONLY /tmp/cerberus-uc25-final-review.md outside worktree, then return verdict and severity-by-actual-effect findings with file:line. No second/duplicate reviewer.

Verbatim Review Focus:
{focus}
ALL rulings with reasons/costs:
'''+ '\n'.join(rulings)+'\n\n## Git Range to Review\n'+tail
assert '[HEAD_SHA]' not in prompt and '[BASE_SHA]' not in prompt
Path('/tmp/cerberus-uc25-review-prompt.md').write_text(prompt);Path('/tmp/cerberus-uc25-tested-head.txt').write_text(head+'\n');print('Complete ONE review prompt prepared for',head,'with all8Rulings and actual5474PASS evidence')
