from pathlib import Path
import json, subprocess, hashlib, shutil
w=Path('/tmp/cerberus-uc25-worktree');primary=Path('/root/repositories/cerberus-api');p=primary/'.superpowers/checkpoints';d=json.loads((p/'open-issues-2026-10-08.json').read_text())
assert d['nextUseCase']=='UC-25';previous=json.loads((p/'uc-24-2026-10-09-complete/cerberus-uc24-dod.json').read_text());assert previous['tests']==5209 and all(x['passed'] for x in previous['definitionOfDone'])
base=previous['mergeCommit'];git=lambda *a:subprocess.check_output(['git',*a],cwd=w,text=True).strip()
assert git('rev-parse','HEAD')==base and git('rev-parse','origin/develop')==base and git('branch','--show-current')=='feature/uc-25-get-folder' and not git('status','--porcelain')
assert git('rev-parse','HEAD^{tree}')==git('rev-parse',previous['testedHead']+'^{tree}')
for f,s in d['preservedUserFilesSha256'].items():assert hashlib.sha256((primary/f).read_bytes()).hexdigest()==s
issue=json.loads(Path('/tmp/cerberus-uc25-issue.json').read_text());assert issue['number']==26 and issue['state']=='OPEN' and 'FR-FD-03' in issue['body']
spec=w/'docs/superpowers/specs/2026-10-09-uc-25-get-folder.md';plan=w/'docs/superpowers/plans/2026-10-09-uc-25-get-folder.md'
assert not spec.exists() and not plan.exists();shutil.copy2('/tmp/cerberus-uc25-spec.md',spec);shutil.copy2('/tmp/cerberus-uc25-plan.md',plan)
script='/root/.codex/plugins/cache/openai-curated-remote/superpowers/6.4.2/skills/subagent-driven-development/scripts/sdd-workspace'
workspace=Path(subprocess.check_output([script,str(plan)],cwd=w,text=True).strip());ledger=workspace/'progress.md';assert not ledger.exists()
rulings='''Ruling: Reuse the freshly verified merged UC24 baseline — actual merged tree equals tested HEAD with5209 unfiltered passes and exact-head CI; this worktree begins at that exact merge — cost if wrong: environmental differences must be caught by whole-family and final fresh six-family tests.
Ruling: Folder detail uses eight fields mirroring existing record detail, without child inventories — five encrypted metadata fields plus current profile/parent/collection references meet the detail contract while existing list/detail endpoints provide inventories — cost if wrong: navigation needs additional permitted list/detail requests rather than one unbounded child payload.
Ruling: Only current direct owned profile references and effective permitted collection references are returned — inherited folder visibility does not invent a direct profile association and foreign grants never expose owner profiles — cost if wrong: clients must distinguish direct organization from inherited visibility.
Ruling: Immediate parent is returned only through independently permitted ancestor routes excluding the target itself — a direct target link/member-leaf grant cannot disclose otherwise unshared ancestry — cost if wrong: clients cannot reconstruct private hierarchy above their permitted leaf.
Ruling: ProfileRecord and CollectionRecord routes never expose folders — folder authority requires actual ProfileFolder or CollectionFolder routes, even if native record access succeeds — cost if wrong: record-only clients must navigate records without their container metadata.
Ruling: Validate every eligible foreign target contributor with owner/recipient pins parsed once per party — overlapping valid authority does not excuse a corrupt relevant binding; unselected/unrelated grants are excluded before verification — cost if wrong: one corrupt contributing route yields whole-response503 and large overlap entails signature work.
Ruling: Hidden/incomplete ancestry returns404 before native/content inspection; fully active actually scoped cycles503 — preserve nonrevealing hidden-target behavior while failing safe on needed structural corruption — cost if wrong: corrupt visible hierarchies require repair and incomplete structures cannot be navigated.
Ruling: Independent formal security/protocol and real external-client approval remain deferred only for develop — explicit user authorization permits this development batch while ordinary native/ownership/snapshot checks, ONE review and release/main/tag gates remain — cost if wrong: latent security or client integration defects still require independent qualification before release.
'''
ledger.write_text(f'# SDD ledger — plan: {plan}\n\nBase: {base}\nBranch: feature/uc-25-get-folder\nIssue:26 UC25GetFolder\nAuthorized all-open-issues batch, automated design/plan gates and inline execution; no repeat approval.\n\n'+rulings+'\nPre-flight Task1→Task2: FolderReadRequest/Details/IFolderReadStore exact signatures and existing FolderListRow agree; Task2 returns Folder +ProfileIds/ParentFolderId/CollectionIds.\nPre-flight Task1+Task2→Task3: QueryMediator GetFolderQuery/Handler/FolderDetailsOutput/FolderReadMessages and explicit Startup registrations agree; canonical path/header/body/noquery guard matches spec.\nGate1: fresh issue26 and UC25/main+AF01..04/FR-FD-03/BR07+22+28/authorization/testing/technology/operations loaded; every FR exists, all AF mapped, three tasks test-first, all five focus lines mapped, exact eight fields and parent-independent visibility decided. No placeholders or undecided interface. Baseline tree verified; no product/test implementation yet.\n')
a=p/'batch-review-decisions-2026-10-08.md';a.write_text(a.read_text()+'\n## UC25 initial decisions\n\n'+rulings)
entry=next((x for x in d['useCases'] if x['id']=='UC-25'),None)
if entry is None:entry={'id':'UC-25','issue':26};d['useCases'].append(entry)
entry.update({'status':'in_progress','branch':'feature/uc-25-get-folder','worktree':str(w),'base':base,'ledger':str(ledger),'currentTask':'Task1 query RED next'})
for k in ('currentTask','resumeInstruction','requiredToResume'):d[k]='UC25 issue26 fresh design/plan/self-check/owned worktree at verified UC24 merge. All8 initialRulings ledgered; three inline TDD tasks/ONE ordinary review/exact-head CI. Task1 query RED next; no product/test files installed yet. Preserve primary user work and independent development-only deferrals.'
d['currentUseCase']='UC-25';d['currentWorktree']=str(w);d['currentBranch']='feature/uc-25-get-folder';d['currentLedger']=str(ledger)
for k in ('activeExecSession','activeTestLog'):d.pop(k,None)
(p/'open-issues-2026-10-08.json').write_text(json.dumps(d,indent=2)+'\n');Path('/tmp/cerberus-uc25-base.txt').write_text(base+'\n');print('UC25 specs/plan/all8Rulings/ledger and checkpoint initialized; no product code.')
