from pathlib import Path
p=Path('/tmp/cerberus-uc21-worktree/tests/Infrastructure/ArturRios.Cerberus.Data.Tests/RecordMoveStoreTests.cs');s=p.read_text()
extra='''
    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenControlledNativeRecipientEditAndOwnerMove_WhenOneHoldsEarlierCollectionLocks_ThenOneWinnerWithoutDeadlock(bool moveFirst)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var c=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var to=await Folder(o);var target=await Record(o,a.Folder.Id);await Members(o,a.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,o,owner,c,client,a.Collection,CollectionGrantAccess.ReadWrite);
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));
        Task<VaultResult<RecordMoveDetails>> move;Task<VaultResult<RecordCreateDetails>> edit;var input=new RecordUpdateInput(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch.AddDays(1));
        if(moveFirst){move=new RecordMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).MoveAsync(new(o.Actor,o.Verifier,target.PublicId,1,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));edit=new RecordUpdateStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection"))).UpdateAsync(new(c.Actor,c.Verifier,target.PublicId,input),ct.Token);}
        else{edit=new RecordUpdateStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).UpdateAsync(new(c.Actor,c.Verifier,target.PublicId,input),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));move=new RecordMoveStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"collection"))).MoveAsync(new(o.Actor,o.Verifier,target.PublicId,1,to.PublicId),ct.Token);}
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(moveFirst?edit.IsCompleted:move.IsCompleted);}finally{release.TrySetResult();}
        await Task.WhenAll(move,edit);if(moveFirst){await Success(target,to,a.Folder,to,move.Result);Assert.Equal("not_found",edit.Result.Error);}else{Assert.Null(edit.Result.Error);Assert.Equal("revision_conflict",move.Result.Error);var row=await Row(target.Id);Assert.Equal(a.Folder.Id,row.FolderId);Assert.Equal(Bytes(input.Envelope),row.Envelope);Assert.Equal(Bytes(a.Folder),Bytes(await FolderRow(a.Folder.Id)));Assert.Equal(Bytes(to),Bytes(await FolderRow(to.Id)));}
    }

    [FunctionalTheory][InlineData("edit",false)][InlineData("edit",true)][InlineData("trash",false)][InlineData("trash",true)]
    public async Task GivenControlledActualOwnedWriterAndMove_WhenOneHoldsAccount_ThenPreserveTheExpectedRevisionWinner(string writer,bool moveFirst)
    {
        using var owner=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var from=await Folder(o);var to=await Folder(o);var target=await Record(o,from.Id);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));
        var pause=new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}));var signal=new ProfileSetup.Factory(fixture,new Signal(blocked,"account"));
        Task<VaultResult<RecordMoveDetails>> move;Task<VaultResult<RecordCreateDetails>>? edit=null;Task<VaultResult<RecordTrashDetails>>? trash=null;
        void StartOther(IDbContextFactory<AppDbContext> factory){if(writer=="edit")edit=new RecordUpdateStore(factory).UpdateAsync(new(o.Actor,o.Verifier,target.PublicId,new(1,ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch)),ct.Token);else trash=new RecordTrashStore(factory).TrashAsync(new(o.Actor,o.Verifier,target.PublicId,1),ct.Token);}
        if(moveFirst){move=new RecordMoveStore(pause).MoveAsync(new(o.Actor,o.Verifier,target.PublicId,1,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));StartOther(signal);}else{StartOther(pause);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));move=new RecordMoveStore(signal).MoveAsync(new(o.Actor,o.Verifier,target.PublicId,1,to.PublicId),ct.Token);}
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(moveFirst?(edit?.IsCompleted??trash!.IsCompleted):move.IsCompleted);}finally{release.TrySetResult();}
        var mr=await move;var otherError=edit is not null?(await edit).Error:(await trash!).Error;
        if(moveFirst){await Success(target,to,from,to,mr);Assert.Equal("revision_conflict",otherError);}else{Assert.Null(otherError);Assert.Equal(writer=="trash"?"not_found":"revision_conflict",mr.Error);var row=await Row(target.Id);Assert.Equal(2,row.Revision);Assert.Equal(writer=="trash"?null:from.Id,row.FolderId);Assert.Equal(Bytes(to),Bytes(await FolderRow(to.Id)));if(writer=="trash")Assert.NotNull(row.DeletedAt);}
    }

    [FunctionalFact]
    public async Task GivenConcurrentMovesAndLostSuccessRetry_WhenReplacingParent_ThenOneStructuralChangeAndNoDuplicateBumps()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Record(s,from.Id);var tasks=new[]{Move(s,target,to.PublicId),Move(s,target,to.PublicId)};var results=await Task.WhenAll(tasks);Assert.Single(results,x=>x.Error is null);Assert.Single(results,x=>x.Error=="revision_conflict");await Success(target,to,from,to,results.Single(x=>x.Error is null));var before=await Snapshot(s);Assert.Equal("revision_conflict",(await Move(s,target,to.PublicId)).Error);Assert.Equal(before,await Snapshot(s));
        var row=await Row(target.Id);var nowFrom=await FolderRow(from.Id);var nowTo=await FolderRow(to.Id);await Success(row,to,nowFrom,nowTo,await Move(s,row,to.PublicId,2));
    }

    [FunctionalTheory][InlineData("account")][InlineData("session")][InlineData("profile")][InlineData("collection")][InlineData("grant")][InlineData("folder")][InlineData("record")]
    public async Task GivenExpiryDuringEachRequiredLockWaitAndStaleRevision_WhenMoving_Then403BeforeConflict(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var to=await Folder(s);var target=await Record(s,a.Folder.Id);await Members(s,a.Collection,[target.Id],[]);var g=await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);var p=await Profile(s,owner,scoped,records:[target.PublicId],folders:[a.Folder.PublicId,to.PublicId]);s=s with{Verifier=await Selected(s,p.Id)};
        var deadline=DateTimeOffset.UtcNow.AddSeconds(2);await using(var db=fixture.CreateContext())await db.VaultAccessSessions.Where(x=>x.HandleVerifier==s.Verifier).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,deadline));var before=await Snapshot(s);
        await using var held=fixture.CreateContext();await using var tx=await held.Database.BeginTransactionAsync();var firstFolder=new[]{a.Folder,to}.OrderBy(x=>x.PublicId).First();var id=kind switch{"account"=>s.InternalId,"profile"=>p.Id,"collection"=>a.Collection.Id,"grant"=>g.Id,"folder"=>firstFolder.Id,_=>target.Id};var table=kind switch{"session"=>"vault_access_session","grant"=>"collection_grant",_=>kind};var sql=kind=="session"?"SELECT FROM cerberus.vault_access_session WHERE handle_verifier={0} FOR UPDATE":"SELECT FROM cerberus."+table+" WHERE id={0} FOR UPDATE";await held.Database.ExecuteSqlRawAsync(sql,kind=="session"?(object)s.Verifier:id);
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(15));var pending=new RecordMoveStore(new ProfileSetup.Factory(fixture,new Signal(reached,table))).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,99,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(pending.IsCompleted);await Past(deadline);await tx.CommitAsync();Assert.Equal("vault_access_denied",(await pending).Error);Assert.Equal(before,await Snapshot(s));
    }

    [FunctionalTheory][InlineData("newCollection")][InlineData("newGrant")][InlineData("sourceParent")]
    public async Task GivenNewEarlierAuthorityAfterDiscovery_WhenMoving_Then409WithoutLateLocksOrLostExternalWinner(string kind)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var from=await Folder(s);var to=await Folder(s);var other=await Folder(s);var target=await Record(s,from.Id);var a=await AssociationSetup.Items(fixture,s);if(kind=="newGrant")await Members(s,a.Collection,[],[to.Id]);
        async Task Change(){if(kind=="newCollection")await Members(s,a.Collection,[],[to.Id]);else if(kind=="newGrant")await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);else{await using var db=fixture.CreateContext();await db.Records.Where(x=>x.Id==target.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.FolderId,other.Id));}}
        DbCommandInterceptor hook=kind=="sourceParent"?new BeforeTarget(Change):new BeforeWrite(Change);var result=await new RecordMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),default);Assert.Equal("revision_conflict",result.Error);
        var row=await Row(target.Id);Assert.Equal(kind=="sourceParent"?other.Id:from.Id,row.FolderId);Assert.Equal(target.Envelope,row.Envelope);Assert.Equal(1,row.Revision);Assert.Equal(Bytes(from),Bytes(await FolderRow(from.Id)));Assert.Equal(Bytes(to),Bytes(await FolderRow(to.Id)));
    }

    [FunctionalTheory][InlineData("sourceHidden","not_found")][InlineData("destinationHidden","not_found")][InlineData("destinationCycle","persistence_unavailable")][InlineData("ownerTerminal","not_found")]
    public async Task GivenCompleteAncestryOrTerminalChangeBeforeWrite_WhenMoving_ThenCurrentRecursiveStatementDenies(string kind,string error)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var sourceRoot=await Folder(s);var from=await Folder(s,sourceRoot.Id);var destinationRoot=await Folder(s);var to=await Folder(s,destinationRoot.Id);var hidden=await Folder(s);var target=await Record(s,from.Id);await using(var db=fixture.CreateContext())await db.Folders.Where(x=>x.Id==hidden.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.DeletedAt,DateTimeOffset.UtcNow));
        var hook=new BeforeWrite(async()=>{await using var db=fixture.CreateContext();if(kind=="ownerTerminal"){db.TerminalErasures.Add(new(){ResourceKind="account",ResourceId=s.AccountId,DeletedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}else{var id=kind=="sourceHidden"?sourceRoot.Id:destinationRoot.Id;await db.Folders.Where(x=>x.Id==id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ParentFolderId,kind=="destinationCycle"?to.Id:hidden.Id));}});
        Assert.Equal(error,(await new RecordMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),default)).Error);Assert.Equal(Bytes(target),Bytes(await Row(target.Id)));Assert.Equal(Bytes(from),Bytes(await FolderRow(from.Id)));Assert.Equal(Bytes(to),Bytes(await FolderRow(to.Id)));
    }

    [FunctionalFact]
    public async Task GivenActualRecipientProtectionRotationAfterNativeValidation_WhenMoving_ThenStaleEvidenceConflictsAndFreshRetrySucceeds()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,s);var target=await Record(s);await Members(s,a.Collection,[],[a.Folder.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);
        var change=new ProtectionChange(recipient.AccountId,1,1,"rotate-content",client.Rewrap(),[new("account",recipient.AccountId,1,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(recipient.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;
        var before=await Snapshot(s);var hook=new BeforeWrite(async()=>Assert.Null((await new VaultProtectionChangeStore(fixture).ChangeAsync(new(recipient.Actor,recipient.Verifier,challenge.ChallengeId,client.Sign(challenge),raw,change),default)).Error));
        Assert.Equal("revision_conflict",(await new RecordMoveStore(new ProfileSetup.Factory(fixture,hook)).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,a.Folder.PublicId),default)).Error);Assert.Equal(before,await Snapshot(s));await Success(target,a.Folder,null,a.Folder,await Move(s,target,a.Folder.PublicId));
    }

    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenActualOwnedCreateOrAssociationWaitsBehindMove_WhenCommitting_ThenNoFkCycleAndBothAuthorizedWritesComplete(bool association)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Record(s,from.Id);var p=await Profile(s,owner,scoped,records:[target.PublicId]);var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));
        var move=new RecordMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var factory=new ProfileSetup.Factory(fixture,new Signal(blocked,"account"));var input=new RecordCreateInput(Guid.NewGuid(),ProfileSetup.Envelope(),DateTimeOffset.UnixEpoch,[],to.PublicId);var create=association?null:new RecordCreateStore(factory).CreateAsync(new(s.Actor,s.Verifier,input),ct.Token);var link=association?new ProfileAssociationStore(factory).ReplaceAsync(new(s.Actor,s.Verifier,p.PublicId,new(p.Revision,[target.PublicId],[to.PublicId],[])),ct.Token):null;
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(create?.IsCompleted??link!.IsCompleted);}finally{release.TrySetResult();}Assert.Null((await move).Error);if(create is not null){Assert.Null((await create).Error);Assert.Equal(to.Revision+2,(await FolderRow(to.Id)).Revision);}if(link is not null){Assert.Null((await link).Error);await using var db=fixture.CreateContext();Assert.Equal(p.Revision+1,(await db.Profiles.SingleAsync(x=>x.Id==p.Id)).Revision);}
        Assert.Equal(to.Id,(await Row(target.Id)).FolderId);Assert.Equal(target.Envelope,(await Row(target.Id)).Envelope);Assert.Equal(from.Revision+1,(await FolderRow(from.Id)).Revision);
    }

    [FunctionalFact]
    public async Task GivenActualOwnerRotationWaitsBehindMove_WhenMoveCommits_ThenStaleInventoryConflictsWithoutConsumingProof()
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Record(s,from.Id);var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),[new("account",s.AccountId,1,ProfileSetup.Envelope(2)),new("record",target.PublicId,1,ProfileSetup.Envelope(2)),new("folder",from.PublicId,1,ProfileSetup.Envelope(2)),new("folder",to.PublicId,1,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;
        var reached=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var release=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var blocked=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);using var ct=new CancellationTokenSource(TimeSpan.FromSeconds(20));var move=new RecordMoveStore(new ProfileSetup.Factory(fixture,new BeforeWrite(async()=>{reached.TrySetResult();await release.Task.WaitAsync(ct.Token);}))).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),ct.Token);await reached.Task.WaitAsync(TimeSpan.FromSeconds(10));var rotation=new VaultProtectionChangeStore(new ProfileSetup.Factory(fixture,new Signal(blocked,"account"))).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),ct.Token);
        try{await blocked.Task.WaitAsync(TimeSpan.FromSeconds(10));Assert.False(rotation.IsCompleted);}finally{release.TrySetResult();}await Success(target,to,from,to,await move);Assert.Equal("revision_conflict",(await rotation).Error);await using var db=fixture.CreateContext();Assert.False((await db.VaultUnlockChallenges.SingleAsync(x=>x.PublicId==challenge.ChallengeId)).Consumed);Assert.Equal(1,(await db.VaultProtections.SingleAsync(x=>x.AccountId==s.InternalId)).Revision);
    }

    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenActualOwnerRotationBeforeOrAfterMove_WhenReloading_ThenRetainCurrentParentAndRespectEpochRevisionAndHandle(bool rotateFirst)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Record(s,from.Id);
        if(!rotateFirst){await Success(target,to,from,to,await Move(s,target,to.PublicId));target=await Row(target.Id);from=await FolderRow(from.Id);to=await FolderRow(to.Id);}
        var change=new ProtectionChange(s.AccountId,1,1,"rotate-content",owner.Rewrap(),[new("account",s.AccountId,1,ProfileSetup.Envelope(2)),new("record",target.PublicId,target.Revision,ProfileSetup.Envelope(2)),new("folder",from.PublicId,from.Revision,ProfileSetup.Envelope(2)),new("folder",to.PublicId,to.Revision,ProfileSetup.Envelope(2))]);var raw=Bytes(change);var challenge=(await new VaultProtectionStore(fixture).ChallengeAsync(s.Actor,"change-protection",ProtocolBinary.Encode(SHA256.HashData(raw)),default)).Data!;Assert.Null((await new VaultProtectionChangeStore(fixture).ChangeAsync(new(s.Actor,s.Verifier,challenge.ChallengeId,owner.Sign(challenge),raw,change),default)).Error);
        Assert.Equal("vault_access_denied",(await Move(s,target,to.PublicId,1)).Error);var row=await Row(target.Id);Assert.Equal(rotateFirst?from.Id:to.Id,row.FolderId);Assert.Equal(2,JsonSerializer.Deserialize<EncryptedEnvelope>(row.Envelope,ProtectionFixture.Json)!.KeyEpoch);
        if(rotateFirst){var verifier=Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32));await using(var db=fixture.CreateContext()){var account=await db.Accounts.SingleAsync(x=>x.Id==s.InternalId);db.VaultAccessSessions.Add(new(){AccountId=s.InternalId,HandleVerifier=verifier,IssuedAt=DateTimeOffset.UtcNow.AddMinutes(-1),ExpiresAt=DateTimeOffset.UtcNow.AddHours(1),PolicyRevision=account.PolicyRevision,RevocationGeneration=account.RevocationGeneration});await db.SaveChangesAsync();}s=s with{Verifier=verifier};var before=await Snapshot(s);Assert.Equal("revision_conflict",(await Move(s,row,to.PublicId,1)).Error);Assert.Equal(before,await Snapshot(s));await Success(row,to,await FolderRow(from.Id),await FolderRow(to.Id),await Move(s,row,to.PublicId,row.Revision));}
    }

    [FunctionalTheory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)][InlineData(true,true)]
    public async Task GivenSequenceExhaustionOrRegressionAtTargetOrParent_WhenMoving_ThenRollbackAllStructuralChanges(bool parent,bool regression)
    {
        using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Record(s,from.Id);var before=await Snapshot(s);await using var db=fixture.CreateContext();var previous=await db.Database.SqlQuery<long>($"SELECT nextval('cerberus.server_sequence') AS \\"Value\\"").SingleAsync();
        async Task Reset(){await using var other=fixture.CreateContext();await other.Database.ExecuteSqlRawAsync(regression?"SELECT setval('cerberus.server_sequence',1,false)":"SELECT setval('cerberus.server_sequence',9007199254740991,true)");}
        try{var store=parent?new RecordMoveStore(new ProfileSetup.Factory(fixture,new BeforeParent(Reset))):Store();if(!parent)await Reset();Assert.Equal(regression?"persistence_unavailable":"revision_conflict",(await store.MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),default)).Error);Assert.Equal(before,await Snapshot(s));}finally{await db.Database.ExecuteSqlInterpolatedAsync($"SELECT setval('cerberus.server_sequence',{previous},true)");}
    }

    [FunctionalTheory][InlineData("afterFirstParent")][InlineData("afterSecondParent")]
    public async Task GivenFailureAfterActualParentMutation_WhenMoving_ThenRollbackBothParentsAndRecord(string stage)
    {using var owner=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var from=await Folder(s);var to=await Folder(s);var target=await Record(s,from.Id);var before=await Snapshot(s);Assert.Equal("persistence_unavailable",(await new RecordMoveStore(new ProfileSetup.Factory(fixture,new Fail(stage))).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),default)).Error);Assert.Equal(before,await Snapshot(s));await Success(target,to,from,to,await Move(s,target,to.PublicId));}

    [FunctionalTheory][InlineData(false)][InlineData(true)]
    public async Task GivenOverlappingRequiredNativeContributorsWithOneBadWrapper_WhenMovingOrForeignDenial_ThenWholeOperation503(bool foreign)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var c=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);var b=await AssociationSetup.Items(fixture,o);var target=await Record(o);await Members(o,a.Collection,foreign?[target.Id]:[],foreign?[]:[a.Folder.Id]);await Members(o,b.Collection,foreign?[target.Id]:[],foreign?[]:[a.Folder.Id]);await AssociationSetup.Grant(fixture,o,owner,c,client,a.Collection,CollectionGrantAccess.ReadWrite);var bad=await AssociationSetup.Grant(fixture,o,owner,c,client,b.Collection,CollectionGrantAccess.ReadOnly);await using(var db=fixture.CreateContext())await db.CollectionGrants.Where(x=>x.Id==bad.Id).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.RecipientKeyEnvelope,"bad"u8.ToArray()));var before=await Snapshot(o);Assert.Equal("persistence_unavailable",(await Move(foreign?c:o,target,a.Folder.PublicId)).Error);Assert.Equal(before,await Snapshot(o));
    }

    [FunctionalFact]
    public async Task GivenNativeVisibleForeignTarget_WhenDenyingMove_ThenOnlyOwnAccountAndSessionLocks()
    {using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var o=await ProfileSetup.Create(fixture,owner);var c=await ProfileSetup.Create(fixture,client);var a=await AssociationSetup.Items(fixture,o);await Members(o,a.Collection,[a.Record.Id],[]);await AssociationSetup.Grant(fixture,o,owner,c,client,a.Collection,CollectionGrantAccess.ReadWrite);var capture=new Capture(fixture);Assert.Equal("vault_access_denied",(await new RecordMoveStore(new ProfileSetup.Factory(fixture,capture)).MoveAsync(new(c.Actor,c.Verifier,a.Record.PublicId,1,null),default)).Error);Assert.Equal(2,capture.Locks.Count);Assert.Contains("cerberus.account",capture.Locks[0]);Assert.Contains("cerberus.vault_access_session",capture.Locks[1]);}

    [FunctionalFact]
    public async Task GivenUnrelatedDeepInventoryAndTwoTargetPaths_WhenMoving_ThenAnalyzeOnlyOneSourceAndDestinationAndOrderOwnedLocks()
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();var s=await ProfileSetup.Create(fixture,owner);var recipient=await ProfileSetup.Create(fixture,client);var root=await Folder(s);var from=await Folder(s,root.Id);var root2=await Folder(s);var child2=await Folder(s,root2.Id);var to=await Folder(s,child2.Id);var target=await Record(s,from.Id);var a=await AssociationSetup.Items(fixture,s);await Members(s,a.Collection,[target.Id],[root2.Id]);await AssociationSetup.Grant(fixture,s,owner,recipient,client,a.Collection);
        var unrelated=await Folder(s);for(var i=0;i<80;i++){unrelated=await Folder(s,unrelated.Id);await Record(s,unrelated.Id);}
        var capture=new Capture(fixture,true);await Success(target,to,from,to,await new RecordMoveStore(new ProfileSetup.Factory(fixture,capture)).MoveAsync(new(s.Actor,s.Verifier,target.PublicId,1,to.PublicId),default));Assert.NotNull(capture.Plan);using var plan=JsonDocument.Parse(capture.Plan);var nodes=Nodes(plan.RootElement).Where(x=>x.TryGetProperty("CTE Name",out _)).ToArray();foreach(var name in new[]{"candidates","destination_candidate"}){var scans=nodes.Where(x=>x.GetProperty("CTE Name").GetString()==name).ToArray();Assert.NotEmpty(scans);Assert.All(scans,x=>Assert.InRange(x.GetProperty("Actual Rows").GetInt32(),0,1));Assert.Contains(scans,x=>x.GetProperty("Actual Rows").GetInt32()==1);}
        var locks=capture.Locks;var collection=locks.FindIndex(x=>x.Contains("cerberus.collection c")&&x.Contains("FOR NO KEY UPDATE"));var grant=locks.FindIndex(x=>x.Contains("collection_grant g")&&x.Contains("FOR SHARE"));var folder=locks.FindIndex(x=>x.Contains("cerberus.folder f")&&x.Contains("FOR NO KEY UPDATE"));var record=locks.FindIndex(x=>x.Contains("cerberus.record WHERE")&&x.Contains("FOR NO KEY UPDATE"));Assert.True(collection>=0&&grant>collection&&folder>grant&&record>folder);Assert.Contains("ORDER BY c.public_id",locks[collection]);Assert.Contains("ORDER BY g.public_id",locks[grant]);Assert.Contains("ORDER BY f.public_id",locks[folder]);
    }

    private static IEnumerable<JsonElement> Nodes(JsonElement element){if(element.ValueKind==JsonValueKind.Object){yield return element;foreach(var p in element.EnumerateObject())foreach(var n in Nodes(p.Value))yield return n;}else if(element.ValueKind==JsonValueKind.Array)foreach(var child in element.EnumerateArray())foreach(var n in Nodes(child))yield return n;}
    private static async Task Past(DateTimeOffset t){var delay=t-DateTimeOffset.UtcNow;if(delay>TimeSpan.Zero)await Task.Delay(delay+TimeSpan.FromMilliseconds(100));}
    private sealed class Signal(TaskCompletionSource reached,string table):DbCommandInterceptor
    {private void Check(DbCommand c){if(c.CommandText.Contains("cerberus."+table)&&c.CommandText.Contains("FOR "))reached.TrySetResult();}public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Check(c);return ValueTask.FromResult(r);}}
    private sealed class BeforeTarget(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&c.CommandText.Contains("cerberus.record WHERE")&&c.CommandText.Contains("FOR NO KEY UPDATE")){used=true;await action();}return r;}}
    private sealed class BeforeParent(Func<Task> action):DbCommandInterceptor
    {private bool used;public override async ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){if(!used&&c.CommandText.StartsWith("UPDATE cerberus.folder SET")){used=true;await action();}return r;}}
    private sealed class Capture(PostgresFixture fixture,bool analyze=false):DbCommandInterceptor
    {
        public List<string> Locks{get;}=[];public string? Plan{get;private set;}
        private void Note(DbCommand c){if(c.CommandText.Contains("FOR UPDATE")||c.CommandText.Contains("FOR NO KEY UPDATE")||c.CommandText.Contains("FOR SHARE"))Locks.Add(c.CommandText);}
        public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<int> r,CancellationToken ct=default){Note(c);return ValueTask.FromResult(r);}
        public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c,CommandEventData d,InterceptionResult<DbDataReader> r,CancellationToken ct=default){Note(c);if(analyze&&Plan is null&&c.CommandText.StartsWith("WITH RECURSIVE")){await using var db=fixture.CreateContext();await db.Database.OpenConnectionAsync(ct);await using var cmd=db.Database.GetDbConnection().CreateCommand();cmd.CommandText="EXPLAIN (ANALYZE, FORMAT JSON) "+c.CommandText;foreach(var p in c.Parameters.Cast<NpgsqlParameter>())cmd.Parameters.Add(p.Clone());Plan=(string)(await cmd.ExecuteScalarAsync(ct))!;}return r;}
    }
'''
s=s.replace('    private RecordMoveStore Store()',extra+'\n    private RecordMoveStore Store()',1)
s=s.replace('private bool written,failed;private int parents;', 'private bool written,failed;private int parents,parentsDone;')
s=s.replace('(stage=="secondParent"&&parents==2)', '(stage=="secondParent"&&parents==2)||(stage=="afterFirstParent"&&parentsDone>=1)||(stage=="afterSecondParent"&&parentsDone>=2)')
s=s.replace('if(IsWrite(c))written=true;return ValueTask.FromResult(result);','if(IsWrite(c))written=true;if(c.CommandText.StartsWith("UPDATE cerberus.folder SET"))parentsDone++;return ValueTask.FromResult(result);')
p.write_text(s)
print('Added remaining controlled actual-store races, all7 expiry waits, native pin rotation/final ancestry/heldset guards, sequence and postparent rollback, real analyzed queryplan/locktrace cases; product unchanged.')
