from pathlib import Path
s=Path('tests/Presentation/ArturRios.Cerberus.WebApi.Tests/RecordTrashHttpTests.cs').read_text()
header=s[:s.index('    [FunctionalTheory]')].replace('RecordTrashHttpTests','RecordMoveHttpTests')
def method(name):
 start=s.rfind('    [Functional',0,s.index('public async Task '+name))
 end=s.find('\n    [Functional',start+5)
 private=s.find('\n    private ',start+5)
 if private>=0 and (end<0 or private<end):end=private
 if end<0:end=s.index('    private async Task<RecordCreateInput> Create',start)
 return s[start:end]
names=['GivenActualNativeVisibleForeignScope_WhenDeletingStaleCorruptTarget_ThenReadOnlyAndReadWriteBoth403','GivenSelectedCollectionLinkRemovedAfterUnlock_WhenTrashingForeignTarget_Then404WithoutExpandingScope','GivenCorruptMetadataOrPersistenceOutage_WhenTrashing_Then503WithoutPartialOperation','GivenCancelledHttpCaller_WhenTrashing_ThenPropagateAndPreserveRecord','GivenHiddenTargetWithBadCipherAndStaleRevision_WhenTrashing_ThenNonrevealing404WithoutMutation','GivenNoncanonicalRoute_WhenTrashing_Then400WithoutMutation','GivenInvalidTransportOrAccess_WhenTrashing_ThenRejectWithoutMutation','GivenRawEmptyAccessHeader_WhenTrashing_Then400','GivenInvalidCurrentIdentity_WhenTrashing_ThenRejectWithoutPersistence','GivenInvalidCurrentActorState_WhenTrashing_ThenNoMutation','GivenCommittedSharedRelationshipChange_WhenTrashing_ThenCurrentPermissionWins','GivenRelevantMalformedNativeAuthority_WhenTrashing_Then503WithoutAnyContentChange']
generic='\n'.join(method(n) for n in names)
generic=generic.replace('Trash(', 'Move(').replace('Delete(', 'PutFolder(').replace('WhenTrashing','WhenMoving').replace('WhenDeleting','WhenMoving').replace('new{expectedRevision=1}','new{expectedRevision=1,folderId=(Guid?)null}')
generic=generic.replace('c.Request.Method="DELETE"','c.Request.Method="PUT"').replace('c.Request.Path="/api/records/"+Guid.NewGuid()','c.Request.Path="/api/records/"+Guid.NewGuid()+"/folder"')
# Route tests and generic transport go through PutFolder, which appends /folder before query.
helpers=s[s.index('    private async Task<RecordCreateInput> Create'):]
helpers=helpers.replace('private static DateTimeOffset Normalize(DateTimeOffset value)=>value.AddTicks(-(value.Ticks%10));','')
helpers=helpers.replace('ProfileRecords=await db.ProfileRecords','ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileRecords=await db.ProfileRecords')
helpers=helpers[:helpers.rfind('}')]
common='''    private static HttpRequestMessage PutFolder(State s,string path,byte[] body){var split=path.IndexOf('?');var uri=split<0?path+"/folder":path[..split]+"/folder"+path[split..];var r=Request(s,body,uri);r.Method=HttpMethod.Put;return r;}
    private async Task<HttpResponseMessage> Move(State s,Guid id,long revision=1,Guid? destination=null){using var req=PutFolder(s,"/api/records/"+id,Bytes(new{expectedRevision=revision,folderId=destination}));return await Gateway.Client.SendAsync(req);}
    private async Task<VaultRecord> Row(Guid id){await using var db=fixture.Context();return await db.Records.AsNoTracking().SingleAsync(x=>x.PublicId==id);}
    private async Task Moved(VaultRecord original,VaultFolder? destination,MoveRecordOutput output)
    {Fields(output,"recordId","folderId","revision","serverSequence");Assert.Equal(original.PublicId,output.RecordId);Assert.Equal(destination?.PublicId,output.FolderId);Assert.Equal(original.Revision+1,output.Revision);Assert.True(output.ServerSequence>original.ServerSequence);var row=await Row(original.PublicId);Assert.Equal(original.AccountId,row.AccountId);Assert.Equal(original.Envelope,row.Envelope);Assert.Equal(original.EditedAt,row.EditedAt);Assert.Equal(destination?.Id,row.FolderId);Assert.Equal(output.Revision,row.Revision);Assert.Equal(output.ServerSequence,row.ServerSequence);Assert.Null(row.DeletedAt);Assert.Null(row.PurgeAt);Assert.NotEqual(original.ConcurrencyStamp,row.ConcurrencyStamp);}
    private async Task<string> Links(State s){await using var db=fixture.Context();return JsonSerializer.Serialize(new{Protected=await Protected(s),Profiles=await db.Profiles.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),Collections=await db.Collections.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.Id).ToArrayAsync(),ProfileRecords=await db.ProfileRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.RecordId).ToArrayAsync(),CollectionRecords=await db.CollectionRecords.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.RecordId).ToArrayAsync(),ProfileFolders=await db.ProfileFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.ProfileId).ThenBy(x=>x.FolderId).ToArrayAsync(),CollectionFolders=await db.CollectionFolders.AsNoTracking().Where(x=>x.AccountId==s.InternalId).OrderBy(x=>x.CollectionId).ThenBy(x=>x.FolderId).ToArrayAsync(),ProfileCollections=await db.ProfileCollections.AsNoTracking().Where(x=>db.Profiles.Any(p=>p.Id==x.ProfileId&&p.AccountId==s.InternalId)).OrderBy(x=>x.ProfileId).ThenBy(x=>x.CollectionId).ToArrayAsync(),Grants=await db.CollectionGrants.AsNoTracking().Where(x=>db.Collections.Any(c=>c.Id==x.CollectionId&&c.AccountId==s.InternalId)).OrderBy(x=>x.Id).ToArrayAsync()});}
'''
owned='''    [FunctionalTheory][InlineData("wide","between")][InlineData("Master","between")][InlineData("PerProfile","between")][InlineData("wide","toRoot")][InlineData("Master","toRoot")][InlineData("PerProfile","toRoot")][InlineData("wide","fromRoot")][InlineData("wide","same")][InlineData("Master","same")][InlineData("PerProfile","same")][InlineData("wide","rootNoop")]
    public async Task GivenActualNativeOwnedScope_WhenMoving_ThenRetainCipherLinksAndHandleAndReturnFourFields(string mode,string route)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var from=await Folder(s,root.Id);var to=await Folder(s,root.Id);var p=await Profile(s,owner,scoped,root,mode=="wide"?"Master":mode);var target=await Create(s,[p.PublicId],route is "fromRoot" or "rootNoop"?null:from.PublicId);var actor=mode=="wide"?s:s with{Access=await Open(s,p,scoped)};var original=await Row(target.RecordId);var links=await Links(s);var destination=route is "toRoot" or "rootNoop"?null:route=="same"?from:to;
        using var response=await Move(actor,target.RecordId,destination:destination?.PublicId);Assert.Contains("record_moved",await response.Content.ReadAsStringAsync());await Moved(original,destination,await Success<MoveRecordOutput>(response,200));Assert.Equal(links,await Links(s));
        await using var db=fixture.Context();var nowFrom=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==from.Id);var nowTo=await db.Folders.AsNoTracking().SingleAsync(x=>x.Id==to.Id);Assert.Equal(from.Revision+(original.FolderId==from.Id && destination?.Id!=from.Id?1:0),nowFrom.Revision);Assert.Equal(to.Revision+(destination?.Id==to.Id && original.FolderId!=to.Id?1:0),nowTo.Revision);Assert.Equal(from.Envelope,nowFrom.Envelope);Assert.Equal(from.EditedAt,nowFrom.EditedAt);Assert.Equal(to.Envelope,nowTo.Envelope);Assert.Equal(to.EditedAt,nowTo.EditedAt);Assert.Equal(root.Revision,(await db.Folders.SingleAsync(x=>x.Id==root.Id)).Revision);using var get=await Read(actor,"/api/records/"+target.RecordId);await Success<RecordDetailsOutput>(get,200);using var list=await Read(actor,"/api/records");Assert.Contains((await Success<RecordListOutput>(list,200)).Items,x=>x.RecordId==target.RecordId);
    }
    [FunctionalTheory][InlineData("Master")][InlineData("PerProfile")]
    public async Task GivenSelectedOwnedCollectionFolderRoute_WhenMovingWithinCommonAncestor_ThenDynamicVisibilityAndWrappersSurvive(string mode)
    {
        using var owner=new ProtectionFixture();using var scoped=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var from=await Folder(s,root.Id);var to=await Folder(s,root.Id);var target=await Create(s,folder:from.PublicId);await using var db=fixture.Context();var c=new VaultCollection{AccountId=s.InternalId,PublicId=Guid.NewGuid(),Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(c);await db.SaveChangesAsync();db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,FolderId=root.Id});await db.SaveChangesAsync();var p=await Profile(s,owner,scoped,mode:mode,collections:[c.PublicId]);var actor=s with{Access=await Open(s,p,scoped)};var original=await Row(target.RecordId);var before=await Links(s);using var response=await Move(actor,target.RecordId,destination:to.PublicId);await Moved(original,to,await Success<MoveRecordOutput>(response,200));Assert.Equal(before,await Links(s));using var get=await Read(actor,"/api/records/"+target.RecordId);Assert.Contains(c.PublicId,(await Success<RecordDetailsOutput>(get,200)).CollectionIds);
    }
    [FunctionalTheory][InlineData(CollectionGrantAccess.ReadOnly,false)][InlineData(CollectionGrantAccess.ReadWrite,false)][InlineData(CollectionGrantAccess.ReadOnly,true)][InlineData(CollectionGrantAccess.ReadWrite,true)]
    public async Task GivenNativeOldNewAndDirectRecipientRoutes_WhenOwnerMoves_ThenGetAndListRecalculateAndOldOnlySelectionLosesVisibility(CollectionGrantAccess access,bool selected)
    {
        using var owner=new ProtectionFixture();using var client=new ProtectionFixture();using var scoped=new ProtectionFixture();using var oldKey=new ProtectionFixture();var o=await Setup(owner);var s=await Setup(client);var from=await Folder(o);var to=await Folder(o);var target=await Create(o,folder:from.PublicId);var (old,oldGrant)=await Share(o,owner,s,client,access,[],[from.Id]);var (next,nextGrant)=await Share(o,owner,s,client,access,[],[to.Id]);var (direct,directGrant)=await Share(o,owner,s,client,access,[target.RecordId],[]);var p=await Profile(s,client,scoped,collections:[old.PublicId,next.PublicId,direct.PublicId]);var oldOnly=await Profile(s,client,oldKey,collections:[old.PublicId]);var oldActor=s with{Access=await Open(s,oldOnly,oldKey)};var actor=selected?s with{Access=await Open(s,p,scoped)}:s;var recipientBefore=await Snapshot(s);var links=await Links(o);var original=await Row(target.RecordId);
        using(var before=await Read(actor,"/api/records/"+target.RecordId)){var data=await Success<RecordDetailsOutput>(before,200);Assert.Contains(old.PublicId,data.CollectionIds);Assert.DoesNotContain(next.PublicId,data.CollectionIds);}using(var response=await Move(o,target.RecordId,destination:to.PublicId))await Moved(original,to,await Success<MoveRecordOutput>(response,200));Assert.Equal(links,await Links(o));Assert.Equal(recipientBefore,await Snapshot(s));using(var after=await Read(actor,"/api/records/"+target.RecordId)){var data=await Success<RecordDetailsOutput>(after,200);Assert.DoesNotContain(old.PublicId,data.CollectionIds);Assert.Contains(next.PublicId,data.CollectionIds);Assert.Contains(direct.PublicId,data.CollectionIds);}using(var list=await Read(actor,"/api/records"))Assert.Contains((await Success<RecordListOutput>(list,200)).Items,x=>x.RecordId==target.RecordId);using(var gone=await Read(oldActor,"/api/records/"+target.RecordId))await Failure(gone,404,"not_found");using(var oldList=await Read(oldActor,"/api/records"))Assert.DoesNotContain((await Success<RecordListOutput>(oldList,200)).Items,x=>x.RecordId==target.RecordId);
    }
    [FunctionalTheory][InlineData("newProfile",false)][InlineData("newCollection",false)][InlineData("hiddenFolder",false)][InlineData("existingProfile",true)][InlineData("existingCollection",true)][InlineData("remove",true)][InlineData("wide",true)]
    public async Task GivenSelectedContentScope_WhenMovingToVisibleOrHiddenFolder_ThenNeverIntroduceNewEffectiveProfileOrCollection(string kind,bool allowed)
    {
        using var owner=new ProtectionFixture();using var key=new ProtectionFixture();using var otherKey=new ProtectionFixture();var s=await Setup(owner);var root=await Folder(s);var from=await Folder(s,root.Id);var to=await Folder(s,kind=="hiddenFolder"?null:root.Id);var p=await Profile(s,owner,key,root);var other=kind is "newProfile" or "existingProfile" or "wide"?await Profile(s,owner,otherKey,to):null;var target=await Create(s,kind=="existingProfile"?[p.PublicId,other!.PublicId]:[p.PublicId],from.PublicId);
        await using(var db=fixture.Context()){if(kind is "newCollection" or "existingCollection"){var c=new VaultCollection{PublicId=Guid.NewGuid(),AccountId=s.InternalId,Envelope=Bytes(Envelope()),EditedAt=DateTimeOffset.UnixEpoch};db.Collections.Add(c);await db.SaveChangesAsync();db.CollectionFolders.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,FolderId=to.Id});if(kind=="existingCollection")db.CollectionRecords.Add(new(){AccountId=s.InternalId,CollectionId=c.Id,RecordId=(await Row(target.RecordId)).Id});await db.SaveChangesAsync();}}
        var actor=kind=="wide"?s:s with{Access=await Open(s,p,key)};var before=await Snapshot(s);var original=await Row(target.RecordId);var destination=kind=="remove"?null:to;using var response=await Move(actor,target.RecordId,destination:destination?.PublicId);if(allowed)await Moved(original,destination,await Success<MoveRecordOutput>(response,200));else{await Failure(response,404,"not_found");Assert.Equal(before,await Snapshot(s));}
    }
'''
strict='''    [FunctionalTheory][InlineData("actor")][InlineData("vaultAccess")][InlineData("recordId")][InlineData("ownerId")][InlineData("profileIds")][InlineData("collectionIds")][InlineData("name")][InlineData("fields")][InlineData("keyWrappers")][InlineData("envelope")][InlineData("editedAt")][InlineData("trashOperationId")][InlineData("deletedAt")][InlineData("purgeAt")][InlineData("unknown")][InlineData("zero")][InlineData("negative")][InlineData("unsafe")][InlineData("missingRevision")][InlineData("missingFolder")][InlineData("duplicateRevision")][InlineData("duplicateFolder")][InlineData("caseRevision")][InlineData("caseFolder")][InlineData("numericString")][InlineData("nullRevision")][InlineData("fraction")][InlineData("overflow")][InlineData("null")][InlineData("array")][InlineData("empty")][InlineData("folderZero")][InlineData("folderBad")][InlineData("folderUppercase")][InlineData("folderCompact")][InlineData("folderNumeric")]
    public async Task GivenStrictOrForgedMoveBody_WhenMoving_Then400WithoutMutation(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);var body=JsonSerializer.SerializeToNode(new{expectedRevision=1,folderId=(Guid?)null},ProtectionFixture.Json)!.AsObject();var fields=new[]{"actor","vaultAccess","recordId","ownerId","profileIds","collectionIds","name","fields","keyWrappers","envelope","editedAt","trashOperationId","deletedAt","purgeAt"};if(fields.Contains(kind))body[kind]=null;if(kind=="unknown")body["secret"]=null;if(kind is "zero" or "negative" or "unsafe")body["expectedRevision"]=kind=="zero"?0:kind=="negative"?-1:9007199254740992;if(kind=="missingRevision")body.Remove("expectedRevision");if(kind=="missingFolder")body.Remove("folderId");if(kind=="caseRevision"){body.Remove("expectedRevision");body["ExpectedRevision"]=1;}if(kind=="caseFolder"){body.Remove("folderId");body["FolderId"]=null;}if(kind=="numericString")body["expectedRevision"]="1";if(kind=="nullRevision")body["expectedRevision"]=null;if(kind=="fraction")body["expectedRevision"]=1.5;if(kind=="overflow")body["expectedRevision"]=9223372036854775808m;if(kind.StartsWith("folder"))body["folderId"]=kind switch{"folderZero"=>Guid.Empty.ToString(),"folderBad"=>"bad","folderUppercase"=>"ABCDEFAB-1234-4321-ABCD-123456789ABC",_=>"abcdefab12344321abcd123456789abc"};if(kind=="folderNumeric")body["folderId"]=1;
        var raw=kind switch{"duplicateRevision"=>"{\\"expectedRevision\\":1,\\"expectedRevision\\":1,\\"folderId\\":null}","duplicateFolder"=>"{\\"expectedRevision\\":1,\\"folderId\\":null,\\"folderId\\":null}","null"=>"null","array"=>"[]","empty"=>"",_=>body.ToJsonString()};var before=await Snapshot(s);using var req=PutFolder(s,"/api/records/"+target.RecordId,Encoding.UTF8.GetBytes(raw));using var r=await Gateway.Client.SendAsync(req);await Failure(r,400);Assert.Equal(before,await Snapshot(s));
    }
    [FunctionalTheory][InlineData("lostSuccess")][InlineData("putWinner")][InlineData("trashWinner")]
    public async Task GivenActualWinningMutation_WhenMovingOldRevision_ThenPreserveWinnerAndUseCurrentState(string kind)
    {
        using var owner=new ProtectionFixture();var s=await Setup(owner);var from=await Folder(s);var to=await Folder(s);var target=await Create(s,folder:from.PublicId);if(kind=="lostSuccess"){using var win=await Move(s,target.RecordId,destination:to.PublicId);await Success<MoveRecordOutput>(win,200);}else{using var req=Request(s,kind=="putWinner"?Bytes(new RecordUpdateInput(1,Envelope(),DateTimeOffset.UnixEpoch)):Bytes(new{expectedRevision=1}),"/api/records/"+target.RecordId);req.Method=kind=="putWinner"?HttpMethod.Put:HttpMethod.Delete;using var win=await Gateway.Client.SendAsync(req);Assert.Equal(HttpStatusCode.OK,win.StatusCode);}var before=await Snapshot(s);using(var retry=await Move(s,target.RecordId,destination:to.PublicId))await Failure(retry,kind=="trashWinner"?404:409,kind=="trashWinner"?"not_found":"revision_conflict");Assert.Equal(before,await Snapshot(s));if(kind!="trashWinner"){var original=await Row(target.RecordId);using var current=await Move(s,target.RecordId,2,to.PublicId);await Moved(original,to,await Success<MoveRecordOutput>(current,200));}
    }
    [FunctionalFact]
    public async Task GivenDamagedOwnedCipher_WhenMoving_Then503WithoutMovingOrRepairingBytes()
    {using var owner=new ProtectionFixture();var s=await Setup(owner);var target=await Create(s);await using(var db=fixture.Context())await db.Records.Where(x=>x.PublicId==target.RecordId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Envelope,"bad"u8.ToArray()));var before=await Snapshot(s);using var response=await Move(s,target.RecordId);await Failure(response,503,"persistence_unavailable");Assert.Equal(before,await Snapshot(s));}
'''
Path('/tmp/cerberus-uc21-http-tests.cs').write_text(header+owned+strict+generic+common+helpers+'}\n')
